VirtualTours: UnityStandardAssets.Water.WaterBaseEditor Class Reference
UnityStandardAssets.Water.WaterBaseEditor Class Reference
Public Member Functions
void OnEnable ()
override void OnInspectorGUI ()
Public Attributes
GameObject oceanBase
SerializedProperty waterQuality
SerializedProperty edgeBlend
Member Function Documentation
OnEnable()
void UnityStandardAssets.Water.WaterBaseEditor.OnEnable ()
References UnityStandardAssets.Water.WaterBaseEditor.edgeBlend, and UnityStandardAssets.Water.WaterBaseEditor.waterQuality.
OnInspectorGUI()
override void UnityStandardAssets.Water.WaterBaseEditor.OnInspectorGUI ()
References UnityStandardAssets.Water.WaterBaseEditor.edgeBlend, WaterEditorUtility.GetMaterialColor(), WaterEditorUtility.GetMaterialFloat(), WaterEditorUtility.GetMaterialTexture(), WaterEditorUtility.GetMaterialVector(), WaterEditorUtility.LocateValidWaterMaterial(), UnityStandardAssets.Water.WaterBaseEditor.oceanBase, WaterEditorUtility.SetMaterialColor(), WaterEditorUtility.SetMaterialFloat(), WaterEditorUtility.SetMaterialTexture(), WaterEditorUtility.SetMaterialVector(), UnityStandardAssets.Water.WaterBase.sharedMaterial, and UnityStandardAssets.Water.WaterBaseEditor.waterQuality.
Member Data Documentation
edgeBlend
SerializedProperty UnityStandardAssets.Water.WaterBaseEditor.edgeBlend
Referenced by UnityStandardAssets.Water.WaterBaseEditor.OnEnable(), and UnityStandardAssets.Water.WaterBaseEditor.OnInspectorGUI().
oceanBase
GameObject UnityStandardAssets.Water.WaterBaseEditor.oceanBase
Referenced by UnityStandardAssets.Water.WaterBaseEditor.OnInspectorGUI().
waterQuality
SerializedProperty UnityStandardAssets.Water.WaterBaseEditor.waterQuality
Referenced by UnityStandardAssets.Water.WaterBaseEditor.OnEnable(), and UnityStandardAssets.Water.WaterBaseEditor.OnInspectorGUI().
The documentation for this class was generated from the following file:
C:/Users/knowl/Desktop/CapstoneProject-master (4)/CapstoneProject-master/VirtualTour/Assets/Standard Assets/Editor/Water/Water4/WaterBaseEditor.cs