VirtualTours: UnityEditor.Timeline.Scrub Class Reference
UnityEditor.Timeline.Scrub Class Reference
Public Member Functions
Scrub (Func< Event, WindowState, bool > onMouseDown, Action< double > onMouseDrag, Action onMouseUp)
Public Member Functions inherited from UnityEditor.Timeline.Manipulator
virtual void Overlay (Event evt, WindowState state)
bool HandleEvent (WindowState state)
Protected Member Functions
override bool MouseDown (Event evt, WindowState state)
override bool MouseUp (Event evt, WindowState state)
override bool MouseDrag (Event evt, WindowState state)
Protected Member Functions inherited from UnityEditor.Timeline.Manipulator
virtual bool MouseWheel (Event evt, WindowState state)
virtual bool DoubleClick (Event evt, WindowState state)
virtual bool KeyDown (Event evt, WindowState state)
virtual bool KeyUp (Event evt, WindowState state)
virtual bool ContextClick (Event evt, WindowState state)
virtual bool ValidateCommand (Event evt, WindowState state)
virtual bool ExecuteCommand (Event evt, WindowState state)
Constructor & Destructor Documentation
Scrub()
UnityEditor.Timeline.Scrub.Scrub (Func< Event, WindowState, bool > onMouseDown, Action< double > onMouseDrag, Action onMouseUp)
Member Function Documentation
MouseDown()
override bool UnityEditor.Timeline.Scrub.MouseDown (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.WindowState.AddCaptured().
MouseDrag()
override bool UnityEditor.Timeline.Scrub.MouseDrag (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.WindowState.GetSnappedTimeAtMousePosition().
MouseUp()
override bool UnityEditor.Timeline.Scrub.MouseUp (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.WindowState.RemoveCaptured().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Trackhead.cs