VirtualTours: TMPro.TextMeshProUGUI Class Reference
TMPro.TextMeshProUGUI Class Reference
Public Member Functions
void CalculateLayoutInputHorizontal ()
Function called by Unity when the horizontal layout needs to be recalculated.
void CalculateLayoutInputVertical ()
Function called by Unity when the vertical layout needs to be recalculated.
override void SetVerticesDirty ()
override void SetLayoutDirty ()
override void SetMaterialDirty ()
override void SetAllDirty ()
override void Rebuild (CanvasUpdate update)
override Material GetModifiedMaterial (Material baseMaterial)
override void RecalculateClipping ()
Method called when the state of a parent changes.
override void Cull (Rect clipRect, bool validRect)
Method called when Stencil Mask needs to be updated on this element and parents.
override void UpdateMeshPadding ()
Function to be used to force recomputing of character padding when Shader / Material properties have been changed via script.
override void ForceMeshUpdate (bool ignoreActiveState=false, bool forceTextReparsing=false)
Function to force regeneration of the text object before its normal process time. This is useful when changes to the text object properties need to be applied immediately.
override TMP_TextInfo GetTextInfo (string text)
Function used to evaluate the length of a text string.
override void ClearMesh ()
Function to clear the geometry of the Primary and Sub Text objects.
override void UpdateGeometry (Mesh mesh, int index)
Function to update the geometry of the main and sub text objects.
override void UpdateVertexData (TMP_VertexDataUpdateFlags flags)
Function to upload the updated vertex data and renderer.
override void UpdateVertexData ()
Function to upload the updated vertex data and renderer.
void UpdateFontAsset ()
override void ComputeMarginSize ()
Update the margin width and height
Public Member Functions inherited from TMPro.TMP_Text
virtual void SetVertices (Vector3[] vertices)
Function to push a new set of vertices to the mesh.
override void CrossFadeColor (Color targetColor, float duration, bool ignoreTimeScale, bool useAlpha)
override void CrossFadeAlpha (float alpha, float duration, bool ignoreTimeScale)
Tweens the alpha of the CanvasRenderer color associated with this Graphic.
void SetText (string text, bool syncTextInputBox=true)
void SetText (string text, float arg0)
void SetText (string text, float arg0, float arg1)
void SetText (string text, float arg0, float arg1, float arg2)
void SetText (string text, float arg0, float arg1, float arg2, float arg3)
void SetText (string text, float arg0, float arg1, float arg2, float arg3, float arg4)
void SetText (string text, float arg0, float arg1, float arg2, float arg3, float arg4, float arg5)
void SetText (string text, float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6)
void SetText (string text, float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7)
void SetText (StringBuilder text)
Set the text using a StringBuilder.
void SetText (char[] text)
Set the text using a char array.
void SetText (char[] text, int start, int length)
Set the text using a char array with specified starting character and length.
void SetCharArray (char[] sourceText)
Character array containing the text to be displayed.
void SetCharArray (char[] sourceText, int start, int length)
Character array containing the text to be displayed.
void SetCharArray (int[] sourceText, int start, int length)
Character array containing the text to be displayed.
Vector2 GetPreferredValues ()
Function to Calculate the Preferred Width and Height of the text object.
Vector2 GetPreferredValues (float width, float height)
Function to Calculate the Preferred Width and Height of the text object given the provided width and height.
Vector2 GetPreferredValues (string text)
Function to Calculate the Preferred Width and Height of the text object given a certain string.
Vector2 GetPreferredValues (string text, float width, float height)
Function to Calculate the Preferred Width and Height of the text object given a certain string and size of text container.
Vector2 GetRenderedValues ()
Method returning the rendered width and height of the text object.
Vector2 GetRenderedValues (bool onlyVisibleCharacters)
virtual void ClearMesh (bool uploadGeometry)
Function to clear the geometry of the Primary and Sub Text objects.
virtual string GetParsedText ()
Function which returns the text after it has been parsed and rich text tags removed.
Protected Member Functions
override void UpdateMaterial ()
override void InternalCrossFadeColor (Color targetColor, float duration, bool ignoreTimeScale, bool useAlpha)
Tweens the CanvasRenderer color associated with this Graphic.
override void InternalCrossFadeAlpha (float alpha, float duration, bool ignoreTimeScale)
Tweens the alpha of the CanvasRenderer color associated with this Graphic.
override void Awake ()
override void OnEnable ()
override void OnDisable ()
override void OnDestroy ()
override void LoadFontAsset ()
Method which derived classes need to override to load Font Assets.
override Material GetMaterial (Material mat)
Function called internally when a new material is assigned via the fontMaterial property.
override Material[] GetMaterials (Material[] mats)
Method returning instances of the materials used by the text object.
override void SetSharedMaterial (Material mat)
Function called internally when a new shared material is assigned via the fontSharedMaterial property.
override Material[] GetSharedMaterials ()
Method returning an array containing the materials used by the text object.
override void SetSharedMaterials (Material[] materials)
Method used to assign new materials to the text and sub text objects.
override void SetOutlineThickness (float thickness)
Function called internally to set the outline thickness property of the material. This will results in an instance of the material.
override void SetFaceColor (Color32 color)
Function called internally to set the face color of the material. This will results in an instance of the material.
override void SetOutlineColor (Color32 color)
Function called internally to set the outline color of the material. This will results in an instance of the material.
override void SetShaderDepth ()
Set the Render Queue and ZTest mode on the current material
override void SetCulling ()
Set the culling mode on the material.
override int SetArraySizes (UnicodeChar[] unicodeChars)
Method used to determine the number of visible characters and required buffer allocations.
override void OnDidApplyAnimationProperties ()
override void OnCanvasHierarchyChanged ()
override void OnTransformParentChanged ()
override void OnRectTransformDimensionsChange ()
override void GenerateTextMesh ()
This is the main function that is responsible for creating / displaying the text.
override Vector3[] GetTextContainerLocalCorners ()
Method to return the local corners of the Text Container or RectTransform.
override void SetActiveSubMeshes (bool state)
Method to Enable or Disable child SubMesh objects.
override void DestroySubMeshObjects ()
Destroy Sub Mesh Objects
override Bounds GetCompoundBounds ()
Method returning the compound bounds of the text object and child sub objects.
Protected Member Functions inherited from TMPro.TMP_Text
virtual void SetFontBaseMaterial (Material mat)
Function called internally when assigning a new base material.
virtual Material CreateMaterialInstance (Material source)
Method to set the materials of the text and sub text objects.
void SetVertexColorGradient (TMP_ColorGradient gradient)
void SetTextSortingOrder (VertexSortingOrder order)
Function to control the sorting of the geometry of the text object.
void SetTextSortingOrder (int[] order)
Function to sort the geometry of the text object in accordance to the provided order.
virtual float GetPaddingForMaterial ()
Get the padding value for the currently assigned material
virtual float GetPaddingForMaterial (Material mat)
Get the padding value for the given material
void ParseInputText ()
Method to parse the input text based on its source
int CharArrayToInternalParsingBuffer (char[] sourceText, ref UnicodeChar[] internalParsingArray)
Copies Content of formatted SetText() to charBuffer.
int StringToInternalParsingBuffer (string sourceText, ref UnicodeChar[] internalParsingArray)
Method to store the content of a string into an integer array.
int StringBuilderToInternalParsingBuffer (StringBuilder sourceText, ref UnicodeChar[] internalParsingArray)
Copy contents of StringBuilder into int array.
float GetPreferredWidth ()
Method to calculate the preferred width of a text object.
float GetPreferredHeight ()
Method to calculate the preferred height of a text object.
float GetRenderedWidth (bool onlyVisibleCharacters)
Method returning the rendered width of the text object.
float GetRenderedHeight (bool onlyVisibleCharacters)
Method returning the rendered height of the text object.
virtual Vector2 CalculatePreferredValues (ref float fontSize, Vector2 marginSize, bool isTextAutoSizingEnabled, bool isWordWrappingEnabled)
Method to calculate the preferred width and height of the text object.
Bounds GetTextBounds ()
Method which returns the bounds of the text object;
Bounds GetTextBounds (bool onlyVisibleCharacters)
Method which returns the bounds of the text object;
void AdjustLineOffset (int startIndex, int endIndex, float offset)
Method to adjust line spacing as a result of using different fonts or font point size.
void ResizeLineExtents (int size)
Function to increase the size of the Line Extents Array.
void InsertNewLine (int i, float baseScale, float currentElementScale, float currentEmScale, float glyphAdjustment, float boldSpacingAdjustment, float characterSpacingAdjustment, float width, float lineGap, ref bool isMaxVisibleDescenderSet, ref float maxVisibleDescender)
Function used in conjunction with GetTextInfo to figure out Array allocations.
void SaveWordWrappingState (ref WordWrapState state, int index, int count)
Save the State of various variables used in the mesh creation loop in conjunction with Word Wrapping
int RestoreWordWrappingState (ref WordWrapState state)
Restore the State of various variables used in the mesh creation loop.
virtual void SaveGlyphVertexInfo (float padding, float style_padding, Color32 vertexColor)
Store vertex information for each character.
virtual void SaveSpriteVertexInfo (Color32 vertexColor)
Store vertex information for each sprite.
virtual void FillCharacterVertexBuffers (int i, int index_X4)
Store vertex attributes into the appropriate TMP_MeshInfo.
virtual void FillCharacterVertexBuffers (int i, int index_X4, bool isVolumetric)
virtual void FillSpriteVertexBuffers (int i, int index_X4)
Fill Vertex Buffers for Sprites
virtual void DrawUnderlineMesh (Vector3 start, Vector3 end, ref int index, float startScale, float endScale, float maxScale, float sdfScale, Color32 underlineColor)
Method to add the underline geometry.
virtual void DrawTextHighlight (Vector3 start, Vector3 end, ref int index, Color32 highlightColor)
void LoadDefaultSettings ()
Internal function used to load the default settings of text objects.
void GetSpecialCharacters (TMP_FontAsset fontAsset)
Method used to find and cache references to the Underline and Ellipsis characters.
void GetEllipsisSpecialCharacter (TMP_FontAsset fontAsset)
void GetUnderlineSpecialCharacter (TMP_FontAsset fontAsset)
void ReplaceTagWithCharacter (int[] chars, int insertionIndex, int tagLength, char c)
Replace a given number of characters (tag) in the array with a new character and shift subsequent characters in the array.
TMP_FontAsset GetFontAssetForWeight (int fontWeight)
Vector2 PackUV (float x, float y, float scale)
Function to pack scale information in the UV2 Channel.
float PackUV (float x, float y)
int HexToInt (char hex)
Function to pack scale information in the UV2 Channel.
int GetUTF16 (string text, int i)
Convert UTF-16 Hex to Char
int GetUTF16 (int[] text, int i)
int GetUTF16 (StringBuilder text, int i)
Convert UTF-16 Hex to Char
int GetUTF32 (string text, int i)
Convert UTF-32 Hex to Char
int GetUTF32 (int[] text, int i)
int GetUTF32 (StringBuilder text, int i)
Convert UTF-32 Hex to Char
Color32 HexCharsToColor (char[] hexChars, int tagCount)
Method to convert Hex color values to Color32
Color32 HexCharsToColor (char[] hexChars, int startIndex, int length)
Method to convert Hex Color values to Color32
float ConvertToFloat (char[] chars, int startIndex, int length)
Extracts a float value from char[] assuming we know the position of the start, end and decimal point.
float ConvertToFloat (char[] chars, int startIndex, int length, out int lastIndex)
Extracts a float value from char[] given a start index and length.
bool ValidateHtmlTag (UnicodeChar[] chars, int startIndex, out int endIndex)
Function to identify and validate the rich tag. Returns the position of the > if the tag was valid.
Protected Attributes
TMP_SubMeshUI[] m_subTextObjects = new TMP_SubMeshUI[8]
Protected Attributes inherited from TMPro.TMP_Text
string m_text
ITextPreprocessor m_TextPreprocessor
bool m_isRightToLeft = false
TMP_FontAsset m_fontAsset
TMP_FontAsset m_currentFontAsset
bool m_isSDFShader
Material m_sharedMaterial
Material m_currentMaterial
MaterialReference[] m_materialReferences = new MaterialReference[32]
Dictionary< int, int > m_materialReferenceIndexLookup = new Dictionary<int, int>()
TMP_TextProcessingStack< MaterialReference > m_materialReferenceStack = new TMP_TextProcessingStack<MaterialReference>(new MaterialReference[16])
int m_currentMaterialIndex
Material[] m_fontSharedMaterials
Material m_fontMaterial
Material[] m_fontMaterials
bool m_isMaterialDirty
Color32 m_fontColor32 = Color.white
Color m_fontColor = Color.white
Color32 m_underlineColor = s_colorWhite
Color32 m_strikethroughColor = s_colorWhite
bool m_enableVertexGradient
ColorMode m_colorMode = ColorMode.FourCornersGradient
VertexGradient m_fontColorGradient = new VertexGradient(Color.white)
TMP_ColorGradient m_fontColorGradientPreset
TMP_SpriteAsset m_spriteAsset
bool m_tintAllSprites
bool m_tintSprite
Color32 m_spriteColor
TMP_StyleSheet m_StyleSheet
int m_TextStyleHashCode
bool m_overrideHtmlColors = false
Color32 m_faceColor = Color.white
Color32 m_outlineColor = Color.black
float m_outlineWidth = 0.0f
float m_fontSize = 36
float m_currentFontSize
float m_fontSizeBase = 36
TMP_TextProcessingStack< float > m_sizeStack = new TMP_TextProcessingStack<float>(16)
FontWeight m_fontWeight = FontWeight.Regular
FontWeight m_FontWeightInternal = FontWeight.Regular
TMP_TextProcessingStack< FontWeight > m_FontWeightStack = new TMP_TextProcessingStack<FontWeight>(8)
bool m_enableAutoSizing
float m_maxFontSize
float m_minFontSize
int m_AutoSizeIterationCount
int m_AutoSizeMaxIterationCount = 100
bool m_IsAutoSizePointSizeSet
float m_fontSizeMin = 0
float m_fontSizeMax = 0
FontStyles m_fontStyle = FontStyles.Normal
FontStyles m_FontStyleInternal = FontStyles.Normal
TMP_FontStyleStack m_fontStyleStack
bool m_isUsingBold = false
HorizontalAlignmentOptions m_HorizontalAlignment = HorizontalAlignmentOptions.Left
VerticalAlignmentOptions m_VerticalAlignment = VerticalAlignmentOptions.Top
TextAlignmentOptions m_textAlignment = TextAlignmentOptions.Converted
HorizontalAlignmentOptions m_lineJustification
TMP_TextProcessingStack< HorizontalAlignmentOptions > m_lineJustificationStack = new TMP_TextProcessingStack<HorizontalAlignmentOptions>(new HorizontalAlignmentOptions[16])
Vector3[] m_textContainerLocalCorners = new Vector3[4]
float m_characterSpacing = 0
float m_cSpacing = 0
float m_monoSpacing = 0
float m_wordSpacing = 0
float m_lineSpacing = 0
float m_lineSpacingDelta = 0
float m_lineHeight = TMP_Math.FLOAT_UNSET
bool m_IsDrivenLineSpacing
float m_lineSpacingMax = 0
float m_paragraphSpacing = 0
float m_charWidthMaxAdj = 0f
float m_charWidthAdjDelta = 0
bool m_enableWordWrapping = false
bool m_isCharacterWrappingEnabled = false
bool m_isNonBreakingSpace = false
bool m_isIgnoringAlignment
float m_wordWrappingRatios = 0.4f
TextOverflowModes m_overflowMode = TextOverflowModes.Overflow
int m_firstOverflowCharacterIndex = -1
TMP_Text m_linkedTextComponent
bool m_isTextTruncated
bool m_enableKerning
float m_GlyphHorizontalAdvanceAdjustment
bool m_enableExtraPadding = false
bool checkPaddingRequired
bool m_isRichText = true
bool m_parseCtrlCharacters = true
bool m_isOverlay = false
bool m_isOrthographic = false
bool m_isCullingEnabled = false
bool m_isMaskingEnabled
bool isMaskUpdateRequired
bool m_ignoreCulling = true
TextureMappingOptions m_horizontalMapping = TextureMappingOptions.Character
TextureMappingOptions m_verticalMapping = TextureMappingOptions.Character
float m_uvLineOffset = 0.0f
TextRenderFlags m_renderMode = TextRenderFlags.Render
VertexSortingOrder m_geometrySortingOrder
bool m_IsTextObjectScaleStatic
bool m_VertexBufferAutoSizeReduction = true
int m_firstVisibleCharacter
int m_maxVisibleCharacters = 99999
int m_maxVisibleWords = 99999
int m_maxVisibleLines = 99999
bool m_useMaxVisibleDescender = true
int m_pageToDisplay = 1
bool m_isNewPage = false
Vector4 m_margin = new Vector4(0, 0, 0, 0)
float m_marginLeft
float m_marginRight
float m_marginWidth
float m_marginHeight
float m_width = -1
TMP_TextInfo m_textInfo
bool m_havePropertiesChanged
bool m_isUsingLegacyAnimationComponent
Transform m_transform
RectTransform m_rectTransform
Vector2 m_PreviousRectTransformSize
Used to track potential changes in RectTransform size to allow us to ignore OnRectTransformDimensionsChange getting called due to rounding errors when using Stretch Anchors.
Vector2 m_PreviousPivotPosition
Used to track potential changes in pivot position to allow us to ignore OnRectTransformDimensionsChange getting called due to rounding errors when using Stretch Anchors.
bool m_autoSizeTextContainer
Mesh m_mesh
bool m_isVolumetricText
TMP_SpriteAnimator m_spriteAnimator
float m_flexibleHeight = -1f
float m_flexibleWidth = -1f
float m_minWidth
float m_minHeight
float m_maxWidth
float m_maxHeight
LayoutElement m_LayoutElement
float m_preferredWidth
float m_renderedWidth
bool m_isPreferredWidthDirty
float m_preferredHeight
float m_renderedHeight
bool m_isPreferredHeightDirty
bool m_isCalculatingPreferredValues
int m_layoutPriority = 0
bool m_isLayoutDirty
bool m_isAwake
float m_fontScale
float m_fontScaleMultiplier
char[] m_htmlTag = new char[128]
RichTextTagAttribute[] m_xmlAttribute = new RichTextTagAttribute[8]
float[] m_attributeParameterValues = new float[16]
float tag_LineIndent = 0
float tag_Indent = 0
TMP_TextProcessingStack< float > m_indentStack = new TMP_TextProcessingStack<float>(new float[16])
bool tag_NoParsing
bool m_isParsingText
Matrix4x4 m_FXMatrix
bool m_isFXMatrixSet
UnicodeChar[] m_InternalParsingBuffer = new UnicodeChar[8]
Array containing the Unicode characters to be parsed.
int m_InternalParsingBufferSize
The number of Unicode characters that have been parsed and contained in the m_InternalParsingBuffer
char[] m_input_CharArray = new char[256]
int m_totalCharacterCount
WordWrapState m_SavedWordWrapState = new WordWrapState()
WordWrapState m_SavedLineState = new WordWrapState()
WordWrapState m_SavedEllipsisState = new WordWrapState()
WordWrapState m_SavedLastValidState = new WordWrapState()
WordWrapState m_SavedSoftLineBreakState = new WordWrapState()
int m_characterCount
int m_firstCharacterOfLine
int m_firstVisibleCharacterOfLine
int m_lastCharacterOfLine
int m_lastVisibleCharacterOfLine
int m_lineNumber
int m_lineVisibleCharacterCount
int m_pageNumber
float m_PageAscender
float m_maxTextAscender
float m_maxCapHeight
float m_ElementAscender
float m_ElementDescender
float m_maxLineAscender
float m_maxLineDescender
float m_startOfLineAscender
float m_startOfLineDescender
float m_lineOffset
Extents m_meshExtents
Color32 m_htmlColor = new Color(255, 255, 255, 128)
TMP_TextProcessingStack< Color32 > m_colorStack = new TMP_TextProcessingStack<Color32>(new Color32[16])
TMP_TextProcessingStack< Color32 > m_underlineColorStack = new TMP_TextProcessingStack<Color32>(new Color32[16])
TMP_TextProcessingStack< Color32 > m_strikethroughColorStack = new TMP_TextProcessingStack<Color32>(new Color32[16])
TMP_TextProcessingStack< HighlightState > m_HighlightStateStack = new TMP_TextProcessingStack<HighlightState>(new HighlightState[16])
TMP_ColorGradient m_colorGradientPreset
TMP_TextProcessingStack< TMP_ColorGradient > m_colorGradientStack = new TMP_TextProcessingStack<TMP_ColorGradient>(new TMP_ColorGradient[16])
bool m_colorGradientPresetIsTinted
float m_tabSpacing = 0
float m_spacing = 0
TMP_TextProcessingStack< int >[] m_TextStyleStacks = new TMP_TextProcessingStack<int>[8]
int m_TextStyleStackDepth = 0
TMP_TextProcessingStack< int > m_ItalicAngleStack = new TMP_TextProcessingStack<int>(new int[16])
int m_ItalicAngle
TMP_TextProcessingStack< int > m_actionStack = new TMP_TextProcessingStack<int>(new int[16])
float m_padding = 0
float m_baselineOffset
TMP_TextProcessingStack< float > m_baselineOffsetStack = new TMP_TextProcessingStack<float>(new float[16])
float m_xAdvance
TMP_TextElementType m_textElementType
TMP_TextElement m_cached_TextElement
SpecialCharacter m_Ellipsis
SpecialCharacter m_Underline
TMP_SpriteAsset m_defaultSpriteAsset
TMP_SpriteAsset m_currentSpriteAsset
int m_spriteCount = 0
int m_spriteIndex
int m_spriteAnimationID
bool m_ignoreActiveState
Properties
override Material materialForRendering [get]
Get the material that will be used for rendering.
override bool autoSizeTextContainer [get, set]
Determines if the size of the text container will be adjusted to fit the text object when it is first created.
override Mesh mesh [get]
Reference to the Mesh used by the text object.
new CanvasRenderer canvasRenderer [get]
Reference to the CanvasRenderer used by the text object.
Vector4 maskOffset [get, set]
Sets the masking offset from the bounds of the object
Properties inherited from TMPro.TMP_Text
virtual string text [get, set]
A string containing the text to be displayed.
ITextPreprocessor textPreprocessor [get, set]
The ITextPreprocessor component referenced by the text object (if any)
bool isRightToLeftText [get, set]
TMP_FontAsset font [get, set]
The Font Asset to be assigned to this text object.
virtual Material fontSharedMaterial [get, set]
The material to be assigned to this text object.
virtual Material[] fontSharedMaterials [get, set]
An array containing the materials used by the text object.
Material fontMaterial [get, set]
The material to be assigned to this text object. An instance of the material will be assigned to the object's renderer.
virtual Material[] fontMaterials [get, set]
The materials to be assigned to this text object. An instance of the materials will be assigned.
override Color color [get, set]
This is the default vertex color assigned to each vertices. Color tags will override vertex colors unless the overrideColorTags is set.
float alpha [get, set]
Sets the vertex color alpha value.
bool enableVertexGradient [get, set]
Determines if Vertex Color Gradient should be used
VertexGradient colorGradient [get, set]
Sets the vertex colors for each of the 4 vertices of the character quads.
TMP_ColorGradient colorGradientPreset [get, set]
Set the vertex colors of the 4 vertices of each character quads.
TMP_SpriteAsset spriteAsset [get, set]
Sprite Asset used by the text object.
bool tintAllSprites [get, set]
Determines whether or not the sprite color is multiplies by the vertex color of the text.
TMP_StyleSheet styleSheet [get, set]
Style sheet used by the text object.
TMP_Style textStyle [get, set]
bool overrideColorTags [get, set]
This overrides the color tags forcing the vertex colors to be the default font color.
Color32 faceColor [get, set]
Sets the color of the _FaceColor property of the assigned material. Changing face color will result in an instance of the material.
Color32 outlineColor [get, set]
Sets the color of the _OutlineColor property of the assigned material. Changing outline color will result in an instance of the material.
float outlineWidth [get, set]
Sets the thickness of the outline of the font. Setting this value will result in an instance of the material.
float fontSize [get, set]
The point size of the font.
float fontScale [get]
The scale of the current text.
FontWeight fontWeight [get, set]
Control the weight of the font if an alternative font asset is assigned for the given weight in the font asset editor.
float pixelsPerUnit [get]
bool enableAutoSizing [get, set]
Enable text auto-sizing
float fontSizeMin [get, set]
Minimum point size of the font when text auto-sizing is enabled.
float fontSizeMax [get, set]
Maximum point size of the font when text auto-sizing is enabled.
FontStyles fontStyle [get, set]
The style of the text
bool isUsingBold [get]
Property used in conjunction with padding calculation for the geometry.
HorizontalAlignmentOptions horizontalAlignment [get, set]
Horizontal alignment options
VerticalAlignmentOptions verticalAlignment [get, set]
Vertical alignment options
TextAlignmentOptions alignment [get, set]
Text alignment options
float characterSpacing [get, set]
Use the extents of the text geometry for alignment instead of font metrics.
float wordSpacing [get, set]
The amount of additional spacing between words.
float lineSpacing [get, set]
The amount of additional spacing to add between each lines of text.
float lineSpacingAdjustment [get, set]
The amount of potential line spacing adjustment before text auto sizing kicks in.
float paragraphSpacing [get, set]
The amount of additional spacing to add between each lines of text.
float characterWidthAdjustment [get, set]
Percentage the width of characters can be adjusted before text auto-sizing begins to reduce the point size.
bool enableWordWrapping [get, set]
Controls whether or not word wrapping is applied. When disabled, the text will be displayed on a single line.
float wordWrappingRatios [get, set]
Controls the blending between using character and word spacing to fill-in the space for justified text.
TextOverflowModes overflowMode [get, set]
bool isTextOverflowing [get]
Indicates if the text exceeds the vertical bounds of its text container.
int firstOverflowCharacterIndex [get]
The first character which exceeds the vertical bounds of its text container.
TMP_Text linkedTextComponent [get, set]
The linked text component used for flowing the text from one text component to another.
bool isTextTruncated [get]
Property indicating whether the text is Truncated or using Ellipsis.
bool enableKerning [get, set]
Determines if kerning is enabled or disabled.
bool extraPadding [get, set]
Adds extra padding around each character. This may be necessary when the displayed text is very small to prevent clipping.
bool richText [get, set]
Enables or Disables Rich Text Tags
bool parseCtrlCharacters [get, set]
Enables or Disables parsing of CTRL characters in input text.
bool isOverlay [get, set]
Sets the RenderQueue along with Ztest to force the text to be drawn last and on top of scene elements.
bool isOrthographic [get, set]
Sets Perspective Correction to Zero for Orthographic Camera mode & 0.875f for Perspective Camera mode.
bool enableCulling [get, set]
Sets the culling on the shaders. Note changing this value will result in an instance of the material.
bool ignoreVisibility [get, set]
Forces objects that are not visible to get refreshed.
TextureMappingOptions horizontalMapping [get, set]
Controls how the face and outline textures will be applied to the text object.
TextureMappingOptions verticalMapping [get, set]
Controls how the face and outline textures will be applied to the text object.
float mappingUvLineOffset [get, set]
Controls the UV Offset for the various texture mapping mode on the text object.
TextRenderFlags renderMode [get, set]
Determines if the Mesh will be rendered.
VertexSortingOrder geometrySortingOrder [get, set]
Determines the sorting order of the geometry of the text object.
bool isTextObjectScaleStatic [get, set]
Determines if a text object will be excluded from the InternalUpdate callback used to handle updates of SDF Scale when the scale of the text object or parent(s) changes.
bool vertexBufferAutoSizeReduction [get, set]
Determines if the data structures allocated to contain the geometry of the text object will be reduced in size if the number of characters required to display the text is reduced by more than 256 characters. This reduction has the benefit of reducing the amount of vertex data being submitted to the graphic device but results in GC when it occurs.
int firstVisibleCharacter [get, set]
The first character which should be made visible in conjunction with the Text Overflow Linked mode.
int maxVisibleCharacters [get, set]
Allows to control how many characters are visible from the input.
int maxVisibleWords [get, set]
Allows to control how many words are visible from the input.
int maxVisibleLines [get, set]
Allows control over how many lines of text are displayed.
bool useMaxVisibleDescender [get, set]
Determines if the text's vertical alignment will be adjusted based on visible descender of the text.
int pageToDisplay [get, set]
Controls which page of text is shown
virtual Vector4 margin [get, set]
The margins of the text object.
TMP_TextInfo textInfo [get]
Returns data about the text object which includes information about each character, word, line, link, etc.
bool havePropertiesChanged [get, set]
Property tracking if any of the text properties have changed. Flag is set before the text is regenerated.
bool isUsingLegacyAnimationComponent [get, set]
Property to handle legacy animation component.
new Transform transform [get]
Returns are reference to the Transform
new RectTransform rectTransform [get]
Returns are reference to the RectTransform
virtual bool autoSizeTextContainer [get, set]
Enables control over setting the size of the text container to match the text object.
virtual Mesh mesh [get]
The mesh used by the font asset and material assigned to the text object.
bool isVolumetricText [get, set]
Determines if the geometry of the characters will be quads or volumetric (cubes).
Bounds bounds [get]
Returns the bounds of the mesh of the text object in world space.
Bounds textBounds [get]
Returns the bounds of the text of the text object.
TMP_SpriteAnimator spriteAnimator [get]
Component used to control wrapping of text following some arbitrary shape.
float flexibleHeight [get]
float flexibleWidth [get]
float minWidth [get]
float minHeight [get]
float maxWidth [get]
float maxHeight [get]
LayoutElement layoutElement [get]
virtual float preferredWidth [get]
Computed preferred width of the text object.
virtual float preferredHeight [get]
Computed preferred height of the text object.
virtual float renderedWidth [get]
Compute the rendered width of the text object.
virtual float renderedHeight [get]
Compute the rendered height of the text object.
int layoutPriority [get]
Events
override Action< TMP_TextInfo > OnPreRenderText
Event to allow users to modify the content of the text info before the text is rendered.
Events inherited from TMPro.TMP_Text
static Func< int, string, TMP_FontAsset > OnFontAssetRequest
Event delegate to allow custom loading of TMP_FontAsset when using the <font="Font Asset Name"> tag.
static Func< int, string, TMP_SpriteAsset > OnSpriteAssetRequest
Event delegate to allow custom loading of TMP_SpriteAsset when using the <sprite="Sprite Asset Name"> tag.
virtual Action< TMP_TextInfo > OnPreRenderText = delegate { }
Event delegate to allow modifying the text geometry before it is uploaded to the mesh and rendered.
Additional Inherited Members
Static Protected Attributes inherited from TMPro.TMP_Text
static Color32 s_colorWhite = new Color32(255, 255, 255, 255)
static Vector2 k_LargePositiveVector2 = new Vector2(TMP_Math.INT_MAX, TMP_Math.INT_MAX)
static Vector2 k_LargeNegativeVector2 = new Vector2(TMP_Math.INT_MIN, TMP_Math.INT_MIN)
static float k_LargePositiveFloat = TMP_Math.FLOAT_MAX
static float k_LargeNegativeFloat = TMP_Math.FLOAT_MIN
static int k_LargePositiveInt = TMP_Math.INT_MAX
static int k_LargeNegativeInt = TMP_Math.INT_MIN
Member Function Documentation
Awake()
override void TMPro.TextMeshProUGUI.Awake () protected
References TMPro.TMP_Settings.instance, TMPro.TMP_Text.LoadDefaultSettings(), TMPro.TextMeshProUGUI.LoadFontAsset(), TMPro.TMP_Text.m_cached_TextElement, TMPro.TMP_Text.m_havePropertiesChanged, TMPro.TMP_Text.m_InternalParsingBuffer, TMPro.TMP_Text.m_isAwake, TMPro.TMP_Text.m_isOrthographic, TMPro.TMP_Text.m_mesh, TMPro.TMP_Text.m_rectTransform, TMPro.TextMeshProUGUI.m_subTextObjects, and TMPro.TMP_Text.m_textInfo.
CalculateLayoutInputHorizontal()
void TMPro.TextMeshProUGUI.CalculateLayoutInputHorizontal ()
Function called by Unity when the horizontal layout needs to be recalculated.
CalculateLayoutInputVertical()
void TMPro.TextMeshProUGUI.CalculateLayoutInputVertical ()
Function called by Unity when the vertical layout needs to be recalculated.
ClearMesh()
override void TMPro.TextMeshProUGUI.ClearMesh () virtual
Function to clear the geometry of the Primary and Sub Text objects.
Reimplemented from TMPro.TMP_Text.
References TMPro.TextMeshProUGUI.canvasRenderer, and TMPro.TextMeshProUGUI.m_subTextObjects.
Referenced by TMPro.TextMeshProUGUI.GenerateTextMesh().
ComputeMarginSize()
override void TMPro.TextMeshProUGUI.ComputeMarginSize () virtual
Update the margin width and height
Reimplemented from TMPro.TMP_Text.
References TMPro.TextMeshProUGUI.GetTextContainerLocalCorners(), TMPro.TMP_Text.m_margin, TMPro.TMP_Text.m_marginHeight, TMPro.TMP_Text.m_marginWidth, TMPro.TMP_Text.m_PreviousPivotPosition, TMPro.TMP_Text.m_PreviousRectTransformSize, TMPro.TMP_Text.m_rectTransform, and TMPro.TMP_Text.rectTransform.
Referenced by TMPro.TextMeshProUGUI.GetTextInfo(), TMPro.TextMeshProUGUI.OnEnable(), TMPro.TextMeshProUGUI.OnRectTransformDimensionsChange(), and TMPro.TextMeshProUGUI.OnTransformParentChanged().
Cull()
override void TMPro.TextMeshProUGUI.Cull (Rect clipRect, bool validRect)
Method called when Stencil Mask needs to be updated on this element and parents.
Override of the Cull function to provide for the ability to override the culling of the text object.
Parameters
clipRect
validRect
References TMPro.TMP_Text.m_isLayoutDirty, TMPro.TextMeshProUGUI.m_subTextObjects, and TMPro.TMP_UpdateManager.RegisterTextElementForCullingUpdate().
DestroySubMeshObjects()
override void TMPro.TextMeshProUGUI.DestroySubMeshObjects () protected virtual
Destroy Sub Mesh Objects
Reimplemented from TMPro.TMP_Text.
References TMPro.TextMeshProUGUI.m_subTextObjects.
ForceMeshUpdate()
override void TMPro.TextMeshProUGUI.ForceMeshUpdate (bool ignoreActiveState = false, bool forceTextReparsing = false) virtual
Function to force regeneration of the text object before its normal process time. This is useful when changes to the text object properties need to be applied immediately.
Parameters
ignoreActiveState Ignore Active State of text objects. Inactive objects are ignored by default.
forceTextReparsing Force re-parsing of the text.
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.m_havePropertiesChanged, and TMPro.TMP_Text.m_ignoreActiveState.
GenerateTextMesh()
override void TMPro.TextMeshProUGUI.GenerateTextMesh () protected virtual
This is the main function that is responsible for creating / displaying the text.
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.AdjustLineOffset(), TMPro.TMP_LineInfo.alignment, TMPro.TMP_CharacterInfo.ascender, TMPro.TMP_LineInfo.ascender, TMPro.TMP_PageInfo.ascender, TMPro.TMP_CharacterInfo.aspectRatio, TMPro.TMP_CharacterInfo.baseLine, TMPro.TMP_LineInfo.baseline, TMPro.TMP_FontAsset.boldSpacing, TMPro.TMP_FontAsset.boldStyle, TMPro.TMP_Offset.bottom, TMPro.TMP_CharacterInfo.bottomLeft, TMPro.TMP_CharacterInfo.bottomRight, TMPro.TMP_CharacterInfo.character, TMPro.TMP_Text.SpecialCharacter.character, TMPro.TMP_LineInfo.characterCount, TMPro.TMP_TextInfo.characterCount, TMPro.TMP_WordInfo.characterCount, TMPro.TMP_TextInfo.characterInfo, TMPro.TMP_FontAsset.characterLookupTable, TMPro.TMP_MeshInfo.Clear(), TMPro.TMP_TextInfo.Clear(), TMPro.TMP_FontStyleStack.Clear(), TMPro.TMP_TextProcessingStack< T >.Clear(), TMPro.TMP_TextInfo.ClearLineInfo(), TMPro.TextMeshProUGUI.ClearMesh(), TMPro.TMP_MeshInfo.ClearUnusedVertices(), TMPro.HighlightState.color, TMPro.TMP_CharacterInfo.color, TMPro.TMP_MeshInfo.colors32, TMPro.TMP_CharacterInfo.descender, TMPro.TMP_LineInfo.descender, TMPro.TMP_PageInfo.descender, TMPro.TMP_Text.DrawTextHighlight(), TMPro.TMP_Text.DrawUnderlineMesh(), TMPro.TMP_CharacterInfo.elementType, TMPro.TMP_Text.FillCharacterVertexBuffers(), TMPro.TMP_Text.FillSpriteVertexBuffers(), TMPro.TMP_LineInfo.firstCharacterIndex, TMPro.TMP_PageInfo.firstCharacterIndex, TMPro.TMP_WordInfo.firstCharacterIndex, TMPro.TMP_Text.firstVisibleCharacter, TMPro.TMP_LineInfo.firstVisibleCharacterIndex, TMPro.TMP_Settings.LineBreakingTable.followingCharacters, TMPro.TMP_Text.font, TMPro.TMP_CharacterInfo.fontAsset, TMPro.TMP_Text.SpecialCharacter.fontAsset, TMPro.TMP_Text.fontScale, TMPro.TMP_Text.ForceMeshUpdate(), TMPro.TMP_CharacterInfo.highlightState, TMPro.TMP_Text.CharacterSubstitution.index, TMPro.TMP_Text.InsertNewLine(), TMPro.TMP_CharacterInfo.isUsingAlternateTypeface, TMPro.TMP_CharacterInfo.isVisible, TMPro.TMP_FontAsset.italicStyle, TMPro.TMP_Text.k_LargeNegativeFloat, TMPro.TMP_Text.k_LargeNegativeVector2, TMPro.TMP_Text.k_LargePositiveFloat, TMPro.TMP_Text.k_LargePositiveVector2, TMPro.TMP_LineInfo.lastCharacterIndex, TMPro.TMP_PageInfo.lastCharacterIndex, TMPro.TMP_WordInfo.lastCharacterIndex, TMPro.TMP_LineInfo.lastVisibleCharacterIndex, TMPro.TMP_Settings.LineBreakingTable.leadingCharacters, TMPro.TMP_Offset.left, TMPro.TMP_LineInfo.length, TMPro.TMP_Settings.linebreakingRules, TMPro.TMP_TextInfo.lineCount, TMPro.TMP_LineInfo.lineExtents, TMPro.TMP_LineInfo.lineHeight, TMPro.TMP_TextInfo.lineInfo, TMPro.TMP_CharacterInfo.lineNumber, TMPro.WordWrapState.lineNumber, TMPro.WordWrapState.lineOffset, TMPro.TMP_Text.m_actionStack, TMPro.TMP_Text.m_AutoSizeIterationCount, TMPro.TMP_Text.m_AutoSizeMaxIterationCount, TMPro.TMP_Text.m_baselineOffset, TMPro.TMP_Text.m_baselineOffsetStack, TMPro.TMP_Text.m_cached_TextElement, TMPro.TMP_Text.m_characterCount, TMPro.TMP_Text.m_characterSpacing, TMPro.TMP_Text.m_charWidthAdjDelta, TMPro.TMP_Text.m_charWidthMaxAdj, TMPro.TMP_Text.m_colorGradientPreset, TMPro.TMP_Text.m_colorGradientStack, TMPro.TMP_Text.m_colorStack, TMPro.TMP_Text.m_cSpacing, TMPro.TMP_Text.m_currentFontAsset, TMPro.TMP_Text.m_currentFontSize, TMPro.TMP_Text.m_currentMaterial, TMPro.TMP_Text.m_currentMaterialIndex, TMPro.TMP_Text.m_currentSpriteAsset, TMPro.TMP_Text.m_ElementAscender, TMPro.TMP_Text.m_ElementDescender, TMPro.TMP_Text.m_Ellipsis, TMPro.TMP_Text.m_enableAutoSizing, TMPro.TMP_Text.m_enableKerning, TMPro.TMP_Text.m_enableWordWrapping, TMPro.TMP_Text.m_firstCharacterOfLine, TMPro.TMP_Text.m_firstOverflowCharacterIndex, TMPro.TMP_Text.m_firstVisibleCharacter, TMPro.TMP_Text.m_firstVisibleCharacterOfLine, TMPro.TMP_Text.m_fontAsset, TMPro.TMP_Text.m_fontColor, TMPro.TMP_Text.m_fontColor32, TMPro.TMP_Text.m_fontScale, TMPro.TMP_Text.m_fontScaleMultiplier, TMPro.TMP_Text.m_fontSize, TMPro.TMP_Text.m_fontSizeMax, TMPro.TMP_Text.m_fontSizeMin, TMPro.TMP_Text.m_fontStyle, TMPro.TMP_Text.m_FontStyleInternal, TMPro.TMP_Text.m_fontStyleStack, TMPro.TMP_Text.m_fontWeight, TMPro.TMP_Text.m_FontWeightInternal, TMPro.TMP_Text.m_FontWeightStack, TMPro.TMP_Text.m_FXMatrix, TMPro.TMP_Text.m_geometrySortingOrder, TMPro.TMP_Text.m_GlyphHorizontalAdvanceAdjustment, TMPro.TMP_Text.m_HighlightStateStack, TMPro.TMP_Text.m_HorizontalAlignment, TMPro.TMP_Text.m_horizontalMapping, TMPro.TMP_Text.m_htmlColor, TMPro.TMP_Text.m_indentStack, TMPro.TMP_Text.m_InternalParsingBuffer, TMPro.TMP_Text.m_IsAutoSizePointSizeSet, TMPro.TMP_Text.m_IsDrivenLineSpacing, TMPro.TMP_Text.m_isFXMatrixSet, TMPro.TMP_Text.m_isNewPage, TMPro.TMP_Text.m_isNonBreakingSpace, TMPro.TMP_Text.m_isOrthographic, TMPro.TMP_Text.m_isParsingText, TMPro.TMP_Text.m_isRichText, TMPro.TMP_Text.m_isRightToLeft, TMPro.TMP_Text.m_isTextTruncated, TMPro.TMP_Text.m_ItalicAngle, TMPro.TMP_Text.m_ItalicAngleStack, TMPro.TMP_Text.m_lastCharacterOfLine, TMPro.TMP_Text.m_lastVisibleCharacterOfLine, TMPro.TMP_Text.m_lineHeight, TMPro.TMP_Text.m_lineJustification, TMPro.TMP_Text.m_lineJustificationStack, TMPro.TMP_Text.m_lineNumber, TMPro.TMP_Text.m_lineOffset, TMPro.TMP_Text.m_lineSpacing, TMPro.TMP_Text.m_lineSpacingDelta, TMPro.TMP_Text.m_lineSpacingMax, TMPro.TMP_Text.m_lineVisibleCharacterCount, TMPro.TMP_Text.m_linkedTextComponent, TMPro.TMP_Text.m_margin, TMPro.TMP_Text.m_marginHeight, TMPro.TMP_Text.m_marginLeft, TMPro.TMP_Text.m_marginRight, TMPro.TMP_Text.m_marginWidth, TMPro.TMP_Text.m_materialReferences, TMPro.TMP_Text.m_materialReferenceStack, TMPro.TMP_Text.m_maxCapHeight, TMPro.TMP_Text.m_maxFontSize, TMPro.TMP_Text.m_maxLineAscender, TMPro.TMP_Text.m_maxLineDescender, TMPro.TMP_Text.m_maxTextAscender, TMPro.TMP_Text.m_maxVisibleCharacters, TMPro.TMP_Text.m_maxVisibleLines, TMPro.TMP_Text.m_maxVisibleWords, TMPro.TMP_Text.m_mesh, TMPro.TMP_Text.m_meshExtents, TMPro.TMP_Text.m_minFontSize, TMPro.TMP_Text.m_monoSpacing, TMPro.TMP_Text.m_overflowMode, TMPro.TMP_Text.m_overrideHtmlColors, TMPro.TMP_Text.m_padding, TMPro.TMP_Text.m_PageAscender, TMPro.TMP_Text.m_pageNumber, TMPro.TMP_Text.m_pageToDisplay, TMPro.TMP_Text.m_paragraphSpacing, TMPro.TMP_Text.m_preferredHeight, TMPro.TMP_Text.m_preferredWidth, TMPro.TMP_Text.m_renderMode, TMPro.TMP_Text.m_SavedEllipsisState, TMPro.TMP_Text.m_SavedLastValidState, TMPro.TMP_Text.m_SavedLineState, TMPro.TMP_Text.m_SavedSoftLineBreakState, TMPro.TMP_Text.m_SavedWordWrapState, TMPro.TMP_Text.m_sharedMaterial, TMPro.TMP_Text.m_sizeStack, TMPro.TMP_Text.m_spriteAnimator, TMPro.TMP_Text.m_spriteAsset, TMPro.TMP_Text.m_spriteColor, TMPro.TMP_Text.m_spriteCount, TMPro.TMP_Text.m_spriteIndex, TMPro.TMP_Text.m_startOfLineAscender, TMPro.TMP_Text.m_startOfLineDescender, TMPro.TMP_Text.m_strikethroughColor, TMPro.TMP_Text.m_strikethroughColorStack, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textAlignment, TMPro.TMP_Text.m_textElementType, TMPro.TMP_Text.m_textInfo, TMPro.TMP_Text.m_totalCharacterCount, TMPro.TMP_Text.m_Underline, TMPro.TMP_Text.m_underlineColor, TMPro.TMP_Text.m_underlineColorStack, TMPro.TMP_Text.m_useMaxVisibleDescender, TMPro.TMP_Text.m_uvLineOffset, TMPro.TMP_Text.m_VerticalAlignment, TMPro.TMP_Text.m_verticalMapping, TMPro.TMP_Text.m_width, TMPro.TMP_Text.m_wordSpacing, TMPro.TMP_Text.m_wordWrappingRatios, TMPro.TMP_Text.m_xAdvance, TMPro.TMP_LineInfo.marginLeft, TMPro.TMP_LineInfo.marginRight, TMPro.TMP_CharacterInfo.material, TMPro.TMP_Text.SpecialCharacter.material, TMPro.TMP_TextInfo.materialCount, TMPro.TMP_Text.SpecialCharacter.materialIndex, TMPro.TMP_CharacterInfo.materialReferenceIndex, TMPro.Extents.max, TMPro.TMP_LineInfo.maxAdvance, TMPro.TextMeshProUGUI.mesh, TMPro.TMP_SubMeshUI.mesh, TMPro.TMP_TextInfo.meshInfo, TMPro.Extents.min, TMPro.TMP_FontAsset.normalSpacingOffset, TMPro.TMP_FontAsset.normalStyle, TMPro.TextMeshProUGUI.OnPreRenderText, TMPro.TMP_CharacterInfo.origin, TMPro.TMP_Text.PackUV(), TMPro.HighlightState.padding, TMPro.TMP_SubMeshUI.padding, TMPro.TMP_TextInfo.pageCount, TMPro.TMP_TextInfo.pageInfo, TMPro.TMP_CharacterInfo.pageNumber, TMPro.TMP_Text.pageToDisplay, TMPro.TMP_CharacterInfo.pointSize, TMPro.TMP_Vertex.position, TMPro.WordWrapState.previous_WordBreak, TMPro.MaterialReference.referenceCount, TMPro.TMP_Text.ResizeLineExtents(), TMPro.TMP_Text.RestoreWordWrappingState(), TMPro.TMP_Offset.right, TMPro.TMP_Text.s_colorWhite, TMPro.TMP_Text.SaveGlyphVertexInfo(), TMPro.TMP_Text.SaveSpriteVertexInfo(), TMPro.TMP_Text.SaveWordWrappingState(), TMPro.TMP_CharacterInfo.scale, TMPro.TMP_TextProcessingStack< T >.SetDefault(), TMPro.TMP_MeshInfo.SortGeometry(), TMPro.TMP_LineInfo.spaceCount, TMPro.TMP_TextInfo.spaceCount, TMPro.TMP_CharacterInfo.spriteAsset, TMPro.TMP_SpriteAsset.spriteCharacterTable, TMPro.TMP_TextInfo.spriteCount, TMPro.TMP_CharacterInfo.spriteIndex, TMPro.WordWrapState.startOfLineAscender, TMPro.TMP_SpriteAnimator.StopAllAnimations(), TMPro.TMP_CharacterInfo.strikethroughColor, TMPro.TMP_CharacterInfo.strikethroughVertexIndex, TMPro.TMP_CharacterInfo.style, TMPro.TMP_FontAsset.tabSize, TMPro.TMP_Text.tag_Indent, TMPro.TMP_Text.tag_LineIndent, TMPro.TMP_Text.tag_NoParsing, TMPro.TMP_Text.text, TMPro.TMP_WordInfo.textComponent, TMPro.TMP_CharacterInfo.textElement, TMPro.TMP_Offset.top, TMPro.TMP_CharacterInfo.topLeft, TMPro.TMP_CharacterInfo.topRight, TMPro.TMP_Text.transform, TMPro.TMP_CharacterInfo.underlineColor, TMPro.TMP_CharacterInfo.underlineVertexIndex, TMPro.TMP_Text.CharacterSubstitution.unicode, TMPro.TMP_Text.UnicodeChar.unicode, TMPro.TMP_Settings.useModernHangulLineBreakingRules, TMPro.TMP_Vertex.uv2, TMPro.TMP_MeshInfo.uvs0, TMPro.TMP_MeshInfo.uvs2, TMPro.TMP_Text.ValidateHtmlTag(), TMPro.TMP_CharacterInfo.vertex_BL, TMPro.TMP_CharacterInfo.vertex_BR, TMPro.TMP_CharacterInfo.vertex_TL, TMPro.TMP_CharacterInfo.vertex_TR, TMPro.TMP_MeshInfo.vertices, TMPro.TMP_LineInfo.visibleCharacterCount, TMPro.TMP_LineInfo.width, TMPro.TMP_LineInfo.wordCount, TMPro.TMP_TextInfo.wordCount, TMPro.TMP_TextInfo.wordInfo, TMPro.TMP_CharacterInfo.xAdvance, TMPro.TMP_GlyphValueRecord.xAdvance, and TMPro.TMP_Offset.zero.
Referenced by TMPro.TextMeshProUGUI.GetTextInfo().
GetCompoundBounds()
override Bounds TMPro.TextMeshProUGUI.GetCompoundBounds () protected virtual
Method returning the compound bounds of the text object and child sub objects.
Returns
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.m_mesh, TMPro.TextMeshProUGUI.m_subTextObjects, and TMPro.TMP_SubMeshUI.mesh.
GetMaterial()
override Material TMPro.TextMeshProUGUI.GetMaterial (Material mat) protected virtual
Function called internally when a new material is assigned via the fontMaterial property.
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.CreateMaterialInstance(), TMPro.TMP_Text.GetPaddingForMaterial(), TMPro.TMP_Text.m_fontMaterial, TMPro.TMP_Text.m_padding, TMPro.TMP_Text.m_sharedMaterial, TMPro.TextMeshProUGUI.SetMaterialDirty(), and TMPro.TextMeshProUGUI.SetVerticesDirty().
GetMaterials()
override Material [] TMPro.TextMeshProUGUI.GetMaterials (Material[] mats) protected virtual
Method returning instances of the materials used by the text object.
Returns
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.fontMaterial, TMPro.TMP_Text.m_fontMaterials, TMPro.TMP_Text.m_fontSharedMaterials, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textInfo, TMPro.TMP_SubMeshUI.material, and TMPro.TMP_TextInfo.materialCount.
GetModifiedMaterial()
override Material TMPro.TextMeshProUGUI.GetModifiedMaterial (Material baseMaterial)
Parameters
baseMaterial
Returns
References TMPro.TMP_Text.transform.
GetSharedMaterials()
override Material [] TMPro.TextMeshProUGUI.GetSharedMaterials () protected virtual
Method returning an array containing the materials used by the text object.
Returns
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.m_fontSharedMaterials, TMPro.TMP_Text.m_sharedMaterial, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textInfo, TMPro.TMP_TextInfo.materialCount, and TMPro.TMP_SubMeshUI.sharedMaterial.
GetTextContainerLocalCorners()
override Vector3 [] TMPro.TextMeshProUGUI.GetTextContainerLocalCorners () protected virtual
Method to return the local corners of the Text Container or RectTransform.
Returns
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.m_rectTransform, and TMPro.TMP_Text.rectTransform.
Referenced by TMPro.TextMeshProUGUI.ComputeMarginSize().
GetTextInfo()
override TMP_TextInfo TMPro.TextMeshProUGUI.GetTextInfo (string text) virtual
Function used to evaluate the length of a text string.
Parameters
text
Returns
Reimplemented from TMPro.TMP_Text.
References TMPro.TextMeshProUGUI.ComputeMarginSize(), TMPro.TextMeshProUGUI.GenerateTextMesh(), TMPro.TMP_Text.m_InternalParsingBuffer, TMPro.TMP_Text.m_renderMode, TMPro.TextMeshProUGUI.SetArraySizes(), TMPro.TMP_Text.StringToInternalParsingBuffer(), TMPro.TMP_Text.text, and TMPro.TMP_Text.textInfo.
InternalCrossFadeAlpha()
override void TMPro.TextMeshProUGUI.InternalCrossFadeAlpha (float alpha, float duration, bool ignoreTimeScale) protected virtual
Tweens the alpha of the CanvasRenderer color associated with this Graphic.
Parameters
alpha Target alpha.
duration Duration of the tween in seconds.
ignoreTimeScale Should ignore Time.scale?
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.alpha, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textInfo, and TMPro.TMP_TextInfo.materialCount.
InternalCrossFadeColor()
override void TMPro.TextMeshProUGUI.InternalCrossFadeColor (Color targetColor, float duration, bool ignoreTimeScale, bool useAlpha) protected virtual
Tweens the CanvasRenderer color associated with this Graphic.
Parameters
targetColor Target color.
duration Tween duration.
ignoreTimeScale Should ignore Time.scale?
useAlpha Should also Tween the alpha channel?
Reimplemented from TMPro.TMP_Text.
References TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textInfo, and TMPro.TMP_TextInfo.materialCount.
LoadFontAsset()
override void TMPro.TextMeshProUGUI.LoadFontAsset () protected virtual
Method which derived classes need to override to load Font Assets.
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_FontAsset.atlasTexture, TMPro.TMP_FontAsset.characterLookupTable, TMPro.TMP_Settings.defaultFontAsset, TMPro.TMP_Text.GetPaddingForMaterial(), TMPro.TMP_Text.GetSpecialCharacters(), TMPro.TMP_Text.m_fontAsset, TMPro.TMP_Text.m_padding, TMPro.TMP_Text.m_sharedMaterial, TMPro.TMP_Asset.material, TMPro.TMP_FontAsset.ReadFontAssetDefinition(), and TMPro.TextMeshProUGUI.SetMaterialDirty().
Referenced by TMPro.TextMeshProUGUI.Awake(), and TMPro.TextMeshProUGUI.UpdateFontAsset().
OnCanvasHierarchyChanged()
override void TMPro.TextMeshProUGUI.OnCanvasHierarchyChanged () protected
References TMPro.TMP_Text.m_isAwake, and TMPro.TMP_Text.m_IsTextObjectScaleStatic.
OnDestroy()
override void TMPro.TextMeshProUGUI.OnDestroy () protected
References TMPro.TMP_Text.m_mesh.
OnDidApplyAnimationProperties()
override void TMPro.TextMeshProUGUI.OnDidApplyAnimationProperties () protected
References TMPro.TMP_Text.m_havePropertiesChanged, TMPro.TextMeshProUGUI.SetLayoutDirty(), and TMPro.TextMeshProUGUI.SetVerticesDirty().
OnDisable()
override void TMPro.TextMeshProUGUI.OnDisable () protected
References TMPro.TMP_Text.m_isAwake, TMPro.TMP_Text.m_rectTransform, TMPro.TextMeshProUGUI.RecalculateClipping(), and TMPro.TextMeshProUGUI.SetActiveSubMeshes().
OnEnable()
override void TMPro.TextMeshProUGUI.OnEnable () protected
References TMPro.TextMeshProUGUI.ComputeMarginSize(), TMPro.TMP_Text.m_isAwake, TMPro.TMP_Text.m_IsTextObjectScaleStatic, TMPro.TextMeshProUGUI.RecalculateClipping(), TMPro.TextMeshProUGUI.SetActiveSubMeshes(), and TMPro.TextMeshProUGUI.SetAllDirty().
OnRectTransformDimensionsChange()
override void TMPro.TextMeshProUGUI.OnRectTransformDimensionsChange () protected
References TMPro.TextMeshProUGUI.ComputeMarginSize(), TMPro.TMP_Text.m_PreviousPivotPosition, TMPro.TMP_Text.m_PreviousRectTransformSize, TMPro.TMP_Text.m_rectTransform, TMPro.TMP_Text.rectTransform, TMPro.TextMeshProUGUI.SetLayoutDirty(), and TMPro.TextMeshProUGUI.SetVerticesDirty().
OnTransformParentChanged()
override void TMPro.TextMeshProUGUI.OnTransformParentChanged () protected
References TMPro.TextMeshProUGUI.ComputeMarginSize(), and TMPro.TMP_Text.m_havePropertiesChanged.
Rebuild()
override void TMPro.TextMeshProUGUI.Rebuild (CanvasUpdate update)
Parameters
update
References TMPro.TMP_Text.GetPreferredValues(), TMPro.TMP_Text.m_autoSizeTextContainer, TMPro.TMP_Text.m_isMaterialDirty, TMPro.TMP_Text.m_rectTransform, and TMPro.TextMeshProUGUI.UpdateMaterial().
RecalculateClipping()
override void TMPro.TextMeshProUGUI.RecalculateClipping ()
Method called when the state of a parent changes.
Referenced by TMPro.TextMeshProUGUI.OnDisable(), and TMPro.TextMeshProUGUI.OnEnable().
SetActiveSubMeshes()
override void TMPro.TextMeshProUGUI.SetActiveSubMeshes (bool state) protected virtual
Method to Enable or Disable child SubMesh objects.
Parameters
state
Reimplemented from TMPro.TMP_Text.
References TMPro.TextMeshProUGUI.m_subTextObjects.
Referenced by TMPro.TextMeshProUGUI.OnDisable(), and TMPro.TextMeshProUGUI.OnEnable().
SetAllDirty()
override void TMPro.TextMeshProUGUI.SetAllDirty ()
References TMPro.TextMeshProUGUI.SetLayoutDirty(), TMPro.TextMeshProUGUI.SetMaterialDirty(), and TMPro.TextMeshProUGUI.SetVerticesDirty().
Referenced by TMPro.TMP_SubMeshUI.OnDestroy(), and TMPro.TextMeshProUGUI.OnEnable().
SetArraySizes()
override int TMPro.TextMeshProUGUI.SetArraySizes (UnicodeChar[] unicodeChars) protected virtual
Method used to determine the number of visible characters and required buffer allocations.
Parameters
unicodeChars
Returns
Reimplemented from TMPro.TMP_Text.
References TMPro.MaterialReference.AddMaterialReference(), TMPro.TMP_SubMeshUI.AddSubTextObject(), TMPro.TMP_CharacterInfo.character, TMPro.TMP_Text.SpecialCharacter.character, TMPro.TMP_TextInfo.characterInfo, TMPro.TMP_FontStyleStack.Clear(), TMPro.TMP_Text.ClearMesh(), TMPro.TMP_Settings.defaultFontAsset, TMPro.TMP_CharacterInfo.elementType, TMPro.TMP_TextElement.elementType, TMPro.TMP_Settings.fallbackFontAssets, TMPro.MaterialReference.fallbackMaterial, TMPro.TMP_SubMeshUI.fallbackMaterial, TMPro.TMP_SubMeshUI.fallbackSourceMaterial, TMPro.MaterialReference.fontAsset, TMPro.TMP_CharacterInfo.fontAsset, TMPro.TMP_SubMeshUI.fontAsset, TMPro.TMP_Text.SpecialCharacter.fontAsset, TMPro.TMP_FontAssetUtilities.GetCharacterFromFontAsset(), TMPro.TMP_FontAssetUtilities.GetCharacterFromFontAssets(), TMPro.TMP_Text.GetEllipsisSpecialCharacter(), TMPro.TMP_TextElement.glyph, TMPro.TMP_TextElement.glyphIndex, TMPro.TMP_CharacterInfo.index, TMPro.TMP_Asset.instanceID, TMPro.MaterialReference.isFallbackMaterial, TMPro.TMP_CharacterInfo.isUsingAlternateTypeface, TMPro.TMP_Text.UnicodeChar.length, TMPro.TMP_Text.m_currentFontAsset, TMPro.TMP_Text.m_currentMaterial, TMPro.TMP_Text.m_currentMaterialIndex, TMPro.TMP_Text.m_currentSpriteAsset, TMPro.TMP_Text.m_Ellipsis, TMPro.TMP_Text.m_fontAsset, TMPro.TMP_Text.m_fontStyle, TMPro.TMP_Text.m_FontStyleInternal, TMPro.TMP_Text.m_fontStyleStack, TMPro.TMP_Text.m_fontWeight, TMPro.TMP_Text.m_FontWeightInternal, TMPro.TMP_Text.m_FontWeightStack, TMPro.TMP_Text.m_InternalParsingBufferSize, TMPro.TMP_Text.m_isCalculatingPreferredValues, TMPro.TMP_Text.m_isParsingText, TMPro.TMP_Text.m_isRichText, TMPro.TMP_Text.m_isUsingBold, TMPro.TMP_Text.m_linkedTextComponent, TMPro.TMP_Text.m_materialReferenceIndexLookup, TMPro.TMP_Text.m_materialReferences, TMPro.TMP_Text.m_materialReferenceStack, TMPro.TMP_Text.m_mesh, TMPro.TMP_Text.m_overflowMode, TMPro.TMP_Text.m_padding, TMPro.TMP_Text.m_rectTransform, TMPro.TMP_Text.m_sharedMaterial, TMPro.TMP_Text.m_spriteIndex, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textElementType, TMPro.TMP_Text.m_textInfo, TMPro.TMP_Text.m_totalCharacterCount, TMPro.TMP_Text.m_VertexBufferAutoSizeReduction, TMPro.TMP_Settings.matchMaterialPreset, TMPro.MaterialReference.material, TMPro.TMP_Asset.material, TMPro.TMP_CharacterInfo.material, TMPro.TMP_MeshInfo.material, TMPro.TMP_Text.SpecialCharacter.material, TMPro.TMP_TextInfo.materialCount, TMPro.TMP_Text.SpecialCharacter.materialIndex, TMPro.TMP_CharacterInfo.materialReferenceIndex, TMPro.TextMeshProUGUI.mesh, TMPro.TMP_TextInfo.meshInfo, TMPro.TMP_Settings.missingGlyphCharacter, TMPro.MaterialReference.referenceCount, TMPro.TMP_MeshInfo.ResizeMeshInfo(), TMPro.TMP_TextProcessingStack< T >.SetDefault(), TMPro.TMP_SubMeshUI.sharedMaterial, TMPro.MaterialReference.spriteAsset, TMPro.TMP_CharacterInfo.spriteAsset, TMPro.TMP_SubMeshUI.spriteAsset, TMPro.TMP_SpriteAsset.spriteCharacterTable, TMPro.TMP_TextInfo.spriteCount, TMPro.TMP_CharacterInfo.spriteIndex, TMPro.TMP_Text.UnicodeChar.stringIndex, TMPro.TMP_CharacterInfo.stringLength, TMPro.TMP_Text.tag_NoParsing, TMPro.TMP_Text.text, TMPro.TMP_TextElement.textAsset, TMPro.TMP_CharacterInfo.textElement, TMPro.TMP_Text.UnicodeChar.unicode, TMPro.TMP_TextElement.unicode, TMPro.TMP_Text.ValidateHtmlTag(), TMPro.TMP_MeshInfo.vertices, and TMPro.TMP_Settings.warningsDisabled.
Referenced by TMPro.TextMeshProUGUI.GetTextInfo().
SetCulling()
override void TMPro.TextMeshProUGUI.SetCulling () protected virtual
Set the culling mode on the material.
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.m_isCullingEnabled, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TextMeshProUGUI.materialForRendering, and TMPro.TMP_SubMeshUI.materialForRendering.
SetFaceColor()
override void TMPro.TextMeshProUGUI.SetFaceColor (Color32 color) protected virtual
Function called internally to set the face color of the material. This will results in an instance of the material.
Parameters
color
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.color, TMPro.TMP_Text.CreateMaterialInstance(), TMPro.TMP_Text.GetPaddingForMaterial(), TMPro.TMP_Text.m_fontMaterial, TMPro.TMP_Text.m_padding, and TMPro.TMP_Text.m_sharedMaterial.
SetLayoutDirty()
override void TMPro.TextMeshProUGUI.SetLayoutDirty ()
References TMPro.TMP_Text.m_isLayoutDirty, TMPro.TMP_Text.m_isPreferredHeightDirty, TMPro.TMP_Text.m_isPreferredWidthDirty, and TMPro.TMP_Text.rectTransform.
Referenced by TMPro.TextMeshProUGUI.OnDidApplyAnimationProperties(), TMPro.TextMeshProUGUI.OnRectTransformDimensionsChange(), and TMPro.TextMeshProUGUI.SetAllDirty().
SetMaterialDirty()
override void TMPro.TextMeshProUGUI.SetMaterialDirty ()
References TMPro.TMP_Text.m_isMaterialDirty.
Referenced by TMPro.TextMeshProUGUI.GetMaterial(), TMPro.TextMeshProUGUI.LoadFontAsset(), TMPro.TextMeshProUGUI.SetAllDirty(), and TMPro.TextMeshProUGUI.SetSharedMaterial().
SetOutlineColor()
override void TMPro.TextMeshProUGUI.SetOutlineColor (Color32 color) protected virtual
Function called internally to set the outline color of the material. This will results in an instance of the material.
Parameters
color
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.color, TMPro.TMP_Text.CreateMaterialInstance(), TMPro.TMP_Text.GetPaddingForMaterial(), TMPro.TMP_Text.m_fontMaterial, TMPro.TMP_Text.m_padding, and TMPro.TMP_Text.m_sharedMaterial.
SetOutlineThickness()
override void TMPro.TextMeshProUGUI.SetOutlineThickness (float thickness) protected virtual
Function called internally to set the outline thickness property of the material. This will results in an instance of the material.
Parameters
thickness
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.CreateMaterialInstance(), TMPro.TMP_Text.GetPaddingForMaterial(), TMPro.TMP_Text.m_fontMaterial, TMPro.TMP_Text.m_padding, and TMPro.TMP_Text.m_sharedMaterial.
SetShaderDepth()
override void TMPro.TextMeshProUGUI.SetShaderDepth () protected virtual
Set the Render Queue and ZTest mode on the current material
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.m_isOverlay, and TMPro.TMP_Text.m_sharedMaterial.
SetSharedMaterial()
override void TMPro.TextMeshProUGUI.SetSharedMaterial (Material mat) protected virtual
Function called internally when a new shared material is assigned via the fontSharedMaterial property.
Parameters
mat
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.GetPaddingForMaterial(), TMPro.TMP_Text.m_padding, TMPro.TMP_Text.m_sharedMaterial, and TMPro.TextMeshProUGUI.SetMaterialDirty().
SetSharedMaterials()
override void TMPro.TextMeshProUGUI.SetSharedMaterials (Material[] materials) protected virtual
Method used to assign new materials to the text and sub text objects.
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.GetPaddingForMaterial(), TMPro.TMP_Text.m_fontSharedMaterials, TMPro.TMP_Text.m_padding, TMPro.TMP_Text.m_sharedMaterial, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textInfo, TMPro.TMP_TextInfo.materialCount, and TMPro.TMP_SubMeshUI.sharedMaterial.
SetVerticesDirty()
override void TMPro.TextMeshProUGUI.SetVerticesDirty ()
Referenced by TMPro.TextMeshProUGUI.GetMaterial(), TMPro.TextMeshProUGUI.OnDidApplyAnimationProperties(), TMPro.TextMeshProUGUI.OnRectTransformDimensionsChange(), TMPro.TextMeshProUGUI.SetAllDirty(), and TMPro.TMP_SubMeshUI.SetVerticesDirty().
UpdateFontAsset()
void TMPro.TextMeshProUGUI.UpdateFontAsset ()
References TMPro.TextMeshProUGUI.LoadFontAsset().
UpdateGeometry()
override void TMPro.TextMeshProUGUI.UpdateGeometry (Mesh mesh, int index) virtual
Function to update the geometry of the main and sub text objects.
Parameters
mesh
index
Reimplemented from TMPro.TMP_Text.
References TMPro.TextMeshProUGUI.m_subTextObjects, and TMPro.TextMeshProUGUI.mesh.
UpdateMaterial()
override void TMPro.TextMeshProUGUI.UpdateMaterial () protected
References TMPro.TextMeshProUGUI.canvasRenderer, TMPro.TMP_Text.m_sharedMaterial, and TMPro.TextMeshProUGUI.materialForRendering.
Referenced by TMPro.TextMeshProUGUI.Rebuild().
UpdateMeshPadding()
override void TMPro.TextMeshProUGUI.UpdateMeshPadding () virtual
Function to be used to force recomputing of character padding when Shader / Material properties have been changed via script.
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_Text.checkPaddingRequired, TMPro.TMP_Text.m_enableExtraPadding, TMPro.TMP_Text.m_havePropertiesChanged, TMPro.TMP_Text.m_isMaskingEnabled, TMPro.TMP_Text.m_isUsingBold, TMPro.TMP_Text.m_padding, TMPro.TMP_Text.m_sharedMaterial, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textInfo, and TMPro.TMP_TextInfo.materialCount.
UpdateVertexData() [1/2]
override void TMPro.TextMeshProUGUI.UpdateVertexData () virtual
Function to upload the updated vertex data and renderer.
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_MeshInfo.ClearUnusedVertices(), TMPro.TMP_MeshInfo.colors32, TMPro.TMP_Text.m_mesh, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textInfo, TMPro.TMP_TextInfo.materialCount, TMPro.TextMeshProUGUI.mesh, TMPro.TMP_SubMeshUI.mesh, TMPro.TMP_TextInfo.meshInfo, TMPro.TMP_MeshInfo.uvs0, TMPro.TMP_MeshInfo.uvs2, and TMPro.TMP_MeshInfo.vertices.
UpdateVertexData() [2/2]
override void TMPro.TextMeshProUGUI.UpdateVertexData (TMP_VertexDataUpdateFlags flags) virtual
Function to upload the updated vertex data and renderer.
Reimplemented from TMPro.TMP_Text.
References TMPro.TMP_MeshInfo.colors32, TMPro.TMP_Text.m_mesh, TMPro.TextMeshProUGUI.m_subTextObjects, TMPro.TMP_Text.m_textInfo, TMPro.TMP_TextInfo.materialCount, TMPro.TextMeshProUGUI.mesh, TMPro.TMP_SubMeshUI.mesh, TMPro.TMP_TextInfo.meshInfo, TMPro.TMP_MeshInfo.uvs0, TMPro.TMP_MeshInfo.uvs2, and TMPro.TMP_MeshInfo.vertices.
Member Data Documentation
m_subTextObjects
TMP_SubMeshUI [] TMPro.TextMeshProUGUI.m_subTextObjects = new TMP_SubMeshUI[8] protected
Referenced by TMPro.TextMeshProUGUI.Awake(), TMPro.TextMeshProUGUI.ClearMesh(), TMPro.TextMeshProUGUI.Cull(), TMPro.TextMeshProUGUI.DestroySubMeshObjects(), TMPro.TextMeshProUGUI.GenerateTextMesh(), TMPro.TextMeshProUGUI.GetCompoundBounds(), TMPro.TextMeshProUGUI.GetMaterials(), TMPro.TextMeshProUGUI.GetSharedMaterials(), TMPro.TextMeshProUGUI.InternalCrossFadeAlpha(), TMPro.TextMeshProUGUI.InternalCrossFadeColor(), TMPro.TextMeshProUGUI.SetActiveSubMeshes(), TMPro.TextMeshProUGUI.SetArraySizes(), TMPro.TextMeshProUGUI.SetCulling(), TMPro.TextMeshProUGUI.SetSharedMaterials(), TMPro.TextMeshProUGUI.UpdateGeometry(), TMPro.TextMeshProUGUI.UpdateMeshPadding(), and TMPro.TextMeshProUGUI.UpdateVertexData().
Property Documentation
autoSizeTextContainer
override bool TMPro.TextMeshProUGUI.autoSizeTextContainer get set
Determines if the size of the text container will be adjusted to fit the text object when it is first created.
canvasRenderer
new CanvasRenderer TMPro.TextMeshProUGUI.canvasRenderer get
Reference to the CanvasRenderer used by the text object.
Referenced by TMPro.TextMeshProUGUI.ClearMesh(), and TMPro.TextMeshProUGUI.UpdateMaterial().
maskOffset
Vector4 TMPro.TextMeshProUGUI.maskOffset get set
Sets the masking offset from the bounds of the object
materialForRendering
override Material TMPro.TextMeshProUGUI.materialForRendering get
Get the material that will be used for rendering.
Referenced by TMPro.TextMeshProUGUI.SetCulling(), and TMPro.TextMeshProUGUI.UpdateMaterial().
mesh
override Mesh TMPro.TextMeshProUGUI.mesh get
Reference to the Mesh used by the text object.
Referenced by TMPro.TextMeshProUGUI.GenerateTextMesh(), TMPro.TextMeshProUGUI.SetArraySizes(), TMPro.TextMeshProUGUI.UpdateGeometry(), and TMPro.TextMeshProUGUI.UpdateVertexData().
Event Documentation
OnPreRenderText
override Action<TMP_TextInfo> TMPro.TextMeshProUGUI.OnPreRenderText
Event to allow users to modify the content of the text info before the text is rendered.
Referenced by TMPro.TextMeshProUGUI.GenerateTextMesh().
The documentation for this class was generated from the following files:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/TextMeshProUGUI.cs
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/TMPro_UGUI_Private.cs