VirtualTours: UnityEditor.Timeline.EaseClip Class Reference
UnityEditor.Timeline.EaseClip Class Reference
Public Member Functions
override void Overlay (Event evt, WindowState state)
Public Member Functions inherited from UnityEditor.Timeline.Manipulator
bool HandleEvent (WindowState state)
Static Public Attributes
static readonly string EaseInClipText = L10n.Tr("Ease In Clip")
static readonly string EaseOutClipText = L10n.Tr("Ease Out Clip")
static readonly string EaseInText = L10n.Tr("Ease In")
static readonly string EaseOutText = L10n.Tr("Ease Out")
static readonly string DurationFrameText = L10n.Tr(" Duration {0:0.00;-0.00} frames ")
static readonly string DurationSecText = L10n.Tr(" Duration {0:0.00;-0.00} s ")
static readonly string DeltaFrameText = L10n.Tr("({0:+0.00;-0.00} frames)")
static readonly string DeltaSecText = L10n.Tr("({0:+0.00;-0.00} s)")
Protected Member Functions
override bool MouseDown (Event evt, WindowState state)
bool MouseDownInternal (Event evt, WindowState state, TimelineClipHandle handle)
override bool MouseUp (Event evt, WindowState state)
override bool MouseDrag (Event evt, WindowState state)
Protected Member Functions inherited from UnityEditor.Timeline.Manipulator
virtual bool MouseWheel (Event evt, WindowState state)
virtual bool DoubleClick (Event evt, WindowState state)
virtual bool KeyDown (Event evt, WindowState state)
virtual bool KeyUp (Event evt, WindowState state)
virtual bool ContextClick (Event evt, WindowState state)
virtual bool ValidateCommand (Event evt, WindowState state)
virtual bool ExecuteCommand (Event evt, WindowState state)
Member Function Documentation
MouseDown()
override bool UnityEditor.Timeline.EaseClip.MouseDown (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.EaseClip.MouseDownInternal().
MouseDownInternal()
bool UnityEditor.Timeline.EaseClip.MouseDownInternal (Event evt, WindowState state, TimelineClipHandle handle) protected
References UnityEditor.Timeline.WindowState.AddCaptured(), UnityEditor.Timeline.TimelineClipGUI.clip, UnityEngine.Timeline.TimelineClip.clipCaps, UnityEditor.Timeline.TimelineClipHandle.clipGUI, UnityEngine.Timeline.TimelineClip.easeInDuration, UnityEngine.Timeline.TimelineClip.easeOutDuration, UnityEngine.Timeline.TimelineClip.hasBlendIn, UnityEngine.Timeline.TimelineClip.hasBlendOut, UnityEditor.Timeline.TimelineCursors.SetCursor(), and UnityEditor.Timeline.TimelineClipHandle.trimDirection.
Referenced by UnityEditor.Timeline.EaseClip.MouseDown().
MouseDrag()
override bool UnityEditor.Timeline.EaseClip.MouseDrag (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.TimelineClipHandle.clipGUI, UnityEngine.Timeline.TimelineClip.duration, UnityEditor.Timeline.EaseClip.EaseInClipText, UnityEngine.Timeline.TimelineClip.easeInDuration, UnityEditor.Timeline.EaseClip.EaseOutClipText, UnityEngine.Timeline.TimelineClip.easeOutDuration, and UnityEditor.Timeline.WindowState.PixelDeltaToDeltaTime().
MouseUp()
override bool UnityEditor.Timeline.EaseClip.MouseUp (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.WindowState.captured, and UnityEditor.Timeline.TimelineCursors.ClearCursor().
Overlay()
override void UnityEditor.Timeline.EaseClip.Overlay (Event evt, WindowState state) virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.TimelineClipHandle.clipGUI, UnityEditor.Timeline.TimelineItemGUI.rect, UnityEditor.Timeline.TimelineWindow.styles, and UnityEditor.Timeline.DirectorStyles.tinyFont.
Member Data Documentation
DeltaFrameText
readonly string UnityEditor.Timeline.EaseClip.DeltaFrameText = L10n.Tr("({0:+0.00;-0.00} frames)") static
DeltaSecText
readonly string UnityEditor.Timeline.EaseClip.DeltaSecText = L10n.Tr("({0:+0.00;-0.00} s)") static
DurationFrameText
readonly string UnityEditor.Timeline.EaseClip.DurationFrameText = L10n.Tr(" Duration {0:0.00;-0.00} frames ") static
DurationSecText
readonly string UnityEditor.Timeline.EaseClip.DurationSecText = L10n.Tr(" Duration {0:0.00;-0.00} s ") static
EaseInClipText
readonly string UnityEditor.Timeline.EaseClip.EaseInClipText = L10n.Tr("Ease In Clip") static
Referenced by UnityEditor.Timeline.EaseClip.MouseDrag().
EaseInText
readonly string UnityEditor.Timeline.EaseClip.EaseInText = L10n.Tr("Ease In") static
EaseOutClipText
readonly string UnityEditor.Timeline.EaseClip.EaseOutClipText = L10n.Tr("Ease Out Clip") static
Referenced by UnityEditor.Timeline.EaseClip.MouseDrag().
EaseOutText
readonly string UnityEditor.Timeline.EaseClip.EaseOutText = L10n.Tr("Ease Out") static
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Manipulators/Sequence/EaseClip.cs