VirtualTours: TMPro.EditorUtilities.TMP_FontAssetEditor Class Reference
TMPro.EditorUtilities.TMP_FontAssetEditor Class Reference
Public Member Functions
void OnEnable ()
void OnDisable ()
override void OnInspectorGUI ()
Member Function Documentation
OnDisable()
void TMPro.EditorUtilities.TMP_FontAssetEditor.OnDisable ()
OnEnable()
void TMPro.EditorUtilities.TMP_FontAssetEditor.OnEnable ()
References TMPro.TMP_SerializedPropertyHolder.fontAsset, TMPro.TMP_FontAsset.fontFeatureTable, TMPro.KerningTable.kerningPairs, and TMPro.TMP_FontAsset.ReadFontAssetDefinition().
OnInspectorGUI()
override void TMPro.EditorUtilities.TMP_FontAssetEditor.OnInspectorGUI ()
References TMPro.TMP_FontAsset.atlasTextures, TMPro.TMP_FontAsset.characterLookupTable, TMPro.TMP_FontAsset.characterTable, TMPro.TMP_FontAsset.faceInfo, TMPro.TMP_SerializedPropertyHolder.firstCharacter, TMPro.TMP_FontAsset.fontFeatureTable, TMPro.TMP_FontFeatureTable.glyphPairAdjustmentRecords, TMPro.TMP_FontAsset.glyphTable, TMPro.TMP_Asset.material, TMPro.TMP_FontAsset.ReadFontAssetDefinition(), TMPro.TMP_SerializedPropertyHolder.secondCharacter, TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow.ShowFontAtlasCreatorWindow(), TMPro.TMP_FontFeatureTable.SortGlyphPairAdjustmentRecords(), TMPro.TMP_FontAsset.sourceFontFile, and TMPro.TMP_FontAsset.version.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Editor/TMP_FontAssetEditor.cs