VirtualTours: VSCodeEditor.VSCodeScriptEditor Class Reference
VSCodeEditor.VSCodeScriptEditor Class Reference
Public Member Functions
bool TryGetInstallationForPath (string editorPath, out CodeEditor.Installation installation)
void OnGUI ()
void CreateIfDoesntExist ()
void SyncIfNeeded (string[] addedFiles, string[] deletedFiles, string[] movedFiles, string[] movedFromFiles, string[] importedFiles)
void SyncAll ()
bool OpenProject (string path, int line, int column)
VSCodeScriptEditor (IDiscovery discovery, IGenerator projectGeneration)
void Initialize (string editorInstallationPath)
Properties
CodeEditor.Installation[] Installations [get]
Constructor & Destructor Documentation
VSCodeScriptEditor()
VSCodeEditor.VSCodeScriptEditor.VSCodeScriptEditor (IDiscovery discovery, IGenerator projectGeneration)
Member Function Documentation
CreateIfDoesntExist()
void VSCodeEditor.VSCodeScriptEditor.CreateIfDoesntExist ()
References VSCodeEditor.IGenerator.SolutionExists(), and VSCodeEditor.IGenerator.Sync().
Initialize()
void VSCodeEditor.VSCodeScriptEditor.Initialize (string editorInstallationPath)
OnGUI()
void VSCodeEditor.VSCodeScriptEditor.OnGUI ()
OpenProject()
bool VSCodeEditor.VSCodeScriptEditor.OpenProject (string path, int line, int column)
References VSCodeEditor.IGenerator.ProjectDirectory.
SyncAll()
void VSCodeEditor.VSCodeScriptEditor.SyncAll ()
References VSCodeEditor.IGenerator.Sync().
SyncIfNeeded()
void VSCodeEditor.VSCodeScriptEditor.SyncIfNeeded (string[] addedFiles, string[] deletedFiles, string[] movedFiles, string[] movedFromFiles, string[] importedFiles)
References VSCodeEditor.IGenerator.SyncIfNeeded().
TryGetInstallationForPath()
bool VSCodeEditor.VSCodeScriptEditor.TryGetInstallationForPath (string editorPath, out CodeEditor.Installation installation)
References VSCodeEditor.VSCodeScriptEditor.Installations.
Property Documentation
Installations
CodeEditor.Installation [] VSCodeEditor.VSCodeScriptEditor.Installations get
Referenced by VSCodeEditor.VSCodeScriptEditor.TryGetInstallationForPath().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.ide.vscode@1.2.2/Editor/VSCodeScriptEditor.cs