VirtualTours: UnityEditor.Timeline.TimelineAnimationUtilities Class Reference
UnityEditor.Timeline.TimelineAnimationUtilities Class Reference
Classes
struct RigidTransform
Public Types
enum class OffsetEditMode { None = -1 , Translation = 0 , Rotation = 1 }
Static Public Member Functions
static bool ValidateOffsetAvailabitity (PlayableDirector director, Animator animator)
static TimelineClip GetPreviousClip (TimelineClip clip)
static TimelineClip GetNextClip (TimelineClip clip)
static RigidTransform UpdateClipOffsets (AnimationPlayableAsset asset, AnimationTrack track, Transform transform, Vector3 globalPosition, Quaternion globalRotation)
static RigidTransform GetTrackOffsets (AnimationTrack track, Transform transform)
static void UpdateTrackOffset (AnimationTrack track, Transform transform, RigidTransform offsets)
static void MatchPrevious (TimelineClip currentClip, Transform matchPoint, PlayableDirector director)
static void MatchNext (TimelineClip currentClip, Transform matchPoint, PlayableDirector director)
static TimelineWindowTimeControl CreateTimeController (WindowState state, TimelineClip clip)
static TimelineWindowTimeControl CreateTimeController (WindowState state, TimelineWindowTimeControl.ClipData clipData)
static void EditAnimationClipWithTimeController (AnimationClip animationClip, TimelineWindowTimeControl timeController, Object sourceObject)
static void UnlinkAnimationWindowFromTracks (IEnumerable< TrackAsset > tracks)
static void UnlinkAnimationWindowFromClips (IEnumerable< TimelineClip > timelineClips)
static void UnlinkAnimationWindowFromAnimationClips (ICollection< AnimationClip > clips)
static void UnlinkAnimationWindow ()
static int GetAnimationWindowCurrentFrame ()
static void SetAnimationWindowCurrentFrame (int frame)
static void ConstrainCurveToBooleanValues (AnimationCurve curve)
static void ConstrainCurveToRange (AnimationCurve curve, float minValue, float maxValue)
static bool IsAnimationClip (TimelineClip clip)
Member Enumeration Documentation
OffsetEditMode
enum UnityEditor.Timeline.TimelineAnimationUtilities.OffsetEditMode strong
Enumerator
None
Translation
Rotation
Member Function Documentation
ConstrainCurveToBooleanValues()
static void UnityEditor.Timeline.TimelineAnimationUtilities.ConstrainCurveToBooleanValues (AnimationCurve curve) static
ConstrainCurveToRange()
static void UnityEditor.Timeline.TimelineAnimationUtilities.ConstrainCurveToRange (AnimationCurve curve, float minValue, float maxValue) static
CreateTimeController() [1/2]
static TimelineWindowTimeControl UnityEditor.Timeline.TimelineAnimationUtilities.CreateTimeController (WindowState state, TimelineClip clip) static
References UnityEditor.Timeline.TimelineWindowTimeControl.Init().
Referenced by UnityEditor.Timeline.EditTrackInAnimationWindow.Do(), and UnityEditor.Timeline.EditClipInAnimationWindow.Execute().
CreateTimeController() [2/2]
static TimelineWindowTimeControl UnityEditor.Timeline.TimelineAnimationUtilities.CreateTimeController (WindowState state, TimelineWindowTimeControl.ClipData clipData) static
References UnityEditor.Timeline.TimelineWindowTimeControl.Init().
EditAnimationClipWithTimeController()
static void UnityEditor.Timeline.TimelineAnimationUtilities.EditAnimationClipWithTimeController (AnimationClip animationClip, TimelineWindowTimeControl timeController, Object sourceObject) static
Referenced by UnityEditor.Timeline.EditTrackInAnimationWindow.Do(), and UnityEditor.Timeline.EditClipInAnimationWindow.Execute().
GetAnimationWindowCurrentFrame()
static int UnityEditor.Timeline.TimelineAnimationUtilities.GetAnimationWindowCurrentFrame () static
GetNextClip()
static TimelineClip UnityEditor.Timeline.TimelineAnimationUtilities.GetNextClip (TimelineClip clip) static
References UnityEngine.Timeline.TimelineClip.parentTrack, and UnityEngine.Timeline.TimelineClip.start.
Referenced by UnityEditor.Timeline.TimelineAnimationUtilities.MatchNext().
GetPreviousClip()
static TimelineClip UnityEditor.Timeline.TimelineAnimationUtilities.GetPreviousClip (TimelineClip clip) static
Referenced by UnityEditor.Timeline.TimelineAnimationUtilities.MatchPrevious().
GetTrackOffsets()
static RigidTransform UnityEditor.Timeline.TimelineAnimationUtilities.GetTrackOffsets (AnimationTrack track, Transform transform) static
References UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Compose(), UnityEngine.Timeline.AnimationTrack.position, and UnityEngine.Timeline.AnimationTrack.rotation.
IsAnimationClip()
static bool UnityEditor.Timeline.TimelineAnimationUtilities.IsAnimationClip (TimelineClip clip) static
References UnityEngine.Timeline.TimelineClip.asset.
Referenced by UnityEditor.Timeline.ResetOffsets.Execute(), UnityEditor.Timeline.MatchOffsetsPreviousAction.GetDisplayState(), UnityEditor.Timeline.MatchOffsetsNextAction.GetDisplayState(), and UnityEditor.Timeline.ResetOffsets.GetDisplayState().
MatchNext()
static void UnityEditor.Timeline.TimelineAnimationUtilities.MatchNext (TimelineClip currentClip, Transform matchPoint, PlayableDirector director) static
References UnityEngine.Timeline.TimelineClip.asset, UnityEngine.Timeline.TimelineClip.blendInDuration, UnityEngine.Timeline.TimelineClip.blendOutDuration, UnityEngine.Timeline.TimelineClip.end, UnityEditor.Timeline.TimelineAnimationUtilities.GetNextClip(), UnityEngine.Timeline.TimelineClip.parentTrack, UnityEngine.Timeline.TimelineClip.start, and UnityEditor.Timeline.TimelineAnimationUtilities.UpdateClipOffsets().
MatchPrevious()
static void UnityEditor.Timeline.TimelineAnimationUtilities.MatchPrevious (TimelineClip currentClip, Transform matchPoint, PlayableDirector director) static
References UnityEngine.Timeline.TimelineClip.asset, UnityEngine.Timeline.TimelineClip.blendInDuration, UnityEngine.Timeline.TimelineClip.blendOutDuration, UnityEngine.Timeline.TimelineClip.end, UnityEditor.Timeline.TimelineAnimationUtilities.GetPreviousClip(), UnityEngine.Timeline.TimelineClip.parentTrack, UnityEngine.Timeline.TimelineClip.start, and UnityEditor.Timeline.TimelineAnimationUtilities.UpdateClipOffsets().
SetAnimationWindowCurrentFrame()
static void UnityEditor.Timeline.TimelineAnimationUtilities.SetAnimationWindowCurrentFrame (int frame) static
UnlinkAnimationWindow()
static void UnityEditor.Timeline.TimelineAnimationUtilities.UnlinkAnimationWindow () static
UnlinkAnimationWindowFromAnimationClips()
static void UnityEditor.Timeline.TimelineAnimationUtilities.UnlinkAnimationWindowFromAnimationClips (ICollection< AnimationClip > clips) static
Referenced by UnityEditor.Timeline.TimelineAnimationUtilities.UnlinkAnimationWindowFromClips(), and UnityEditor.Timeline.TimelineAnimationUtilities.UnlinkAnimationWindowFromTracks().
UnlinkAnimationWindowFromClips()
static void UnityEditor.Timeline.TimelineAnimationUtilities.UnlinkAnimationWindowFromClips (IEnumerable< TimelineClip > timelineClips) static
References UnityEditor.Timeline.TimelineAnimationUtilities.UnlinkAnimationWindowFromAnimationClips().
UnlinkAnimationWindowFromTracks()
static void UnityEditor.Timeline.TimelineAnimationUtilities.UnlinkAnimationWindowFromTracks (IEnumerable< TrackAsset > tracks) static
References UnityEditor.Timeline.TimelineAnimationUtilities.UnlinkAnimationWindowFromAnimationClips().
Referenced by UnityEditor.Timeline.DeleteTracks.Execute().
UpdateClipOffsets()
static RigidTransform UnityEditor.Timeline.TimelineAnimationUtilities.UpdateClipOffsets (AnimationPlayableAsset asset, AnimationTrack track, Transform transform, Vector3 globalPosition, Quaternion globalRotation) static
References UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Compose(), UnityEngine.Timeline.AnimationPlayableAsset.position, and UnityEngine.Timeline.AnimationPlayableAsset.rotation.
Referenced by UnityEditor.Timeline.TimelineAnimationUtilities.MatchNext(), and UnityEditor.Timeline.TimelineAnimationUtilities.MatchPrevious().
UpdateTrackOffset()
static void UnityEditor.Timeline.TimelineAnimationUtilities.UpdateTrackOffset (AnimationTrack track, Transform transform, RigidTransform offsets) static
References UnityEngine.Timeline.AnimationTrack.eulerAngles, UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.position, UnityEngine.Timeline.AnimationTrack.position, and UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.rotation.
ValidateOffsetAvailabitity()
static bool UnityEditor.Timeline.TimelineAnimationUtilities.ValidateOffsetAvailabitity (PlayableDirector director, Animator animator) static
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Animation/TimelineAnimationUtilities.cs