VirtualTours: UnityEngine.Timeline.RuntimeClip Class Reference
UnityEngine.Timeline.RuntimeClip Class Reference
Public Member Functions
RuntimeClip (TimelineClip clip, Playable clipPlayable, Playable parentMixer)
void SetTime (double time)
void SetDuration (double duration)
override void EvaluateAt (double localTime, FrameData frameData)
override void Reset ()
Properties
override double start [get]
override double duration [get]
TimelineClip clip [get]
Playable mixer [get]
Playable playable [get]
override bool enable [set]
Constructor & Destructor Documentation
RuntimeClip()
UnityEngine.Timeline.RuntimeClip.RuntimeClip (TimelineClip clip, Playable clipPlayable, Playable parentMixer)
References UnityEngine.Timeline.RuntimeClip.clip.
Member Function Documentation
EvaluateAt()
override void UnityEngine.Timeline.RuntimeClip.EvaluateAt (double localTime, FrameData frameData) virtual
Implements UnityEngine.Timeline.RuntimeElement.
References UnityEngine.Timeline.RuntimeClip.clip, UnityEngine.Timeline.RuntimeClip.enable, UnityEngine.Timeline.TimelineClip.end, UnityEngine.Timeline.TimelineClip.EvaluateMixIn(), UnityEngine.Timeline.TimelineClip.EvaluateMixOut(), UnityEngine.Timeline.TimelineClip.extrapolatedDuration, UnityEngine.Timeline.TimelineClip.IsPostExtrapolatedTime(), UnityEngine.Timeline.TimelineClip.IsPreExtrapolatedTime(), UnityEngine.Timeline.RuntimeClip.mixer, UnityEngine.Timeline.RuntimeClip.playable, UnityEngine.Timeline.RuntimeClip.SetDuration(), UnityEngine.Timeline.RuntimeClip.SetTime(), UnityEngine.Timeline.TimelineClip.start, UnityEngine.Timeline.DiscreteTime.tickValue, and UnityEngine.Timeline.TimelineClip.ToLocalTime().
Reset()
override void UnityEngine.Timeline.RuntimeClip.Reset () virtual
Reimplemented from UnityEngine.Timeline.RuntimeElement.
References UnityEngine.Timeline.TimelineClip.clipIn, and UnityEngine.Timeline.RuntimeClip.SetTime().
SetDuration()
void UnityEngine.Timeline.RuntimeClip.SetDuration (double duration)
References UnityEngine.Timeline.RuntimeClip.duration.
Referenced by UnityEngine.Timeline.RuntimeClip.EvaluateAt().
SetTime()
void UnityEngine.Timeline.RuntimeClip.SetTime (double time)
Referenced by UnityEngine.Timeline.RuntimeClip.EvaluateAt(), and UnityEngine.Timeline.RuntimeClip.Reset().
Property Documentation
clip
TimelineClip UnityEngine.Timeline.RuntimeClip.clip get
Referenced by UnityEngine.Timeline.RuntimeClip.EvaluateAt(), and UnityEngine.Timeline.RuntimeClip.RuntimeClip().
duration
override double UnityEngine.Timeline.RuntimeClip.duration get
Referenced by UnityEngine.Timeline.RuntimeClip.SetDuration().
enable
override bool UnityEngine.Timeline.RuntimeClip.enable set
Referenced by UnityEngine.Timeline.RuntimeClip.EvaluateAt().
mixer
Playable UnityEngine.Timeline.RuntimeClip.mixer get
Referenced by UnityEngine.Timeline.RuntimeClip.EvaluateAt().
playable
Playable UnityEngine.Timeline.RuntimeClip.playable get
Referenced by UnityEngine.Timeline.RuntimeClip.EvaluateAt().
start
override double UnityEngine.Timeline.RuntimeClip.start get
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Runtime/Evaluation/RuntimeClip.cs