VirtualTours: UnityEditor.TimelineDragging Class Reference
UnityEditor.TimelineDragging Class Reference
Public Member Functions
delegate bool TypeResolver (IEnumerable< Type > types, Action< Type > onComplete, string format)
TimelineDragging (TreeViewController treeView, TimelineWindow window, TimelineAsset data)
override bool CanStartDrag (TreeViewItem targetItem, List< int > draggedItemIDs, Vector2 mouseDownPosition)
override void StartDrag (TreeViewItem draggedNode, List< int > draggedItemIDs)
override bool DragElement (TreeViewItem targetItem, Rect targetItemRect, int row)
override DragAndDropVisualMode DoDrag (TreeViewItem parentItem, TreeViewItem targetItem, bool perform, DropPosition dropPos)
DragAndDropVisualMode HandleTrackDrop (TreeViewItem parentItem, TreeViewItem targetItem, bool perform, DropPosition dropPos)
Static Public Member Functions
static bool IsDraggingEvent ()
static bool ResolveType (IEnumerable< System.Type > types, Action< Type > onComplete, string formatString)
static DragAndDropVisualMode HandleHierarchyPaneDragAndDrop (IEnumerable< UnityObject > objectsBeingDropped, TrackAsset targetTrack, bool perform, TimelineAsset timeline, PlayableDirector director, TypeResolver typeResolver, TrackAsset insertBefore=null)
static DragAndDropVisualMode HandleClipPaneObjectDragAndDrop (IEnumerable< UnityObject > objectsBeingDropped, TrackAsset targetTrack, bool perform, TimelineAsset timeline, TrackAsset parent, PlayableDirector director, double candidateTime, TypeResolver typeResolver, TrackAsset insertBefore=null)
static DragAndDropVisualMode HandleClipPaneMonoScriptDragAndDrop (IEnumerable< MonoScript > scriptsBeingDropped, TrackAsset targetTrack, bool perform, TimelineAsset timeline, TrackAsset parent, PlayableDirector director, double candidateTime)
Handles drag and drop of a mono script.
static DragAndDropVisualMode HandleClipPanePlayableAssetDragAndDrop (IEnumerable< IPlayableAsset > assetsBeingDropped, TrackAsset targetTrack, bool perform, TimelineAsset timeline, TrackAsset parent, PlayableDirector director, double candidateTime, TypeResolver typeResolver)
static void HandleBindingDragAndDrop (TrackAsset dropTarget, Type requiredBindingType)
Constructor & Destructor Documentation
TimelineDragging()
UnityEditor.TimelineDragging.TimelineDragging (TreeViewController treeView, TimelineWindow window, TimelineAsset data)
Member Function Documentation
CanStartDrag()
override bool UnityEditor.TimelineDragging.CanStartDrag (TreeViewItem targetItem, List< int > draggedItemIDs, Vector2 mouseDownPosition)
DoDrag()
override DragAndDropVisualMode UnityEditor.TimelineDragging.DoDrag (TreeViewItem parentItem, TreeViewItem targetItem, bool perform, DropPosition dropPos)
References UnityEditor.TimelineDragging.HandleClipPaneObjectDragAndDrop(), UnityEditor.TimelineDragging.HandleHierarchyPaneDragAndDrop(), UnityEditor.TimelineDragging.HandleTrackDrop(), UnityEditor.Timeline.TimelineTrackBaseGUI.isDropTarget, and UnityEditor.TimelineDragging.ResolveType().
DragElement()
override bool UnityEditor.TimelineDragging.DragElement (TreeViewItem targetItem, Rect targetItemRect, int row)
References UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.ISequenceState.isReadOnly, and UnityEditor.Timeline.TimelineWindow.state.
HandleBindingDragAndDrop()
static void UnityEditor.TimelineDragging.HandleBindingDragAndDrop (TrackAsset dropTarget, Type requiredBindingType) static
References UnityEditor.Timeline.GameObject.
HandleClipPaneMonoScriptDragAndDrop()
static DragAndDropVisualMode UnityEditor.TimelineDragging.HandleClipPaneMonoScriptDragAndDrop (IEnumerable< MonoScript > scriptsBeingDropped, TrackAsset targetTrack, bool perform, TimelineAsset timeline, TrackAsset parent, PlayableDirector director, double candidateTime) static
Handles drag and drop of a mono script.
Referenced by UnityEditor.TimelineDragging.HandleClipPaneObjectDragAndDrop().
HandleClipPaneObjectDragAndDrop()
static DragAndDropVisualMode UnityEditor.TimelineDragging.HandleClipPaneObjectDragAndDrop (IEnumerable< UnityObject > objectsBeingDropped, TrackAsset targetTrack, bool perform, TimelineAsset timeline, TrackAsset parent, PlayableDirector director, double candidateTime, TypeResolver typeResolver, TrackAsset insertBefore = null) static
References UnityEngine.Timeline.TimelineAsset.CreateMarkerTrack(), UnityEditor.TimelineDragging.HandleClipPaneMonoScriptDragAndDrop(), UnityEditor.TimelineDragging.HandleClipPanePlayableAssetDragAndDrop(), UnityEngine.Timeline.TrackAsset.lockedInHierarchy, and UnityEngine.Timeline.TimelineAsset.markerTrack.
Referenced by UnityEditor.TimelineDragging.DoDrag().
HandleClipPanePlayableAssetDragAndDrop()
static DragAndDropVisualMode UnityEditor.TimelineDragging.HandleClipPanePlayableAssetDragAndDrop (IEnumerable< IPlayableAsset > assetsBeingDropped, TrackAsset targetTrack, bool perform, TimelineAsset timeline, TrackAsset parent, PlayableDirector director, double candidateTime, TypeResolver typeResolver) static
Referenced by UnityEditor.TimelineDragging.HandleClipPaneObjectDragAndDrop().
HandleHierarchyPaneDragAndDrop()
static DragAndDropVisualMode UnityEditor.TimelineDragging.HandleHierarchyPaneDragAndDrop (IEnumerable< UnityObject > objectsBeingDropped, TrackAsset targetTrack, bool perform, TimelineAsset timeline, PlayableDirector director, TypeResolver typeResolver, TrackAsset insertBefore = null) static
References UnityEngine.Timeline.TrackAsset.lockedInHierarchy.
Referenced by UnityEditor.TimelineDragging.DoDrag().
HandleTrackDrop()
DragAndDropVisualMode UnityEditor.TimelineDragging.HandleTrackDrop (TreeViewItem parentItem, TreeViewItem targetItem, bool perform, DropPosition dropPos)
References UnityEditor.Timeline.TimelineTrackBaseGUI.isDropTarget, and UnityEditor.Timeline.TimelineTrackBaseGUI.track.
Referenced by UnityEditor.TimelineDragging.DoDrag().
IsDraggingEvent()
static bool UnityEditor.TimelineDragging.IsDraggingEvent () static
ResolveType()
static bool UnityEditor.TimelineDragging.ResolveType (IEnumerable< System.Type > types, Action< Type > onComplete, string formatString) static
Referenced by UnityEditor.TimelineDragging.DoDrag().
StartDrag()
override void UnityEditor.TimelineDragging.StartDrag (TreeViewItem draggedNode, List< int > draggedItemIDs)
TypeResolver()
delegate bool UnityEditor.TimelineDragging.TypeResolver (IEnumerable< Type > types, Action< Type > onComplete, string format)
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/TimelineDragging.cs