VirtualTours: UnityEditor.Timeline.AnimationClipCurveCache Class Reference
UnityEditor.Timeline.AnimationClipCurveCache Class Reference
Public Member Functions
void OnEnable ()
void OnDisable ()
AnimationClipCurveInfo GetCurveInfo (AnimationClip clip)
void ClearCachedProxyClips ()
void Clear ()
Properties
static AnimationClipCurveCache Instance [get]
Member Function Documentation
Clear()
void UnityEditor.Timeline.AnimationClipCurveCache.Clear ()
References UnityEditor.Timeline.AnimationClipCurveCache.ClearCachedProxyClips().
ClearCachedProxyClips()
void UnityEditor.Timeline.AnimationClipCurveCache.ClearCachedProxyClips ()
Referenced by UnityEditor.Timeline.AnimationClipCurveCache.Clear(), and UnityEditor.Timeline.TimelineTreeViewGUI.Reload().
GetCurveInfo()
AnimationClipCurveInfo UnityEditor.Timeline.AnimationClipCurveCache.GetCurveInfo (AnimationClip clip)
References UnityEditor.Timeline.AnimationClipCurveInfo.dirty, and UnityEditor.Timeline.AnimationClipCurveInfo.Update().
Referenced by UnityEditor.Timeline.Utilities.KeyTraverser.GetClipKeyTimes(), UnityEditor.Timeline.BasePropertyKeyDataSource.GetDescriptions(), UnityEditor.Timeline.BasePropertyKeyDataSource.GetKeys(), UnityEditor.Timeline.Utilities.KeyTraverser.GetTrackKeyTimes(), and UnityEditor.Timeline.TimelineClipGUI.SnappableEdgesFor().
OnDisable()
void UnityEditor.Timeline.AnimationClipCurveCache.OnDisable ()
OnEnable()
void UnityEditor.Timeline.AnimationClipCurveCache.OnEnable ()
Property Documentation
Instance
AnimationClipCurveCache UnityEditor.Timeline.AnimationClipCurveCache.Instance static get
Referenced by UnityEditor.Timeline.Utilities.KeyTraverser.GetClipKeyTimes(), UnityEditor.Timeline.BasePropertyKeyDataSource.GetDescriptions(), UnityEditor.Timeline.BasePropertyKeyDataSource.GetKeys(), UnityEditor.Timeline.Utilities.KeyTraverser.GetTrackKeyTimes(), UnityEditor.Timeline.TimelineTreeViewGUI.Reload(), and UnityEditor.Timeline.TimelineClipGUI.SnappableEdgesFor().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Animation/AnimationClipCurveCache.cs