VirtualTours: TMPro.EditorUtilities.TMP_EditorPanelUI Class Reference
TMPro.EditorUtilities.TMP_EditorPanelUI Class Reference
Protected Member Functions
override void OnEnable ()
override void DrawExtraSettings ()
void DrawRaycastTarget ()
void DrawMaskable ()
override bool IsMixSelectionTypes ()
override void OnUndoRedo ()
Protected Member Functions inherited from TMPro.EditorUtilities.TMP_BaseEditorPanel
virtual void OnDisable ()
void DrawTextInput ()
void DrawMainSettings ()
void DrawMargins ()
void DrawGeometrySorting ()
void DrawIsTextObjectScaleStatic ()
void DrawRichText ()
void DrawParsing ()
void DrawSpriteAsset ()
void DrawStyleSheet ()
void DrawTextureMapping ()
void DrawKerning ()
void DrawPadding ()
GUIContent[] GetMaterialPresets ()
Method to retrieve the material presets that match the currently selected font asset.
GUIContent[] GetStyleNames ()
void DrawMarginProperty (SerializedProperty property, GUIContent label)
void DrawPropertySlider (GUIContent label, SerializedProperty property)
Additional Inherited Members
Public Member Functions inherited from TMPro.EditorUtilities.TMP_BaseEditorPanel
override void OnInspectorGUI ()
void OnSceneGUI ()
Public Attributes inherited from TMPro.EditorUtilities.TMP_BaseEditorPanel
int selAlignGridA
int selAlignGridB
Protected Attributes inherited from TMPro.EditorUtilities.TMP_BaseEditorPanel
Dictionary< int, int > m_TextStyleIndexLookup = new Dictionary<int, int>()
SerializedProperty m_TextProp
SerializedProperty m_IsRightToLeftProp
string m_RtlText
SerializedProperty m_FontAssetProp
SerializedProperty m_FontSharedMaterialProp
Material[] m_MaterialPresets
GUIContent[] m_MaterialPresetNames
Dictionary< int, int > m_MaterialPresetIndexLookup = new Dictionary<int, int>()
int m_MaterialPresetSelectionIndex
bool m_IsPresetListDirty
List< TMP_Style > m_Styles = new List<TMP_Style>()
GUIContent[] m_StyleNames
int m_StyleSelectionIndex
SerializedProperty m_FontStyleProp
SerializedProperty m_FontColorProp
SerializedProperty m_EnableVertexGradientProp
SerializedProperty m_FontColorGradientProp
SerializedProperty m_FontColorGradientPresetProp
SerializedProperty m_OverrideHtmlColorProp
SerializedProperty m_FontSizeProp
SerializedProperty m_FontSizeBaseProp
SerializedProperty m_AutoSizingProp
SerializedProperty m_FontSizeMinProp
SerializedProperty m_FontSizeMaxProp
SerializedProperty m_LineSpacingMaxProp
SerializedProperty m_CharWidthMaxAdjProp
SerializedProperty m_CharacterSpacingProp
SerializedProperty m_WordSpacingProp
SerializedProperty m_LineSpacingProp
SerializedProperty m_ParagraphSpacingProp
SerializedProperty m_TextAlignmentProp
SerializedProperty m_HorizontalAlignmentProp
SerializedProperty m_VerticalAlignmentProp
SerializedProperty m_HorizontalMappingProp
SerializedProperty m_VerticalMappingProp
SerializedProperty m_UvLineOffsetProp
SerializedProperty m_EnableWordWrappingProp
SerializedProperty m_WordWrappingRatiosProp
SerializedProperty m_TextOverflowModeProp
SerializedProperty m_PageToDisplayProp
SerializedProperty m_LinkedTextComponentProp
SerializedProperty m_ParentLinkedTextComponentProp
SerializedProperty m_EnableKerningProp
SerializedProperty m_IsRichTextProp
SerializedProperty m_HasFontAssetChangedProp
SerializedProperty m_EnableExtraPaddingProp
SerializedProperty m_CheckPaddingRequiredProp
SerializedProperty m_EnableEscapeCharacterParsingProp
SerializedProperty m_UseMaxVisibleDescenderProp
SerializedProperty m_GeometrySortingOrderProp
SerializedProperty m_IsTextObjectScaleStaticProp
SerializedProperty m_SpriteAssetProp
SerializedProperty m_StyleSheetAssetProp
SerializedProperty m_TextStyleHashCodeProp
SerializedProperty m_MarginProp
SerializedProperty m_ColorModeProp
bool m_HavePropertiesChanged
TMP_Text m_TextComponent
TMP_Text m_PreviousLinkedTextComponent
RectTransform m_RectTransform
Material m_TargetMaterial
Vector3[] m_RectCorners = new Vector3[4]
Vector3[] m_HandlePoints = new Vector3[4]
Static Protected Attributes inherited from TMPro.EditorUtilities.TMP_BaseEditorPanel
static readonly GUIContent k_ExtraSettingsLabel = new GUIContent("Extra Settings")
static string[] k_UiStateLabel = new string[] { "<i>(Click to collapse)</i> ", "<i>(Click to expand)</i> " }
static int s_EventId
Member Function Documentation
DrawExtraSettings()
override void TMPro.EditorUtilities.TMP_EditorPanelUI.DrawExtraSettings () protected virtual
Implements TMPro.EditorUtilities.TMP_BaseEditorPanel.
References TMPro.EditorUtilities.TMP_BaseEditorPanel.DrawGeometrySorting(), TMPro.EditorUtilities.TMP_BaseEditorPanel.DrawIsTextObjectScaleStatic(), TMPro.EditorUtilities.TMP_BaseEditorPanel.DrawKerning(), TMPro.EditorUtilities.TMP_BaseEditorPanel.DrawMargins(), TMPro.EditorUtilities.TMP_EditorPanelUI.DrawMaskable(), TMPro.EditorUtilities.TMP_BaseEditorPanel.DrawPadding(), TMPro.EditorUtilities.TMP_BaseEditorPanel.DrawParsing(), TMPro.EditorUtilities.TMP_EditorPanelUI.DrawRaycastTarget(), TMPro.EditorUtilities.TMP_BaseEditorPanel.DrawRichText(), TMPro.EditorUtilities.TMP_BaseEditorPanel.DrawSpriteAsset(), TMPro.EditorUtilities.TMP_BaseEditorPanel.DrawStyleSheet(), TMPro.EditorUtilities.TMP_BaseEditorPanel.Foldout.extraSettings, and TMPro.EditorUtilities.TMP_BaseEditorPanel.k_UiStateLabel.
DrawMaskable()
void TMPro.EditorUtilities.TMP_EditorPanelUI.DrawMaskable () protected
References TMPro.EditorUtilities.TMP_BaseEditorPanel.m_HavePropertiesChanged, and TMPro.EditorUtilities.TMP_BaseEditorPanel.m_TextComponent.
Referenced by TMPro.EditorUtilities.TMP_EditorPanelUI.DrawExtraSettings().
DrawRaycastTarget()
void TMPro.EditorUtilities.TMP_EditorPanelUI.DrawRaycastTarget () protected
References TMPro.EditorUtilities.TMP_BaseEditorPanel.m_HavePropertiesChanged, and TMPro.EditorUtilities.TMP_BaseEditorPanel.m_TextComponent.
Referenced by TMPro.EditorUtilities.TMP_EditorPanelUI.DrawExtraSettings().
IsMixSelectionTypes()
override bool TMPro.EditorUtilities.TMP_EditorPanelUI.IsMixSelectionTypes () protected virtual
Implements TMPro.EditorUtilities.TMP_BaseEditorPanel.
OnEnable()
override void TMPro.EditorUtilities.TMP_EditorPanelUI.OnEnable () protected virtual
Reimplemented from TMPro.EditorUtilities.TMP_BaseEditorPanel.
OnUndoRedo()
override void TMPro.EditorUtilities.TMP_EditorPanelUI.OnUndoRedo () protected virtual
Implements TMPro.EditorUtilities.TMP_BaseEditorPanel.
References TMPro.EditorUtilities.TMP_BaseEditorPanel.s_EventId.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Editor/TMP_EditorPanelUI.cs