VirtualTours: TMPro.TMP_FontAssetUtilities Class Reference
TMPro.TMP_FontAssetUtilities Class Reference
Static Public Member Functions
static TMP_Character GetCharacterFromFontAsset (uint unicode, TMP_FontAsset sourceFontAsset, bool includeFallbacks, FontStyles fontStyle, FontWeight fontWeight, out bool isAlternativeTypeface)
Returns the text element (character) for the given unicode value taking into consideration the requested font style and weight. Function searches the source font asset, its list of font assets assigned as alternative typefaces and potentially its fallbacks. The font asset out parameter contains a reference to the font asset containing the character. The typeface type indicates whether the returned font asset is the source font asset, an alternative typeface or fallback font asset.
static TMP_Character GetCharacterFromFontAssets (uint unicode, TMP_FontAsset sourceFontAsset, List< TMP_FontAsset > fontAssets, bool includeFallbacks, FontStyles fontStyle, FontWeight fontWeight, out bool isAlternativeTypeface)
Returns the text element (character) for the given unicode value taking into consideration the requested font style and weight. Function searches the provided list of font assets, the list of font assets assigned as alternative typefaces to them as well as their fallbacks. The font asset out parameter contains a reference to the font asset containing the character. The typeface type indicates whether the returned font asset is the source font asset, an alternative typeface or fallback font asset.
static TMP_SpriteCharacter GetSpriteCharacterFromSpriteAsset (uint unicode, TMP_SpriteAsset spriteAsset, bool includeFallbacks)
Properties
static TMP_FontAssetUtilities instance [get]
Get a singleton instance of the Font Asset Utilities class.
Member Function Documentation
GetCharacterFromFontAsset()
static TMP_Character TMPro.TMP_FontAssetUtilities.GetCharacterFromFontAsset (uint unicode, TMP_FontAsset sourceFontAsset, bool includeFallbacks, FontStyles fontStyle, FontWeight fontWeight, out bool isAlternativeTypeface) static
Returns the text element (character) for the given unicode value taking into consideration the requested font style and weight. Function searches the source font asset, its list of font assets assigned as alternative typefaces and potentially its fallbacks. The font asset out parameter contains a reference to the font asset containing the character. The typeface type indicates whether the returned font asset is the source font asset, an alternative typeface or fallback font asset.
Parameters
unicode The unicode value of the requested character
sourceFontAsset The font asset to be searched
includeFallbacks Include the fallback font assets in the search
fontStyle The font style
fontWeight The font weight
isAlternativeTypeface Indicates if the OUT font asset is an alternative typeface or fallback font asset
fontAsset The font asset that contains the requested character
Returns
Referenced by TMPro.TMP_Text.GetEllipsisSpecialCharacter(), TMPro.TMP_Text.GetUnderlineSpecialCharacter(), TMPro.TextMeshPro.SetArraySizes(), and TMPro.TextMeshProUGUI.SetArraySizes().
GetCharacterFromFontAssets()
static TMP_Character TMPro.TMP_FontAssetUtilities.GetCharacterFromFontAssets (uint unicode, TMP_FontAsset sourceFontAsset, List< TMP_FontAsset > fontAssets, bool includeFallbacks, FontStyles fontStyle, FontWeight fontWeight, out bool isAlternativeTypeface) static
Returns the text element (character) for the given unicode value taking into consideration the requested font style and weight. Function searches the provided list of font assets, the list of font assets assigned as alternative typefaces to them as well as their fallbacks. The font asset out parameter contains a reference to the font asset containing the character. The typeface type indicates whether the returned font asset is the source font asset, an alternative typeface or fallback font asset.
Parameters
unicode The unicode value of the requested character
sourceFontAsset The font asset originating the search query
fontAssets The list of font assets to search
includeFallbacks Determines if the fallback of each font assets on the list will be searched
fontStyle The font style
fontWeight The font weight
isAlternativeTypeface Determines if the OUT font asset is an alternative typeface or fallback font asset
Returns
References TMPro.TMP_Asset.instanceID.
Referenced by TMPro.TMP_Text.GetEllipsisSpecialCharacter(), TMPro.TextMeshPro.SetArraySizes(), and TMPro.TextMeshProUGUI.SetArraySizes().
GetSpriteCharacterFromSpriteAsset()
static TMP_SpriteCharacter TMPro.TMP_FontAssetUtilities.GetSpriteCharacterFromSpriteAsset (uint unicode, TMP_SpriteAsset spriteAsset, bool includeFallbacks) static
Parameters
unicode
spriteAsset
includeFallbacks
Returns
References TMPro.TMP_SpriteAsset.fallbackSpriteAssets, TMPro.TMP_Asset.instanceID, and TMPro.TMP_SpriteAsset.spriteCharacterLookupTable.
Property Documentation
instance
TMP_FontAssetUtilities TMPro.TMP_FontAssetUtilities.instance static get
Get a singleton instance of the Font Asset Utilities class.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/TMP_FontAssetUtilities.cs