VirtualTours: UnityEditor.Timeline.TimelineZoomManipulator Class Reference
UnityEditor.Timeline.TimelineZoomManipulator Class Reference
Static Public Attributes
static readonly TimelineZoomManipulator Instance = new TimelineZoomManipulator()
Protected Member Functions
override bool MouseDown (Event evt, WindowState state)
override bool MouseWheel (Event evt, WindowState state)
override bool MouseDrag (Event evt, WindowState state)
Protected Member Functions inherited from UnityEditor.Timeline.Manipulator
virtual bool MouseUp (Event evt, WindowState state)
virtual bool DoubleClick (Event evt, WindowState state)
virtual bool KeyDown (Event evt, WindowState state)
virtual bool KeyUp (Event evt, WindowState state)
virtual bool ContextClick (Event evt, WindowState state)
virtual bool ValidateCommand (Event evt, WindowState state)
virtual bool ExecuteCommand (Event evt, WindowState state)
Additional Inherited Members
Public Member Functions inherited from UnityEditor.Timeline.Manipulator
virtual void Overlay (Event evt, WindowState state)
bool HandleEvent (WindowState state)
Member Function Documentation
MouseDown()
override bool UnityEditor.Timeline.TimelineZoomManipulator.MouseDown (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.WindowState.PixelToTime(), and UnityEditor.Timeline.WindowState.timeAreaShownRange.
MouseDrag()
override bool UnityEditor.Timeline.TimelineZoomManipulator.MouseDrag (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
MouseWheel()
override bool UnityEditor.Timeline.TimelineZoomManipulator.MouseWheel (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.TimelineWindow.horizontalScrollbarHeight, UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.WindowState.PixelToTime(), UnityEditor.Timeline.TimelineWindow.sequenceContentRect, and UnityEditor.Timeline.WindowState.timeAreaShownRange.
Member Data Documentation
Instance
readonly TimelineZoomManipulator UnityEditor.Timeline.TimelineZoomManipulator.Instance = new TimelineZoomManipulator() static
Referenced by UnityEditor.Timeline.ZoomIn.Execute(), and UnityEditor.Timeline.ZoomOut.Execute().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/ManipulationsTimeline.cs