VirtualTours: UnityEditor.Timeline.Signals.SignalReceiverTreeView Class Reference
UnityEditor.Timeline.Signals.SignalReceiverTreeView Class Reference
Public Member Functions
SignalReceiverTreeView (TreeViewState state, MultiColumnHeader multiColumnHeader, SignalReceiver receiver, SerializedObject serializedObject)
void SetSignalContext (SignalAsset assetContext=null)
void Draw ()
void RefreshIfDirty ()
Static Public Member Functions
static MultiColumnHeaderState.Column[] GetColumns ()
Protected Member Functions
override TreeViewItem BuildRoot ()
override void RowGUI (RowGUIArgs args)
override float GetCustomRowHeight (int row, TreeViewItem treeItem)
Properties
bool dirty [set]
bool readonlySignals [get, set]
Constructor & Destructor Documentation
SignalReceiverTreeView()
UnityEditor.Timeline.Signals.SignalReceiverTreeView.SignalReceiverTreeView (TreeViewState state, MultiColumnHeader multiColumnHeader, SignalReceiver receiver, SerializedObject serializedObject)
Member Function Documentation
BuildRoot()
override TreeViewItem UnityEditor.Timeline.Signals.SignalReceiverTreeView.BuildRoot () protected
References UnityEditor.Timeline.Signals.SignalReceiverTreeView.readonlySignals.
Draw()
void UnityEditor.Timeline.Signals.SignalReceiverTreeView.Draw ()
Referenced by UnityEditor.Timeline.Signals.SignalReceiverInspector.OnInspectorGUI().
GetColumns()
static MultiColumnHeaderState.Column [] UnityEditor.Timeline.Signals.SignalReceiverTreeView.GetColumns () static
GetCustomRowHeight()
override float UnityEditor.Timeline.Signals.SignalReceiverTreeView.GetCustomRowHeight (int row, TreeViewItem treeItem) protected
References UnityEditor.Timeline.Signals.SignalReceiverItem.GetHeight().
RefreshIfDirty()
void UnityEditor.Timeline.Signals.SignalReceiverTreeView.RefreshIfDirty ()
References UnityEditor.Timeline.Signals.SignalReceiverTreeView.dirty.
Referenced by UnityEditor.Timeline.Signals.SignalReceiverInspector.OnInspectorGUI().
RowGUI()
override void UnityEditor.Timeline.Signals.SignalReceiverTreeView.RowGUI (RowGUIArgs args) protected
SetSignalContext()
void UnityEditor.Timeline.Signals.SignalReceiverTreeView.SetSignalContext (SignalAsset assetContext = null)
References UnityEditor.Timeline.Signals.SignalReceiverTreeView.dirty.
Property Documentation
dirty
bool UnityEditor.Timeline.Signals.SignalReceiverTreeView.dirty set
Referenced by UnityEditor.Timeline.Signals.SignalReceiverInspector.OnInspectorGUI(), UnityEditor.Timeline.Signals.SignalReceiverTreeView.RefreshIfDirty(), and UnityEditor.Timeline.Signals.SignalReceiverTreeView.SetSignalContext().
readonlySignals
bool UnityEditor.Timeline.Signals.SignalReceiverTreeView.readonlySignals get set
Referenced by UnityEditor.Timeline.Signals.SignalReceiverTreeView.BuildRoot().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Signals/TreeView/SignalReceiverTreeView.cs