VirtualTours: UnityEditor.Timeline.TrackAssetInspector Class Reference
UnityEditor.Timeline.TrackAssetInspector Class Reference
Public Member Functions
override void OnInspectorGUI ()
virtual void OnEnable ()
Protected Member Functions
bool IsTrackLocked ()
virtual void DrawTrackProperties ()
virtual void ApplyChanges ()
Properties
TimelineWindow timelineWindow [get]
Member Function Documentation
ApplyChanges()
virtual void UnityEditor.Timeline.TrackAssetInspector.ApplyChanges () protected virtual
Reimplemented in UnityEngine.Timeline.AudioTrackInspector.
DrawTrackProperties()
virtual void UnityEditor.Timeline.TrackAssetInspector.DrawTrackProperties () protected virtual
Reimplemented in UnityEngine.Timeline.AudioTrackInspector.
IsTrackLocked()
bool UnityEditor.Timeline.TrackAssetInspector.IsTrackLocked () protected
Referenced by UnityEditor.Timeline.ActivationTrackInspector.OnInspectorGUI(), UnityEditor.Timeline.AnimationTrackInspector.OnInspectorGUI(), and UnityEditor.Timeline.TrackAssetInspector.OnInspectorGUI().
OnEnable()
virtual void UnityEditor.Timeline.TrackAssetInspector.OnEnable () virtual
Reimplemented in UnityEditor.Timeline.GroupTrackInspector, UnityEditor.Timeline.AnimationTrackInspector, UnityEngine.Timeline.AudioTrackInspector, and UnityEditor.Timeline.ActivationTrackInspector.
References UnityEditor.Timeline.CustomTimelineEditorCache.GetTrackEditor().
OnInspectorGUI()
override void UnityEditor.Timeline.TrackAssetInspector.OnInspectorGUI ()
References UnityEditor.Timeline.TrackAssetInspector.IsTrackLocked().
Property Documentation
timelineWindow
TimelineWindow UnityEditor.Timeline.TrackAssetInspector.timelineWindow get protected
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/inspectors/TrackAssetInspector.cs