VirtualTours: UnityEditor.Timeline.SnapEngine Class Reference
UnityEditor.Timeline.SnapEngine Class Reference
Public Member Functions
SnapEngine (IAttractable attractable, IAttractionHandler attractionHandler, ManipulateEdges manipulateEdges, WindowState state, Vector2 mousePosition, IEnumerable< ISnappable > snappables=null)
void Snap (Vector2 currentMousePosition, EventModifiers modifiers)
void OnGUI (bool showLeft=true, bool showRight=true)
Static Public Member Functions
static IEnumerable< ISnappable > GetVisibleSnappables (WindowState state)
Static Public Attributes
static bool displayDebugLayout
Constructor & Destructor Documentation
SnapEngine()
UnityEditor.Timeline.SnapEngine.SnapEngine (IAttractable attractable, IAttractionHandler attractionHandler, ManipulateEdges manipulateEdges, WindowState state, Vector2 mousePosition, IEnumerable< ISnappable > snappables = null)
References UnityEditor.Timeline.ISequenceState.asset, UnityEngine.Timeline.TimelineAsset.duration, UnityEngine.Timeline.TimelineAsset.durationMode, UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.ISequenceState.GetEvaluableRange(), UnityEditor.Timeline.SnapEngine.GetVisibleSnappables(), UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.WindowState.IsEditingASubTimeline(), UnityEditor.Timeline.WindowState.masterSequence, UnityEditor.Timeline.TimelineMode.ShouldShowTimeCursor(), and UnityEditor.Timeline.ISequenceState.time.
Member Function Documentation
GetVisibleSnappables()
static IEnumerable<ISnappable> UnityEditor.Timeline.SnapEngine.GetVisibleSnappables (WindowState state) static
References UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.WindowState.spacePartitioner, UnityEditor.Timeline.TimelineWindow.state, and UnityEditor.Timeline.WindowState.timeAreaRect.
Referenced by UnityEditor.Timeline.SnapEngine.SnapEngine().
OnGUI()
void UnityEditor.Timeline.SnapEngine.OnGUI (bool showLeft = true, bool showRight = true)
References UnityEditor.Timeline.SnapEngine.displayDebugLayout, UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.TimelineWindow.state, and UnityEditor.Timeline.WindowState.timeAreaRect.
Referenced by UnityEditor.Timeline.SelectAndMoveItem.Overlay(), and UnityEditor.Timeline.TrimClip.Overlay().
Snap()
void UnityEditor.Timeline.SnapEngine.Snap (Vector2 currentMousePosition, EventModifiers modifiers)
Referenced by UnityEditor.Timeline.SelectAndMoveItem.MouseDrag(), and UnityEditor.Timeline.TrimClip.MouseDrag().
Member Data Documentation
displayDebugLayout
bool UnityEditor.Timeline.SnapEngine.displayDebugLayout static
Referenced by UnityEditor.Timeline.SnapEngine.OnGUI().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/Snapping/SnapEngine.cs