VirtualTours: UnityEngine.Timeline.TimeControlPlayable Class Reference
UnityEngine.Timeline.TimeControlPlayable Class Reference
A PlayableBehaviour that manages a component that implements the ITimeControl interface
Public Member Functions
void Initialize (ITimeControl timeControl)
Initializes the behaviour
override void PrepareFrame (Playable playable, FrameData info)
This function is called during the PrepareFrame phase of the PlayableGraph.
override void OnBehaviourPlay (Playable playable, FrameData info)
This function is called when the Playable play state is changed to Playables.PlayState.Playing.
override void OnBehaviourPause (Playable playable, FrameData info)
This function is called when the Playable play state is changed to PlayState.Paused.
Static Public Member Functions
static ScriptPlayable< TimeControlPlayable > Create (PlayableGraph graph, ITimeControl timeControl)
Creates a Playable with a TimeControlPlayable behaviour attached
Detailed Description
A PlayableBehaviour that manages a component that implements the ITimeControl interface
Member Function Documentation
Create()
static ScriptPlayable<TimeControlPlayable> UnityEngine.Timeline.TimeControlPlayable.Create (PlayableGraph graph, ITimeControl timeControl) static
Creates a Playable with a TimeControlPlayable behaviour attached
Parameters
graph The PlayableGraph to inject the Playable into.
timeControl
Returns
Initialize()
void UnityEngine.Timeline.TimeControlPlayable.Initialize (ITimeControl timeControl)
Initializes the behaviour
Parameters
timeControl Component that implements the ITimeControl interface
OnBehaviourPause()
override void UnityEngine.Timeline.TimeControlPlayable.OnBehaviourPause (Playable playable, FrameData info)
This function is called when the Playable play state is changed to PlayState.Paused.
Parameters
playable The playable this behaviour is attached to.
info A FrameData structure that contains information about the current frame context.
References UnityEngine.Timeline.ITimeControl.OnControlTimeStop().
OnBehaviourPlay()
override void UnityEngine.Timeline.TimeControlPlayable.OnBehaviourPlay (Playable playable, FrameData info)
This function is called when the Playable play state is changed to Playables.PlayState.Playing.
Parameters
playable The Playable that owns the current PlayableBehaviour.
info A FrameData structure that contains information about the current frame context.
References UnityEngine.Timeline.ITimeControl.OnControlTimeStart().
PrepareFrame()
override void UnityEngine.Timeline.TimeControlPlayable.PrepareFrame (Playable playable, FrameData info)
This function is called during the PrepareFrame phase of the PlayableGraph.
Parameters
playable The Playable that owns the current PlayableBehaviour.
info A FrameData structure that contains information about the current frame context.
References UnityEngine.Timeline.ITimeControl.SetTime().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Runtime/Playables/TimeControlPlayable.cs