VirtualTours: UnityEditor.Timeline.AnimationTrackRecorder Class Reference
UnityEditor.Timeline.AnimationTrackRecorder Class Reference
Public Member Functions
void PrepareForRecord (WindowState state)
AnimationClip PrepareTrack (TrackAsset track, WindowState state, GameObject gameObject, out double startTime)
void FinializeTrack (TrackAsset track, WindowState state)
void FinalizeRecording (WindowState state)
Static Public Member Functions
static string GetUniqueRecordedClipName (Object owner, string name)
static TimelineClip AddRecordableClip (TrackAsset parentTrack, WindowState state, double atTime)
Static Public Attributes
static readonly string kRecordClipDefaultName = L10n.Tr("Recorded")
Properties
TimelineClip recordClip [get]
Member Function Documentation
AddRecordableClip()
static TimelineClip UnityEditor.Timeline.AnimationTrackRecorder.AddRecordableClip (TrackAsset parentTrack, WindowState state, double atTime) static
References UnityEditor.Timeline.ISequenceState.asset, UnityEngine.Timeline.AnimationTrack.CreateRecordableClip(), UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.AnimationTrackRecorder.GetUniqueRecordedClipName(), UnityEditor.Timeline.AnimationTrackRecorder.kRecordClipDefaultName, UnityEngine.Timeline.TimelineClip.mixInCurve, and UnityEditor.Timeline.WindowState.Refresh().
Referenced by UnityEditor.Timeline.AnimationTrackRecorder.PrepareTrack().
FinalizeRecording()
void UnityEditor.Timeline.AnimationTrackRecorder.FinalizeRecording (WindowState state)
References UnityEditor.Timeline.WindowState.EvaluateImmediate(), UnityEditor.Timeline.WindowState.GetWindow(), UnityEditor.Timeline.WindowState.rebuildGraph, and UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
FinializeTrack()
void UnityEditor.Timeline.AnimationTrackRecorder.FinializeTrack (TrackAsset track, WindowState state)
References UnityEditor.Timeline.WindowState.CalculateRowRects(), UnityEngine.Timeline.TimelineClip.duration, and UnityEditor.Timeline.AnimationTrackRecorder.recordClip.
GetUniqueRecordedClipName()
static string UnityEditor.Timeline.AnimationTrackRecorder.GetUniqueRecordedClipName (Object owner, string name) static
Referenced by UnityEditor.Timeline.AnimationTrackRecorder.AddRecordableClip().
PrepareForRecord()
void UnityEditor.Timeline.AnimationTrackRecorder.PrepareForRecord (WindowState state)
PrepareTrack()
AnimationClip UnityEditor.Timeline.AnimationTrackRecorder.PrepareTrack (TrackAsset track, WindowState state, GameObject gameObject, out double startTime)
References UnityEditor.Timeline.AnimationTrackRecorder.AddRecordableClip(), UnityEngine.Timeline.TimelineClip.animationClip, UnityEngine.Timeline.TimelineClip.duration, UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.AnimationTrackRecorder.recordClip, UnityEngine.Timeline.TimelineClip.start, UnityEditor.Timeline.ISequenceState.time, and UnityEngine.Timeline.TimelineClip.ToLocalTimeUnbound().
Member Data Documentation
kRecordClipDefaultName
readonly string UnityEditor.Timeline.AnimationTrackRecorder.kRecordClipDefaultName = L10n.Tr("Recorded") static
Referenced by UnityEditor.Timeline.AnimationTrackRecorder.AddRecordableClip().
Property Documentation
recordClip
TimelineClip UnityEditor.Timeline.AnimationTrackRecorder.recordClip get
Referenced by UnityEditor.Timeline.AnimationTrackRecorder.FinializeTrack(), and UnityEditor.Timeline.AnimationTrackRecorder.PrepareTrack().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Recording/AnimationTrackRecorder.cs