VirtualTours: TMPro.TMP_EditorTests Class Reference
TMPro.TMP_EditorTests Class Reference
Public Member Functions
void Setup ()
void InternalResourceCheck (string filePath, string guid)
void TextParsing_TextInfoTest_WordWrappingDisabled (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
void TextParsing_TextInfoTest_WordWrappingEnabled (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
void TextParsing_TextInfoTest_TopJustifiedAlignment (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
void TextParsing_TextInfoTest_RichText (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
Member Function Documentation
InternalResourceCheck()
void TMPro.TMP_EditorTests.InternalResourceCheck (string filePath, string guid)
Setup()
void TMPro.TMP_EditorTests.Setup ()
References TMPro.TMP_Text.fontSize.
TextParsing_TextInfoTest_RichText()
void TMPro.TMP_EditorTests.TextParsing_TextInfoTest_RichText (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
References TMPro.TMP_Text.alignment, TMPro.TMP_TextInfo.characterCount, TMPro.TMP_Text.enableWordWrapping, TMPro.TextMeshPro.ForceMeshUpdate(), TMPro.TMP_TextInfo.lineCount, TMPro.TMP_Text.rectTransform, TMPro.TMP_TextInfo.spaceCount, TMPro.TMP_Text.text, TMPro.TMP_Text.textInfo, and TMPro.TMP_TextInfo.wordCount.
TextParsing_TextInfoTest_TopJustifiedAlignment()
void TMPro.TMP_EditorTests.TextParsing_TextInfoTest_TopJustifiedAlignment (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
References TMPro.TMP_Text.alignment, TMPro.TMP_TextInfo.characterCount, TMPro.TMP_Text.enableWordWrapping, TMPro.TextMeshPro.ForceMeshUpdate(), TMPro.TMP_TextInfo.lineCount, TMPro.TMP_Text.rectTransform, TMPro.TMP_TextInfo.spaceCount, TMPro.TMP_Text.text, TMPro.TMP_Text.textInfo, and TMPro.TMP_TextInfo.wordCount.
TextParsing_TextInfoTest_WordWrappingDisabled()
void TMPro.TMP_EditorTests.TextParsing_TextInfoTest_WordWrappingDisabled (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
References TMPro.TMP_Text.alignment, TMPro.TMP_TextInfo.characterCount, TMPro.TMP_Text.enableWordWrapping, TMPro.TextMeshPro.ForceMeshUpdate(), TMPro.TMP_TextInfo.lineCount, TMPro.TMP_Text.rectTransform, TMPro.TMP_TextInfo.spaceCount, TMPro.TMP_Text.text, TMPro.TMP_Text.textInfo, and TMPro.TMP_TextInfo.wordCount.
TextParsing_TextInfoTest_WordWrappingEnabled()
void TMPro.TMP_EditorTests.TextParsing_TextInfoTest_WordWrappingEnabled (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
References TMPro.TMP_Text.alignment, TMPro.TMP_TextInfo.characterCount, TMPro.TMP_Text.enableWordWrapping, TMPro.TextMeshPro.ForceMeshUpdate(), TMPro.TMP_TextInfo.lineCount, TMPro.TMP_Text.rectTransform, TMPro.TMP_TextInfo.spaceCount, TMPro.TMP_Text.text, TMPro.TMP_Text.textInfo, and TMPro.TMP_TextInfo.wordCount.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Tests/Editor/TMP_EditorTests.cs