VirtualTours: Packages.Rider.Editor.RiderScriptEditor Class Reference
Packages.Rider.Editor.RiderScriptEditor Class Reference
Public Member Functions
RiderScriptEditor (IDiscovery discovery, IGenerator projectGeneration)
void OnGUI ()
void SyncIfNeeded (string[] addedFiles, string[] deletedFiles, string[] movedFiles, string[] movedFromFiles, string[] importedFiles)
void SyncAll ()
void Initialize (string editorInstallationPath)
bool OpenProject (string path, int line, int column)
bool TryGetInstallationForPath (string editorPath, out CodeEditor.Installation installation)
void CreateSolutionIfDoesntExist ()
Static Public Member Functions
static bool IsRiderInstallation (string path)
Properties
static string CurrentEditor [get]
CodeEditor.Installation[] Installations [get]
Constructor & Destructor Documentation
RiderScriptEditor()
Packages.Rider.Editor.RiderScriptEditor.RiderScriptEditor (IDiscovery discovery, IGenerator projectGeneration)
Member Function Documentation
CreateSolutionIfDoesntExist()
void Packages.Rider.Editor.RiderScriptEditor.CreateSolutionIfDoesntExist ()
References Packages.Rider.Editor.IGenerator.HasSolutionBeenGenerated(), and Packages.Rider.Editor.IGenerator.Sync().
Initialize()
void Packages.Rider.Editor.RiderScriptEditor.Initialize (string editorInstallationPath)
References Packages.Rider.Editor.RiderScriptEditorData.Invalidate(), and Packages.Rider.Editor.IGenerator.Sync().
IsRiderInstallation()
static bool Packages.Rider.Editor.RiderScriptEditor.IsRiderInstallation (string path) static
Referenced by Packages.Rider.Editor.PostProcessors.RiderAssetPostprocessor.OnPreGeneratingCSProjectFiles(), and Packages.Rider.Editor.RiderScriptEditor.TryGetInstallationForPath().
OnGUI()
void Packages.Rider.Editor.RiderScriptEditor.OnGUI ()
References Packages.Rider.Editor.IGenerator.AssemblyNameProvider, Packages.Rider.Editor.IGenerator.GenerateAll(), and Packages.Rider.Editor.IAssemblyNameProvider.GeneratePlayerProjects().
OpenProject()
bool Packages.Rider.Editor.RiderScriptEditor.OpenProject (string path, int line, int column)
SyncAll()
void Packages.Rider.Editor.RiderScriptEditor.SyncAll ()
References Packages.Rider.Editor.IGenerator.Sync().
SyncIfNeeded()
void Packages.Rider.Editor.RiderScriptEditor.SyncIfNeeded (string[] addedFiles, string[] deletedFiles, string[] movedFiles, string[] movedFromFiles, string[] importedFiles)
References Packages.Rider.Editor.IGenerator.SyncIfNeeded().
TryGetInstallationForPath()
bool Packages.Rider.Editor.RiderScriptEditor.TryGetInstallationForPath (string editorPath, out CodeEditor.Installation installation)
References Packages.Rider.Editor.RiderScriptEditor.IsRiderInstallation().
Property Documentation
CurrentEditor
string Packages.Rider.Editor.RiderScriptEditor.CurrentEditor static get
Referenced by Packages.Rider.Editor.RiderScriptEditorData.Init(), and Packages.Rider.Editor.RiderPathLocator.RiderInfo.RiderInfo().
Installations
CodeEditor.Installation [] Packages.Rider.Editor.RiderScriptEditor.Installations get
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.ide.rider@1.2.1/Rider/Editor/RiderScriptEditor.cs