VirtualTours: UnityEditor.Timeline.TimelineWindowTimeControl Class Reference
UnityEditor.Timeline.TimelineWindowTimeControl Class Reference
Classes
struct ClipData
Public Member Functions
void Init (AnimationWindowState animState, TimelineClip clip)
void Init (AnimationWindowState animState, ClipData clip)
override void OnEnable ()
void OnDisable ()
override void GoToTime (float newTime)
override void GoToFrame (int frame)
override void StartScrubTime ()
override void EndScrubTime ()
override void ScrubTime (float newTime)
override void GoToPreviousFrame ()
override void GoToNextFrame ()
override void GoToPreviousKeyframe ()
override void GoToNextKeyframe ()
override void GoToFirstKeyframe ()
override void GoToLastKeyframe ()
override bool StartPlayback ()
override void StopPlayback ()
override bool PlaybackUpdate ()
override bool StartRecording (Object targetObject)
override void StopRecording ()
override void OnSelectionChanged ()
override void ResampleAnimation ()
override bool StartPreview ()
override void StopPreview ()
override void ProcessCandidates ()
override void ClearCandidates ()
Properties
override AnimationKeyTime time [get]
override bool canPlay [get]
override bool playing [get]
override bool canRecord [get]
override bool recording [get]
override bool canPreview [get]
override bool previewing [get]
Member Function Documentation
ClearCandidates()
override void UnityEditor.Timeline.TimelineWindowTimeControl.ClearCandidates ()
EndScrubTime()
override void UnityEditor.Timeline.TimelineWindowTimeControl.EndScrubTime ()
GoToFirstKeyframe()
override void UnityEditor.Timeline.TimelineWindowTimeControl.GoToFirstKeyframe ()
References UnityEditor.Timeline.TimelineWindowTimeControl.GoToTime().
GoToFrame()
override void UnityEditor.Timeline.TimelineWindowTimeControl.GoToFrame (int frame)
GoToLastKeyframe()
override void UnityEditor.Timeline.TimelineWindowTimeControl.GoToLastKeyframe ()
References UnityEngine.Timeline.TimelineClip.asset, UnityEngine.Timeline.AnimationPlayableAsset.clip, UnityEngine.Timeline.TimelineClip.clipAssetDuration, UnityEngine.Timeline.TimelineClip.curves, UnityEditor.Timeline.TimelineWindowTimeControl.ClipData.duration, and UnityEditor.Timeline.TimelineWindowTimeControl.GoToTime().
GoToNextFrame()
override void UnityEditor.Timeline.TimelineWindowTimeControl.GoToNextFrame ()
References UnityEditor.Timeline.WindowState.editSequence, and UnityEditor.Timeline.ISequenceState.frame.
GoToNextKeyframe()
override void UnityEditor.Timeline.TimelineWindowTimeControl.GoToNextKeyframe ()
References UnityEditor.Timeline.TimelineWindowTimeControl.GoToTime(), and UnityEditor.Timeline.TimelineWindowTimeControl.time.
GoToPreviousFrame()
override void UnityEditor.Timeline.TimelineWindowTimeControl.GoToPreviousFrame ()
References UnityEditor.Timeline.WindowState.editSequence, and UnityEditor.Timeline.ISequenceState.frame.
GoToPreviousKeyframe()
override void UnityEditor.Timeline.TimelineWindowTimeControl.GoToPreviousKeyframe ()
References UnityEditor.Timeline.TimelineWindowTimeControl.GoToTime(), and UnityEditor.Timeline.TimelineWindowTimeControl.time.
GoToTime()
override void UnityEditor.Timeline.TimelineWindowTimeControl.GoToTime (float newTime)
Referenced by UnityEditor.Timeline.TimelineWindowTimeControl.GoToFirstKeyframe(), UnityEditor.Timeline.TimelineWindowTimeControl.GoToLastKeyframe(), UnityEditor.Timeline.TimelineWindowTimeControl.GoToNextKeyframe(), and UnityEditor.Timeline.TimelineWindowTimeControl.GoToPreviousKeyframe().
Init() [1/2]
void UnityEditor.Timeline.TimelineWindowTimeControl.Init (AnimationWindowState animState, ClipData clip)
Init() [2/2]
void UnityEditor.Timeline.TimelineWindowTimeControl.Init (AnimationWindowState animState, TimelineClip clip)
Referenced by UnityEditor.Timeline.TimelineAnimationUtilities.CreateTimeController().
OnDisable()
void UnityEditor.Timeline.TimelineWindowTimeControl.OnDisable ()
References UnityEditor.Timeline.WindowState.OnTimeChange.
OnEnable()
override void UnityEditor.Timeline.TimelineWindowTimeControl.OnEnable ()
References UnityEditor.Timeline.WindowState.OnTimeChange.
OnSelectionChanged()
override void UnityEditor.Timeline.TimelineWindowTimeControl.OnSelectionChanged ()
PlaybackUpdate()
override bool UnityEditor.Timeline.TimelineWindowTimeControl.PlaybackUpdate ()
References UnityEditor.Timeline.WindowState.playing.
ProcessCandidates()
override void UnityEditor.Timeline.TimelineWindowTimeControl.ProcessCandidates ()
ResampleAnimation()
override void UnityEditor.Timeline.TimelineWindowTimeControl.ResampleAnimation ()
ScrubTime()
override void UnityEditor.Timeline.TimelineWindowTimeControl.ScrubTime (float newTime)
StartPlayback()
override bool UnityEditor.Timeline.TimelineWindowTimeControl.StartPlayback ()
References UnityEditor.Timeline.WindowState.playing.
StartPreview()
override bool UnityEditor.Timeline.TimelineWindowTimeControl.StartPreview ()
References UnityEditor.Timeline.WindowState.previewMode.
StartRecording()
override bool UnityEditor.Timeline.TimelineWindowTimeControl.StartRecording (Object targetObject)
References UnityEditor.Timeline.WindowState.ArmForRecord(), UnityEditor.Timeline.TimelineWindowTimeControl.canRecord, and UnityEditor.Timeline.WindowState.recording.
StartScrubTime()
override void UnityEditor.Timeline.TimelineWindowTimeControl.StartScrubTime ()
StopPlayback()
override void UnityEditor.Timeline.TimelineWindowTimeControl.StopPlayback ()
StopPreview()
override void UnityEditor.Timeline.TimelineWindowTimeControl.StopPreview ()
References UnityEditor.Timeline.WindowState.previewMode.
StopRecording()
override void UnityEditor.Timeline.TimelineWindowTimeControl.StopRecording ()
References UnityEditor.Timeline.WindowState.UnarmForRecord().
Property Documentation
canPlay
override bool UnityEditor.Timeline.TimelineWindowTimeControl.canPlay get
canPreview
override bool UnityEditor.Timeline.TimelineWindowTimeControl.canPreview get
canRecord
override bool UnityEditor.Timeline.TimelineWindowTimeControl.canRecord get
Referenced by UnityEditor.Timeline.TimelineWindowTimeControl.StartRecording().
playing
override bool UnityEditor.Timeline.TimelineWindowTimeControl.playing get
previewing
override bool UnityEditor.Timeline.TimelineWindowTimeControl.previewing get
recording
override bool UnityEditor.Timeline.TimelineWindowTimeControl.recording get
time
override AnimationKeyTime UnityEditor.Timeline.TimelineWindowTimeControl.time get
Referenced by UnityEditor.Timeline.TimelineWindowTimeControl.GoToNextKeyframe(), and UnityEditor.Timeline.TimelineWindowTimeControl.GoToPreviousKeyframe().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Window/TimelineWindowTimeControl.cs