VirtualTours: UnityEditor.Timeline.TrackDrawer Class Reference
UnityEditor.Timeline.TrackDrawer Class Reference
Public Member Functions
virtual bool DrawTrackHeaderButton (Rect rect, TrackAsset track, WindowState state)
virtual bool DrawTrack (Rect trackRect, TrackAsset trackAsset, Vector2 visibleTime, WindowState state)
virtual void DrawRecordingBackground (Rect trackRect, TrackAsset trackAsset, Vector2 visibleTime, WindowState state)
Static Public Member Functions
static TrackDrawer CreateInstance (TrackAsset trackAsset)
Properties
TrackAsset track [get]
Member Function Documentation
CreateInstance()
static TrackDrawer UnityEditor.Timeline.TrackDrawer.CreateInstance (TrackAsset trackAsset) static
References UnityEditor.Timeline.TrackDrawer.CreateInstance(), and UnityEditor.Timeline.TrackDrawer.track.
Referenced by UnityEditor.Timeline.TrackDrawer.CreateInstance(), and UnityEditor.Timeline.TimelineTrackBaseGUI.TimelineTrackBaseGUI().
DrawRecordingBackground()
virtual void UnityEditor.Timeline.TrackDrawer.DrawRecordingBackground (Rect trackRect, TrackAsset trackAsset, Vector2 visibleTime, WindowState state) virtual
Reimplemented in UnityEditor.Timeline.AnimationTrackDrawer.
References UnityEngine.Timeline.DirectorNamedColor.colorTrackBackgroundRecording, UnityEditor.Timeline.DirectorStyles.customSkin, and UnityEditor.Timeline.DirectorStyles.Instance.
DrawTrack()
virtual bool UnityEditor.Timeline.TrackDrawer.DrawTrack (Rect trackRect, TrackAsset trackAsset, Vector2 visibleTime, WindowState state) virtual
Reimplemented in UnityEditor.Timeline.InfiniteTrackDrawer.
Referenced by UnityEditor.Timeline.TimelineTrackGUI.Draw().
DrawTrackHeaderButton()
virtual bool UnityEditor.Timeline.TrackDrawer.DrawTrackHeaderButton (Rect rect, TrackAsset track, WindowState state) virtual
Reimplemented in UnityEditor.Timeline.AnimationTrackDrawer.
Property Documentation
track
TrackAsset UnityEditor.Timeline.TrackDrawer.track get protected
Referenced by UnityEditor.Timeline.InfiniteTrackDrawer.CanDraw(), UnityEditor.Timeline.TrackDrawer.CreateInstance(), and UnityEditor.Timeline.AnimationTrackDrawer.DrawTrackHeaderButton().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/Drawers/TrackDrawer.cs