VirtualTours: UnityEditor.Timeline.CurveDataSource Class Reference
UnityEditor.Timeline.CurveDataSource Class Reference
Public Member Functions
virtual void UpdateCurves (List< CurveWrapper > updatedCurves)
virtual void RebuildCurves ()
Rect GetBackgroundRect (WindowState state)
List< CurveWrapper > GenerateWrappers (List< EditorCurveBinding > bindings)
Static Public Member Functions
static CurveDataSource Create (IRowGUI trackGUI)
static CurveDataSource Create (TimelineClipGUI clipGUI)
Protected Member Functions
CurveDataSource (IRowGUI trackGUI)
virtual void ConfigureCurveWrapper (CurveWrapper wrapper)
virtual int CreateHashCode ()
Properties
int id [get]
IRowGUI trackGUI [get]
abstract AnimationClip animationClip [get]
abstract float start [get]
abstract float timeScale [get]
abstract string groupingName [get]
Constructor & Destructor Documentation
CurveDataSource()
UnityEditor.Timeline.CurveDataSource.CurveDataSource (IRowGUI trackGUI) protected
References UnityEditor.Timeline.CurveDataSource.trackGUI.
Member Function Documentation
ConfigureCurveWrapper()
virtual void UnityEditor.Timeline.CurveDataSource.ConfigureCurveWrapper (CurveWrapper wrapper) protected virtual
Reimplemented in UnityEditor.Timeline.TrackParametersCurveDataSource, and UnityEditor.Timeline.ClipParametersCurveDataSource.
References UnityEditor.Timeline.CurveDataSource.animationClip.
Referenced by UnityEditor.Timeline.CurveDataSource.GenerateWrappers().
Create() [1/2]
static CurveDataSource UnityEditor.Timeline.CurveDataSource.Create (IRowGUI trackGUI) static
References UnityEditor.Timeline.IRowGUI.asset, and UnityEditor.Timeline.CurveDataSource.trackGUI.
Create() [2/2]
static CurveDataSource UnityEditor.Timeline.CurveDataSource.Create (TimelineClipGUI clipGUI) static
References UnityEngine.Timeline.TimelineClip.animationClip, and UnityEditor.Timeline.TimelineClipGUI.clip.
CreateHashCode()
virtual int UnityEditor.Timeline.CurveDataSource.CreateHashCode () protected virtual
Reimplemented in UnityEditor.Timeline.ClipParametersCurveDataSource, and UnityEditor.Timeline.ClipAnimationCurveDataSource.
GenerateWrappers()
List<CurveWrapper> UnityEditor.Timeline.CurveDataSource.GenerateWrappers (List< EditorCurveBinding > bindings)
References UnityEditor.Timeline.CurveDataSource.ConfigureCurveWrapper().
Referenced by UnityEditor.BindingSelector.RefreshCurves().
GetBackgroundRect()
Rect UnityEditor.Timeline.CurveDataSource.GetBackgroundRect (WindowState state)
References UnityEditor.Timeline.ISequenceState.asset, UnityEngine.Timeline.TimelineAsset.duration, UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.WindowState.timeAreaScale, and UnityEditor.Timeline.WindowState.timeAreaTranslation.
RebuildCurves()
virtual void UnityEditor.Timeline.CurveDataSource.RebuildCurves () virtual
Reimplemented in UnityEditor.Timeline.TrackParametersCurveDataSource, and UnityEditor.Timeline.ClipParametersCurveDataSource.
UpdateCurves()
virtual void UnityEditor.Timeline.CurveDataSource.UpdateCurves (List< CurveWrapper > updatedCurves) virtual
Reimplemented in UnityEditor.Timeline.TrackParametersCurveDataSource, and UnityEditor.Timeline.ClipParametersCurveDataSource.
Property Documentation
animationClip
abstract AnimationClip UnityEditor.Timeline.CurveDataSource.animationClip get
Referenced by UnityEditor.Timeline.CurveDataSource.ConfigureCurveWrapper(), UnityEditor.BindingSelector.Delete(), and UnityEditor.BindingSelector.InitIfNeeded().
groupingName
abstract string UnityEditor.Timeline.CurveDataSource.groupingName get
Referenced by UnityEditorInternal.BindingTreeViewDataSource.FetchData().
id
int UnityEditor.Timeline.CurveDataSource.id get
start
abstract float UnityEditor.Timeline.CurveDataSource.start get
timeScale
abstract float UnityEditor.Timeline.CurveDataSource.timeScale get
trackGUI
IRowGUI UnityEditor.Timeline.CurveDataSource.trackGUI get protected
Referenced by UnityEditor.Timeline.CurveDataSource.Create(), and UnityEditor.Timeline.CurveDataSource.CurveDataSource().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Animation/CurveDataSource.cs