VirtualTours: UnityEditor.Timeline.TimelineMarkerClusterGUI Class Reference
UnityEditor.Timeline.TimelineMarkerClusterGUI Class Reference
Public Member Functions
TimelineMarkerClusterGUI (List< TimelineMarkerGUI > guis, IRowGUI parent, IZOrderProvider zOrderProvider, LayerZOrder layerZOrder)
override void Select ()
override void Deselect ()
override void Draw (Rect trackRect, bool trackRectChanged, WindowState state)
override Rect RectToTimeline (Rect trackRect, WindowState state)
void CycleTop ()
Public Member Functions inherited from UnityEditor.Timeline.TimelineItemGUI
virtual bool IsSelected ()
virtual void StartDrag ()
virtual void StopDrag ()
Static Public Member Functions
static bool CanCycleMarkers ()
static void CycleMarkers ()
Properties
TimelineMarkerGUI topMarker [get]
override double start [get]
override double end [get]
override ITimelineItem item [get]
Properties inherited from UnityEditor.Timeline.TimelineItemGUI
abstract ITimelineItem item [get]
abstract double start [get]
abstract double end [get]
LayerZOrder zOrder [get, set]
bool visible [get, set]
bool isInvalid [get, set]
IRowGUI parent [get]
Rect rect [get]
Rect treeViewRect [get, protected set]
Properties inherited from UnityEditor.Timeline.ILayerable
LayerZOrder zOrder [get]
Additional Inherited Members
Protected Member Functions inherited from UnityEditor.Timeline.TimelineItemGUI
TimelineItemGUI (IRowGUI parent)
Protected Attributes inherited from UnityEditor.Timeline.TimelineItemGUI
readonly DirectorStyles m_Styles
Constructor & Destructor Documentation
TimelineMarkerClusterGUI()
UnityEditor.Timeline.TimelineMarkerClusterGUI.TimelineMarkerClusterGUI (List< TimelineMarkerGUI > guis, IRowGUI parent, IZOrderProvider zOrderProvider, LayerZOrder layerZOrder)
References UnityEditor.Timeline.TimelineMarkerGUI.onStartDrag, UnityEditor.Timeline.TimelineMarkerClusterGUI.topMarker, and UnityEditor.Timeline.TimelineItemGUI.zOrder.
Member Function Documentation
CanCycleMarkers()
static bool UnityEditor.Timeline.TimelineMarkerClusterGUI.CanCycleMarkers () static
References UnityEditor.Timeline.TimelineMarkerGUI.IsSelected(), and UnityEditor.Timeline.TimelineMarkerClusterGUI.topMarker.
CycleMarkers()
static void UnityEditor.Timeline.TimelineMarkerClusterGUI.CycleMarkers () static
References UnityEditor.Timeline.TimelineMarkerGUI.Deselect(), and UnityEditor.Timeline.TimelineMarkerClusterGUI.topMarker.
Referenced by UnityEditor.Timeline.SelectAndMoveItem.MouseUp().
CycleTop()
void UnityEditor.Timeline.TimelineMarkerClusterGUI.CycleTop ()
References UnityEditor.Timeline.TimelineMarkerGUI.onStartDrag, UnityEditor.Timeline.TimelineMarkerClusterGUI.topMarker, and UnityEditor.Timeline.TimelineItemGUI.zOrder.
Deselect()
override void UnityEditor.Timeline.TimelineMarkerClusterGUI.Deselect () virtual
Reimplemented from UnityEditor.Timeline.TimelineItemGUI.
Draw()
override void UnityEditor.Timeline.TimelineMarkerClusterGUI.Draw (Rect trackRect, bool trackRectChanged, WindowState state) virtual
Implements UnityEditor.Timeline.TimelineItemGUI.
References UnityEditor.Timeline.TimelineMarkerGUI.Draw(), UnityEditor.Timeline.DirectorStyles.Instance, UnityEditor.Timeline.DirectorStyles.markerMultiOverlay, UnityEditor.Timeline.TimelineMarkerClusterGUI.topMarker, and UnityEditor.Timeline.TimelineItemGUI.treeViewRect.
RectToTimeline()
override Rect UnityEditor.Timeline.TimelineMarkerClusterGUI.RectToTimeline (Rect trackRect, WindowState state) virtual
Implements UnityEditor.Timeline.TimelineItemGUI.
References UnityEditor.Timeline.TimelineMarkerGUI.RectToTimeline(), and UnityEditor.Timeline.TimelineMarkerClusterGUI.topMarker.
Select()
override void UnityEditor.Timeline.TimelineMarkerClusterGUI.Select () virtual
Reimplemented from UnityEditor.Timeline.TimelineItemGUI.
Property Documentation
end
override double UnityEditor.Timeline.TimelineMarkerClusterGUI.end get
item
override ITimelineItem UnityEditor.Timeline.TimelineMarkerClusterGUI.item get
start
override double UnityEditor.Timeline.TimelineMarkerClusterGUI.start get
topMarker
TimelineMarkerGUI UnityEditor.Timeline.TimelineMarkerClusterGUI.topMarker get
Referenced by UnityEditor.Timeline.TimelineMarkerClusterGUI.CanCycleMarkers(), UnityEditor.Timeline.TimelineMarkerClusterGUI.CycleMarkers(), UnityEditor.Timeline.TimelineMarkerClusterGUI.CycleTop(), UnityEditor.Timeline.TimelineMarkerClusterGUI.Draw(), UnityEditor.Timeline.TimelineMarkerClusterGUI.RectToTimeline(), and UnityEditor.Timeline.TimelineMarkerClusterGUI.TimelineMarkerClusterGUI().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/ItemGui/TimelineMarkerClusterGUI.cs