VirtualTours: UnityEditor.Timeline.MuteSelectedTrack Class Reference
UnityEditor.Timeline.MuteSelectedTrack Class Reference
Public Member Functions
override bool Execute (WindowState state, TrackAsset[] tracks)
Static Public Member Functions
static void Mute (WindowState state, TrackAsset[] tracks, bool shouldMute)
Static Public Member Functions inherited from UnityEditor.Timeline.TrackAction
static void Invoke< T > (WindowState state, TrackAsset[] tracks)
static void GetMenuEntries (WindowState state, Vector2? mousePos, TrackAsset[] tracks, List< MenuActionItem > items)
static bool HandleShortcut (WindowState state, Event evt, TrackAsset[] tracks)
Static Public Member Functions inherited from UnityEditor.Timeline.MenuItemActionBase
static IEnumerable< Type > GetActionsOfType (Type actionType)
static ShortcutAttribute GetShortcutAttributeForAction (MenuItemActionBase action)
static void BuildMenu (GenericMenu menu, List< MenuActionItem > items)
static ActiveInModeAttribute GetActiveInModeAttribute (MenuItemActionBase action)
static bool IsActionActiveInMode (MenuItemActionBase action, TimelineModes mode)
Static Public Attributes
static readonly string UnmuteSelectedText = L10n.Tr("Unmute selected track only")
Protected Member Functions
override MenuActionDisplayState GetDisplayState (WindowState state, TrackAsset[] tracks)
override string GetDisplayName (TrackAsset[] tracks)
Protected Member Functions inherited from UnityEditor.Timeline.TrackAction
virtual bool IsChecked (WindowState state, TrackAsset[] tracks)
Additional Inherited Members
Static Protected Attributes inherited from UnityEditor.Timeline.MenuItemActionBase
static bool s_ShowActionTriggeredByShortcut = false
Properties inherited from UnityEditor.Timeline.MenuItemActionBase
Vector2? mousePosition [get, set]
int priority [get]
string category [get]
string menuName [get]
string? shortCut [get]
bool showInMenu [get]
Member Function Documentation
Execute()
override bool UnityEditor.Timeline.MuteSelectedTrack.Execute (WindowState state, TrackAsset[] tracks) virtual
Implements UnityEditor.Timeline.TrackAction.
References UnityEditor.Timeline.MuteSelectedTrack.Mute().
GetDisplayName()
override string UnityEditor.Timeline.MuteSelectedTrack.GetDisplayName (TrackAsset[] tracks) protected virtual
Reimplemented from UnityEditor.Timeline.TrackAction.
References UnityEditor.Timeline.MuteSelectedTrack.UnmuteSelectedText.
GetDisplayState()
override MenuActionDisplayState UnityEditor.Timeline.MuteSelectedTrack.GetDisplayState (WindowState state, TrackAsset[] tracks) protected virtual
Reimplemented from UnityEditor.Timeline.TrackAction.
Mute()
static void UnityEditor.Timeline.MuteSelectedTrack.Mute (WindowState state, TrackAsset[] tracks, bool shouldMute) static
References UnityEditor.Timeline.WindowState.Refresh().
Referenced by UnityEditor.Timeline.MuteSelectedTrack.Execute().
Member Data Documentation
UnmuteSelectedText
readonly string UnityEditor.Timeline.MuteSelectedTrack.UnmuteSelectedText = L10n.Tr("Unmute selected track only") static
Referenced by UnityEditor.Timeline.MuteSelectedTrack.GetDisplayName().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Actions/TrackActions.cs