VirtualTours: UnityEditor.Timeline.TimelineDataSource Class Reference
UnityEditor.Timeline.TimelineDataSource Class Reference
Public Member Functions
TimelineDataSource (TimelineTreeViewGUI parentGUI, TreeViewController treeView, TimelineWindow sequencerWindow)
override bool IsExpanded (TreeViewItem item)
override bool IsExpandable (TreeViewItem item)
sealed override void FetchData ()
override bool CanBeParent (TreeViewItem item)
void ExpandItems (TreeViewItem item)
Properties
List< TimelineTrackBaseGUI > allTrackGuis [get]
Constructor & Destructor Documentation
TimelineDataSource()
UnityEditor.Timeline.TimelineDataSource.TimelineDataSource (TimelineTreeViewGUI parentGUI, TreeViewController treeView, TimelineWindow sequencerWindow)
References UnityEditor.Timeline.TimelineDataSource.FetchData().
Member Function Documentation
CanBeParent()
override bool UnityEditor.Timeline.TimelineDataSource.CanBeParent (TreeViewItem item)
ExpandItems()
void UnityEditor.Timeline.TimelineDataSource.ExpandItems (TreeViewItem item)
References UnityEditor.Timeline.TimelineTrackBaseGUI.track.
FetchData()
sealed override void UnityEditor.Timeline.TimelineDataSource.FetchData ()
References UnityEditor.Timeline.TimelineDataSource.allTrackGuis.
Referenced by UnityEditor.Timeline.TimelineDataSource.TimelineDataSource().
IsExpandable()
override bool UnityEditor.Timeline.TimelineDataSource.IsExpandable (TreeViewItem item)
References UnityEditor.Timeline.TimelineTrackBaseGUI.expandable.
Referenced by UnityEditor.Timeline.TimelineDataSource.IsExpanded().
IsExpanded()
override bool UnityEditor.Timeline.TimelineDataSource.IsExpanded (TreeViewItem item)
References UnityEditor.Timeline.TimelineDataSource.IsExpandable().
Property Documentation
allTrackGuis
List<TimelineTrackBaseGUI> UnityEditor.Timeline.TimelineDataSource.allTrackGuis get
Referenced by UnityEditor.Timeline.TimelineDataSource.FetchData().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/TimelineDataSource.cs