VirtualTours: Microsoft.Unity.VisualStudio.Editor.ProjectGeneration Class Reference
Microsoft.Unity.VisualStudio.Editor.ProjectGeneration Class Reference
Public Member Functions
ProjectGeneration ()
ProjectGeneration (string tempDirectory)
ProjectGeneration (string tempDirectory, IAssemblyNameProvider assemblyNameProvider, IFileIO fileIoProvider, IGUIDGenerator guidGenerator)
bool SyncIfNeeded (IEnumerable< string > affectedFiles, IEnumerable< string > reimportedFiles)
Syncs the scripting solution if any affected files are relevant.
void Sync ()
bool HasSolutionBeenGenerated ()
bool IsSupportedFile (string path)
void GenerateAndWriteSolutionAndProjects ()
string ProjectFile (Assembly assembly)
string SolutionFile ()
Static Public Attributes
static readonly string MSBuildNamespaceUri = "http://schemas.microsoft.com/developer/msbuild/2003"
Properties
string ProjectDirectory [get]
IAssemblyNameProvider AssemblyNameProvider [get]
Properties inherited from Microsoft.Unity.VisualStudio.Editor.IGenerator
string ProjectDirectory [get]
IAssemblyNameProvider AssemblyNameProvider [get]
Constructor & Destructor Documentation
ProjectGeneration() [1/3]
Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectGeneration ()
ProjectGeneration() [2/3]
Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectGeneration (string tempDirectory)
ProjectGeneration() [3/3]
Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectGeneration (string tempDirectory, IAssemblyNameProvider assemblyNameProvider, IFileIO fileIoProvider, IGUIDGenerator guidGenerator)
References Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectDirectory.
Member Function Documentation
GenerateAndWriteSolutionAndProjects()
void Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.GenerateAndWriteSolutionAndProjects ()
Referenced by Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.Sync().
HasSolutionBeenGenerated()
bool Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.HasSolutionBeenGenerated ()
Implements Microsoft.Unity.VisualStudio.Editor.IGenerator.
References Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.SolutionFile().
Referenced by Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.SyncIfNeeded().
IsSupportedFile()
bool Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.IsSupportedFile (string path)
Implements Microsoft.Unity.VisualStudio.Editor.IGenerator.
ProjectFile()
string Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectFile (Assembly assembly)
References Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectDirectory.
SolutionFile()
string Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.SolutionFile ()
Implements Microsoft.Unity.VisualStudio.Editor.IGenerator.
References Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectDirectory.
Referenced by Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.HasSolutionBeenGenerated().
Sync()
void Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.Sync ()
Implements Microsoft.Unity.VisualStudio.Editor.IGenerator.
References Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.GenerateAndWriteSolutionAndProjects().
Referenced by Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.SyncIfNeeded().
SyncIfNeeded()
bool Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.SyncIfNeeded (IEnumerable< string > affectedFiles, IEnumerable< string > reimportedFiles)
Syncs the scripting solution if any affected files are relevant.
Returns
Whether the solution was synced.
Parameters
affectedFiles A set of files whose status has changed
reimportedFiles A set of files that got reimported
Implements Microsoft.Unity.VisualStudio.Editor.IGenerator.
References Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.HasSolutionBeenGenerated(), and Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.Sync().
Member Data Documentation
MSBuildNamespaceUri
readonly string Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.MSBuildNamespaceUri = "http://schemas.microsoft.com/developer/msbuild/2003" static
Property Documentation
AssemblyNameProvider
IAssemblyNameProvider Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.AssemblyNameProvider get
ProjectDirectory
string Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectDirectory get
Referenced by Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectFile(), Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.ProjectGeneration(), and Microsoft.Unity.VisualStudio.Editor.ProjectGeneration.SolutionFile().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.ide.visualstudio@2.0.2/Editor/ProjectGeneration/ProjectGeneration.cs