VirtualTours: UnityStandardAssets.Water.SpecularLightingEditor Class Reference
UnityStandardAssets.Water.SpecularLightingEditor Class Reference
Public Member Functions
void OnEnable ()
override void OnInspectorGUI ()
Member Function Documentation
OnEnable()
void UnityStandardAssets.Water.SpecularLightingEditor.OnEnable ()
OnInspectorGUI()
override void UnityStandardAssets.Water.SpecularLightingEditor.OnInspectorGUI ()
References WaterEditorUtility.GetMaterialColor(), WaterEditorUtility.GetMaterialFloat(), WaterEditorUtility.SetMaterialColor(), WaterEditorUtility.SetMaterialFloat(), and UnityStandardAssets.Water.WaterBase.sharedMaterial.
The documentation for this class was generated from the following file:
Assets/Standard Assets/Editor/Water/Water4/SpecularLightingEditor.cs