VirtualTours: TMPro.TMP_RuntimeTests Class Reference
TMPro.TMP_RuntimeTests Class Reference
Public Member Functions
void Setup ()
void Parsing_TextInfo_WordWrapDisabled (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
void Parsing_TextInfo_WordWrapEnabled (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
void Parsing_TextInfo_AlignmentTopJustified (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
void Parsing_TextInfo_RichText (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
Static Public Member Functions
static IEnumerable< object[]> TestCases_Parsing_TextInfo_WordWrapDisabled ()
static IEnumerable< object[]> TestCases_Parsing_TextInfo_WordWrapEnabled ()
static IEnumerable< object[]> TestCases_Parsing_TextInfo_AlignmentTopJustified ()
static IEnumerable< object[]> TestCases_Parsing_TextInfo_RichText ()
Member Function Documentation
Parsing_TextInfo_AlignmentTopJustified()
void TMPro.TMP_RuntimeTests.Parsing_TextInfo_AlignmentTopJustified (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
References TMPro.TMP_Text.alignment, TMPro.TMP_TextInfo.characterCount, TMPro.TMP_Text.enableWordWrapping, TMPro.TextMeshPro.ForceMeshUpdate(), TMPro.TMP_TextInfo.lineCount, TMPro.TMP_Text.rectTransform, TMPro.TMP_TextInfo.spaceCount, TMPro.TMP_Text.text, TMPro.TMP_Text.textInfo, and TMPro.TMP_TextInfo.wordCount.
Parsing_TextInfo_RichText()
void TMPro.TMP_RuntimeTests.Parsing_TextInfo_RichText (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
References TMPro.TMP_Text.alignment, TMPro.TMP_TextInfo.characterCount, TMPro.TMP_Text.enableWordWrapping, TMPro.TextMeshPro.ForceMeshUpdate(), TMPro.TMP_TextInfo.lineCount, TMPro.TMP_Text.rectTransform, TMPro.TMP_TextInfo.spaceCount, TMPro.TMP_Text.text, TMPro.TMP_Text.textInfo, and TMPro.TMP_TextInfo.wordCount.
Parsing_TextInfo_WordWrapDisabled()
void TMPro.TMP_RuntimeTests.Parsing_TextInfo_WordWrapDisabled (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
References TMPro.TMP_Text.alignment, TMPro.TMP_TextInfo.characterCount, TMPro.TMP_Text.enableWordWrapping, TMPro.TextMeshPro.ForceMeshUpdate(), TMPro.TMP_TextInfo.lineCount, TMPro.TMP_Text.rectTransform, TMPro.TMP_TextInfo.spaceCount, TMPro.TMP_Text.text, TMPro.TMP_Text.textInfo, and TMPro.TMP_TextInfo.wordCount.
Parsing_TextInfo_WordWrapEnabled()
void TMPro.TMP_RuntimeTests.Parsing_TextInfo_WordWrapEnabled (int sourceTextIndex, int characterCount, int spaceCount, int wordCount, int lineCount)
References TMPro.TMP_Text.alignment, TMPro.TMP_TextInfo.characterCount, TMPro.TMP_Text.enableWordWrapping, TMPro.TextMeshPro.ForceMeshUpdate(), TMPro.TMP_TextInfo.lineCount, TMPro.TMP_Text.rectTransform, TMPro.TMP_TextInfo.spaceCount, TMPro.TMP_Text.text, TMPro.TMP_Text.textInfo, and TMPro.TMP_TextInfo.wordCount.
Setup()
void TMPro.TMP_RuntimeTests.Setup ()
References TMPro.TMP_Text.fontSize.
TestCases_Parsing_TextInfo_AlignmentTopJustified()
static IEnumerable<object[]> TMPro.TMP_RuntimeTests.TestCases_Parsing_TextInfo_AlignmentTopJustified () static
TestCases_Parsing_TextInfo_RichText()
static IEnumerable<object[]> TMPro.TMP_RuntimeTests.TestCases_Parsing_TextInfo_RichText () static
TestCases_Parsing_TextInfo_WordWrapDisabled()
static IEnumerable<object[]> TMPro.TMP_RuntimeTests.TestCases_Parsing_TextInfo_WordWrapDisabled () static
TestCases_Parsing_TextInfo_WordWrapEnabled()
static IEnumerable<object[]> TMPro.TMP_RuntimeTests.TestCases_Parsing_TextInfo_WordWrapEnabled () static
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Tests/Runtime/TMP_RuntimeTests.cs