VirtualTours: Packages.Rider.Editor.RiderScriptEditorData Class Reference
Packages.Rider.Editor.RiderScriptEditorData Class Reference
Public Member Functions
void Init ()
void Invalidate (string editorInstallationPath)
Member Function Documentation
Init()
void Packages.Rider.Editor.RiderScriptEditorData.Init ()
References Packages.Rider.Editor.RiderScriptEditor.CurrentEditor, and Packages.Rider.Editor.RiderScriptEditorData.Invalidate().
Referenced by Packages.Rider.Editor.RiderPathLocator.RiderInfo.RiderInfo().
Invalidate()
void Packages.Rider.Editor.RiderScriptEditorData.Invalidate (string editorInstallationPath)
Referenced by Packages.Rider.Editor.RiderScriptEditorData.Init(), and Packages.Rider.Editor.RiderScriptEditor.Initialize().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.ide.rider@1.2.1/Rider/Editor/RiderScriptEditorData.cs