VirtualTours: UnityEditor.Timeline.MoveItemHandler Class Reference
UnityEditor.Timeline.MoveItemHandler Class Reference
Public Member Functions
MoveItemHandler (WindowState state)
void Grab (IEnumerable< ITimelineItem > items, TrackAsset referenceTrack)
void Grab (IEnumerable< ITimelineItem > items, TrackAsset referenceTrack, Vector2 mousePosition)
void Drop ()
bool ShouldSnapTo (ISnappable snappable)
void UpdateTrackTarget (TrackAsset track)
void OnGUI (Event evt)
void OnAttractedEdge (IAttractable attractable, ManipulateEdges manipulateEdges, AttractedEdge edge, double time)
void RefreshPreviewItems ()
void OnTrackDetach ()
Properties
TrackAsset targetTrack [get]
bool allowTrackSwitch [get]
MovingItems[] movingItems [get]
double start [get]
double end [get]
Properties inherited from UnityEditor.Timeline.IAttractable
double start [get]
double end [get]
Constructor & Destructor Documentation
MoveItemHandler()
UnityEditor.Timeline.MoveItemHandler.MoveItemHandler (WindowState state)
Member Function Documentation
Drop()
void UnityEditor.Timeline.MoveItemHandler.Drop ()
References UnityEditor.Timeline.MoveItemHandler.movingItems.
Grab() [1/2]
void UnityEditor.Timeline.MoveItemHandler.Grab (IEnumerable< ITimelineItem > items, TrackAsset referenceTrack)
Referenced by UnityEditor.Timeline.SelectAndMoveItem.MouseDrag().
Grab() [2/2]
void UnityEditor.Timeline.MoveItemHandler.Grab (IEnumerable< ITimelineItem > items, TrackAsset referenceTrack, Vector2 mousePosition)
References UnityEditor.Timeline.MoveItemHandler.allowTrackSwitch, UnityEditor.Timeline.MovingItems.end, UnityEditor.Timeline.MoveItemHandler.movingItems, UnityEditor.Timeline.MovingItems.start, and UnityEditor.Timeline.MoveItemHandler.targetTrack.
OnAttractedEdge()
void UnityEditor.Timeline.MoveItemHandler.OnAttractedEdge (IAttractable attractable, ManipulateEdges manipulateEdges, AttractedEdge edge, double time)
Implements UnityEditor.Timeline.IAttractionHandler.
References UnityEditor.Timeline.MoveItemHandler.end, UnityEditor.Timeline.MoveItemHandler.movingItems, UnityEditor.Timeline.MoveItemHandler.RefreshPreviewItems(), and UnityEditor.Timeline.MoveItemHandler.start.
OnGUI()
void UnityEditor.Timeline.MoveItemHandler.OnGUI (Event evt)
References UnityEditor.Timeline.TimelineCursors.ClearCursor(), and UnityEditor.Timeline.MoveItemHandler.movingItems.
Referenced by UnityEditor.Timeline.SelectAndMoveItem.Overlay().
OnTrackDetach()
void UnityEditor.Timeline.MoveItemHandler.OnTrackDetach ()
References UnityEditor.Timeline.MoveItemHandler.movingItems.
Referenced by UnityEditor.Timeline.SelectAndMoveItem.MouseDrag().
RefreshPreviewItems()
void UnityEditor.Timeline.MoveItemHandler.RefreshPreviewItems ()
References UnityEditor.Timeline.MoveItemHandler.movingItems.
Referenced by UnityEditor.Timeline.MoveItemHandler.OnAttractedEdge(), and UnityEditor.Timeline.MoveItemHandler.UpdateTrackTarget().
ShouldSnapTo()
bool UnityEditor.Timeline.MoveItemHandler.ShouldSnapTo (ISnappable snappable)
Implements UnityEditor.Timeline.IAttractable.
UpdateTrackTarget()
void UnityEditor.Timeline.MoveItemHandler.UpdateTrackTarget (TrackAsset track)
References UnityEditor.Timeline.MoveItemHandler.movingItems, UnityEditor.Timeline.MoveItemHandler.RefreshPreviewItems(), and UnityEditor.Timeline.MoveItemHandler.targetTrack.
Referenced by UnityEditor.Timeline.SelectAndMoveItem.MouseDrag().
Property Documentation
allowTrackSwitch
bool UnityEditor.Timeline.MoveItemHandler.allowTrackSwitch get
Referenced by UnityEditor.Timeline.MoveItemHandler.Grab(), and UnityEditor.Timeline.SelectAndMoveItem.Overlay().
end
double UnityEditor.Timeline.MoveItemHandler.end get
Referenced by UnityEditor.Timeline.MoveItemHandler.OnAttractedEdge(), and UnityEditor.Timeline.SelectAndMoveItem.Overlay().
movingItems
MovingItems [] UnityEditor.Timeline.MoveItemHandler.movingItems get
Referenced by UnityEditor.Timeline.MoveItemHandler.Drop(), UnityEditor.Timeline.MoveItemHandler.Grab(), UnityEditor.Timeline.MoveItemHandler.OnAttractedEdge(), UnityEditor.Timeline.MoveItemHandler.OnGUI(), UnityEditor.Timeline.MoveItemHandler.OnTrackDetach(), UnityEditor.Timeline.MoveItemHandler.RefreshPreviewItems(), UnityEditor.Timeline.TimelineClipGUI.SnappableEdgesFor(), and UnityEditor.Timeline.MoveItemHandler.UpdateTrackTarget().
start
double UnityEditor.Timeline.MoveItemHandler.start get
Referenced by UnityEditor.Timeline.MoveItemHandler.OnAttractedEdge(), and UnityEditor.Timeline.SelectAndMoveItem.Overlay().
targetTrack
TrackAsset UnityEditor.Timeline.MoveItemHandler.targetTrack get
Referenced by UnityEditor.Timeline.MoveItemHandler.Grab(), UnityEditor.Timeline.SelectAndMoveItem.Overlay(), and UnityEditor.Timeline.MoveItemHandler.UpdateTrackTarget().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Manipulators/Move/MoveItemHandler.cs