VirtualTours: UnityEditor.Timeline.TimelineTreeView Class Reference
UnityEditor.Timeline.TimelineTreeView Class Reference
Public Member Functions
TimelineTreeView (TimelineWindow sequencerWindow, TreeViewController treeView)
void OnInitialize ()
Rect GetRectForFraming (int row)
virtual void BeginRowGUI ()
virtual void EndRowGUI ()
virtual void OnRowGUI (Rect rowRect, TreeViewItem item, int row, bool selected, bool focused)
Rect GetRenameRect (Rect rowRect, int row, TreeViewItem item)
void BeginPingItem (TreeViewItem item, float topPixelOfRow, float availableWidth)
void EndPingItem ()
Rect GetRowRect (int row, float rowWidth)
Rect GetRowRect (int row)
void CalculateRowRects ()
virtual bool BeginRename (TreeViewItem item, float delay)
virtual void EndRename ()
virtual float GetContentIndent (TreeViewItem item)
int GetNumRowsOnPageUpDown (TreeViewItem fromItem, bool pageUp, float heightOfTreeView)
void GetFirstAndLastRowVisible (out int firstRowVisible, out int lastRowVisible)
Vector2 GetTotalSize ()
Protected Member Functions
virtual Vector2 GetSizeOfRow (TreeViewItem item)
virtual float GetFoldoutIndent (TreeViewItem item)
Properties
bool showInsertionMarker [get, set]
virtual float topRowMargin [get]
virtual float bottomRowMargin [get]
virtual float halfDropBetweenHeight [get]
Constructor & Destructor Documentation
TimelineTreeView()
UnityEditor.Timeline.TimelineTreeView.TimelineTreeView (TimelineWindow sequencerWindow, TreeViewController treeView)
References UnityEditor.Timeline.DirectorStyles.foldout, UnityEditor.Timeline.DirectorStyles.Instance, and UnityEditor.Timeline.TimelineWindow.state.
Member Function Documentation
BeginPingItem()
void UnityEditor.Timeline.TimelineTreeView.BeginPingItem (TreeViewItem item, float topPixelOfRow, float availableWidth)
BeginRename()
virtual bool UnityEditor.Timeline.TimelineTreeView.BeginRename (TreeViewItem item, float delay) virtual
BeginRowGUI()
virtual void UnityEditor.Timeline.TimelineTreeView.BeginRowGUI () virtual
References UnityEditor.Timeline.TimelineTreeView.CalculateRowRects(), and UnityEditor.Timeline.TimelineTreeView.GetRowRect().
CalculateRowRects()
void UnityEditor.Timeline.TimelineTreeView.CalculateRowRects ()
References UnityEditor.Timeline.TimelineTreeView.GetSizeOfRow(), UnityEditor.Timeline.TimelineTreeView.halfDropBetweenHeight, UnityEditor.Timeline.TimelineTrackBaseGUI.isExpanded, and UnityEditor.Timeline.TimelineGroupGUI.SetExpanded().
Referenced by UnityEditor.Timeline.TimelineTreeView.BeginRowGUI(), and UnityEditor.Timeline.TimelineTreeView.GetFirstAndLastRowVisible().
EndPingItem()
void UnityEditor.Timeline.TimelineTreeView.EndPingItem ()
EndRename()
virtual void UnityEditor.Timeline.TimelineTreeView.EndRename () virtual
EndRowGUI()
virtual void UnityEditor.Timeline.TimelineTreeView.EndRowGUI () virtual
GetContentIndent()
virtual float UnityEditor.Timeline.TimelineTreeView.GetContentIndent (TreeViewItem item) virtual
References UnityEditor.Timeline.TimelineTreeView.GetFoldoutIndent().
GetFirstAndLastRowVisible()
void UnityEditor.Timeline.TimelineTreeView.GetFirstAndLastRowVisible (out int firstRowVisible, out int lastRowVisible)
References UnityEditor.Timeline.TimelineTreeView.CalculateRowRects(), UnityEditor.Timeline.TimelineTrackBaseGUI.visibleExpanded, and UnityEditor.Timeline.TimelineTrackBaseGUI.visibleRow.
GetFoldoutIndent()
virtual float UnityEditor.Timeline.TimelineTreeView.GetFoldoutIndent (TreeViewItem item) protected virtual
References UnityEditor.Timeline.DirectorStyles.kBaseIndent.
Referenced by UnityEditor.Timeline.TimelineTreeView.GetContentIndent(), and UnityEditor.Timeline.TimelineTreeView.OnRowGUI().
GetNumRowsOnPageUpDown()
int UnityEditor.Timeline.TimelineTreeView.GetNumRowsOnPageUpDown (TreeViewItem fromItem, bool pageUp, float heightOfTreeView)
GetRectForFraming()
Rect UnityEditor.Timeline.TimelineTreeView.GetRectForFraming (int row)
References UnityEditor.Timeline.TimelineTreeView.GetRowRect().
GetRenameRect()
Rect UnityEditor.Timeline.TimelineTreeView.GetRenameRect (Rect rowRect, int row, TreeViewItem item)
GetRowRect() [1/2]
Rect UnityEditor.Timeline.TimelineTreeView.GetRowRect (int row)
GetRowRect() [2/2]
Rect UnityEditor.Timeline.TimelineTreeView.GetRowRect (int row, float rowWidth)
Referenced by UnityEditor.Timeline.TimelineTreeView.BeginRowGUI(), and UnityEditor.Timeline.TimelineTreeView.GetRectForFraming().
GetSizeOfRow()
virtual Vector2 UnityEditor.Timeline.TimelineTreeView.GetSizeOfRow (TreeViewItem item) protected virtual
References UnityEditor.Timeline.TrackEditor.DefaultTrackHeight.
Referenced by UnityEditor.Timeline.TimelineTreeView.CalculateRowRects().
GetTotalSize()
Vector2 UnityEditor.Timeline.TimelineTreeView.GetTotalSize ()
OnInitialize()
void UnityEditor.Timeline.TimelineTreeView.OnInitialize ()
OnRowGUI()
virtual void UnityEditor.Timeline.TimelineTreeView.OnRowGUI (Rect rowRect, TreeViewItem item, int row, bool selected, bool focused) virtual
References UnityEditor.Timeline.TimelineTreeView.GetFoldoutIndent(), UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.TimelineTreeView.showInsertionMarker, UnityEditor.Timeline.TimelineWindow.state, and UnityEditor.Timeline.TimelineMode.TrackState().
Property Documentation
bottomRowMargin
virtual float UnityEditor.Timeline.TimelineTreeView.bottomRowMargin get
halfDropBetweenHeight
virtual float UnityEditor.Timeline.TimelineTreeView.halfDropBetweenHeight get
Referenced by UnityEditor.Timeline.TimelineTreeView.CalculateRowRects().
showInsertionMarker
bool UnityEditor.Timeline.TimelineTreeView.showInsertionMarker get set
Referenced by UnityEditor.Timeline.TimelineTreeView.OnRowGUI().
topRowMargin
virtual float UnityEditor.Timeline.TimelineTreeView.topRowMargin get
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/TimelineTreeView.cs