VirtualTours: UnityEditor.Timeline.TimelineGroupGUI Class Reference
UnityEditor.Timeline.TimelineGroupGUI Class Reference
Public Member Functions
Rect ToWindowSpace (Rect localRect)
TimelineGroupGUI (TreeViewController treeview, TimelineTreeViewGUI treeviewGUI, int id, int depth, TreeViewItem parent, string displayName, TrackAsset trackAsset, bool isRoot)
virtual float GetHeight (WindowState state)
override void OnGraphRebuilt ()
void SetExpanded (bool expanded)
override void Draw (Rect headerRect, Rect contentRect, WindowState state)
Public Member Functions inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
virtual float GetVerticalSpacingBetweenTracks ()
void DrawInsertionMarkers (Rect rowRectWithIndent)
void ClearDrawFlags ()
Protected Member Functions
bool IsSubTrack ()
TrackAsset ParentTrack ()
Protected Member Functions inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
TimelineTrackBaseGUI (int id, int depth, TreeViewItem parent, string displayName, TrackAsset trackAsset, TreeViewController tv, TimelineTreeViewGUI tvgui)
void DrawTrackState (Rect trackRect, Rect expandedRect, TrackAsset track)
float DrawMuteButton (Rect rect, WindowState state)
float DrawLockButton (Rect rect, WindowState state)
Protected Attributes
DirectorStyles m_Styles
Rect m_TreeViewRect = new Rect(0, 0, 0, 0)
GUIContent m_ProblemIcon = new GUIContent()
Protected Attributes inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
bool m_IsRoot = false
Properties
override Rect boundingRect [get]
override bool expandable [get]
Rect expandedRect [get, set]
Rect rowRect [get, set]
Rect dropRect [get, set]
Properties inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
Vector2 treeViewToWindowTransformation [get, set]
bool isExpanded [get, set]
bool isDropTarget [protected get, set]
TrackAsset track [get]
TimelineWindow TimelineWindow [get]
TrackDrawer drawer [get]
bool visibleRow [get, set]
bool visibleExpanded [get, set]
bool drawInsertionMarkerBefore [get, set]
bool drawInsertionMarkerAfter [get, set]
abstract Rect boundingRect [get]
abstract bool expandable [get]
Properties inherited from UnityEditor.Timeline.IBounds
Rect boundingRect [get]
Additional Inherited Members
Static Public Member Functions inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
static TimelineTrackBaseGUI FindGUITrack (TrackAsset track)
Static Protected Attributes inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
const float k_ButtonSize = 16.0f
Constructor & Destructor Documentation
TimelineGroupGUI()
UnityEditor.Timeline.TimelineGroupGUI.TimelineGroupGUI (TreeViewController treeview, TimelineTreeViewGUI treeviewGUI, int id, int depth, TreeViewItem parent, string displayName, TrackAsset trackAsset, bool isRoot)
References UnityEditor.Timeline.ISequenceState.asset, UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.DirectorStyles.Instance, UnityEditor.Timeline.TimelineTrackBaseGUI.m_IsRoot, UnityEditor.Timeline.TimelineGroupGUI.m_Styles, UnityEditor.Timeline.TimelineWindow.state, and UnityEditor.Timeline.TimelineTreeViewGUI.TimelineWindow.
Member Function Documentation
Draw()
override void UnityEditor.Timeline.TimelineGroupGUI.Draw (Rect headerRect, Rect contentRect, WindowState state) virtual
Implements UnityEditor.Timeline.TimelineTrackBaseGUI.
Reimplemented in UnityEditor.Timeline.TimelineTrackGUI.
References UnityEngine.Timeline.DirectorNamedColor.colorDropTarget, UnityEngine.Timeline.DirectorNamedColor.colorGroupTrackBackground, UnityEngine.Timeline.DirectorNamedColor.colorSelection, UnityEngine.Timeline.DirectorNamedColor.colorTrackBackgroundRecording, UnityEngine.Timeline.DirectorNamedColor.colorTrackBackgroundSelected, UnityEngine.Timeline.DirectorNamedColor.colorTrackSubSequenceBackgroundSelected, UnityEditor.Timeline.DirectorStyles.customSkin, UnityEditor.Timeline.DirectorStyles.displayBackground, UnityEditor.Timeline.TimelineTrackBaseGUI.DrawTrackState(), UnityEditor.Timeline.TimelineGroupGUI.expandedRect, UnityEditor.Timeline.DirectorStyles.groupBackground, UnityEditor.Timeline.DirectorStyles.Instance, UnityEditor.Timeline.TimelineTrackBaseGUI.isDropTarget, UnityEditor.Timeline.WindowState.IsEditingASubTimeline(), UnityEditor.Timeline.TimelineTrackBaseGUI.isExpanded, UnityEditor.Timeline.TimelineTrackBaseGUI.m_IsRoot, UnityEditor.Timeline.TimelineGroupGUI.m_Styles, UnityEditor.Timeline.TimelineGroupGUI.m_TreeViewRect, UnityEditor.Timeline.DirectorStyles.referenceTrackLabel, UnityEditor.Timeline.WindowState.timeAreaRect, and UnityEditor.Timeline.TimelineTrackBaseGUI.track.
GetHeight()
virtual float UnityEditor.Timeline.TimelineGroupGUI.GetHeight (WindowState state) virtual
Reimplemented in UnityEditor.Timeline.TimelineTrackGUI.
References UnityEditor.Timeline.TrackEditor.DefaultTrackHeight.
IsSubTrack()
bool UnityEditor.Timeline.TimelineGroupGUI.IsSubTrack () protected
References UnityEngine.Timeline.TrackAsset.parent, and UnityEditor.Timeline.TimelineTrackBaseGUI.track.
Referenced by UnityEditor.Timeline.TimelineGroupGUI.ParentTrack(), and UnityEditor.Timeline.TimelineTrackGUI.TimelineTrackGUI().
OnGraphRebuilt()
override void UnityEditor.Timeline.TimelineGroupGUI.OnGraphRebuilt () virtual
Implements UnityEditor.Timeline.TimelineTrackBaseGUI.
Reimplemented in UnityEditor.Timeline.TimelineTrackGUI.
ParentTrack()
TrackAsset UnityEditor.Timeline.TimelineGroupGUI.ParentTrack () protected
References UnityEditor.Timeline.TimelineGroupGUI.IsSubTrack(), UnityEngine.Timeline.TrackAsset.parent, and UnityEditor.Timeline.TimelineTrackBaseGUI.track.
SetExpanded()
void UnityEditor.Timeline.TimelineGroupGUI.SetExpanded (bool expanded)
References UnityEditor.Timeline.TimelineTrackBaseGUI.isExpanded, and UnityEditor.Timeline.TimelineTrackBaseGUI.track.
Referenced by UnityEditor.Timeline.TimelineTreeView.CalculateRowRects().
ToWindowSpace()
Rect UnityEditor.Timeline.TimelineGroupGUI.ToWindowSpace (Rect localRect)
References UnityEditor.Timeline.TimelineTrackBaseGUI.treeViewToWindowTransformation.
Referenced by UnityEditor.Timeline.InlineCurveResizeHandle.Draw(), and UnityEditor.Timeline.TrackResizeHandle.Draw().
Member Data Documentation
m_ProblemIcon
GUIContent UnityEditor.Timeline.TimelineGroupGUI.m_ProblemIcon = new GUIContent() protected
m_Styles
DirectorStyles UnityEditor.Timeline.TimelineGroupGUI.m_Styles protected
Referenced by UnityEditor.Timeline.TimelineGroupGUI.Draw(), and UnityEditor.Timeline.TimelineGroupGUI.TimelineGroupGUI().
m_TreeViewRect
Rect UnityEditor.Timeline.TimelineGroupGUI.m_TreeViewRect = new Rect(0, 0, 0, 0) protected
Referenced by UnityEditor.Timeline.TimelineGroupGUI.Draw(), and UnityEditor.Timeline.TimelineTrackGUI.Draw().
Property Documentation
boundingRect
override Rect UnityEditor.Timeline.TimelineGroupGUI.boundingRect get
dropRect
Rect UnityEditor.Timeline.TimelineGroupGUI.dropRect get set
expandable
override bool UnityEditor.Timeline.TimelineGroupGUI.expandable get
expandedRect
Rect UnityEditor.Timeline.TimelineGroupGUI.expandedRect get set
Referenced by UnityEditor.Timeline.TimelineGroupGUI.Draw().
rowRect
Rect UnityEditor.Timeline.TimelineGroupGUI.rowRect get set
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/TrackGui/TimelineGroupGUI.cs