VirtualTours: Packages.Rider.Editor.ProjectGeneration Class Reference
Packages.Rider.Editor.ProjectGeneration Class Reference
Public Member Functions
void GenerateAll (bool generateAll)
ProjectGeneration ()
ProjectGeneration (string tempDirectory)
ProjectGeneration (string tempDirectory, IAssemblyNameProvider assemblyNameProvider, IFileIO fileIoProvider, IGUIDGenerator guidGenerator)
bool SyncIfNeeded (IEnumerable< string > affectedFiles, IEnumerable< string > reimportedFiles)
Syncs the scripting solution if any affected files are relevant.
void Sync ()
bool HasSolutionBeenGenerated ()
void GenerateAndWriteSolutionAndProjects (Type[] types)
string ProjectFile (Assembly assembly)
string SolutionFile ()
Static Public Member Functions
static Type[] GetAssetPostprocessorTypes ()
Static Public Attributes
static readonly string MSBuildNamespaceUri = "http://schemas.microsoft.com/developer/msbuild/2003"
Properties
string ProjectDirectory [get]
Properties inherited from Packages.Rider.Editor.IGenerator
string ProjectDirectory [get]
IAssemblyNameProvider AssemblyNameProvider [get]
Constructor & Destructor Documentation
ProjectGeneration() [1/3]
Packages.Rider.Editor.ProjectGeneration.ProjectGeneration ()
ProjectGeneration() [2/3]
Packages.Rider.Editor.ProjectGeneration.ProjectGeneration (string tempDirectory)
ProjectGeneration() [3/3]
Packages.Rider.Editor.ProjectGeneration.ProjectGeneration (string tempDirectory, IAssemblyNameProvider assemblyNameProvider, IFileIO fileIoProvider, IGUIDGenerator guidGenerator)
References Packages.Rider.Editor.ProjectGeneration.ProjectDirectory.
Member Function Documentation
GenerateAll()
void Packages.Rider.Editor.ProjectGeneration.GenerateAll (bool generateAll)
Implements Packages.Rider.Editor.IGenerator.
GenerateAndWriteSolutionAndProjects()
void Packages.Rider.Editor.ProjectGeneration.GenerateAndWriteSolutionAndProjects (Type[] types)
Referenced by Packages.Rider.Editor.ProjectGeneration.Sync().
GetAssetPostprocessorTypes()
static Type [] Packages.Rider.Editor.ProjectGeneration.GetAssetPostprocessorTypes () static
Referenced by Packages.Rider.Editor.ProjectGeneration.Sync().
HasSolutionBeenGenerated()
bool Packages.Rider.Editor.ProjectGeneration.HasSolutionBeenGenerated ()
Implements Packages.Rider.Editor.IGenerator.
References Packages.Rider.Editor.ProjectGeneration.SolutionFile().
ProjectFile()
string Packages.Rider.Editor.ProjectGeneration.ProjectFile (Assembly assembly)
References Packages.Rider.Editor.ProjectGeneration.ProjectDirectory.
SolutionFile()
string Packages.Rider.Editor.ProjectGeneration.SolutionFile ()
Implements Packages.Rider.Editor.IGenerator.
References Packages.Rider.Editor.ProjectGeneration.ProjectDirectory.
Referenced by Packages.Rider.Editor.ProjectGeneration.HasSolutionBeenGenerated().
Sync()
void Packages.Rider.Editor.ProjectGeneration.Sync ()
Implements Packages.Rider.Editor.IGenerator.
References Packages.Rider.Editor.ProjectGeneration.GenerateAndWriteSolutionAndProjects(), and Packages.Rider.Editor.ProjectGeneration.GetAssetPostprocessorTypes().
Referenced by Packages.Rider.Editor.ProjectGeneration.SyncIfNeeded().
SyncIfNeeded()
bool Packages.Rider.Editor.ProjectGeneration.SyncIfNeeded (IEnumerable< string > affectedFiles, IEnumerable< string > reimportedFiles)
Syncs the scripting solution if any affected files are relevant.
Returns
Whether the solution was synced.
Parameters
affectedFiles A set of files whose status has changed
reimportedFiles A set of files that got reimported
Implements Packages.Rider.Editor.IGenerator.
References Packages.Rider.Editor.ProjectGeneration.Sync().
Member Data Documentation
MSBuildNamespaceUri
readonly string Packages.Rider.Editor.ProjectGeneration.MSBuildNamespaceUri = "http://schemas.microsoft.com/developer/msbuild/2003" static
Property Documentation
ProjectDirectory
string Packages.Rider.Editor.ProjectGeneration.ProjectDirectory get
Referenced by Packages.Rider.Editor.ProjectGeneration.ProjectFile(), Packages.Rider.Editor.ProjectGeneration.ProjectGeneration(), and Packages.Rider.Editor.ProjectGeneration.SolutionFile().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.ide.rider@1.2.1/Rider/Editor/ProjectGeneration/ProjectGeneration.cs