VirtualTours: UnityEditor.Timeline.SpacePartitioner Class Reference
UnityEditor.Timeline.SpacePartitioner Class Reference
Classes
class CachedList
Public Member Functions
void Clear ()
void AddBounds (IBounds bounds)
void AddBounds (object item, Rect rect)
IEnumerable< T > GetItemsAtPosition< T > (Vector2 position)
Get items of type T at a given position
IEnumerable< T > GetItemsInArea< T > (Rect area)
void DebugDraw (Color fillColor, Color outlineColor)
Member Function Documentation
AddBounds() [1/2]
void UnityEditor.Timeline.SpacePartitioner.AddBounds (IBounds bounds)
References UnityEditor.Timeline.IBounds.boundingRect.
Referenced by UnityEditor.Timeline.TimelineClipHandle.Draw(), UnityEditor.Timeline.InlineCurveEditor.Draw(), UnityEditor.Timeline.InlineCurveResizeHandle.Draw(), UnityEditor.Timeline.TrackResizeHandle.Draw(), UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw(), and UnityEditor.Timeline.TimelineMarkerGUI.Draw().
AddBounds() [2/2]
void UnityEditor.Timeline.SpacePartitioner.AddBounds (object item, Rect rect)
References UnityEngine.Timeline.IntervalTree< T >.Add().
Clear()
void UnityEditor.Timeline.SpacePartitioner.Clear ()
References UnityEngine.Timeline.IntervalTree< T >.Clear().
DebugDraw()
void UnityEditor.Timeline.SpacePartitioner.DebugDraw (Color fillColor, Color outlineColor)
References UnityEngine.Timeline.IntervalTree< T >.IntersectsWithRange().
GetItemsAtPosition< T >()
IEnumerable<T> UnityEditor.Timeline.SpacePartitioner.GetItemsAtPosition< T > (Vector2 position)
Get items of type T at a given position
Parameters
position
inClipSpace
Template Parameters
T
Uses a (1,1) sized box Use .ToList() or .ToArray() when not enumerating the result immediately
Returns
References UnityEditor.Timeline.SpacePartitioner.GetItemsInArea< T >().
GetItemsInArea< T >()
IEnumerable<T> UnityEditor.Timeline.SpacePartitioner.GetItemsInArea< T > (Rect area)
Parameters
area
inClipSpace
Template Parameters
T
Returns
References UnityEngine.Timeline.IntervalTree< T >.IntersectsWithRange().
Referenced by UnityEditor.Timeline.SpacePartitioner.GetItemsAtPosition< T >().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Utilities/SpacePartitioner.cs