VirtualTours: UnityEditor.Timeline.InfiniteTrackDrawer Class Reference
UnityEditor.Timeline.InfiniteTrackDrawer Class Reference
Public Member Functions
InfiniteTrackDrawer (IPropertyKeyDataSource dataSource)
bool CanDraw (TrackAsset track, WindowState state)
override bool DrawTrack (Rect trackRect, TrackAsset trackAsset, Vector2 visibleTime, WindowState state)
Public Member Functions inherited from UnityEditor.Timeline.TrackDrawer
virtual bool DrawTrackHeaderButton (Rect rect, TrackAsset track, WindowState state)
virtual void DrawRecordingBackground (Rect trackRect, TrackAsset trackAsset, Vector2 visibleTime, WindowState state)
Additional Inherited Members
Static Public Member Functions inherited from UnityEditor.Timeline.TrackDrawer
static TrackDrawer CreateInstance (TrackAsset trackAsset)
Properties inherited from UnityEditor.Timeline.TrackDrawer
TrackAsset track [get]
Constructor & Destructor Documentation
InfiniteTrackDrawer()
UnityEditor.Timeline.InfiniteTrackDrawer.InfiniteTrackDrawer (IPropertyKeyDataSource dataSource)
Member Function Documentation
CanDraw()
bool UnityEditor.Timeline.InfiniteTrackDrawer.CanDraw (TrackAsset track, WindowState state)
References UnityEditor.Timeline.WindowState.IsArmedForRecord(), and UnityEditor.Timeline.TrackDrawer.track.
Referenced by UnityEditor.Timeline.InfiniteTrackDrawer.DrawTrack().
DrawTrack()
override bool UnityEditor.Timeline.InfiniteTrackDrawer.DrawTrack (Rect trackRect, TrackAsset trackAsset, Vector2 visibleTime, WindowState state) virtual
Reimplemented from UnityEditor.Timeline.TrackDrawer.
References UnityEditor.Timeline.DirectorStyles.bottomShadow, UnityEditor.Timeline.InfiniteTrackDrawer.CanDraw(), UnityEditor.Timeline.DirectorStyles.infiniteTrack, UnityEditor.Timeline.DirectorStyles.Instance, UnityEditor.Timeline.WindowState.IsArmedForRecord(), and UnityEditor.Timeline.WindowState.recording.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/Drawers/InfiniteTrackDrawer.cs