VirtualTours: Unity.Cloud.Collaborate.Components.TabPageComponent Class Reference
Unity.Cloud.Collaborate.Components.TabPageComponent Class Reference abstract
Public Member Functions
void SetActive (bool active)
Set active status of this page.
Protected Member Functions
abstract void SetActive ()
Set this tab page active.
abstract void SetInactive ()
Set this tab page inactive.
Properties
bool Active [get]
Current active status for this page.
Member Function Documentation
SetActive() [1/2]
abstract void Unity.Cloud.Collaborate.Components.TabPageComponent.SetActive () protected pure virtual
Set this tab page active.
Referenced by Unity.Cloud.Collaborate.Components.TabPageComponent.SetActive().
SetActive() [2/2]
void Unity.Cloud.Collaborate.Components.TabPageComponent.SetActive (bool active)
Set active status of this page.
Parameters
active True if the page is to be active.
References Unity.Cloud.Collaborate.Components.TabPageComponent.Active, Unity.Cloud.Collaborate.Components.TabPageComponent.SetActive(), and Unity.Cloud.Collaborate.Components.TabPageComponent.SetInactive().
SetInactive()
abstract void Unity.Cloud.Collaborate.Components.TabPageComponent.SetInactive () protected pure virtual
Set this tab page inactive.
Referenced by Unity.Cloud.Collaborate.Components.TabPageComponent.SetActive().
Property Documentation
Active
bool Unity.Cloud.Collaborate.Components.TabPageComponent.Active get protected
Current active status for this page.
Referenced by Unity.Cloud.Collaborate.Components.TabPageComponent.SetActive().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.collab-proxy@1.3.9/Editor/Components/TabPageComponent.cs