VirtualTours: TMPro.MaterialReferenceManager Class Reference
TMPro.MaterialReferenceManager Class Reference
Public Member Functions
bool Contains (TMP_FontAsset font)
Add new material reference and return the index of this new reference in the materialReferences array.
bool Contains (TMP_SpriteAsset sprite)
Function to check if the sprite asset is already referenced.
Static Public Member Functions
static void AddFontAsset (TMP_FontAsset fontAsset)
Add new font asset reference to dictionary.
static void AddSpriteAsset (TMP_SpriteAsset spriteAsset)
Add new Sprite Asset to dictionary.
static void AddSpriteAsset (int hashCode, TMP_SpriteAsset spriteAsset)
Add new Sprite Asset to dictionary.
static void AddFontMaterial (int hashCode, Material material)
Add new Material reference to dictionary.
static void AddColorGradientPreset (int hashCode, TMP_ColorGradient spriteAsset)
Add new Color Gradient Preset to dictionary.
static bool TryGetFontAsset (int hashCode, out TMP_FontAsset fontAsset)
Function returning the Font Asset corresponding to the provided hash code.
static bool TryGetSpriteAsset (int hashCode, out TMP_SpriteAsset spriteAsset)
Function returning the Sprite Asset corresponding to the provided hash code.
static bool TryGetColorGradientPreset (int hashCode, out TMP_ColorGradient gradientPreset)
Function returning the Color Gradient Preset corresponding to the provided hash code.
static bool TryGetMaterial (int hashCode, out Material material)
Function returning the Font Material corresponding to the provided hash code.
Properties
static MaterialReferenceManager instance [get]
Get a singleton instance of the registry
Member Function Documentation
AddColorGradientPreset()
static void TMPro.MaterialReferenceManager.AddColorGradientPreset (int hashCode, TMP_ColorGradient spriteAsset) static
Add new Color Gradient Preset to dictionary.
Parameters
hashCode
spriteAsset
References TMPro.MaterialReferenceManager.instance.
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
AddFontAsset()
static void TMPro.MaterialReferenceManager.AddFontAsset (TMP_FontAsset fontAsset) static
Add new font asset reference to dictionary.
Parameters
fontAsset
References TMPro.MaterialReferenceManager.instance.
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
AddFontMaterial()
static void TMPro.MaterialReferenceManager.AddFontMaterial (int hashCode, Material material) static
Add new Material reference to dictionary.
Parameters
hashCode
material
References TMPro.MaterialReferenceManager.instance.
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
AddSpriteAsset() [1/2]
static void TMPro.MaterialReferenceManager.AddSpriteAsset (int hashCode, TMP_SpriteAsset spriteAsset) static
Add new Sprite Asset to dictionary.
Parameters
hashCode
spriteAsset
References TMPro.MaterialReferenceManager.instance.
AddSpriteAsset() [2/2]
static void TMPro.MaterialReferenceManager.AddSpriteAsset (TMP_SpriteAsset spriteAsset) static
Add new Sprite Asset to dictionary.
Parameters
hashCode
spriteAsset
References TMPro.MaterialReferenceManager.instance.
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
Contains() [1/2]
bool TMPro.MaterialReferenceManager.Contains (TMP_FontAsset font)
Add new material reference and return the index of this new reference in the materialReferences array.
Parameters
material
materialHashCode
fontAsset
Add new material reference and return the index of this new reference in the materialReferences array.
Parameters
material
materialHashCode
spriteAsset
Returns
Function to check if the font asset is already referenced.
Parameters
font
Returns
References TMPro.TMP_Asset.hashCode.
Contains() [2/2]
bool TMPro.MaterialReferenceManager.Contains (TMP_SpriteAsset sprite)
Function to check if the sprite asset is already referenced.
Parameters
font
Returns
References TMPro.TMP_Asset.hashCode.
TryGetColorGradientPreset()
static bool TMPro.MaterialReferenceManager.TryGetColorGradientPreset (int hashCode, out TMP_ColorGradient gradientPreset) static
Function returning the Color Gradient Preset corresponding to the provided hash code.
Parameters
hashCode
gradientPreset
Returns
References TMPro.MaterialReferenceManager.instance.
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
TryGetFontAsset()
static bool TMPro.MaterialReferenceManager.TryGetFontAsset (int hashCode, out TMP_FontAsset fontAsset) static
Function returning the Font Asset corresponding to the provided hash code.
Parameters
hashCode
fontAsset
Returns
References TMPro.MaterialReferenceManager.instance.
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
TryGetMaterial()
static bool TMPro.MaterialReferenceManager.TryGetMaterial (int hashCode, out Material material) static
Function returning the Font Material corresponding to the provided hash code.
Parameters
hashCode
material
Returns
References TMPro.MaterialReferenceManager.instance.
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
TryGetSpriteAsset()
static bool TMPro.MaterialReferenceManager.TryGetSpriteAsset (int hashCode, out TMP_SpriteAsset spriteAsset) static
Function returning the Sprite Asset corresponding to the provided hash code.
Parameters
hashCode
spriteAsset
Returns
References TMPro.MaterialReferenceManager.instance.
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
Property Documentation
instance
MaterialReferenceManager TMPro.MaterialReferenceManager.instance static get
Get a singleton instance of the registry
Referenced by TMPro.MaterialReferenceManager.AddColorGradientPreset(), TMPro.MaterialReferenceManager.AddFontAsset(), TMPro.MaterialReferenceManager.AddFontMaterial(), TMPro.MaterialReferenceManager.AddSpriteAsset(), TMPro.MaterialReferenceManager.TryGetColorGradientPreset(), TMPro.MaterialReferenceManager.TryGetFontAsset(), TMPro.MaterialReferenceManager.TryGetMaterial(), and TMPro.MaterialReferenceManager.TryGetSpriteAsset().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/MaterialReferenceManager.cs