VirtualTours: UnityEditor.Timeline.EditSubTimeline Class Reference
UnityEditor.Timeline.EditSubTimeline Class Reference
Public Member Functions
override bool Execute (WindowState state, TimelineClip[] clips)
Protected Member Functions
override MenuActionDisplayState GetDisplayState (WindowState state, TimelineClip[] clips)
override void AddMenuItem (WindowState state, TimelineClip[] items, List< MenuActionItem > menuItems)
Member Function Documentation
AddMenuItem()
override void UnityEditor.Timeline.EditSubTimeline.AddMenuItem (WindowState state, TimelineClip[] items, List< MenuActionItem > menuItems) protected
References UnityEditor.Timeline.ISequenceState.director, UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.EditSubTimeline.Execute(), UnityEditor.Timeline.EditSubTimeline.GetDisplayState(), UnityEditor.Timeline.TimelineWindow.instance, and UnityEditor.Timeline.TimelineMode.mode.
Execute()
override bool UnityEditor.Timeline.EditSubTimeline.Execute (WindowState state, TimelineClip[] clips)
References UnityEditor.Timeline.ISequenceState.director, and UnityEditor.Timeline.WindowState.editSequence.
Referenced by UnityEditor.Timeline.EditSubTimeline.AddMenuItem().
GetDisplayState()
override MenuActionDisplayState UnityEditor.Timeline.EditSubTimeline.GetDisplayState (WindowState state, TimelineClip[] clips) protected
Referenced by UnityEditor.Timeline.EditSubTimeline.AddMenuItem().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Actions/ClipsActions.cs