VirtualTours: UnityEditor.Timeline.TimelineMarkerHeaderGUI Class Reference
UnityEditor.Timeline.TimelineMarkerHeaderGUI Class Reference
Public Member Functions
TimelineMarkerHeaderGUI (TimelineAsset asset, WindowState state)
void Draw (Rect markerHeaderRect, Rect markerContentRect, WindowState state)
void Rebuild ()
Properties
TrackAsset asset [get]
Rect boundingRect [get]
bool locked [get]
bool showMarkers [get]
bool muted [get]
LayerZOrder zOrder [get]
Properties inherited from UnityEditor.Timeline.IRowGUI
TrackAsset asset [get]
Rect boundingRect [get]
bool locked [get]
bool showMarkers [get]
bool muted [get]
Properties inherited from UnityEditor.Timeline.ILayerable
LayerZOrder zOrder [get]
Constructor & Destructor Documentation
TimelineMarkerHeaderGUI()
UnityEditor.Timeline.TimelineMarkerHeaderGUI.TimelineMarkerHeaderGUI (TimelineAsset asset, WindowState state)
References UnityEditor.Timeline.TimelineMarkerHeaderGUI.asset.
Member Function Documentation
Draw()
void UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw (Rect markerHeaderRect, Rect markerContentRect, WindowState state)
References UnityEditor.Timeline.SpacePartitioner.AddBounds(), UnityEditor.Timeline.TimelineMarkerHeaderGUI.asset, UnityEditor.Timeline.TimelineMarkerHeaderGUI.boundingRect, UnityEngine.Timeline.DirectorNamedColor.colorTrackFont, UnityEditor.Timeline.DirectorStyles.customSkin, UnityEditor.Timeline.ItemsLayer.Draw(), UnityEditor.Timeline.DirectorStyles.Instance, UnityEditor.Timeline.TimelineMarkerHeaderGUI.locked, UnityEditor.Timeline.TimelineMarkerHeaderGUI.muted, UnityEditor.Timeline.TimelineMarkerHeaderGUI.Rebuild(), UnityEditor.Timeline.WindowState.showMarkerHeader, UnityEditor.Timeline.WindowState.spacePartitioner, UnityEditor.Timeline.WindowState.timeAreaRect, and UnityEditor.Timeline.DirectorStyles.trackHeaderFont.
Rebuild()
void UnityEditor.Timeline.TimelineMarkerHeaderGUI.Rebuild ()
References UnityEditor.Timeline.TimelineMarkerHeaderGUI.asset.
Referenced by UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw().
Property Documentation
asset
TrackAsset UnityEditor.Timeline.TimelineMarkerHeaderGUI.asset get
Referenced by UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw(), UnityEditor.Timeline.TimelineMarkerHeaderGUI.Rebuild(), and UnityEditor.Timeline.TimelineMarkerHeaderGUI.TimelineMarkerHeaderGUI().
boundingRect
Rect UnityEditor.Timeline.TimelineMarkerHeaderGUI.boundingRect get
Referenced by UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw().
locked
bool UnityEditor.Timeline.TimelineMarkerHeaderGUI.locked get
Referenced by UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw().
muted
bool UnityEditor.Timeline.TimelineMarkerHeaderGUI.muted get
Referenced by UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw().
showMarkers
bool UnityEditor.Timeline.TimelineMarkerHeaderGUI.showMarkers get
zOrder
LayerZOrder UnityEditor.Timeline.TimelineMarkerHeaderGUI.zOrder get
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Window/TimelineMarkerHeaderGUI.cs