VirtualTours: TimelinePreferencesProvider Class Reference
TimelinePreferencesProvider Class Reference
Public Member Functions
TimelinePreferencesProvider (string path, SettingsScope scopes, IEnumerable< string > keywords=null)
override void OnActivate (string searchContext, VisualElement rootElement)
override void OnGUI (string searchContext)
Static Public Member Functions
static SettingsProvider CreateTimelineProjectSettingProvider ()
Constructor & Destructor Documentation
TimelinePreferencesProvider()
TimelinePreferencesProvider.TimelinePreferencesProvider (string path, SettingsScope scopes, IEnumerable< string > keywords = null)
Referenced by CreateTimelineProjectSettingProvider().
Member Function Documentation
CreateTimelineProjectSettingProvider()
static SettingsProvider TimelinePreferencesProvider.CreateTimelineProjectSettingProvider () static
References TimelinePreferencesProvider().
OnActivate()
override void TimelinePreferencesProvider.OnActivate (string searchContext, VisualElement rootElement)
References TimelinePreferences.Save().
OnGUI()
override void TimelinePreferencesProvider.OnGUI (string searchContext)
References TimelinePreferences.audioScrubbing, and TimelinePreferences.Save().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/inspectors/TimelinePreferences.cs