VirtualTours: TMPro.TMP_SpriteAnimator Class Reference
TMPro.TMP_SpriteAnimator Class Reference
Public Member Functions
void StopAllAnimations ()
void DoSpriteAnimation (int currentCharacter, TMP_SpriteAsset spriteAsset, int start, int end, int framerate)
Member Function Documentation
DoSpriteAnimation()
void TMPro.TMP_SpriteAnimator.DoSpriteAnimation (int currentCharacter, TMP_SpriteAsset spriteAsset, int start, int end, int framerate)
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
StopAllAnimations()
void TMPro.TMP_SpriteAnimator.StopAllAnimations ()
Referenced by TMPro.TextMeshPro.GenerateTextMesh(), and TMPro.TextMeshProUGUI.GenerateTextMesh().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/TMP_SpriteAnimator.cs