VirtualTours: UnityEditor.Timeline.ItemsLayer Class Reference
UnityEditor.Timeline.ItemsLayer Class Reference
Public Member Functions
LayerZOrder Next ()
virtual void Draw (Rect rect, WindowState state)
Protected Member Functions
void AddItem (TimelineItemGUI item)
ItemsLayer (Layer layerOrder)
Properties
IEnumerable< TimelineItemGUI > items [get]
Constructor & Destructor Documentation
ItemsLayer()
UnityEditor.Timeline.ItemsLayer.ItemsLayer (Layer layerOrder) protected
Member Function Documentation
AddItem()
void UnityEditor.Timeline.ItemsLayer.AddItem (TimelineItemGUI item) protected
Referenced by UnityEditor.Timeline.ClipsLayer.ClipsLayer().
Draw()
virtual void UnityEditor.Timeline.ItemsLayer.Draw (Rect rect, WindowState state) virtual
Reimplemented in UnityEditor.Timeline.ClipsLayer.
References UnityEditor.Timeline.WindowState.PixelDeltaToDeltaTime(), and UnityEditor.Timeline.WindowState.timeAreaShownRange.
Referenced by UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw().
Next()
LayerZOrder UnityEditor.Timeline.ItemsLayer.Next ()
Implements UnityEditor.Timeline.IZOrderProvider.
Property Documentation
items
IEnumerable<TimelineItemGUI> UnityEditor.Timeline.ItemsLayer.items get
Referenced by UnityEditor.Timeline.ClipsLayer.Draw().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/Drawers/Layers/ItemsLayer.cs