VirtualTours: UnityEditor.Timeline.ItemAction< T > Class Template Reference
UnityEditor.Timeline.ItemAction< T > Class Template Reference abstract
Public Member Functions
abstract bool Execute (WindowState state, T[] items)
bool CanExecute (WindowState state, T[] items)
Static Public Member Functions
static bool HandleShortcut (WindowState state, Event evt, T item)
static void GetMenuEntries (T[] items, List< MenuActionItem > menuItems)
static bool Invoke< TAction > (WindowState state, T[] items)
static bool Invoke< TAction > (WindowState state, T item)
Static Public Member Functions inherited from UnityEditor.Timeline.MenuItemActionBase
static IEnumerable< Type > GetActionsOfType (Type actionType)
static ShortcutAttribute GetShortcutAttributeForAction (MenuItemActionBase action)
static void BuildMenu (GenericMenu menu, List< MenuActionItem > items)
static ActiveInModeAttribute GetActiveInModeAttribute (MenuItemActionBase action)
static bool IsActionActiveInMode (MenuItemActionBase action, TimelineModes mode)
Protected Member Functions
virtual MenuActionDisplayState GetDisplayState (WindowState state, T[] items)
virtual string GetDisplayName (T[] items)
virtual void AddMenuItem (WindowState state, T[] items, List< MenuActionItem > menuItem)
Additional Inherited Members
Static Protected Attributes inherited from UnityEditor.Timeline.MenuItemActionBase
static bool s_ShowActionTriggeredByShortcut = false
Properties inherited from UnityEditor.Timeline.MenuItemActionBase
Vector2? mousePosition [get, set]
int priority [get]
string category [get]
string menuName [get]
string? shortCut [get]
bool showInMenu [get]
Member Function Documentation
AddMenuItem()
virtual void UnityEditor.Timeline.ItemAction< T >.AddMenuItem (WindowState state, T[] items, List< MenuActionItem > menuItem) protected virtual
References UnityEditor.Timeline.MenuItemActionBase.category, UnityEditor.Timeline.ItemAction< T >.Execute(), UnityEditor.Timeline.ItemAction< T >.GetDisplayName(), UnityEditor.Timeline.ItemAction< T >.GetDisplayState(), UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.MenuItemActionBase.IsActionActiveInMode(), UnityEditor.Timeline.TimelineMode.mode, UnityEditor.Timeline.MenuItemActionBase.priority, and UnityEditor.Timeline.MenuItemActionBase.shortCut.
CanExecute()
bool UnityEditor.Timeline.ItemAction< T >.CanExecute (WindowState state, T[] items)
References UnityEditor.Timeline.ItemAction< T >.GetDisplayState().
Execute()
abstract bool UnityEditor.Timeline.ItemAction< T >.Execute (WindowState state, T[] items) pure virtual
Referenced by UnityEditor.Timeline.ItemAction< T >.AddMenuItem(), and UnityEditor.Timeline.ItemAction< T >.HandleShortcut().
GetDisplayName()
virtual string UnityEditor.Timeline.ItemAction< T >.GetDisplayName (T[] items) protected virtual
References UnityEditor.Timeline.MenuItemActionBase.menuName.
Referenced by UnityEditor.Timeline.ItemAction< T >.AddMenuItem().
GetDisplayState()
virtual MenuActionDisplayState UnityEditor.Timeline.ItemAction< T >.GetDisplayState (WindowState state, T[] items) protected virtual
Referenced by UnityEditor.Timeline.ItemAction< T >.AddMenuItem(), and UnityEditor.Timeline.ItemAction< T >.CanExecute().
GetMenuEntries()
static void UnityEditor.Timeline.ItemAction< T >.GetMenuEntries (T[] items, List< MenuActionItem > menuItems) static
References UnityEditor.Timeline.TimelineWindow.instance, and UnityEditor.Timeline.TimelineWindow.state.
HandleShortcut()
static bool UnityEditor.Timeline.ItemAction< T >.HandleShortcut (WindowState state, Event evt, T item) static
References UnityEditor.Timeline.ItemAction< T >.Execute(), UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.MenuItemActionBase.IsActionActiveInMode(), UnityEditor.Timeline.ShortcutAttribute.MatchesEvent(), UnityEditor.Timeline.TimelineMode.mode, and UnityEditor.Timeline.MenuItemActionBase.s_ShowActionTriggeredByShortcut.
Referenced by UnityEditor.Timeline.ItemActionShortcutManipulator.ExecuteCommand().
Invoke< TAction >() [1/2]
static bool UnityEditor.Timeline.ItemAction< T >.Invoke< TAction > (WindowState state, T item) static
Type Constraints
TAction : ItemAction<T>
References UnityEditor.Timeline.ItemAction< T >.Invoke< TAction >().
Invoke< TAction >() [2/2]
static bool UnityEditor.Timeline.ItemAction< T >.Invoke< TAction > (WindowState state, T[] items) static
Type Constraints
TAction : ItemAction<T>
Referenced by UnityEditor.Timeline.ItemAction< T >.Invoke< TAction >().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Actions/ItemAction.cs