VirtualTours: TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow Class Reference
TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow Class Reference
Public Member Functions
void OnEnable ()
void OnDisable ()
void OnGUI ()
void Update ()
TMP_FontFeatureTable GetKerningTable ()
Static Public Member Functions
static void ShowFontAtlasCreatorWindow ()
static void ShowFontAtlasCreatorWindow (Font sourceFontFile)
static void ShowFontAtlasCreatorWindow (TMP_FontAsset fontAsset)
Member Function Documentation
GetKerningTable()
TMP_FontFeatureTable TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow.GetKerningTable ()
References TMPro.TMP_FontFeatureTable.glyphPairAdjustmentRecords, and TMPro.TMP_FontFeatureTable.SortGlyphPairAdjustmentRecords().
OnDisable()
void TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow.OnDisable ()
OnEnable()
void TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow.OnEnable ()
OnGUI()
void TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow.OnGUI ()
ShowFontAtlasCreatorWindow() [1/3]
static void TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow.ShowFontAtlasCreatorWindow () static
Referenced by TMPro.EditorUtilities.TMP_FontAssetEditor.OnInspectorGUI().
ShowFontAtlasCreatorWindow() [2/3]
static void TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow.ShowFontAtlasCreatorWindow (Font sourceFontFile) static
ShowFontAtlasCreatorWindow() [3/3]
static void TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow.ShowFontAtlasCreatorWindow (TMP_FontAsset fontAsset) static
References TMPro.TMP_FontAsset.atlasTexture, TMPro.TMP_FontAsset.creationSettings, TMPro.TMP_FontAsset.GetCharactersArray(), and TMPro.FontAssetCreationSettings.sourceFontFileGUID.
Update()
void TMPro.EditorUtilities.TMPro_FontAssetCreatorWindow.Update ()
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Editor/TMPro_FontAssetCreatorWindow.cs