VirtualTours: UnityEditor.Timeline.Utilities.KeyTraverser Class Reference
UnityEditor.Timeline.Utilities.KeyTraverser Class Reference
Public Member Functions
KeyTraverser (TimelineAsset timeline, float epsilon)
float GetNextKey (float key, int dirtyStamp)
float GetPrevKey (float key, int dirtyStamp)
int GetKeyCount (int dirtyStamp)
Static Public Member Functions
static IEnumerable< float > GetClipKeyTimes (TimelineClip clip)
static IEnumerable< float > GetTrackKeyTimes (AnimationTrack track)
Properties
int lastIndex [get]
Constructor & Destructor Documentation
KeyTraverser()
UnityEditor.Timeline.Utilities.KeyTraverser.KeyTraverser (TimelineAsset timeline, float epsilon)
Member Function Documentation
GetClipKeyTimes()
static IEnumerable<float> UnityEditor.Timeline.Utilities.KeyTraverser.GetClipKeyTimes (TimelineClip clip) static
References UnityEngine.Timeline.TimelineClip.animationClip, UnityEngine.Timeline.TimelineClip.end, UnityEditor.Timeline.AnimationClipCurveCache.GetCurveInfo(), UnityEditor.Timeline.AnimationClipCurveCache.Instance, UnityEditor.Timeline.AnimationClipCurveInfo.keyTimes, and UnityEngine.Timeline.TimelineClip.start.
Referenced by UnityEditor.Timeline.Utilities.KeyTraverser.GetTrackKeyTimes().
GetKeyCount()
int UnityEditor.Timeline.Utilities.KeyTraverser.GetKeyCount (int dirtyStamp)
GetNextKey()
float UnityEditor.Timeline.Utilities.KeyTraverser.GetNextKey (float key, int dirtyStamp)
GetPrevKey()
float UnityEditor.Timeline.Utilities.KeyTraverser.GetPrevKey (float key, int dirtyStamp)
GetTrackKeyTimes()
static IEnumerable<float> UnityEditor.Timeline.Utilities.KeyTraverser.GetTrackKeyTimes (AnimationTrack track) static
References UnityEditor.Timeline.Utilities.KeyTraverser.GetClipKeyTimes(), UnityEditor.Timeline.AnimationClipCurveCache.GetCurveInfo(), UnityEngine.Timeline.AnimationTrack.inClipMode, UnityEngine.Timeline.AnimationTrack.infiniteClip, UnityEditor.Timeline.AnimationClipCurveCache.Instance, and UnityEditor.Timeline.AnimationClipCurveInfo.keyTimes.
Property Documentation
lastIndex
int UnityEditor.Timeline.Utilities.KeyTraverser.lastIndex get
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Utilities/KeyTraverser.cs