VirtualTours: UnityEditor.Timeline.TrimItemModeMix Class Reference
UnityEditor.Timeline.TrimItemModeMix Class Reference
Public Member Functions
void OnBeforeTrim (ITrimmable item, TrimEdge trimDirection)
void TrimStart (ITrimmable item, double time, bool affectTimeScale)
void TrimEnd (ITrimmable item, double time, bool affectTimeScale)
void DrawGUI (WindowState state, Rect bounds, Color color, TrimEdge edge)
Member Function Documentation
DrawGUI()
void UnityEditor.Timeline.TrimItemModeMix.DrawGUI (WindowState state, Rect bounds, Color color, TrimEdge edge)
Implements UnityEditor.Timeline.ITrimItemDrawer.
References UnityEditor.Timeline.TimelineCursors.ClearCursor(), and UnityEditor.Timeline.TimelineCursors.SetCursor().
OnBeforeTrim()
void UnityEditor.Timeline.TrimItemModeMix.OnBeforeTrim (ITrimmable item, TrimEdge trimDirection)
Implements UnityEditor.Timeline.ITrimItemMode.
References UnityEditor.Timeline.ITimelineItem.end, UnityEditor.Timeline.ITimelineItem.parentTrack, and UnityEditor.Timeline.ITimelineItem.start.
TrimEnd()
void UnityEditor.Timeline.TrimItemModeMix.TrimEnd (ITrimmable item, double time, bool affectTimeScale)
Implements UnityEditor.Timeline.ITrimItemMode.
References UnityEditor.Timeline.ITrimmable.SetEnd().
TrimStart()
void UnityEditor.Timeline.TrimItemModeMix.TrimStart (ITrimmable item, double time, bool affectTimeScale)
Implements UnityEditor.Timeline.ITrimItemMode.
References UnityEditor.Timeline.ITrimmable.SetStart().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Manipulators/Trim/TrimItemModeMix.cs