VirtualTours: UnityEngine.Timeline.IntervalTree< T > Class Template Reference
UnityEngine.Timeline.IntervalTree< T > Class Template Reference
Classes
struct Entry
Public Member Functions
void Add (T item)
Add an IInterval to the tree
void IntersectsWith (Int64 value, List< T > results)
Query the tree at a particular time
void IntersectsWithRange (Int64 start, Int64 end, List< T > results)
Query the tree at a particular range of time
void UpdateIntervals ()
Updates the intervals from their source. Use this to detect if the data in the tree has changed.
void Clear ()
Properties
bool dirty [get, set]
Whether the tree will be rebuilt on the next query
Member Function Documentation
Add()
void UnityEngine.Timeline.IntervalTree< T >.Add (T item)
Add an IInterval to the tree
References UnityEngine.Timeline.IntervalTree< T >.dirty.
Referenced by UnityEditor.Timeline.SpacePartitioner.AddBounds().
Clear()
void UnityEngine.Timeline.IntervalTree< T >.Clear ()
Referenced by UnityEditor.Timeline.SpacePartitioner.Clear().
IntersectsWith()
void UnityEngine.Timeline.IntervalTree< T >.IntersectsWith (Int64 value, List< T > results)
Query the tree at a particular time
Parameters
value
results
References UnityEngine.Timeline.IntervalTree< T >.dirty.
IntersectsWithRange()
void UnityEngine.Timeline.IntervalTree< T >.IntersectsWithRange (Int64 start, Int64 end, List< T > results)
Query the tree at a particular range of time
Parameters
start
end
results
References UnityEngine.Timeline.IntervalTree< T >.dirty.
Referenced by UnityEditor.Timeline.SpacePartitioner.DebugDraw(), and UnityEditor.Timeline.SpacePartitioner.GetItemsInArea< T >().
UpdateIntervals()
void UnityEngine.Timeline.IntervalTree< T >.UpdateIntervals ()
Updates the intervals from their source. Use this to detect if the data in the tree has changed.
References UnityEngine.Timeline.IntervalTree< T >.dirty.
Property Documentation
dirty
bool UnityEngine.Timeline.IntervalTree< T >.dirty get set
Whether the tree will be rebuilt on the next query
Referenced by UnityEngine.Timeline.IntervalTree< T >.Add(), UnityEngine.Timeline.IntervalTree< T >.IntersectsWith(), UnityEngine.Timeline.IntervalTree< T >.IntersectsWithRange(), and UnityEngine.Timeline.IntervalTree< T >.UpdateIntervals().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Runtime/Evaluation/IntervalTree.cs