VirtualTours: TMPro.TMP_SubMesh Class Reference
TMPro.TMP_SubMesh Class Reference
Public Member Functions
void DestroySelf ()
float GetPaddingForMaterial ()
Function called when the padding value for the material needs to be re-calculated.
void UpdateMeshPadding (bool isExtraPadding, bool isUsingBold)
Function to update the padding values of the object.
void SetVerticesDirty ()
void SetMaterialDirty ()
Static Public Member Functions
static TMP_SubMesh AddSubTextObject (TextMeshPro textComponent, MaterialReference materialReference)
Protected Member Functions
void UpdateMaterial ()
Properties
TMP_FontAsset fontAsset [get, set]
The TMP Font Asset assigned to this sub text object.
TMP_SpriteAsset spriteAsset [get, set]
The TMP Sprite Asset assigned to this sub text object.
Material material [get, set]
The material to be assigned to this object. Returns an instance of the material.
Material sharedMaterial [get, set]
The material to be assigned to this text object.
Material fallbackMaterial [get, set]
The fallback material created from the properties of the fallback source material.
Material fallbackSourceMaterial [get, set]
The source material used by the fallback font
bool isDefaultMaterial [get, set]
Is the text object using the default font asset material.
float padding [get, set]
Padding value resulting for the property settings on the material.
new Renderer renderer [get]
The Mesh Renderer of this text sub object.
MeshFilter meshFilter [get]
The MeshFilter of this text sub object.
Mesh mesh [get, set]
The Mesh of this text sub object.
TMP_Text textComponent [get]
Member Function Documentation
AddSubTextObject()
static TMP_SubMesh TMPro.TMP_SubMesh.AddSubTextObject (TextMeshPro textComponent, MaterialReference materialReference) static
References TMPro.MaterialReference.fontAsset, TMPro.MaterialReference.isDefaultMaterial, TMPro.MaterialReference.material, TMPro.TMP_SubMesh.renderer, TMPro.MaterialReference.spriteAsset, TMPro.TMP_SubMesh.textComponent, and TMPro.TMP_Text.transform.
Referenced by TMPro.TextMeshPro.SetArraySizes().
DestroySelf()
void TMPro.TMP_SubMesh.DestroySelf ()
GetPaddingForMaterial()
float TMPro.TMP_SubMesh.GetPaddingForMaterial ()
Function called when the padding value for the material needs to be re-calculated.
Returns
References TMPro.TMP_Text.extraPadding, TMPro.TMP_Text.isUsingBold, and TMPro.TMP_SubMesh.padding.
SetMaterialDirty()
void TMPro.TMP_SubMesh.SetMaterialDirty ()
References TMPro.TMP_SubMesh.UpdateMaterial().
SetVerticesDirty()
void TMPro.TMP_SubMesh.SetVerticesDirty ()
References TMPro.TMP_Text.havePropertiesChanged, and TMPro.TextMeshPro.SetVerticesDirty().
UpdateMaterial()
void TMPro.TMP_SubMesh.UpdateMaterial () protected
References TMPro.TMP_Text.fontSharedMaterial, TMPro.TMP_SubMesh.renderer, and TMPro.TMP_SubMesh.textComponent.
Referenced by TMPro.TMP_SubMesh.SetMaterialDirty().
UpdateMeshPadding()
void TMPro.TMP_SubMesh.UpdateMeshPadding (bool isExtraPadding, bool isUsingBold)
Function to update the padding values of the object.
Parameters
isExtraPadding
isBold
Property Documentation
fallbackMaterial
Material TMPro.TMP_SubMesh.fallbackMaterial get set
The fallback material created from the properties of the fallback source material.
fallbackSourceMaterial
Material TMPro.TMP_SubMesh.fallbackSourceMaterial get set
The source material used by the fallback font
fontAsset
TMP_FontAsset TMPro.TMP_SubMesh.fontAsset get set
The TMP Font Asset assigned to this sub text object.
isDefaultMaterial
bool TMPro.TMP_SubMesh.isDefaultMaterial get set
Is the text object using the default font asset material.
material
Material TMPro.TMP_SubMesh.material get set
The material to be assigned to this object. Returns an instance of the material.
mesh
Mesh TMPro.TMP_SubMesh.mesh get set
The Mesh of this text sub object.
Referenced by TMPro.TextMeshPro.UpdateVertexData().
meshFilter
MeshFilter TMPro.TMP_SubMesh.meshFilter get
The MeshFilter of this text sub object.
padding
float TMPro.TMP_SubMesh.padding get set
Padding value resulting for the property settings on the material.
Referenced by TMPro.TMP_SubMesh.GetPaddingForMaterial().
renderer
new Renderer TMPro.TMP_SubMesh.renderer get
The Mesh Renderer of this text sub object.
Referenced by TMPro.TMP_SubMesh.AddSubTextObject(), TMPro.EditorUtilities.TMP_SubMesh_Editor.OnEnable(), and TMPro.TMP_SubMesh.UpdateMaterial().
sharedMaterial
Material TMPro.TMP_SubMesh.sharedMaterial get set
The material to be assigned to this text object.
spriteAsset
TMP_SpriteAsset TMPro.TMP_SubMesh.spriteAsset get set
The TMP Sprite Asset assigned to this sub text object.
textComponent
TMP_Text TMPro.TMP_SubMesh.textComponent get
Reference to the parent Text Component.
Referenced by TMPro.TMP_SubMesh.AddSubTextObject(), and TMPro.TMP_SubMesh.UpdateMaterial().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/TMP_SubMesh.cs