VirtualTours: UnityEditor.Timeline.TimelineAction Class Reference
UnityEditor.Timeline.TimelineAction Class Reference abstract
Public Member Functions
abstract bool Execute (WindowState state)
virtual MenuActionDisplayState GetDisplayState (WindowState state)
virtual bool IsChecked (WindowState state)
Static Public Member Functions
static void Invoke< T > (WindowState state)
static void GetMenuEntries (IEnumerable< TimelineAction > actions, Vector2? mousePos, List< MenuActionItem > items)
static bool HandleShortcut (WindowState state, Event evt)
Static Public Member Functions inherited from UnityEditor.Timeline.MenuItemActionBase
static IEnumerable< Type > GetActionsOfType (Type actionType)
static ShortcutAttribute GetShortcutAttributeForAction (MenuItemActionBase action)
static void BuildMenu (GenericMenu menu, List< MenuActionItem > items)
static ActiveInModeAttribute GetActiveInModeAttribute (MenuItemActionBase action)
static bool IsActionActiveInMode (MenuItemActionBase action, TimelineModes mode)
Static Public Attributes
static readonly TimelineAction[] AllActions = GetActionsOfType(typeof(TimelineAction)).Select(x => (TimelineAction)x.GetConstructors()[0].Invoke(null)).ToArray()
static readonly TimelineAction[] MenuActions = AllActions.Where(a => a.showInMenu && !(a is MarkerHeaderAction)).ToArray()
Protected Member Functions
string GetDisplayName (WindowState state)
Static Protected Member Functions
static bool DoInternal (Type t, WindowState state)
Additional Inherited Members
Static Protected Attributes inherited from UnityEditor.Timeline.MenuItemActionBase
static bool s_ShowActionTriggeredByShortcut = false
Properties inherited from UnityEditor.Timeline.MenuItemActionBase
Vector2? mousePosition [get, set]
int priority [get]
string category [get]
string menuName [get]
string? shortCut [get]
bool showInMenu [get]
Member Function Documentation
DoInternal()
static bool UnityEditor.Timeline.TimelineAction.DoInternal (Type t, WindowState state) static protected
Referenced by UnityEditor.Timeline.CopyAction.Do(), and UnityEditor.Timeline.PasteAction.Do().
Execute()
abstract bool UnityEditor.Timeline.TimelineAction.Execute (WindowState state) pure virtual
Implemented in UnityEditor.Timeline.ToggleShowMarkersOnTimeline, UnityEditor.Timeline.ToggleMuteMarkersOnTimeline, UnityEditor.Timeline.ToggleClipTrackArea, UnityEditor.Timeline.MultiselectDownTrack, UnityEditor.Timeline.MultiselectUpTrack, UnityEditor.Timeline.MultiselectRightClip, UnityEditor.Timeline.MultiselectLeftClip, UnityEditor.Timeline.SelectDownTrack, UnityEditor.Timeline.SelectDownClip, UnityEditor.Timeline.SelectUpTrack, UnityEditor.Timeline.SelectUpClip, UnityEditor.Timeline.SelectRightClip, UnityEditor.Timeline.SelectLeftClip, UnityEditor.Timeline.UnCollapseGroup, UnityEditor.Timeline.CollapseGroup, UnityEditor.Timeline.ZoomOut, UnityEditor.Timeline.ZoomIn, UnityEditor.Timeline.GotoEndAction, UnityEditor.Timeline.GotoStartAction, UnityEditor.Timeline.NextKeyAction, UnityEditor.Timeline.PrevKeyAction, UnityEditor.Timeline.FrameSelectedAction, UnityEditor.Timeline.FrameAllAction, UnityEditor.Timeline.NextFrameAction, UnityEditor.Timeline.PreviousFrameAction, UnityEditor.Timeline.SelectAllAction, UnityEditor.Timeline.PlayTimelineAction, UnityEditor.Timeline.MatchContent, UnityEditor.Timeline.DeleteAction, UnityEditor.Timeline.DuplicateAction, UnityEditor.Timeline.PasteAction, and UnityEditor.Timeline.CopyAction.
Referenced by UnityEditor.Timeline.TimelineAction.Invoke< T >().
GetDisplayName()
string UnityEditor.Timeline.TimelineAction.GetDisplayName (WindowState state) protected
References UnityEditor.Timeline.MenuItemActionBase.menuName.
GetDisplayState()
virtual MenuActionDisplayState UnityEditor.Timeline.TimelineAction.GetDisplayState (WindowState state) virtual
Reimplemented in UnityEditor.Timeline.MatchContent, UnityEditor.Timeline.DeleteAction, UnityEditor.Timeline.PasteAction, and UnityEditor.Timeline.CopyAction.
GetMenuEntries()
static void UnityEditor.Timeline.TimelineAction.GetMenuEntries (IEnumerable< TimelineAction > actions, Vector2? mousePos, List< MenuActionItem > items) static
References UnityEditor.Timeline.MenuItemActionBase.category, UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.MenuItemActionBase.IsActionActiveInMode(), UnityEditor.Timeline.TimelineMode.mode, UnityEditor.Timeline.MenuItemActionBase.priority, UnityEditor.Timeline.MenuItemActionBase.shortCut, and UnityEditor.Timeline.TimelineWindow.state.
HandleShortcut()
static bool UnityEditor.Timeline.TimelineAction.HandleShortcut (WindowState state, Event evt) static
References UnityEditor.Timeline.TimelineAction.AllActions, UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.MenuItemActionBase.IsActionActiveInMode(), UnityEditor.Timeline.ShortcutAttribute.MatchesEvent(), UnityEditor.Timeline.TimelineMode.mode, and UnityEditor.Timeline.MenuItemActionBase.s_ShowActionTriggeredByShortcut.
Referenced by UnityEditor.Timeline.TimelineShortcutManipulator.ExecuteCommand().
Invoke< T >()
static void UnityEditor.Timeline.TimelineAction.Invoke< T > (WindowState state) static
Type Constraints
T : TimelineAction
References UnityEditor.Timeline.TimelineAction.AllActions, and UnityEditor.Timeline.TimelineAction.Execute().
IsChecked()
virtual bool UnityEditor.Timeline.TimelineAction.IsChecked (WindowState state) virtual
Reimplemented in UnityEditor.Timeline.ToggleShowMarkersOnTimeline, and UnityEditor.Timeline.ToggleMuteMarkersOnTimeline.
Member Data Documentation
AllActions
readonly TimelineAction [] UnityEditor.Timeline.TimelineAction.AllActions = GetActionsOfType(typeof(TimelineAction)).Select(x => (TimelineAction)x.GetConstructors()[0].Invoke(null)).ToArray() static
Referenced by UnityEditor.Timeline.TimelineAction.HandleShortcut(), and UnityEditor.Timeline.TimelineAction.Invoke< T >().
MenuActions
readonly TimelineAction [] UnityEditor.Timeline.TimelineAction.MenuActions = AllActions.Where(a => a.showInMenu && !(a is MarkerHeaderAction)).ToArray() static
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Actions/TimelineActions.cs