VirtualTours: UnityEditorInternal.BindingTreeViewDataSource Class Reference
UnityEditorInternal.BindingTreeViewDataSource Class Reference
Public Member Functions
BindingTreeViewDataSource (TreeViewController treeView, AnimationClip clip, CurveDataSource curveDataSource)
override void FetchData ()
void UpdateData ()
Static Public Member Functions
static string GroupName (EditorCurveBinding binding)
Static Public Attributes
const int RootID = int.MinValue
const int GroupID = -1
Constructor & Destructor Documentation
BindingTreeViewDataSource()
UnityEditorInternal.BindingTreeViewDataSource.BindingTreeViewDataSource (TreeViewController treeView, AnimationClip clip, CurveDataSource curveDataSource)
Member Function Documentation
FetchData()
override void UnityEditorInternal.BindingTreeViewDataSource.FetchData ()
References UnityEditorInternal.BindingTreeViewDataSource.GroupID, UnityEditor.Timeline.CurveDataSource.groupingName, UnityEditorInternal.BindingTreeViewDataSource.GroupName(), and UnityEditorInternal.BindingTreeViewDataSource.RootID.
GroupName()
static string UnityEditorInternal.BindingTreeViewDataSource.GroupName (EditorCurveBinding binding) static
Referenced by UnityEditorInternal.BindingTreeViewDataSource.FetchData().
UpdateData()
void UnityEditorInternal.BindingTreeViewDataSource.UpdateData ()
Referenced by UnityEditor.BindingSelector.InitIfNeeded(), and UnityEditor.BindingSelector.RefreshTree().
Member Data Documentation
GroupID
const int UnityEditorInternal.BindingTreeViewDataSource.GroupID = -1 static
Referenced by UnityEditorInternal.BindingTreeViewDataSource.FetchData(), and UnityEditorInternal.BindingTreeViewGUI.OnRowGUI().
RootID
const int UnityEditorInternal.BindingTreeViewDataSource.RootID = int.MinValue static
Referenced by UnityEditorInternal.BindingTreeViewDataSource.FetchData(), and UnityEditorInternal.BindingTreeViewGUI.OnRowGUI().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Animation/BindingTreeViewDataSource.cs