VirtualTours: UnityEditor.Timeline.SelectAndMoveItem Class Reference
UnityEditor.Timeline.SelectAndMoveItem Class Reference
Public Member Functions
override void Overlay (Event evt, WindowState state)
Public Member Functions inherited from UnityEditor.Timeline.Manipulator
bool HandleEvent (WindowState state)
Protected Member Functions
override bool MouseDown (Event evt, WindowState state)
override bool MouseUp (Event evt, WindowState state)
override bool DoubleClick (Event evt, WindowState state)
override bool MouseDrag (Event evt, WindowState state)
Protected Member Functions inherited from UnityEditor.Timeline.Manipulator
virtual bool MouseWheel (Event evt, WindowState state)
virtual bool KeyDown (Event evt, WindowState state)
virtual bool KeyUp (Event evt, WindowState state)
virtual bool ContextClick (Event evt, WindowState state)
virtual bool ValidateCommand (Event evt, WindowState state)
virtual bool ExecuteCommand (Event evt, WindowState state)
Member Function Documentation
DoubleClick()
override bool UnityEditor.Timeline.SelectAndMoveItem.DoubleClick (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.SelectAndMoveItem.MouseDown(), and UnityEditor.Timeline.SelectAndMoveItem.MouseUp().
MouseDown()
override bool UnityEditor.Timeline.SelectAndMoveItem.MouseDown (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
Referenced by UnityEditor.Timeline.SelectAndMoveItem.DoubleClick().
MouseDrag()
override bool UnityEditor.Timeline.SelectAndMoveItem.MouseDrag (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.WindowState.AddCaptured(), UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.WindowState.Evaluate(), UnityEditor.Timeline.MoveItemHandler.Grab(), UnityEditor.Timeline.ISequenceState.isReadOnly, UnityEditor.Timeline.MoveItemHandler.OnTrackDetach(), UnityEditor.Timeline.SnapEngine.Snap(), and UnityEditor.Timeline.MoveItemHandler.UpdateTrackTarget().
MouseUp()
override bool UnityEditor.Timeline.SelectAndMoveItem.MouseUp (Event evt, WindowState state) protected virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.TimelineCursors.ClearCursor(), UnityEditor.Timeline.TimelineMarkerClusterGUI.CycleMarkers(), UnityEditor.Timeline.WindowState.Evaluate(), UnityEditor.Timeline.WindowState.RemoveCaptured(), and UnityEditor.Timeline.ISelectable.Select().
Referenced by UnityEditor.Timeline.SelectAndMoveItem.DoubleClick().
Overlay()
override void UnityEditor.Timeline.SelectAndMoveItem.Overlay (Event evt, WindowState state) virtual
Reimplemented from UnityEditor.Timeline.Manipulator.
References UnityEditor.Timeline.MoveItemHandler.allowTrackSwitch, UnityEditor.Timeline.MoveItemHandler.end, UnityEditor.Timeline.SnapEngine.OnGUI(), UnityEditor.Timeline.MoveItemHandler.OnGUI(), UnityEditor.Timeline.TimeAreaAutoPanner.OnGUI(), UnityEditor.Timeline.MoveItemHandler.start, and UnityEditor.Timeline.MoveItemHandler.targetTrack.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Manipulators/Sequence/SelectAndMoveItem.cs