VirtualTours: TMPro.TMP_SpriteAsset Class Reference
TMPro.TMP_SpriteAsset Class Reference
Public Member Functions
void UpdateLookupTables ()
Function to update the sprite name and unicode lookup tables. This function should be called when a sprite's name or unicode value changes or when a new sprite is added.
int GetSpriteIndexFromHashcode (int hashCode)
Function which returns the sprite index using the hashcode of the name
int GetSpriteIndexFromUnicode (uint unicode)
Returns the index of the sprite for the given unicode value.
int GetSpriteIndexFromName (string name)
Returns the index of the sprite for the given name.
void SortGlyphTable ()
Sort the sprite glyph table by glyph index.
Static Public Member Functions
static TMP_SpriteAsset SearchForSpriteByUnicode (TMP_SpriteAsset spriteAsset, uint unicode, bool includeFallbacks, out int spriteIndex)
Search through the given sprite asset and its fallbacks for the specified sprite matching the given unicode character.
static TMP_SpriteAsset SearchForSpriteByHashCode (TMP_SpriteAsset spriteAsset, int hashCode, bool includeFallbacks, out int spriteIndex)
Search the given sprite asset and fallbacks for a sprite whose hash code value of its name matches the target hash code.
Public Attributes
Texture spriteSheet
List< TMP_Sprite > spriteInfoList
List< TMP_SpriteAsset > fallbackSpriteAssets
List which contains the Fallback font assets for this font.
Public Attributes inherited from TMPro.TMP_Asset
int hashCode
HashCode based on the name of the asset.
Material material
The material used by this asset.
int materialHashCode
HashCode based on the name of the material assigned to this asset.
Properties
string version [get, set]
The version of the sprite asset class. Version 1.1.0 updates the asset data structure to be compatible with new font asset structure.
FaceInfo faceInfo [get, set]
Information about the sprite asset's face.
List< TMP_SpriteCharacter > spriteCharacterTable [get, set]
Dictionary< uint, TMP_SpriteCharacter > spriteCharacterLookupTable [get, set]
Dictionary used to lookup sprite characters by their unicode value.
List< TMP_SpriteGlyph > spriteGlyphTable [get, set]
Properties inherited from TMPro.TMP_Asset
int instanceID [get]
Instance ID of the TMP Asset
Member Function Documentation
GetSpriteIndexFromHashcode()
int TMPro.TMP_SpriteAsset.GetSpriteIndexFromHashcode (int hashCode)
Function which returns the sprite index using the hashcode of the name
Parameters
hashCode
Returns
References TMPro.TMP_Asset.hashCode, and TMPro.TMP_SpriteAsset.UpdateLookupTables().
Referenced by TMPro.TMP_SpriteAsset.GetSpriteIndexFromName(), and TMPro.TMP_SpriteAsset.SearchForSpriteByHashCode().
GetSpriteIndexFromName()
int TMPro.TMP_SpriteAsset.GetSpriteIndexFromName (string name)
Returns the index of the sprite for the given name.
Parameters
name
Returns
References TMPro.TMP_SpriteAsset.GetSpriteIndexFromHashcode(), TMPro.TMP_Asset.hashCode, and TMPro.TMP_SpriteAsset.UpdateLookupTables().
GetSpriteIndexFromUnicode()
int TMPro.TMP_SpriteAsset.GetSpriteIndexFromUnicode (uint unicode)
Returns the index of the sprite for the given unicode value.
Parameters
unicode
Returns
References TMPro.TMP_TextElement.glyphIndex, and TMPro.TMP_SpriteAsset.UpdateLookupTables().
Referenced by TMPro.TMP_SpriteAsset.SearchForSpriteByHashCode(), and TMPro.TMP_SpriteAsset.SearchForSpriteByUnicode().
SearchForSpriteByHashCode()
static TMP_SpriteAsset TMPro.TMP_SpriteAsset.SearchForSpriteByHashCode (TMP_SpriteAsset spriteAsset, int hashCode, bool includeFallbacks, out int spriteIndex) static
Search the given sprite asset and fallbacks for a sprite whose hash code value of its name matches the target hash code.
Parameters
spriteAsset The Sprite Asset to search for the given sprite whose name matches the hashcode value
hashCode The hash code value matching the name of the sprite
includeFallbacks Include fallback sprite assets in the search
spriteIndex The index of the sprite matching the provided hash code
Returns
The Sprite Asset that contains the sprite
References TMPro.TMP_Settings.defaultSpriteAsset, TMPro.TMP_SpriteAsset.fallbackSpriteAssets, TMPro.TMP_SpriteAsset.GetSpriteIndexFromHashcode(), TMPro.TMP_SpriteAsset.GetSpriteIndexFromUnicode(), TMPro.TMP_Asset.hashCode, TMPro.TMP_Asset.instanceID, and TMPro.TMP_Settings.missingCharacterSpriteUnicode.
Referenced by TMPro.TMP_Text.ValidateHtmlTag().
SearchForSpriteByUnicode()
static TMP_SpriteAsset TMPro.TMP_SpriteAsset.SearchForSpriteByUnicode (TMP_SpriteAsset spriteAsset, uint unicode, bool includeFallbacks, out int spriteIndex) static
Search through the given sprite asset and its fallbacks for the specified sprite matching the given unicode character.
Parameters
spriteAsset The font asset to search for the given character.
unicode The character to find.
glyph out parameter containing the glyph for the specified character (if found).
Returns
References TMPro.TMP_Settings.defaultSpriteAsset, TMPro.TMP_SpriteAsset.fallbackSpriteAssets, and TMPro.TMP_SpriteAsset.GetSpriteIndexFromUnicode().
SortGlyphTable()
void TMPro.TMP_SpriteAsset.SortGlyphTable ()
Sort the sprite glyph table by glyph index.
UpdateLookupTables()
void TMPro.TMP_SpriteAsset.UpdateLookupTables ()
Function to update the sprite name and unicode lookup tables. This function should be called when a sprite's name or unicode value changes or when a new sprite is added.
References TMPro.TMP_TextElement.glyph, TMPro.TMP_TextElement.glyphIndex, TMPro.TMP_Asset.hashCode, TMPro.TMP_Asset.material, and TMPro.TMP_TextElement.textAsset.
Referenced by TMPro.TMP_SpriteAsset.GetSpriteIndexFromHashcode(), TMPro.TMP_SpriteAsset.GetSpriteIndexFromName(), TMPro.TMP_SpriteAsset.GetSpriteIndexFromUnicode(), and TMPro.EditorUtilities.TMP_SpriteAssetEditor.OnInspectorGUI().
Member Data Documentation
fallbackSpriteAssets
List<TMP_SpriteAsset> TMPro.TMP_SpriteAsset.fallbackSpriteAssets
List which contains the Fallback font assets for this font.
Referenced by TMPro.TMP_FontAssetUtilities.GetSpriteCharacterFromSpriteAsset(), TMPro.TMP_SpriteAsset.SearchForSpriteByHashCode(), and TMPro.TMP_SpriteAsset.SearchForSpriteByUnicode().
spriteInfoList
List<TMP_Sprite> TMPro.TMP_SpriteAsset.spriteInfoList
spriteSheet
Texture TMPro.TMP_SpriteAsset.spriteSheet
Referenced by TMPro.TMP_Text.SaveSpriteVertexInfo().
Property Documentation
faceInfo
FaceInfo TMPro.TMP_SpriteAsset.faceInfo get set
Information about the sprite asset's face.
Referenced by TMPro.TMP_Text.CalculatePreferredValues().
spriteCharacterLookupTable
Dictionary<uint, TMP_SpriteCharacter> TMPro.TMP_SpriteAsset.spriteCharacterLookupTable get set
Dictionary used to lookup sprite characters by their unicode value.
Referenced by TMPro.TMP_FontAssetUtilities.GetSpriteCharacterFromSpriteAsset().
spriteCharacterTable
List<TMP_SpriteCharacter> TMPro.TMP_SpriteAsset.spriteCharacterTable get set
Referenced by TMPro.TMP_Text.CalculatePreferredValues(), TMPro.TextMeshPro.GenerateTextMesh(), TMPro.TextMeshProUGUI.GenerateTextMesh(), TMPro.TextMeshPro.SetArraySizes(), TMPro.TextMeshProUGUI.SetArraySizes(), and TMPro.TMP_Text.ValidateHtmlTag().
spriteGlyphTable
List<TMP_SpriteGlyph> TMPro.TMP_SpriteAsset.spriteGlyphTable get set
Referenced by TMPro.EditorUtilities.TMP_SpriteCharacterPropertyDrawer.OnGUI().
version
string TMPro.TMP_SpriteAsset.version get set
The version of the sprite asset class. Version 1.1.0 updates the asset data structure to be compatible with new font asset structure.
Referenced by TMPro.EditorUtilities.TMP_SpriteAssetEditor.OnInspectorGUI().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/TMP_SpriteAsset.cs