VirtualTours: UnityEditor.Timeline.TrimItemModeReplace Class Reference
UnityEditor.Timeline.TrimItemModeReplace Class Reference
Public Member Functions
void OnBeforeTrim (ITrimmable item, TrimEdge trimDirection)
void TrimStart (ITrimmable item, double time, bool affectTimeScale)
void TrimEnd (ITrimmable item, double time, bool affectTimeScale)
void DrawGUI (WindowState state, Rect bounds, Color color, TrimEdge edge)
Member Function Documentation
DrawGUI()
void UnityEditor.Timeline.TrimItemModeReplace.DrawGUI (WindowState state, Rect bounds, Color color, TrimEdge edge)
Implements UnityEditor.Timeline.ITrimItemDrawer.
References UnityEditor.Timeline.TimelineCursors.ClearCursor(), UnityEditor.Timeline.ITimelineItem.end, UnityEditor.Timeline.DirectorStyles.kMixToolColor, UnityEditor.Timeline.TimelineCursors.SetCursor(), and UnityEditor.Timeline.ITimelineItem.start.
OnBeforeTrim()
void UnityEditor.Timeline.TrimItemModeReplace.OnBeforeTrim (ITrimmable item, TrimEdge trimDirection)
Implements UnityEditor.Timeline.ITrimItemMode.
References UnityEditor.Timeline.ITimelineItem.end, UnityEditor.Timeline.ITimelineItem.parentTrack, and UnityEditor.Timeline.ITimelineItem.start.
TrimEnd()
void UnityEditor.Timeline.TrimItemModeReplace.TrimEnd (ITrimmable item, double time, bool affectTimeScale)
Implements UnityEditor.Timeline.ITrimItemMode.
References UnityEditor.Timeline.ITimelineItem.end, UnityEditor.Timeline.ITrimmable.SetEnd(), UnityEditor.Timeline.ITrimmable.SetStart(), and UnityEditor.Timeline.ITimelineItem.start.
TrimStart()
void UnityEditor.Timeline.TrimItemModeReplace.TrimStart (ITrimmable item, double time, bool affectTimeScale)
Implements UnityEditor.Timeline.ITrimItemMode.
References UnityEditor.Timeline.ITimelineItem.end, UnityEditor.Timeline.ITrimmable.SetEnd(), UnityEditor.Timeline.ITrimmable.SetStart(), and UnityEditor.Timeline.ITimelineItem.start.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Manipulators/Trim/TrimItemModeReplace.cs