VirtualTours: TMPro.TMP_Dropdown Class Reference
TMPro.TMP_Dropdown Class Reference
A standard dropdown that presents a list of options when clicked, of which one can be chosen.
Classes
class DropdownEvent
UnityEvent callback for when a dropdown current option is changed.
class DropdownItem
class OptionData
Class to store the text and/or image of a single option in the dropdown list.
class OptionDataList
Class used internally to store the list of options for the dropdown list.
Public Member Functions
void SetValueWithoutNotify (int input)
Set index number of the current selection in the Dropdown without invoking onValueChanged callback.
void RefreshShownValue ()
Refreshes the text and image (if available) of the currently selected option.
void AddOptions (List< OptionData > options)
Add multiple options to the options of the Dropdown based on a list of OptionData objects.
void AddOptions (List< string > options)
Add multiple text-only options to the options of the Dropdown based on a list of strings.
void AddOptions (List< Sprite > options)
Add multiple image-only options to the options of the Dropdown based on a list of Sprites.
void ClearOptions ()
Clear the list of options in the Dropdown.
virtual void OnPointerClick (PointerEventData eventData)
Handling for when the dropdown is initially 'clicked'. Typically shows the dropdown
virtual void OnSubmit (BaseEventData eventData)
Handling for when the dropdown is selected and a submit event is processed. Typically shows the dropdown
virtual void OnCancel (BaseEventData eventData)
This will hide the dropdown list.
void Show ()
Show the dropdown.
void Hide ()
Hide the dropdown list. I.e. close it.
Protected Member Functions
TMP_Dropdown ()
override void Awake ()
override void Start ()
override void OnDisable ()
virtual GameObject CreateBlocker (Canvas rootCanvas)
Create a blocker that blocks clicks to other controls while the dropdown list is open.
virtual void DestroyBlocker (GameObject blocker)
Convenience method to explicitly destroy the previously generated blocker object
virtual GameObject CreateDropdownList (GameObject template)
Create the dropdown list to be shown when the dropdown is clicked. The dropdown list should correspond to the provided template GameObject, equivalent to instantiating a copy of it.
virtual void DestroyDropdownList (GameObject dropdownList)
Convenience method to explicitly destroy the previously generated dropdown list
virtual DropdownItem CreateItem (DropdownItem itemTemplate)
Create a dropdown item based upon the item template.
virtual void DestroyItem (DropdownItem item)
Convenience method to explicitly destroy the previously generated Items.
Properties
RectTransform template [get, set]
The Rect Transform of the template for the dropdown list.
TMP_Text captionText [get, set]
The Text component to hold the text of the currently selected option.
Image captionImage [get, set]
The Image component to hold the image of the currently selected option.
Graphic placeholder [get, set]
The placeholder Graphic component. Shown when no option is selected.
TMP_Text itemText [get, set]
The Text component to hold the text of the item.
Image itemImage [get, set]
The Image component to hold the image of the item
List< OptionData > options [get, set]
The list of possible options. A text string and an image can be specified for each option.
DropdownEvent onValueChanged [get, set]
A UnityEvent that is invoked when a user has clicked one of the options in the dropdown list.
float alphaFadeSpeed [get, set]
The time interval at which a drop down will appear and disappear
int value [get, set]
The Value is the index number of the current selection in the Dropdown. 0 is the first option in the Dropdown, 1 is the second, and so on.
bool IsExpanded [get]
Detailed Description
A standard dropdown that presents a list of options when clicked, of which one can be chosen.
The dropdown component is a Selectable. When an option is chosen, the label and/or image of the control changes to show the chosen option.
When a dropdown event occurs a callback is sent to any registered listeners of onValueChanged.
Constructor & Destructor Documentation
TMP_Dropdown()
TMPro.TMP_Dropdown.TMP_Dropdown () protected
Member Function Documentation
AddOptions() [1/3]
void TMPro.TMP_Dropdown.AddOptions (List< OptionData > options)
Add multiple options to the options of the Dropdown based on a list of OptionData objects.
Parameters
options The list of OptionData to add.
///
See AddOptions(List<string> options) for code example of usages.
References TMPro.TMP_Dropdown.options, and TMPro.TMP_Dropdown.RefreshShownValue().
AddOptions() [2/3]
void TMPro.TMP_Dropdown.AddOptions (List< Sprite > options)
Add multiple image-only options to the options of the Dropdown based on a list of Sprites.
Parameters
options The list of Sprites to add.
See AddOptions(List<string> options) for code example of usages.
References TMPro.TMP_Dropdown.options, and TMPro.TMP_Dropdown.RefreshShownValue().
AddOptions() [3/3]
void TMPro.TMP_Dropdown.AddOptions (List< string > options)
Add multiple text-only options to the options of the Dropdown based on a list of strings.
Add a List of string messages to the Dropdown. The Dropdown shows each member of the list as a separate option.
Parameters
options The list of text strings to add.
//Create a new Dropdown GameObject by going to the Hierarchy and clicking Create>UI>Dropdown - TextMeshPro. Attach this script to the Dropdown GameObject.
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
public class Example : MonoBehaviour
{
    //Create a List of new Dropdown options
    List<string> m_DropOptions = new List<string> { "Option 1", "Option 2"};
    //This is the Dropdown
    TMP_Dropdown m_Dropdown;
    void Start()
    {
        //Fetch the Dropdown GameObject the script is attached to
        m_Dropdown = GetComponent<TMP_Dropdown>();
        //Clear the old options of the Dropdown menu
        m_Dropdown.ClearOptions();
        //Add the options created in the List above
        m_Dropdown.AddOptions(m_DropOptions);
    }
}
References TMPro.TMP_Dropdown.options, and TMPro.TMP_Dropdown.RefreshShownValue().
Awake()
override void TMPro.TMP_Dropdown.Awake () protected
ClearOptions()
void TMPro.TMP_Dropdown.ClearOptions ()
Clear the list of options in the Dropdown.
References TMPro.TMP_Dropdown.options, and TMPro.TMP_Dropdown.RefreshShownValue().
CreateBlocker()
virtual GameObject TMPro.TMP_Dropdown.CreateBlocker (Canvas rootCanvas) protected virtual
Create a blocker that blocks clicks to other controls while the dropdown list is open.
Override this method to implement a different way to obtain a blocker GameObject.
Parameters
rootCanvas The root canvas the dropdown is under.
Returns
The created blocker object
References TMPro.TMP_Dropdown.Hide().
Referenced by TMPro.TMP_Dropdown.Show().
CreateDropdownList()
virtual GameObject TMPro.TMP_Dropdown.CreateDropdownList (GameObject template) protected virtual
Create the dropdown list to be shown when the dropdown is clicked. The dropdown list should correspond to the provided template GameObject, equivalent to instantiating a copy of it.
Override this method to implement a different way to obtain a dropdown list GameObject.
Parameters
template The template to create the dropdown list from.
Returns
The created drop down list gameobject.
Referenced by TMPro.TMP_Dropdown.Show().
CreateItem()
virtual DropdownItem TMPro.TMP_Dropdown.CreateItem (DropdownItem itemTemplate) protected virtual
Create a dropdown item based upon the item template.
Override this method to implement a different way to obtain an option item. The option item should correspond to the provided template DropdownItem and its GameObject, equivalent to instantiating a copy of it.
Parameters
itemTemplate e template to create the option item from.
Returns
The created dropdown item component
DestroyBlocker()
virtual void TMPro.TMP_Dropdown.DestroyBlocker (GameObject blocker) protected virtual
Convenience method to explicitly destroy the previously generated blocker object
Override this method to implement a different way to dispose of a blocker GameObject that blocks clicks to other controls while the dropdown list is open.
Parameters
blocker The blocker object to destroy.
Referenced by TMPro.TMP_Dropdown.Hide(), and TMPro.TMP_Dropdown.OnDisable().
DestroyDropdownList()
virtual void TMPro.TMP_Dropdown.DestroyDropdownList (GameObject dropdownList) protected virtual
Convenience method to explicitly destroy the previously generated dropdown list
Override this method to implement a different way to dispose of a dropdown list GameObject.
Parameters
dropdownList The dropdown list GameObject to destroy
DestroyItem()
virtual void TMPro.TMP_Dropdown.DestroyItem (DropdownItem item) protected virtual
Convenience method to explicitly destroy the previously generated Items.
Override this method to implement a different way to dispose of an option item. Likely no action needed since destroying the dropdown list destroys all contained items as well.
Parameters
item The Item to destroy.
Hide()
void TMPro.TMP_Dropdown.Hide ()
Hide the dropdown list. I.e. close it.
References TMPro.TMP_Dropdown.DestroyBlocker().
Referenced by TMPro.TMP_Dropdown.CreateBlocker(), and TMPro.TMP_Dropdown.OnCancel().
OnCancel()
virtual void TMPro.TMP_Dropdown.OnCancel (BaseEventData eventData) virtual
This will hide the dropdown list.
Called by a BaseInputModule when a Cancel event occurs.
Parameters
eventData The associated event data.
References TMPro.TMP_Dropdown.Hide().
OnDisable()
override void TMPro.TMP_Dropdown.OnDisable () protected
References TMPro.TMP_Dropdown.DestroyBlocker().
OnPointerClick()
virtual void TMPro.TMP_Dropdown.OnPointerClick (PointerEventData eventData) virtual
Handling for when the dropdown is initially 'clicked'. Typically shows the dropdown
Parameters
eventData The associated event data.
References TMPro.TMP_Dropdown.Show().
OnSubmit()
virtual void TMPro.TMP_Dropdown.OnSubmit (BaseEventData eventData) virtual
Handling for when the dropdown is selected and a submit event is processed. Typically shows the dropdown
Parameters
eventData The associated event data.
References TMPro.TMP_Dropdown.Show().
RefreshShownValue()
void TMPro.TMP_Dropdown.RefreshShownValue ()
Refreshes the text and image (if available) of the currently selected option.
If you have modified the list of options, you should call this method afterwards to ensure that the visual state of the dropdown corresponds to the updated options.
References TMPro.TMP_Dropdown.OptionData.image, TMPro.TMP_Dropdown.options, TMPro.TMP_Dropdown.OptionData.text, and TMPro.TMP_Text.text.
Referenced by TMPro.TMP_Dropdown.AddOptions(), TMPro.TMP_Dropdown.ClearOptions(), and TMPro.TMP_Dropdown.Start().
SetValueWithoutNotify()
void TMPro.TMP_Dropdown.SetValueWithoutNotify (int input)
Set index number of the current selection in the Dropdown without invoking onValueChanged callback.
Parameters
input The new index for the current selection.
Show()
void TMPro.TMP_Dropdown.Show ()
Show the dropdown.
Plan for dropdown scrolling to ensure dropdown is contained within screen.
We assume the Canvas is the screen that the dropdown must be kept inside. This is always valid for screen space canvas modes. For world space canvases we don't know how it's used, but it could be e.g. for an in-game monitor. We consider it a fair constraint that the canvas must be big enough to contain dropdowns.
References TMPro.TMP_Dropdown.CreateBlocker(), TMPro.TMP_Dropdown.CreateDropdownList(), TMPro.TMP_Dropdown.options, and TMPro.TMP_Dropdown.value.
Referenced by TMPro.TMP_Dropdown.OnPointerClick(), and TMPro.TMP_Dropdown.OnSubmit().
Start()
override void TMPro.TMP_Dropdown.Start () protected
References TMPro.TMP_Dropdown.RefreshShownValue().
Property Documentation
alphaFadeSpeed
float TMPro.TMP_Dropdown.alphaFadeSpeed get set
The time interval at which a drop down will appear and disappear
captionImage
Image TMPro.TMP_Dropdown.captionImage get set
The Image component to hold the image of the currently selected option.
captionText
TMP_Text TMPro.TMP_Dropdown.captionText get set
The Text component to hold the text of the currently selected option.
IsExpanded
bool TMPro.TMP_Dropdown.IsExpanded get
itemImage
Image TMPro.TMP_Dropdown.itemImage get set
The Image component to hold the image of the item
itemText
TMP_Text TMPro.TMP_Dropdown.itemText get set
The Text component to hold the text of the item.
onValueChanged
DropdownEvent TMPro.TMP_Dropdown.onValueChanged get set
A UnityEvent that is invoked when a user has clicked one of the options in the dropdown list.
Use this to detect when a user selects one or more options in the Dropdown. Add a listener to perform an action when this UnityEvent detects a selection by the user. See https://unity3d.com/learn/tutorials/topics/scripting/delegates for more information on delegates.
//Create a new Dropdown GameObject by going to the Hierarchy and clicking Create>UI>Dropdown - TextMeshPro. Attach this script to the Dropdown GameObject.
//Set your own Text in the Inspector window
using UnityEngine;
using UnityEngine.UI;
using TMPro;
public class Example : MonoBehaviour
{
    TMP_Dropdown m_Dropdown;
    public Text m_Text;
    void Start()
    {
        //Fetch the Dropdown GameObject
        m_Dropdown = GetComponent<TMP_Dropdown>();
        //Add listener for when the value of the Dropdown changes, to take action
        m_Dropdown.onValueChanged.AddListener(delegate {
                DropdownValueChanged(m_Dropdown);
            });
        //Initialize the Text to say the first value of the Dropdown
        m_Text.text = "First Value : " + m_Dropdown.value;
    }
    //Output the new value of the Dropdown into Text
    void DropdownValueChanged(TMP_Dropdown change)
    {
        m_Text.text =  "New Value : " + change.value;
    }
}
options
List<OptionData> TMPro.TMP_Dropdown.options get set
The list of possible options. A text string and an image can be specified for each option.
This is the list of options within the Dropdown. Each option contains Text and/or image data that you can specify using UI.Dropdown.OptionData before adding to the Dropdown list. This also unlocks the ability to edit the Dropdown, including the insertion, removal, and finding of options, as well as other useful tools
///
//Create a new Dropdown GameObject by going to the Hierarchy and clicking Create>UI>Dropdown - TextMeshPro. Attach this script to the Dropdown GameObject.
using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;
using TMPro;
public class Example : MonoBehaviour
{
    //Use these for adding options to the Dropdown List
    TMP_Dropdown.OptionData m_NewData, m_NewData2;
    //The list of messages for the Dropdown
    List<TMP_Dropdown.OptionData> m_Messages = new List<TMP_Dropdown.OptionData>();
@verbatim
//This is the Dropdown
TMP_Dropdown m_Dropdown;
string m_MyString;
int m_Index;
void Start()
{
    //Fetch the Dropdown GameObject the script is attached to
    m_Dropdown = GetComponent<TMP_Dropdown>();
    //Clear the old options of the Dropdown menu
    m_Dropdown.ClearOptions();
    //Create a new option for the Dropdown menu which reads "Option 1" and add to messages List
    m_NewData = new TMP_Dropdown.OptionData();
    m_NewData.text = "Option 1";
    m_Messages.Add(m_NewData);
    //Create a new option for the Dropdown menu which reads "Option 2" and add to messages List
    m_NewData2 = new TMP_Dropdown.OptionData();
    m_NewData2.text = "Option 2";
    m_Messages.Add(m_NewData2);
    //Take each entry in the message List
    foreach (TMP_Dropdown.OptionData message in m_Messages)
    {
        //Add each entry to the Dropdown
        m_Dropdown.options.Add(message);
        //Make the index equal to the total number of entries
        m_Index = m_Messages.Count - 1;
    }
}
//This OnGUI function is used here for a quick demonstration. See the [[wiki:UISystem|UI Section]] for more information about setting up your own UI.
void OnGUI()
{
    //TextField for user to type new entry to add to Dropdown
    m_MyString = GUI.TextField(new Rect(0, 40, 100, 40), m_MyString);
    //Press the "Add" Button to add a new entry to the Dropdown
    if (GUI.Button(new Rect(0, 0, 100, 40), "Add"))
    {
        //Make the index the last number of entries
        m_Index = m_Messages.Count;
        //Create a temporary option
        TMP_Dropdown.OptionData temp = new TMP_Dropdown.OptionData();
        //Make the option the data from the TextField
        temp.text = m_MyString;
        //Update the messages list with the TextField data
        m_Messages.Add(temp);
        //Add the Textfield data to the Dropdown
        m_Dropdown.options.Insert(m_Index, temp);
    }
    //Press the "Remove" button to delete the selected option
    if (GUI.Button(new Rect(110, 0, 100, 40), "Remove"))
    {
        //Remove the current selected item from the Dropdown from the messages List
        m_Messages.RemoveAt(m_Dropdown.value);
        //Remove the current selection from the Dropdown
        m_Dropdown.options.RemoveAt(m_Dropdown.value);
    }
}
@endverbatim }
Referenced by TMPro.TMP_Dropdown.AddOptions(), TMPro.TMP_Dropdown.ClearOptions(), TMPro.TMP_Dropdown.RefreshShownValue(), and TMPro.TMP_Dropdown.Show().
placeholder
Graphic TMPro.TMP_Dropdown.placeholder get set
The placeholder Graphic component. Shown when no option is selected.
template
RectTransform TMPro.TMP_Dropdown.template get set
The Rect Transform of the template for the dropdown list.
value
int TMPro.TMP_Dropdown.value get set
The Value is the index number of the current selection in the Dropdown. 0 is the first option in the Dropdown, 1 is the second, and so on.
//Create a new Dropdown GameObject by going to the Hierarchy and clicking Create>UI>Dropdown - TextMeshPro. Attach this script to the Dropdown GameObject.
//Set your own Text in the Inspector window
using UnityEngine;
using UnityEngine.UI;
using TMPro;
public class Example : MonoBehaviour
{
    //Attach this script to a Dropdown GameObject
    TMP_Dropdown m_Dropdown;
    //This is the string that stores the current selection m_Text of the Dropdown
    string m_Message;
    //This Text outputs the current selection to the screen
    public Text m_Text;
    //This is the index value of the Dropdown
    int m_DropdownValue;
    void Start()
    {
        //Fetch the DropDown component from the GameObject
        m_Dropdown = GetComponent<TMP_Dropdown>();
        //Output the first Dropdown index value
        Debug.Log("Starting Dropdown Value : " + m_Dropdown.value);
    }
    void Update()
    {
        //Keep the current index of the Dropdown in a variable
        m_DropdownValue = m_Dropdown.value;
        //Change the message to say the name of the current Dropdown selection using the value
        m_Message = m_Dropdown.options[m_DropdownValue].text;
        //Change the on screen Text to reflect the current Dropdown selection
        m_Text.text = m_Message;
    }
}
Referenced by TMPro.TMP_Dropdown.Show().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/TMP_Dropdown.cs