VirtualTours: UnityEditor.Timeline.Manipulator Class Reference
UnityEditor.Timeline.Manipulator Class Reference
Public Member Functions
virtual void Overlay (Event evt, WindowState state)
bool HandleEvent (WindowState state)
Protected Member Functions
virtual bool MouseDown (Event evt, WindowState state)
virtual bool MouseDrag (Event evt, WindowState state)
virtual bool MouseWheel (Event evt, WindowState state)
virtual bool MouseUp (Event evt, WindowState state)
virtual bool DoubleClick (Event evt, WindowState state)
virtual bool KeyDown (Event evt, WindowState state)
virtual bool KeyUp (Event evt, WindowState state)
virtual bool ContextClick (Event evt, WindowState state)
virtual bool ValidateCommand (Event evt, WindowState state)
virtual bool ExecuteCommand (Event evt, WindowState state)
Member Function Documentation
ContextClick()
virtual bool UnityEditor.Timeline.Manipulator.ContextClick (Event evt, WindowState state) protected virtual
Reimplemented in UnityEditor.Timeline.ContextMenuManipulator, UnityEditor.Timeline.TimeAreaContextMenu, UnityEditor.Timeline.PlayheadContextMenu, and UnityEditor.Timeline.TimelineMarkerHeaderContextMenu.
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
DoubleClick()
virtual bool UnityEditor.Timeline.Manipulator.DoubleClick (Event evt, WindowState state) protected virtual
Reimplemented in UnityEditor.Timeline.TrackDoubleClick, UnityEditor.Timeline.DrillIntoClip, and UnityEditor.Timeline.SelectAndMoveItem.
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
ExecuteCommand()
virtual bool UnityEditor.Timeline.Manipulator.ExecuteCommand (Event evt, WindowState state) protected virtual
Reimplemented in UnityEditor.Timeline.TrackShortcutManipulator, UnityEditor.Timeline.InlineCurvesShortcutManipulator, UnityEditor.Timeline.TimelineShortcutManipulator, and UnityEditor.Timeline.ItemActionShortcutManipulator.
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
HandleEvent()
bool UnityEditor.Timeline.Manipulator.HandleEvent (WindowState state)
References UnityEditor.Timeline.Manipulator.ContextClick(), UnityEditor.Timeline.Manipulator.DoubleClick(), UnityEditor.Timeline.Manipulator.ExecuteCommand(), UnityEditor.Timeline.Manipulator.KeyDown(), UnityEditor.Timeline.Manipulator.KeyUp(), UnityEditor.Timeline.Manipulator.MouseDown(), UnityEditor.Timeline.Manipulator.MouseDrag(), UnityEditor.Timeline.Manipulator.MouseUp(), UnityEditor.Timeline.Manipulator.MouseWheel(), and UnityEditor.Timeline.Manipulator.ValidateCommand().
KeyDown()
virtual bool UnityEditor.Timeline.Manipulator.KeyDown (Event evt, WindowState state) protected virtual
Reimplemented in UnityEditor.Timeline.InlineCurvesShortcutManipulator.
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
KeyUp()
virtual bool UnityEditor.Timeline.Manipulator.KeyUp (Event evt, WindowState state) protected virtual
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
MouseDown()
virtual bool UnityEditor.Timeline.Manipulator.MouseDown (Event evt, WindowState state) protected virtual
Reimplemented in UnityEditor.Timeline.TrackResize, UnityEditor.Timeline.InlineCurveResize, UnityEditor.Timeline.TimelineZoomManipulator, UnityEditor.Timeline.TimelinePanManipulator, UnityEditor.Timeline.ContextMenuManipulator, UnityEditor.Timeline.Scrub, UnityEditor.Timeline.TrimClip, UnityEditor.Timeline.SelectAndMoveItem, UnityEditor.Timeline.ClearSelection, UnityEditor.Timeline.Jog, and UnityEditor.Timeline.EaseClip.
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
MouseDrag()
virtual bool UnityEditor.Timeline.Manipulator.MouseDrag (Event evt, WindowState state) protected virtual
Reimplemented in UnityEditor.Timeline.TrackResize, UnityEditor.Timeline.InlineCurveResize, UnityEditor.Timeline.TimelineZoomManipulator, UnityEditor.Timeline.TimelinePanManipulator, UnityEditor.Timeline.Scrub, UnityEditor.Timeline.TrimClip, UnityEditor.Timeline.SelectAndMoveItem, UnityEditor.Timeline.Jog, and UnityEditor.Timeline.EaseClip.
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
MouseUp()
virtual bool UnityEditor.Timeline.Manipulator.MouseUp (Event evt, WindowState state) protected virtual
Reimplemented in UnityEditor.Timeline.TrackResize, UnityEditor.Timeline.InlineCurveResize, UnityEditor.Timeline.TimelinePanManipulator, UnityEditor.Timeline.Scrub, UnityEditor.Timeline.TrimClip, UnityEditor.Timeline.SelectAndMoveItem, UnityEditor.Timeline.Jog, and UnityEditor.Timeline.EaseClip.
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
MouseWheel()
virtual bool UnityEditor.Timeline.Manipulator.MouseWheel (Event evt, WindowState state) protected virtual
Reimplemented in UnityEditor.Timeline.TimelineZoomManipulator, UnityEditor.Timeline.TimelinePanManipulator, and UnityEditor.Timeline.TrackZoom.
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
Overlay()
virtual void UnityEditor.Timeline.Manipulator.Overlay (Event evt, WindowState state) virtual
Reimplemented in UnityEditor.Timeline.TrackResize, UnityEditor.Timeline.InlineCurveResize, UnityEditor.Timeline.TrimClip, UnityEditor.Timeline.SelectAndMoveItem, and UnityEditor.Timeline.EaseClip.
ValidateCommand()
virtual bool UnityEditor.Timeline.Manipulator.ValidateCommand (Event evt, WindowState state) protected virtual
Reimplemented in UnityEditor.Timeline.TimelineShortcutManipulator.
Referenced by UnityEditor.Timeline.Manipulator.HandleEvent().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/Manipulator.cs