VirtualTours: UnityEditor.BindingSelector Class Reference
UnityEditor.BindingSelector Class Reference
Public Member Functions
BindingSelector (EditorWindow window, CurveEditor curveEditor, TreeViewState trackGlobalTreeViewState)
virtual void Delete (WindowState state)
void OnGUI (Rect targetRect)
void InitIfNeeded (Rect rect, CurveDataSource dataSource, bool isNewSelection)
void RefreshCurves ()
void RefreshTree ()
Properties
TreeViewController treeViewController [get]
bool selectable [get]
object selectableObject [get]
bool selected [get, set]
Constructor & Destructor Documentation
BindingSelector()
UnityEditor.BindingSelector.BindingSelector (EditorWindow window, CurveEditor curveEditor, TreeViewState trackGlobalTreeViewState)
Member Function Documentation
Delete()
virtual void UnityEditor.BindingSelector.Delete (WindowState state) virtual
References UnityEditor.Timeline.CurveDataSource.animationClip, and UnityEditor.Timeline.WindowState.rebuildGraph.
InitIfNeeded()
void UnityEditor.BindingSelector.InitIfNeeded (Rect rect, CurveDataSource dataSource, bool isNewSelection)
References UnityEditor.Timeline.CurveDataSource.animationClip, and UnityEditorInternal.BindingTreeViewDataSource.UpdateData().
OnGUI()
void UnityEditor.BindingSelector.OnGUI (Rect targetRect)
RefreshCurves()
void UnityEditor.BindingSelector.RefreshCurves ()
References UnityEditor.Timeline.CurveDataSource.GenerateWrappers().
RefreshTree()
void UnityEditor.BindingSelector.RefreshTree ()
References UnityEditor.BindingSelector.selected, and UnityEditorInternal.BindingTreeViewDataSource.UpdateData().
Property Documentation
selectable
bool UnityEditor.BindingSelector.selectable get
selectableObject
object UnityEditor.BindingSelector.selectableObject get
selected
bool UnityEditor.BindingSelector.selected get set
Referenced by UnityEditor.BindingSelector.RefreshTree().
treeViewController
TreeViewController UnityEditor.BindingSelector.treeViewController get
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Animation/BindingSelector.cs