VirtualTours: UnityEditor.Timeline.WindowState Class Reference
UnityEditor.Timeline.WindowState Class Reference
Public Member Functions
WindowState (TimelineWindow w, SequenceHierarchy hierarchy)
void AddCaptured (Manipulator manipulator)
void RemoveCaptured (Manipulator manipulator)
void OnDestroy ()
void OnSceneSaved ()
void SetCurrentSequence (TimelineAsset timelineAsset, PlayableDirector director, TimelineClip hostClip)
void PopSequencesUntilCount (int count)
SequencePath GetCurrentSequencePath ()
void SetCurrentSequencePath (SequencePath path, bool forceRebuild)
IEnumerable< ISequenceState > GetAllSequences ()
double SnapToFrameIfRequired (double currentTime)
void Reset ()
double GetSnappedTimeAtMousePosition (Vector2 mousePos)
void SetTimeAreaTransform (Vector2 newTranslation, Vector2 newScale)
void SetTimeAreaShownRange (float min, float max)
void ResetPreviewMode ()
bool TimeIsInRange (float value)
bool RangeIsVisible (Range range)
void EnsurePlayHeadIsVisible ()
void SetPlayHeadToMiddle ()
TimelineWindow GetWindow ()
void Play ()
void Pause ()
void SetPlaying (bool start)
void Stop ()
void RebuildPlayableGraph ()
void Evaluate ()
void EvaluateImmediate ()
void Refresh ()
void UpdateViewStateHash ()
bool IsEditingASubItem ()
bool IsEditingASubTimeline ()
bool IsEditingAnEmptyTimeline ()
bool IsEditingAPrefabAsset ()
bool IsCurrentEditingASequencerTextField ()
float TimeToTimeAreaPixel (double t)
float TimeToScreenSpacePixel (double time)
float TimeToPixel (double time)
float PixelToTime (float pixel)
float PixelDeltaToDeltaTime (float p)
float TimeAreaPixelToTime (float pixel)
float ScreenSpacePixelToTimeAreaTime (float p)
float TrackSpacePixelToTimeAreaTime (float p)
void OffsetTimeArea (int pixels)
GameObject GetSceneReference (TrackAsset asset)
void CalculateRowRects ()
void ArmForRecord (TrackAsset track)
void UnarmForRecord (TrackAsset track)
void UpdateRecordingState ()
bool IsTrackRecordable (TrackAsset track)
bool IsArmedForRecord (TrackAsset track)
TrackAsset GetArmedTrack (TrackAsset track)
void GatherProperties (PlayableDirector director)
void AddStartFrameDelegate (PendingUpdateDelegate updateDelegate)
void AddEndFrameDelegate (PendingUpdateDelegate updateDelegate)
void UpdateRootPlayableDuration (double duration)
void InvokeTimeChangeCallback ()
Static Public Attributes
static readonly float kMaxShownTime = (float)TimeUtility.k_MaxTimelineDurationInSeconds
Properties
static double kTimeEpsilon [get]
static AnimationModeDriver previewDriver [get]
EditorWindow editorWindow [get]
ISequenceState?? editSequence [get]
ISequenceState?? masterSequence [get]
ISequenceState? referenceSequence [get]
bool rebuildGraph [get, set]
float mouseDragLag [get, set]
SpacePartitioner spacePartitioner [get]
SpacePartitioner headerSpacePartitioner [get]
List< Manipulator > captured [get]
bool isJogging [get, set]
int viewStateHash [get]
float bindingAreaWidth [get, set]
float sequencerHeaderWidth [get, set]
float mainAreaWidth [get, set]
float trackScale [get, set]
int dirtyStamp [get]
bool showQuadTree [get, set]
bool canRecord [get]
bool recording [get, set]
bool previewMode [get, set]
bool playing [get]
float playbackSpeed [get, set]
bool frameSnap [get, set]
bool edgeSnaps [get, set]
bool muteAudioScrubbing [get, set]
bool playRangeLoopMode [get, set]
TimeReferenceMode timeReferenceMode [get, set]
bool timeInFrames [get, set]
bool showAudioWaveform [get, set]
Vector2 playRange [get, set]
bool showMarkerHeader [get, set]
EditMode.EditType editType [get, set]
PlaybackScrollMode autoScrollMode [get, set]
bool isClipSnapping [get, set]
List< PlayableDirector > previewedDirectors [get]
Vector2 timeAreaShownRange [get]
Vector2 timeAreaTranslation [get]
Vector2 timeAreaScale [get]
Rect timeAreaRect [get]
float windowHeight [get]
bool playRangeEnabled [get, set]
Events
Action< WindowState, Event > windowOnGuiStarted
Action< WindowState, Event > windowOnGuiFinished
Action< bool > OnPlayStateChange
Action OnDirtyStampChange
Action OnRebuildGraphChange
Action OnTimeChange
Action OnRecordingChange
Action OnBeforeSequenceChange
Action OnAfterSequenceChange
Constructor & Destructor Documentation
WindowState()
UnityEditor.Timeline.WindowState.WindowState (TimelineWindow w, SequenceHierarchy hierarchy)
References UnityEditor.Timeline.SequenceHierarchy.Init(), UnityEditor.Timeline.WindowState.muteAudioScrubbing, and UnityEditor.Timeline.TimelineWindow.preferences.
Member Function Documentation
AddCaptured()
void UnityEditor.Timeline.WindowState.AddCaptured (Manipulator manipulator)
Referenced by UnityEditor.Timeline.TrimClip.MouseDown(), UnityEditor.Timeline.Scrub.MouseDown(), UnityEditor.Timeline.InlineCurveResize.MouseDown(), UnityEditor.Timeline.TrackResize.MouseDown(), UnityEditor.Timeline.EaseClip.MouseDownInternal(), and UnityEditor.Timeline.SelectAndMoveItem.MouseDrag().
AddEndFrameDelegate()
void UnityEditor.Timeline.WindowState.AddEndFrameDelegate (PendingUpdateDelegate updateDelegate)
AddStartFrameDelegate()
void UnityEditor.Timeline.WindowState.AddStartFrameDelegate (PendingUpdateDelegate updateDelegate)
ArmForRecord()
void UnityEditor.Timeline.WindowState.ArmForRecord (TrackAsset track)
References UnityEditor.Timeline.WindowState.CalculateRowRects(), UnityEditor.Timeline.ISequenceState.director, UnityEditor.Timeline.WindowState.editSequence, and UnityEditor.Timeline.WindowState.recording.
Referenced by UnityEditor.Timeline.TimelineWindowTimeControl.StartRecording().
CalculateRowRects()
void UnityEditor.Timeline.WindowState.CalculateRowRects ()
Referenced by UnityEditor.Timeline.WindowState.ArmForRecord(), and UnityEditor.Timeline.AnimationTrackRecorder.FinializeTrack().
EnsurePlayHeadIsVisible()
void UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible ()
References UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.WindowState.PixelToTime(), UnityEditor.Timeline.WindowState.SetTimeAreaShownRange(), UnityEditor.Timeline.ISequenceState.time, and UnityEditor.Timeline.WindowState.timeAreaRect.
Referenced by UnityEditor.Timeline.GotoStartAction.Execute(), and UnityEditor.Timeline.GotoEndAction.Execute().
Evaluate()
void UnityEditor.Timeline.WindowState.Evaluate ()
References UnityEditor.Timeline.ISequenceState.director, UnityEditor.Timeline.WindowState.GatherProperties(), UnityEditor.Timeline.WindowState.masterSequence, and UnityEditor.Timeline.WindowState.previewMode.
Referenced by UnityEditor.Timeline.FrameSelectedAction.FrameRange(), UnityEditor.Timeline.SelectAndMoveItem.MouseDrag(), UnityEditor.Timeline.SelectAndMoveItem.MouseUp(), UnityEditor.Timeline.AnimationPlayableAssetInspector.OnInspectorGUI(), and UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
EvaluateImmediate()
void UnityEditor.Timeline.WindowState.EvaluateImmediate ()
References UnityEditor.Timeline.ISequenceState.director, UnityEditor.Timeline.WindowState.GatherProperties(), UnityEditor.Timeline.WindowState.masterSequence, and UnityEditor.Timeline.WindowState.previewMode.
Referenced by UnityEditor.Timeline.AnimationTrackRecorder.FinalizeRecording(), and UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
GatherProperties()
void UnityEditor.Timeline.WindowState.GatherProperties (PlayableDirector director)
References UnityEditor.Timeline.WindowState.previewDriver, and UnityEditor.Timeline.WindowState.previewMode.
Referenced by UnityEditor.Timeline.WindowState.Evaluate(), UnityEditor.Timeline.WindowState.EvaluateImmediate(), and UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
GetAllSequences()
IEnumerable<ISequenceState> UnityEditor.Timeline.WindowState.GetAllSequences ()
GetArmedTrack()
TrackAsset UnityEditor.Timeline.WindowState.GetArmedTrack (TrackAsset track)
Referenced by UnityEditor.Timeline.WindowState.IsArmedForRecord().
GetCurrentSequencePath()
SequencePath UnityEditor.Timeline.WindowState.GetCurrentSequencePath ()
GetSceneReference()
GameObject UnityEditor.Timeline.WindowState.GetSceneReference (TrackAsset asset)
References UnityEditor.Timeline.ISequenceState.director, UnityEditor.Timeline.WindowState.editSequence, and UnityEditor.Timeline.GameObject.
Referenced by UnityEditor.Timeline.EditTrackInAnimationWindow.Do(), and UnityEditor.Timeline.EditClipInAnimationWindow.Execute().
GetSnappedTimeAtMousePosition()
double UnityEditor.Timeline.WindowState.GetSnappedTimeAtMousePosition (Vector2 mousePos)
References UnityEditor.Timeline.WindowState.ScreenSpacePixelToTimeAreaTime(), and UnityEditor.Timeline.WindowState.SnapToFrameIfRequired().
Referenced by UnityEditor.Timeline.Scrub.MouseDrag().
GetWindow()
TimelineWindow UnityEditor.Timeline.WindowState.GetWindow ()
Referenced by UnityEditor.Timeline.TimelineMarkerHeaderContextMenu.ContextClick(), UnityEditor.Timeline.TimelineTrackGUI.Draw(), UnityEditor.Timeline.SelectAllAction.Execute(), UnityEditor.Timeline.FrameAllAction.Execute(), UnityEditor.Timeline.AnimationTrackRecorder.FinalizeRecording(), UnityEditor.Timeline.ClearSelection.MouseDown(), UnityEditor.Timeline.TrackResize.MouseDown(), UnityEditor.Timeline.InlineCurveResize.MouseDrag(), UnityEditor.Timeline.RectangleTool.OnGUI(), UnityEditor.Timeline.InlineCurveResize.Overlay(), UnityEditor.Timeline.TrackResize.Overlay(), and UnityEditor.Timeline.TimeAreaAutoPanner.TimeAreaAutoPanner().
InvokeTimeChangeCallback()
void UnityEditor.Timeline.WindowState.InvokeTimeChangeCallback ()
References UnityEditor.Timeline.WindowState.OnTimeChange.
IsArmedForRecord()
bool UnityEditor.Timeline.WindowState.IsArmedForRecord (TrackAsset track)
References UnityEditor.Timeline.WindowState.GetArmedTrack().
Referenced by UnityEditor.Timeline.InfiniteTrackDrawer.CanDraw(), UnityEditor.Timeline.InfiniteTrackDrawer.DrawTrack(), and UnityEditor.Timeline.WindowState.IsTrackRecordable().
IsCurrentEditingASequencerTextField()
bool UnityEditor.Timeline.WindowState.IsCurrentEditingASequencerTextField ()
References UnityEditor.Timeline.ISequenceState.asset, and UnityEditor.Timeline.WindowState.editSequence.
Referenced by UnityEditor.Timeline.TimelineShortcutManipulator.ExecuteCommand(), UnityEditor.Timeline.InlineCurvesShortcutManipulator.ExecuteCommand(), UnityEditor.Timeline.TrackShortcutManipulator.ExecuteCommand(), UnityEditor.Timeline.WindowState.IsEditingASubItem(), and UnityEditor.Timeline.RectangleTool.OnGUI().
IsEditingAnEmptyTimeline()
bool UnityEditor.Timeline.WindowState.IsEditingAnEmptyTimeline ()
References UnityEditor.Timeline.ISequenceState.asset, and UnityEditor.Timeline.WindowState.editSequence.
Referenced by UnityEditor.Timeline.TimelineMode.ShouldShowTimeArea().
IsEditingAPrefabAsset()
bool UnityEditor.Timeline.WindowState.IsEditingAPrefabAsset ()
References UnityEditor.Timeline.ISequenceState.director, and UnityEditor.Timeline.WindowState.editSequence.
IsEditingASubItem()
bool UnityEditor.Timeline.WindowState.IsEditingASubItem ()
References UnityEditor.Timeline.WindowState.IsCurrentEditingASequencerTextField().
Referenced by UnityEditor.Timeline.FrameAllAction.Execute(), UnityEditor.Timeline.FrameSelectedAction.Execute(), and UnityEditor.Timeline.ItemActionShortcutManipulator.ExecuteCommand().
IsEditingASubTimeline()
bool UnityEditor.Timeline.WindowState.IsEditingASubTimeline ()
References UnityEditor.Timeline.WindowState.editSequence, and UnityEditor.Timeline.WindowState.masterSequence.
Referenced by UnityEditor.Timeline.TimelineGroupGUI.Draw(), and UnityEditor.Timeline.SnapEngine.SnapEngine().
IsTrackRecordable()
bool UnityEditor.Timeline.WindowState.IsTrackRecordable (TrackAsset track)
References UnityEditor.Timeline.WindowState.IsArmedForRecord().
OffsetTimeArea()
void UnityEditor.Timeline.WindowState.OffsetTimeArea (int pixels)
References UnityEditor.Timeline.WindowState.SetTimeAreaTransform(), UnityEditor.Timeline.WindowState.timeAreaScale, and UnityEditor.Timeline.WindowState.timeAreaTranslation.
OnDestroy()
void UnityEditor.Timeline.WindowState.OnDestroy ()
References UnityEditor.Timeline.WindowState.Stop(), UnityEditor.Timeline.WindowState.windowOnGuiFinished, and UnityEditor.Timeline.WindowState.windowOnGuiStarted.
OnSceneSaved()
void UnityEditor.Timeline.WindowState.OnSceneSaved ()
Pause()
void UnityEditor.Timeline.WindowState.Pause ()
References UnityEditor.Timeline.ISequenceState.director, and UnityEditor.Timeline.WindowState.masterSequence.
Referenced by UnityEditor.Timeline.WindowState.SetPlaying().
PixelDeltaToDeltaTime()
float UnityEditor.Timeline.WindowState.PixelDeltaToDeltaTime (float p)
References UnityEditor.Timeline.WindowState.PixelToTime().
Referenced by UnityEditor.Timeline.ItemsLayer.Draw(), and UnityEditor.Timeline.EaseClip.MouseDrag().
PixelToTime()
float UnityEditor.Timeline.WindowState.PixelToTime (float pixel)
References UnityEditor.Timeline.WindowState.timeAreaRect.
Referenced by UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible(), UnityEditor.Timeline.TimelineZoomManipulator.MouseDown(), UnityEditor.Timeline.TimelineZoomManipulator.MouseWheel(), UnityEditor.Timeline.RectangleZoom.OnFinish(), UnityEditor.Timeline.WindowState.PixelDeltaToDeltaTime(), UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle(), and UnityEditor.Timeline.WindowState.TimeAreaPixelToTime().
Play()
void UnityEditor.Timeline.WindowState.Play ()
References UnityEditor.Timeline.ISequenceState.director, UnityEditor.Timeline.ISequenceState.duration, UnityEditor.Timeline.WindowState.masterSequence, UnityEditor.Timeline.WindowState.previewMode, and UnityEditor.Timeline.ISequenceState.time.
Referenced by UnityEditor.Timeline.Jog.MouseDown(), UnityEditor.Timeline.Jog.MouseDrag(), UnityEditor.Timeline.Jog.MouseUp(), UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), and UnityEditor.Timeline.WindowState.SetPlaying().
PopSequencesUntilCount()
void UnityEditor.Timeline.WindowState.PopSequencesUntilCount (int count)
References UnityEditor.Timeline.WindowState.OnAfterSequenceChange, and UnityEditor.Timeline.WindowState.OnBeforeSequenceChange.
RangeIsVisible()
bool UnityEditor.Timeline.WindowState.RangeIsVisible (Range range)
References UnityEditor.Timeline.Range.end, and UnityEditor.Timeline.Range.start.
RebuildPlayableGraph()
void UnityEditor.Timeline.WindowState.RebuildPlayableGraph ()
References UnityEditor.Timeline.ISequenceState.director, UnityEditor.Timeline.WindowState.editSequence, and UnityEditor.Timeline.WindowState.masterSequence.
Referenced by UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
Refresh()
void UnityEditor.Timeline.WindowState.Refresh ()
References UnityEditor.Timeline.WindowState.dirtyStamp, and UnityEditor.Timeline.WindowState.rebuildGraph.
Referenced by UnityEditor.Timeline.TimelineRecordingContextualResponder.AddKey(), UnityEditor.Timeline.AnimationTrackRecorder.AddRecordableClip(), UnityEditor.Timeline.PasteAction.Execute(), UnityEditor.Timeline.DeleteAction.Execute(), UnityEditor.Timeline.Split.Execute(), UnityEditor.Timeline.DeleteTracks.Execute(), UnityEditor.Timeline.DuplicateTracks.Execute(), UnityEditor.Timeline.TimelineRecordingContextualResponder.GoToNextKeyframe(), UnityEditor.Timeline.TimelineRecordingContextualResponder.GoToPreviousKeyframe(), UnityEditor.Timeline.MuteSelectedTrack.Mute(), UnityEditor.Timeline.MuteTrack.Mute(), UnityEditor.Timeline.TimeFieldDrawer.OnGUI(), UnityEditor.Timeline.TimelineRecordingContextualResponder.RemoveCurve(), and UnityEditor.Timeline.TimelineRecordingContextualResponder.RemoveKey().
RemoveCaptured()
void UnityEditor.Timeline.WindowState.RemoveCaptured (Manipulator manipulator)
Referenced by UnityEditor.Timeline.SelectAndMoveItem.MouseUp(), UnityEditor.Timeline.Scrub.MouseUp(), and UnityEditor.Timeline.InlineCurveResize.MouseUp().
Reset()
void UnityEditor.Timeline.WindowState.Reset ()
References UnityEditor.Timeline.WindowState.previewMode, and UnityEditor.Timeline.WindowState.recording.
ResetPreviewMode()
void UnityEditor.Timeline.WindowState.ResetPreviewMode ()
References UnityEditor.Timeline.WindowState.previewMode.
ScreenSpacePixelToTimeAreaTime()
float UnityEditor.Timeline.WindowState.ScreenSpacePixelToTimeAreaTime (float p)
References UnityEditor.Timeline.WindowState.timeAreaRect, and UnityEditor.Timeline.WindowState.TrackSpacePixelToTimeAreaTime().
Referenced by UnityEditor.Timeline.WindowState.GetSnappedTimeAtMousePosition().
SetCurrentSequence()
void UnityEditor.Timeline.WindowState.SetCurrentSequence (TimelineAsset timelineAsset, PlayableDirector director, TimelineClip hostClip)
References UnityEditor.Timeline.WindowState.OnAfterSequenceChange, and UnityEditor.Timeline.WindowState.OnBeforeSequenceChange.
SetCurrentSequencePath()
void UnityEditor.Timeline.WindowState.SetCurrentSequencePath (SequencePath path, bool forceRebuild)
References UnityEditor.Timeline.WindowState.OnAfterSequenceChange, and UnityEditor.Timeline.WindowState.OnBeforeSequenceChange.
SetPlayHeadToMiddle()
void UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle ()
References UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.WindowState.PixelToTime(), UnityEditor.Timeline.WindowState.SetTimeAreaShownRange(), UnityEditor.Timeline.ISequenceState.time, and UnityEditor.Timeline.WindowState.timeAreaRect.
SetPlaying()
void UnityEditor.Timeline.WindowState.SetPlaying (bool start)
References UnityEditor.Timeline.WindowState.Pause(), UnityEditor.Timeline.WindowState.Play(), and UnityEditor.Timeline.WindowState.playing.
Referenced by UnityEditor.Timeline.PlayTimelineAction.Execute().
SetTimeAreaShownRange()
void UnityEditor.Timeline.WindowState.SetTimeAreaShownRange (float min, float max)
Referenced by UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible(), UnityEditor.Timeline.FrameSelectedAction.FrameRange(), UnityEditor.Timeline.RectangleZoom.OnFinish(), and UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle().
SetTimeAreaTransform()
void UnityEditor.Timeline.WindowState.SetTimeAreaTransform (Vector2 newTranslation, Vector2 newScale)
Referenced by UnityEditor.Timeline.WindowState.OffsetTimeArea().
SnapToFrameIfRequired()
double UnityEditor.Timeline.WindowState.SnapToFrameIfRequired (double currentTime)
References UnityEditor.Timeline.WindowState.frameSnap.
Referenced by UnityEditor.Timeline.WindowState.GetSnappedTimeAtMousePosition().
Stop()
void UnityEditor.Timeline.WindowState.Stop ()
References UnityEditor.Timeline.ISequenceState.director, and UnityEditor.Timeline.WindowState.masterSequence.
Referenced by UnityEditor.Timeline.WindowState.OnDestroy().
TimeAreaPixelToTime()
float UnityEditor.Timeline.WindowState.TimeAreaPixelToTime (float pixel)
References UnityEditor.Timeline.WindowState.PixelToTime().
TimeIsInRange()
bool UnityEditor.Timeline.WindowState.TimeIsInRange (float value)
TimeToPixel()
float UnityEditor.Timeline.WindowState.TimeToPixel (double time)
References UnityEditor.Timeline.WindowState.timeAreaRect.
Referenced by UnityEditor.Timeline.MoveItemModeRipple.AdjustStartTime(), UnityEditor.Timeline.TimeAreaItem.Draw(), and UnityEditor.ClipCurveEditor.DrawCurveEditor().
TimeToScreenSpacePixel()
float UnityEditor.Timeline.WindowState.TimeToScreenSpacePixel (double time)
References UnityEditor.Timeline.WindowState.timeAreaScale, and UnityEditor.Timeline.WindowState.timeAreaTranslation.
TimeToTimeAreaPixel()
float UnityEditor.Timeline.WindowState.TimeToTimeAreaPixel (double t)
References UnityEditor.Timeline.WindowState.sequencerHeaderWidth, UnityEditor.Timeline.WindowState.timeAreaScale, and UnityEditor.Timeline.WindowState.timeAreaTranslation.
TrackSpacePixelToTimeAreaTime()
float UnityEditor.Timeline.WindowState.TrackSpacePixelToTimeAreaTime (float p)
References UnityEditor.Timeline.WindowState.timeAreaScale, and UnityEditor.Timeline.WindowState.timeAreaTranslation.
Referenced by UnityEditor.Timeline.WindowState.ScreenSpacePixelToTimeAreaTime().
UnarmForRecord()
void UnityEditor.Timeline.WindowState.UnarmForRecord (TrackAsset track)
References UnityEditor.Timeline.ISequenceState.director, UnityEditor.Timeline.WindowState.editSequence, and UnityEditor.Timeline.WindowState.recording.
Referenced by UnityEditor.Timeline.TimelineWindowTimeControl.StopRecording().
UpdateRecordingState()
void UnityEditor.Timeline.WindowState.UpdateRecordingState ()
References UnityEditor.Timeline.ISequenceState.director, UnityEditor.Timeline.WindowState.editSequence, and UnityEditor.Timeline.WindowState.recording.
UpdateRootPlayableDuration()
void UnityEditor.Timeline.WindowState.UpdateRootPlayableDuration (double duration)
References UnityEditor.Timeline.ISequenceState.director, and UnityEditor.Timeline.WindowState.editSequence.
Referenced by UnityEditor.Timeline.TrimClip.MouseDrag().
UpdateViewStateHash()
void UnityEditor.Timeline.WindowState.UpdateViewStateHash ()
References UnityEditor.Timeline.WindowState.timeAreaScale, UnityEditor.Timeline.WindowState.timeAreaTranslation, UnityEditor.Timeline.WindowState.trackScale, and UnityEditor.Timeline.WindowState.viewStateHash.
Member Data Documentation
kMaxShownTime
readonly float UnityEditor.Timeline.WindowState.kMaxShownTime = (float)TimeUtility.k_MaxTimelineDurationInSeconds static
Property Documentation
autoScrollMode
PlaybackScrollMode UnityEditor.Timeline.WindowState.autoScrollMode get set
bindingAreaWidth
float UnityEditor.Timeline.WindowState.bindingAreaWidth get set
canRecord
bool UnityEditor.Timeline.WindowState.canRecord get
captured
List<Manipulator> UnityEditor.Timeline.WindowState.captured get
Referenced by UnityEditor.Timeline.EaseClip.MouseUp(), and UnityEditor.Timeline.TrimClip.MouseUp().
dirtyStamp
int UnityEditor.Timeline.WindowState.dirtyStamp get
Referenced by UnityEditor.Timeline.PrevKeyAction.Execute(), UnityEditor.Timeline.NextKeyAction.Execute(), and UnityEditor.Timeline.WindowState.Refresh().
edgeSnaps
bool UnityEditor.Timeline.WindowState.edgeSnaps get set
editorWindow
EditorWindow UnityEditor.Timeline.WindowState.editorWindow get
Referenced by UnityEditor.Timeline.TimelinePanManipulator.MouseUp().
editSequence
ISequenceState?? UnityEditor.Timeline.WindowState.editSequence get
Referenced by UnityEditor.Timeline.TimelineWindow.AddItemsToMenu(), UnityEditor.Timeline.EditSubTimeline.AddMenuItem(), UnityEditor.Timeline.AnimationTrackRecorder.AddRecordableClip(), UnityEditor.Timeline.WindowState.ArmForRecord(), UnityEditor.Timeline.PlayheadContextMenu.ContextClick(), UnityEditor.Timeline.DrillIntoClip.DoubleClick(), UnityEditor.TimelineDragging.DragElement(), UnityEditor.Timeline.TimelineClipHandle.Draw(), UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible(), UnityEditor.Timeline.PreviousFrameAction.Execute(), UnityEditor.Timeline.NextFrameAction.Execute(), UnityEditor.Timeline.FrameAllAction.Execute(), UnityEditor.Timeline.PrevKeyAction.Execute(), UnityEditor.Timeline.NextKeyAction.Execute(), UnityEditor.Timeline.GotoStartAction.Execute(), UnityEditor.Timeline.GotoEndAction.Execute(), UnityEditor.Timeline.EditSubTimeline.Execute(), UnityEditor.Timeline.TrimStart.Execute(), UnityEditor.Timeline.TrimEnd.Execute(), UnityEditor.Timeline.Split.Execute(), UnityEditor.Timeline.DeleteTracks.Execute(), UnityEditor.Timeline.CurveDataSource.GetBackgroundRect(), UnityEditor.Timeline.TrimStart.GetDisplayState(), UnityEditor.Timeline.TrimEnd.GetDisplayState(), UnityEditor.Timeline.Split.GetDisplayState(), UnityEditor.Timeline.WindowState.GetSceneReference(), UnityEditor.Timeline.TimelineWindowTimeControl.GoToNextFrame(), UnityEditor.Timeline.TimelineWindowTimeControl.GoToPreviousFrame(), UnityEditor.Timeline.TimelineRecordingContextualResponder.IsAnimatable(), UnityEditor.Timeline.ToggleMuteMarkersOnTimeline.IsChecked(), UnityEditor.Timeline.WindowState.IsCurrentEditingASequencerTextField(), UnityEditor.Timeline.WindowState.IsEditingAnEmptyTimeline(), UnityEditor.Timeline.WindowState.IsEditingAPrefabAsset(), UnityEditor.Timeline.WindowState.IsEditingASubTimeline(), UnityEditor.Timeline.SelectAndMoveItem.MouseDrag(), UnityEditor.Timeline.TrimClip.MouseDrag(), UnityEditor.Timeline.AnimationTrackRecorder.PrepareTrack(), UnityEditor.Timeline.TimelineReadOnlyMode.PreviewState(), UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), UnityEditor.Timeline.WindowState.RebuildPlayableGraph(), UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle(), UnityEditor.Timeline.TimelineReadOnlyMode.ShouldShowPlayRange(), UnityEditor.Timeline.TimelineReadOnlyMode.ShouldShowTimeCursor(), UnityEditor.Timeline.TimelineWindow.ShowButton(), UnityEditor.Timeline.SnapEngine.SnapEngine(), UnityEditor.Timeline.TimelineGroupGUI.TimelineGroupGUI(), UnityEditor.Timeline.TimelineReadOnlyMode.ToolbarState(), UnityEditor.Timeline.WindowState.UnarmForRecord(), UnityEditor.Timeline.WindowState.UpdateRecordingState(), and UnityEditor.Timeline.WindowState.UpdateRootPlayableDuration().
editType
EditMode.EditType UnityEditor.Timeline.WindowState.editType get set
frameSnap
bool UnityEditor.Timeline.WindowState.frameSnap get set
Referenced by UnityEditor.Timeline.WindowState.SnapToFrameIfRequired().
headerSpacePartitioner
SpacePartitioner UnityEditor.Timeline.WindowState.headerSpacePartitioner get
Referenced by UnityEditor.Timeline.InlineCurveResizeHandle.Draw(), and UnityEditor.Timeline.TrackResizeHandle.Draw().
isClipSnapping
bool UnityEditor.Timeline.WindowState.isClipSnapping get set
isJogging
bool UnityEditor.Timeline.WindowState.isJogging get set
Referenced by UnityEditor.Timeline.Jog.MouseDown(), UnityEditor.Timeline.Jog.MouseDrag(), and UnityEditor.Timeline.Jog.MouseUp().
kTimeEpsilon
double UnityEditor.Timeline.WindowState.kTimeEpsilon static get
mainAreaWidth
float UnityEditor.Timeline.WindowState.mainAreaWidth get set
masterSequence
ISequenceState?? UnityEditor.Timeline.WindowState.masterSequence get
Referenced by UnityEditor.Timeline.WindowState.Evaluate(), UnityEditor.Timeline.WindowState.EvaluateImmediate(), UnityEditor.Timeline.WindowState.IsEditingASubTimeline(), UnityEditor.Timeline.WindowState.Pause(), UnityEditor.Timeline.WindowState.Play(), UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), UnityEditor.Timeline.WindowState.RebuildPlayableGraph(), UnityEditor.Timeline.SnapEngine.SnapEngine(), and UnityEditor.Timeline.WindowState.Stop().
mouseDragLag
float UnityEditor.Timeline.WindowState.mouseDragLag get set
muteAudioScrubbing
bool UnityEditor.Timeline.WindowState.muteAudioScrubbing get set
Referenced by UnityEditor.Timeline.WindowState.WindowState().
playbackSpeed
float UnityEditor.Timeline.WindowState.playbackSpeed get set
Referenced by UnityEditor.Timeline.Jog.MouseDown(), UnityEditor.Timeline.Jog.MouseDrag(), and UnityEditor.Timeline.Jog.MouseUp().
playing
bool UnityEditor.Timeline.WindowState.playing get
Referenced by UnityEditor.Timeline.PlayTimelineAction.Execute(), UnityEditor.Timeline.TimelineWindowTimeControl.PlaybackUpdate(), UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), UnityEditor.Timeline.WindowState.SetPlaying(), and UnityEditor.Timeline.TimelineWindowTimeControl.StartPlayback().
playRange
Vector2 UnityEditor.Timeline.WindowState.playRange get set
Referenced by UnityEditor.Timeline.PlayheadContextMenu.ContextClick().
playRangeEnabled
bool UnityEditor.Timeline.WindowState.playRangeEnabled get set
Referenced by UnityEditor.Timeline.TimelineActiveMode.ShouldShowPlayRange(), and UnityEditor.Timeline.TimelineReadOnlyMode.ShouldShowPlayRange().
playRangeLoopMode
bool UnityEditor.Timeline.WindowState.playRangeLoopMode get set
previewDriver
AnimationModeDriver UnityEditor.Timeline.WindowState.previewDriver static get
Referenced by UnityEditor.Timeline.WindowState.GatherProperties().
previewedDirectors
List<PlayableDirector> UnityEditor.Timeline.WindowState.previewedDirectors get
previewMode
bool UnityEditor.Timeline.WindowState.previewMode get set
Referenced by UnityEditor.Timeline.WindowState.Evaluate(), UnityEditor.Timeline.WindowState.EvaluateImmediate(), UnityEditor.Timeline.DeleteTracks.Execute(), UnityEditor.Timeline.WindowState.GatherProperties(), UnityEditor.Timeline.WindowState.Play(), UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), UnityEditor.Timeline.WindowState.Reset(), UnityEditor.Timeline.WindowState.ResetPreviewMode(), UnityEditor.Timeline.TimelineWindowTimeControl.StartPreview(), and UnityEditor.Timeline.TimelineWindowTimeControl.StopPreview().
rebuildGraph
bool UnityEditor.Timeline.WindowState.rebuildGraph get set
Referenced by UnityEditor.BindingSelector.Delete(), UnityEditor.Timeline.AnimationTrackDrawer.DrawTrackHeaderButton(), UnityEditor.Timeline.AnimationTrackRecorder.FinalizeRecording(), UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), and UnityEditor.Timeline.WindowState.Refresh().
recording
bool UnityEditor.Timeline.WindowState.recording get set
Referenced by UnityEditor.Timeline.WindowState.ArmForRecord(), UnityEditor.Timeline.InfiniteTrackDrawer.DrawTrack(), UnityEditor.Timeline.WindowState.Reset(), UnityEditor.Timeline.TimelineWindowTimeControl.StartRecording(), UnityEditor.Timeline.WindowState.UnarmForRecord(), and UnityEditor.Timeline.WindowState.UpdateRecordingState().
referenceSequence
ISequenceState? UnityEditor.Timeline.WindowState.referenceSequence get
Referenced by UnityEditor.Timeline.PlayheadContextMenu.ContextClick(), UnityEditor.ClipCurveEditor.DrawCurveEditor(), UnityEditor.Timeline.PrevKeyAction.Execute(), and UnityEditor.Timeline.NextKeyAction.Execute().
sequencerHeaderWidth
float UnityEditor.Timeline.WindowState.sequencerHeaderWidth get set
Referenced by UnityEditor.Timeline.TimeAreaItem.Draw(), and UnityEditor.Timeline.WindowState.TimeToTimeAreaPixel().
showAudioWaveform
bool UnityEditor.Timeline.WindowState.showAudioWaveform get set
Referenced by UnityEditor.Timeline.AudioPlayableAssetEditor.DrawBackground().
showMarkerHeader
bool UnityEditor.Timeline.WindowState.showMarkerHeader get set
Referenced by UnityEditor.Timeline.TimelineMarkerHeaderContextMenu.ContextClick(), UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw(), UnityEditor.Timeline.ToggleMuteMarkersOnTimeline.Execute(), and UnityEditor.Timeline.ToggleShowMarkersOnTimeline.IsChecked().
showQuadTree
bool UnityEditor.Timeline.WindowState.showQuadTree get set
spacePartitioner
SpacePartitioner UnityEditor.Timeline.WindowState.spacePartitioner get
Referenced by UnityEditor.Timeline.TimelineClipHandle.Draw(), UnityEditor.Timeline.InlineCurveEditor.Draw(), UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw(), UnityEditor.Timeline.TimelineMarkerGUI.Draw(), UnityEditor.Timeline.SnapEngine.GetVisibleSnappables(), and UnityEditor.Timeline.RectangleSelect.OnFinish().
timeAreaRect
Rect UnityEditor.Timeline.WindowState.timeAreaRect get
Referenced by UnityEditor.Timeline.TimeAreaContextMenu.ContextClick(), UnityEditor.Timeline.TimelineGroupGUI.Draw(), UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw(), UnityEditor.Timeline.TimeAreaItem.Draw(), UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible(), UnityEditor.Timeline.SnapEngine.GetVisibleSnappables(), UnityEditor.Timeline.SnapEngine.OnGUI(), UnityEditor.Timeline.WindowState.PixelToTime(), UnityEditor.Timeline.WindowState.ScreenSpacePixelToTimeAreaTime(), UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle(), and UnityEditor.Timeline.WindowState.TimeToPixel().
timeAreaScale
Vector2 UnityEditor.Timeline.WindowState.timeAreaScale get
Referenced by UnityEditor.Timeline.TimelineClipUnion.Draw(), UnityEditor.Timeline.CurveDataSource.GetBackgroundRect(), UnityEditor.Timeline.WindowState.OffsetTimeArea(), UnityEditor.Timeline.TimelineClipGUI.RectToTimeline(), UnityEditor.Timeline.TimelineMarkerGUI.RectToTimeline(), UnityEditor.Timeline.WindowState.TimeToScreenSpacePixel(), UnityEditor.Timeline.WindowState.TimeToTimeAreaPixel(), UnityEditor.Timeline.WindowState.TrackSpacePixelToTimeAreaTime(), and UnityEditor.Timeline.WindowState.UpdateViewStateHash().
timeAreaShownRange
Vector2 UnityEditor.Timeline.WindowState.timeAreaShownRange get
Referenced by UnityEditor.Timeline.TimelineTrackGUI.Draw(), UnityEditor.Timeline.ItemsLayer.Draw(), UnityEditor.ClipCurveEditor.DrawCurveEditor(), UnityEditor.Timeline.FrameSelectedAction.FrameRange(), UnityEditor.Timeline.TimelineZoomManipulator.MouseDown(), UnityEditor.Timeline.TimelineZoomManipulator.MouseWheel(), and UnityEditor.Timeline.TimelineClipGUI.SnappableEdgesFor().
timeAreaTranslation
Vector2 UnityEditor.Timeline.WindowState.timeAreaTranslation get
Referenced by UnityEditor.Timeline.TimelineClipUnion.Draw(), UnityEditor.Timeline.CurveDataSource.GetBackgroundRect(), UnityEditor.Timeline.WindowState.OffsetTimeArea(), UnityEditor.Timeline.TimelineClipGUI.RectToTimeline(), UnityEditor.Timeline.TimelineMarkerGUI.RectToTimeline(), UnityEditor.Timeline.WindowState.TimeToScreenSpacePixel(), UnityEditor.Timeline.WindowState.TimeToTimeAreaPixel(), UnityEditor.Timeline.WindowState.TrackSpacePixelToTimeAreaTime(), and UnityEditor.Timeline.WindowState.UpdateViewStateHash().
timeInFrames
bool UnityEditor.Timeline.WindowState.timeInFrames get set
timeReferenceMode
TimeReferenceMode UnityEditor.Timeline.WindowState.timeReferenceMode get set
trackScale
float UnityEditor.Timeline.WindowState.trackScale get set
Referenced by UnityEditor.Timeline.TrackResize.MouseDrag(), UnityEditor.Timeline.TrackZoom.MouseWheel(), and UnityEditor.Timeline.WindowState.UpdateViewStateHash().
viewStateHash
int UnityEditor.Timeline.WindowState.viewStateHash get
Referenced by UnityEditor.Timeline.WindowState.UpdateViewStateHash().
windowHeight
float UnityEditor.Timeline.WindowState.windowHeight get
Event Documentation
OnAfterSequenceChange
Action UnityEditor.Timeline.WindowState.OnAfterSequenceChange
Referenced by UnityEditor.Timeline.WindowState.PopSequencesUntilCount(), UnityEditor.Timeline.WindowState.SetCurrentSequence(), and UnityEditor.Timeline.WindowState.SetCurrentSequencePath().
OnBeforeSequenceChange
Action UnityEditor.Timeline.WindowState.OnBeforeSequenceChange
Referenced by UnityEditor.Timeline.WindowState.PopSequencesUntilCount(), UnityEditor.Timeline.WindowState.SetCurrentSequence(), and UnityEditor.Timeline.WindowState.SetCurrentSequencePath().
OnDirtyStampChange
Action UnityEditor.Timeline.WindowState.OnDirtyStampChange
OnPlayStateChange
Action<bool> UnityEditor.Timeline.WindowState.OnPlayStateChange
OnRebuildGraphChange
Action UnityEditor.Timeline.WindowState.OnRebuildGraphChange
OnRecordingChange
Action UnityEditor.Timeline.WindowState.OnRecordingChange
OnTimeChange
Action UnityEditor.Timeline.WindowState.OnTimeChange
Referenced by UnityEditor.Timeline.WindowState.InvokeTimeChangeCallback(), UnityEditor.Timeline.TimelineWindowTimeControl.OnDisable(), and UnityEditor.Timeline.TimelineWindowTimeControl.OnEnable().
windowOnGuiFinished
Action<WindowState, Event> UnityEditor.Timeline.WindowState.windowOnGuiFinished
Referenced by UnityEditor.Timeline.WindowState.OnDestroy().
windowOnGuiStarted
Action<WindowState, Event> UnityEditor.Timeline.WindowState.windowOnGuiStarted
Referenced by UnityEditor.Timeline.WindowState.OnDestroy().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/State/WindowState.cs