VirtualTours: UnityEditor.Timeline.SequenceHierarchy Class Reference
UnityEditor.Timeline.SequenceHierarchy Class Reference
Public Member Functions
void Init (WindowState owner)
void Add (TimelineAsset asset, PlayableDirector director, TimelineClip hostClip)
void Remove ()
ISequenceState GetStateAtIndex (int index)
void RemoveUntilCount (int expectedCount)
void Clear ()
SequencePath ToSequencePath ()
bool NeedsUpdate (SequencePath path, bool forceRebuild)
void FromSequencePath (SequencePath path, bool forceRebuild)
Static Public Member Functions
static SequenceHierarchy CreateInstance ()
Properties
ISequenceState masterSequence [get]
ISequenceState editSequence [get]
int count [get]
IEnumerable< ISequenceState > allSequences [get]
Member Function Documentation
Add()
void UnityEditor.Timeline.SequenceHierarchy.Add (TimelineAsset asset, PlayableDirector director, TimelineClip hostClip)
Clear()
void UnityEditor.Timeline.SequenceHierarchy.Clear ()
CreateInstance()
static SequenceHierarchy UnityEditor.Timeline.SequenceHierarchy.CreateInstance () static
References UnityEditor.Timeline.SequenceHierarchy.CreateInstance().
Referenced by UnityEditor.Timeline.SequenceHierarchy.CreateInstance().
FromSequencePath()
void UnityEditor.Timeline.SequenceHierarchy.FromSequencePath (SequencePath path, bool forceRebuild)
References UnityEditor.Timeline.GameObject, UnityEditor.Timeline.SequenceHierarchy.NeedsUpdate(), UnityEditor.Timeline.SequencePath.selectionRoot, and UnityEditor.Timeline.SequencePath.subElements.
GetStateAtIndex()
ISequenceState UnityEditor.Timeline.SequenceHierarchy.GetStateAtIndex (int index)
Init()
void UnityEditor.Timeline.SequenceHierarchy.Init (WindowState owner)
Referenced by UnityEditor.Timeline.WindowState.WindowState().
NeedsUpdate()
bool UnityEditor.Timeline.SequenceHierarchy.NeedsUpdate (SequencePath path, bool forceRebuild)
References UnityEditor.Timeline.SequencePath.AreEqual().
Referenced by UnityEditor.Timeline.SequenceHierarchy.FromSequencePath().
Remove()
void UnityEditor.Timeline.SequenceHierarchy.Remove ()
RemoveUntilCount()
void UnityEditor.Timeline.SequenceHierarchy.RemoveUntilCount (int expectedCount)
ToSequencePath()
SequencePath UnityEditor.Timeline.SequenceHierarchy.ToSequencePath ()
Property Documentation
allSequences
IEnumerable<ISequenceState> UnityEditor.Timeline.SequenceHierarchy.allSequences get
count
int UnityEditor.Timeline.SequenceHierarchy.count get
editSequence
ISequenceState UnityEditor.Timeline.SequenceHierarchy.editSequence get
masterSequence
ISequenceState UnityEditor.Timeline.SequenceHierarchy.masterSequence get
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/State/SequenceHierarchy.cs