VirtualTours: UnityEditor.Timeline.CustomTimelineEditorCache Class Reference
UnityEditor.Timeline.CustomTimelineEditorCache Class Reference
Static Public Member Functions
static TEditorClass GetEditorForType< TEditorClass, TRuntimeClass > (Type type)
static void ClearCache< TEditorClass > ()
static ClipEditor GetClipEditor (TimelineClip clip)
static ClipEditor GetDefaultClipEditor ()
static TrackEditor GetTrackEditor (TrackAsset track)
static TrackEditor GetDefaultTrackEditor ()
static MarkerEditor GetMarkerEditor (IMarker marker)
static MarkerEditor GetDefaultMarkerEditor ()
Member Function Documentation
ClearCache< TEditorClass >()
static void UnityEditor.Timeline.CustomTimelineEditorCache.ClearCache< TEditorClass > () static
Type Constraints
TEditorClass : class
TEditorClass : new()
GetClipEditor()
static ClipEditor UnityEditor.Timeline.CustomTimelineEditorCache.GetClipEditor (TimelineClip clip) static
References UnityEngine.Timeline.TimelineClip.asset, and UnityEditor.Timeline.CustomTimelineEditorCache.GetDefaultClipEditor().
Referenced by UnityEditor.Timeline.TimelineClipGUI.TimelineClipGUI().
GetDefaultClipEditor()
static ClipEditor UnityEditor.Timeline.CustomTimelineEditorCache.GetDefaultClipEditor () static
Referenced by UnityEditor.Timeline.CustomTimelineEditorCache.GetClipEditor().
GetDefaultMarkerEditor()
static MarkerEditor UnityEditor.Timeline.CustomTimelineEditorCache.GetDefaultMarkerEditor () static
GetDefaultTrackEditor()
static TrackEditor UnityEditor.Timeline.CustomTimelineEditorCache.GetDefaultTrackEditor () static
Referenced by UnityEditor.Timeline.TimelineTrackGUI.TimelineTrackGUI().
GetEditorForType< TEditorClass, TRuntimeClass >()
static TEditorClass UnityEditor.Timeline.CustomTimelineEditorCache.GetEditorForType< TEditorClass, TRuntimeClass > (Type type) static
Type Constraints
TEditorClass : class
TEditorClass : new()
GetMarkerEditor()
static MarkerEditor UnityEditor.Timeline.CustomTimelineEditorCache.GetMarkerEditor (IMarker marker) static
Referenced by UnityEditor.Timeline.TimelineMarkerGUI.TimelineMarkerGUI().
GetTrackEditor()
static TrackEditor UnityEditor.Timeline.CustomTimelineEditorCache.GetTrackEditor (TrackAsset track) static
Referenced by UnityEditor.Timeline.TrackAssetInspector.OnEnable(), and UnityEditor.Timeline.TimelineTrackGUI.TimelineTrackGUI().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/CustomEditors/CustomTimelineEditorCache.cs