VirtualTours: UnityEngine.Timeline.TimelineAsset Class Reference
UnityEngine.Timeline.TimelineAsset Class Reference
A PlayableAsset that represents a timeline.
Classes
class EditorSettings
Properties of the timeline that are used by the editor
Public Types
enum class MediaType {
Animation , Audio , Texture = 2 , Video = 2 ,
Script , Hybrid , Group
}
enum class DurationMode { BasedOnClips , FixedLength }
How the duration of the timeline is determined.
Public Member Functions
TrackAsset GetRootTrack (int index)
Retrieves at root track at the specified index.
IEnumerable< TrackAsset > GetRootTracks ()
Get an enumerable list of all root tracks.
TrackAsset GetOutputTrack (int index)
Retrives the output track from the given index.
IEnumerable< TrackAsset > GetOutputTracks ()
Gets a list of all output tracks in the Timeline.
override Playable CreatePlayable (PlayableGraph graph, GameObject go)
Creates an instance of the timeline
void GatherProperties (PlayableDirector director, IPropertyCollector driver)
Called by the Timeline Editor to gather properties requiring preview.
void CreateMarkerTrack ()
Creates a marker track for the TimelineAsset.
TrackAsset CreateTrack (Type type, TrackAsset parent, string name)
Allows you to create a track and add it to the Timeline.
T CreateTrack< T > (TrackAsset parent, string trackName)
Creates a track and adds it to the Timeline Asset.
T CreateTrack< T > (string trackName)
Creates a track and adds it to the Timeline Asset.
T CreateTrack< T > ()
Creates a track and adds it to the Timeline Asset.
bool DeleteClip (TimelineClip clip)
Delete a clip from this timeline.
bool DeleteTrack (TrackAsset track)
Deletes a track from a timeline, including all clips and subtracks.
Properties
EditorSettings editorSettings [get]
Settings used by timeline for editing purposes
override double duration [get]
The length, in seconds, of the timeline
double fixedDuration [get, set]
The length of the timeline when durationMode is set to fixed length.
DurationMode durationMode [get, set]
The mode used to determine the duration of the Timeline
override IEnumerable< PlayableBinding > outputs [get]
A description of the PlayableOutputs that will be created by the timeline when instantiated.
ClipCaps clipCaps [get]
int outputTrackCount [get]
Returns the the number of output tracks in the Timeline.
int rootTrackCount [get]
Returns the number of tracks at the root level of the timeline.
MarkerTrack markerTrack [get]
Gets the marker track for this TimelineAsset.
Properties inherited from UnityEngine.Timeline.ITimelineClipAsset
ClipCaps clipCaps [get]
Returns a description of the features supported by clips with PlayableAssets implementing this interface.
Detailed Description
A PlayableAsset that represents a timeline.
Member Enumeration Documentation
DurationMode
enum UnityEngine.Timeline.TimelineAsset.DurationMode strong
How the duration of the timeline is determined.
Enumerator
BasedOnClips
The duration of the timeline is determined based on the clips present.
FixedLength
The duration of the timeline is a fixed length.
MediaType
enum UnityEngine.Timeline.TimelineAsset.MediaType strong
Enumerator
Animation
Audio
Texture
Video
Script
Hybrid
Group
Member Function Documentation
CreateMarkerTrack()
void UnityEngine.Timeline.TimelineAsset.CreateMarkerTrack ()
Creates a marker track for the TimelineAsset.
In the editor, the marker track appears under the Timeline ruler.
This track is always bound to the GameObject that contains the PlayableDirector component for the current timeline. The marker track is created the first time this method is called. If the marker track is already created, this method does nothing.
Referenced by UnityEditor.TimelineDragging.HandleClipPaneObjectDragAndDrop().
CreatePlayable()
override Playable UnityEngine.Timeline.TimelineAsset.CreatePlayable (PlayableGraph graph, GameObject go)
Creates an instance of the timeline
Parameters
graph PlayableGraph that will own the playable
go The gameobject that triggered the graph build
Returns
The Root Playable of the Timeline
References UnityEngine.Timeline.TimelinePlayable.Create().
CreateTrack()
TrackAsset UnityEngine.Timeline.TimelineAsset.CreateTrack (Type type, TrackAsset parent, string name)
Allows you to create a track and add it to the Timeline.
Parameters
type The type of track to create. Must derive from TrackAsset.
parent Track to parent to. This can be null.
name Name to give the track.
Returns
The created track.
This method will throw an InvalidOperationException if the parent is not valid. The parent can be any GroupTrack, or a supported parent type of track. For example, this can be used to create override tracks in AnimationTracks.
References UnityEngine.Timeline.TrackAsset.timelineAsset.
Referenced by UnityEngine.Timeline.TimelineAsset.CreateTrack< T >().
CreateTrack< T >() [1/3]
T UnityEngine.Timeline.TimelineAsset.CreateTrack< T > ()
Creates a track and adds it to the Timeline Asset.
Template Parameters
T The type of track being created. The track type must be derived from TrackAsset.
Returns
Returns the created track.
Type Constraints
T : TrackAsset
T : new()
References UnityEngine.Timeline.TimelineAsset.CreateTrack().
CreateTrack< T >() [2/3]
T UnityEngine.Timeline.TimelineAsset.CreateTrack< T > (string trackName)
Creates a track and adds it to the Timeline Asset.
Parameters
trackName The name of the track being created.
Template Parameters
T The type of track being created. The track type must be derived from TrackAsset.
Returns
Returns the created track.
Type Constraints
T : TrackAsset
T : new()
References UnityEngine.Timeline.TimelineAsset.CreateTrack().
CreateTrack< T >() [3/3]
T UnityEngine.Timeline.TimelineAsset.CreateTrack< T > (TrackAsset parent, string trackName)
Creates a track and adds it to the Timeline Asset.
Parameters
parent Track to parent to. This can be null.
trackName The name of the track being created.
Template Parameters
T The type of track being created. The track type must be derived from TrackAsset.
Returns
Returns the created track.
This method will throw an InvalidOperationException if the parent is not valid. The parent can be any GroupTrack, or a supported parent type of track. For example, this can be used to create override tracks in AnimationTracks.
Type Constraints
T : TrackAsset
T : new()
References UnityEngine.Timeline.TimelineAsset.CreateTrack().
DeleteClip()
bool UnityEngine.Timeline.TimelineAsset.DeleteClip (TimelineClip clip)
Delete a clip from this timeline.
Parameters
clip The clip to delete.
Returns
Returns true if the removal was successful
This method will delete a clip and any assets owned by the clip.
References UnityEngine.Timeline.TimelineClip.asset, UnityEngine.Timeline.TimelineClip.curves, UnityEngine.Timeline.TimelineClip.parentTrack, and UnityEngine.Timeline.TrackAsset.timelineAsset.
Referenced by UnityEngine.Timeline.TimelineAsset.DeleteTrack().
DeleteTrack()
bool UnityEngine.Timeline.TimelineAsset.DeleteTrack (TrackAsset track)
Deletes a track from a timeline, including all clips and subtracks.
Parameters
track The track to delete. It must be owned by this Timeline.
Returns
True if the track was deleted successfully.
References UnityEngine.Timeline.TimelineAsset.DeleteClip(), UnityEngine.Timeline.TrackAsset.GetChildTracks(), UnityEngine.Timeline.TrackAsset.parent, and UnityEngine.Timeline.TrackAsset.timelineAsset.
GatherProperties()
void UnityEngine.Timeline.TimelineAsset.GatherProperties (PlayableDirector director, IPropertyCollector driver)
Called by the Timeline Editor to gather properties requiring preview.
Parameters
director The PlayableDirector invoking the preview
driver PropertyCollector used to gather previewable properties
Implements UnityEngine.Timeline.IPropertyPreview.
Referenced by UnityEngine.Timeline.ControlPlayableAsset.GatherProperties().
GetOutputTrack()
TrackAsset UnityEngine.Timeline.TimelineAsset.GetOutputTrack (int index)
Retrives the output track from the given index.
Parameters
index Index of the output track to retrieve. Must be between 0 and outputTrackCount
Returns
The output track from the given index
GetOutputTracks()
IEnumerable<TrackAsset> UnityEngine.Timeline.TimelineAsset.GetOutputTracks ()
Gets a list of all output tracks in the Timeline.
Returns
An IEnumerable of all output tracks
An output track is a track the generates a PlayableOutput. In general, an output track is any track that is not a GroupTrack or subtrack.
GetRootTrack()
TrackAsset UnityEngine.Timeline.TimelineAsset.GetRootTrack (int index)
Retrieves at root track at the specified index.
Parameters
index Index of the root track to get. Must be between 0 and rootTrackCount
A root track refers to all tracks that occur at the root of the timeline. These are the outmost level GroupTracks, and output tracks that do not belong to any group.
GetRootTracks()
IEnumerable<TrackAsset> UnityEngine.Timeline.TimelineAsset.GetRootTracks ()
Get an enumerable list of all root tracks.
Returns
An IEnumerable of all root tracks.
A root track refers to all tracks that occur at the root of the timeline. These are the outmost level GroupTracks, and output tracks that do not belong to any group.
Property Documentation
clipCaps
ClipCaps UnityEngine.Timeline.TimelineAsset.clipCaps get
duration
override double UnityEngine.Timeline.TimelineAsset.duration get
The length, in seconds, of the timeline
Referenced by UnityEditor.Timeline.CurveDataSource.GetBackgroundRect(), UnityEditor.Timeline.ActivationTrackEditor.OnCreate(), and UnityEditor.Timeline.SnapEngine.SnapEngine().
durationMode
DurationMode UnityEngine.Timeline.TimelineAsset.durationMode get set
The mode used to determine the duration of the Timeline
Referenced by UnityEditor.Timeline.SnapEngine.SnapEngine().
editorSettings
EditorSettings UnityEngine.Timeline.TimelineAsset.editorSettings get
Settings used by timeline for editing purposes
fixedDuration
double UnityEngine.Timeline.TimelineAsset.fixedDuration get set
The length of the timeline when durationMode is set to fixed length.
markerTrack
MarkerTrack UnityEngine.Timeline.TimelineAsset.markerTrack get
Gets the marker track for this TimelineAsset.
Returns
Returns the marker track.
Use TrackAsset.GetMarkers to get a list of the markers on the returned track.
Referenced by UnityEditor.Timeline.FrameAllAction.Execute(), UnityEditor.TimelineDragging.HandleClipPaneObjectDragAndDrop(), and UnityEditor.Timeline.ToggleMuteMarkersOnTimeline.IsChecked().
outputs
override IEnumerable<PlayableBinding> UnityEngine.Timeline.TimelineAsset.outputs get
A description of the PlayableOutputs that will be created by the timeline when instantiated.
Each track will create an PlayableOutput
outputTrackCount
int UnityEngine.Timeline.TimelineAsset.outputTrackCount get
Returns the the number of output tracks in the Timeline.
An output track is a track the generates a PlayableOutput. In general, an output track is any track that is not a GroupTrack, a subtrack, or override track.
rootTrackCount
int UnityEngine.Timeline.TimelineAsset.rootTrackCount get
Returns the number of tracks at the root level of the timeline.
A root track refers to all tracks that occur at the root of the timeline. These are the outmost level GroupTracks, and output tracks that do not belong to any group
The documentation for this class was generated from the following files:
Library/PackageCache/com.unity.timeline@1.3.6/Runtime/AssetUpgrade/TimelineUpgrade.cs
Library/PackageCache/com.unity.timeline@1.3.6/Runtime/TimelineAsset.cs
Library/PackageCache/com.unity.timeline@1.3.6/Runtime/TimelineAsset_CreateRemove.cs