VirtualTours: UnityEditor.Timeline.TimelineTrackGUI Class Reference
UnityEditor.Timeline.TimelineTrackGUI Class Reference
Public Member Functions
TimelineTrackGUI (TreeViewController tv, TimelineTreeViewGUI w, int id, int depth, TreeViewItem parent, string displayName, TrackAsset sequenceActor)
override float GetVerticalSpacingBetweenTracks ()
override void Draw (Rect headerRect, Rect contentRect, WindowState state)
override float GetHeight (WindowState state)
override void OnGraphRebuilt ()
Public Member Functions inherited from UnityEditor.Timeline.TimelineGroupGUI
Rect ToWindowSpace (Rect localRect)
TimelineGroupGUI (TreeViewController treeview, TimelineTreeViewGUI treeviewGUI, int id, int depth, TreeViewItem parent, string displayName, TrackAsset trackAsset, bool isRoot)
void SetExpanded (bool expanded)
Public Member Functions inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
void DrawInsertionMarkers (Rect rowRectWithIndent)
void ClearDrawFlags ()
Public Member Functions inherited from UnityEditor.Timeline.IRowGUI
Rect ToWindowSpace (Rect treeViewRect)
Properties
override bool expandable [get]
ClipCurveEditor clipCurveEditor [get]
bool inlineCurvesSelected [get, set]
bool locked [get]
bool showMarkers [get]
bool muted [get]
List< TimelineClipGUI >? clips [get]
int heightExtension [get, set]
Properties inherited from UnityEditor.Timeline.TimelineGroupGUI
override Rect boundingRect [get]
override bool expandable [get]
Rect expandedRect [get, set]
Rect rowRect [get, set]
Rect dropRect [get, set]
Properties inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
Vector2 treeViewToWindowTransformation [get, set]
bool isExpanded [get, set]
bool isDropTarget [protected get, set]
TrackAsset track [get]
TimelineWindow TimelineWindow [get]
TrackDrawer drawer [get]
bool visibleRow [get, set]
bool visibleExpanded [get, set]
bool drawInsertionMarkerBefore [get, set]
bool drawInsertionMarkerAfter [get, set]
abstract Rect boundingRect [get]
abstract bool expandable [get]
Properties inherited from UnityEditor.Timeline.IBounds
Rect boundingRect [get]
Properties inherited from UnityEditor.Timeline.IClipCurveEditorOwner
ClipCurveEditor clipCurveEditor [get]
bool inlineCurvesSelected [get, set]
bool showLoops [get]
TrackAsset owner [get]
Properties inherited from UnityEditor.Timeline.IRowGUI
TrackAsset asset [get]
Rect boundingRect [get]
bool locked [get]
bool showMarkers [get]
bool muted [get]
Additional Inherited Members
Static Public Member Functions inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
static TimelineTrackBaseGUI FindGUITrack (TrackAsset track)
Protected Member Functions inherited from UnityEditor.Timeline.TimelineGroupGUI
bool IsSubTrack ()
TrackAsset ParentTrack ()
Protected Member Functions inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
TimelineTrackBaseGUI (int id, int depth, TreeViewItem parent, string displayName, TrackAsset trackAsset, TreeViewController tv, TimelineTreeViewGUI tvgui)
void DrawTrackState (Rect trackRect, Rect expandedRect, TrackAsset track)
float DrawMuteButton (Rect rect, WindowState state)
float DrawLockButton (Rect rect, WindowState state)
Protected Attributes inherited from UnityEditor.Timeline.TimelineGroupGUI
DirectorStyles m_Styles
Rect m_TreeViewRect = new Rect(0, 0, 0, 0)
GUIContent m_ProblemIcon = new GUIContent()
Protected Attributes inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
bool m_IsRoot = false
Static Protected Attributes inherited from UnityEditor.Timeline.TimelineTrackBaseGUI
const float k_ButtonSize = 16.0f
Constructor & Destructor Documentation
TimelineTrackGUI()
UnityEditor.Timeline.TimelineTrackGUI.TimelineTrackGUI (TreeViewController tv, TimelineTreeViewGUI w, int id, int depth, TreeViewItem parent, string displayName, TrackAsset sequenceActor)
References UnityEditor.Timeline.TrackDrawOptions.errorText, UnityEditor.Timeline.CustomTimelineEditorCache.GetDefaultTrackEditor(), UnityEditor.Timeline.CustomTimelineEditorCache.GetTrackEditor(), UnityEditor.Timeline.TrackEditor.GetTrackOptions(), UnityEditor.Timeline.TimelineTrackGUI.heightExtension, UnityEditor.Timeline.TimelineGroupGUI.IsSubTrack(), UnityEngine.Timeline.TrackAsset.outputs, UnityEditor.Timeline.TimelineTreeViewGUI.TimelineWindow, and UnityEditor.Timeline.TimelineTrackBaseGUI.track.
Member Function Documentation
Draw()
override void UnityEditor.Timeline.TimelineTrackGUI.Draw (Rect headerRect, Rect contentRect, WindowState state) virtual
Reimplemented from UnityEditor.Timeline.TimelineGroupGUI.
References UnityEditor.Timeline.DirectorStyles.autoKey, UnityEditor.Timeline.TrackItemsDrawer.Draw(), UnityEditor.Timeline.TimelineTrackBaseGUI.drawer, UnityEditor.Timeline.TrackDrawer.DrawTrack(), UnityEditor.Timeline.TimelineTrackBaseGUI.DrawTrackState(), UnityEditor.Timeline.DirectorStyles.GetBackgroundImage(), UnityEditor.Timeline.WindowState.GetWindow(), UnityEditor.Timeline.DirectorStyles.Instance, UnityEditor.Timeline.TimelineTrackBaseGUI.isExpanded, UnityEditor.Timeline.TimelineGroupGUI.m_TreeViewRect, UnityEditor.Timeline.WindowState.timeAreaShownRange, and UnityEditor.Timeline.TimelineTrackBaseGUI.track.
GetHeight()
override float UnityEditor.Timeline.TimelineTrackGUI.GetHeight (WindowState state) virtual
Reimplemented from UnityEditor.Timeline.TimelineGroupGUI.
GetVerticalSpacingBetweenTracks()
override float UnityEditor.Timeline.TimelineTrackGUI.GetVerticalSpacingBetweenTracks () virtual
Reimplemented from UnityEditor.Timeline.TimelineTrackBaseGUI.
References UnityEngine.Timeline.TrackAsset.isSubTrack, and UnityEditor.Timeline.TimelineTrackBaseGUI.track.
OnGraphRebuilt()
override void UnityEditor.Timeline.TimelineTrackGUI.OnGraphRebuilt () virtual
Reimplemented from UnityEditor.Timeline.TimelineGroupGUI.
Property Documentation
clipCurveEditor
ClipCurveEditor UnityEditor.Timeline.TimelineTrackGUI.clipCurveEditor get
clips
List<TimelineClipGUI>? UnityEditor.Timeline.TimelineTrackGUI.clips get
expandable
override bool UnityEditor.Timeline.TimelineTrackGUI.expandable get
heightExtension
int UnityEditor.Timeline.TimelineTrackGUI.heightExtension get set
Referenced by UnityEditor.Timeline.TimelineTrackGUI.TimelineTrackGUI().
inlineCurvesSelected
bool UnityEditor.Timeline.TimelineTrackGUI.inlineCurvesSelected get set
locked
bool UnityEditor.Timeline.TimelineTrackGUI.locked get
muted
bool UnityEditor.Timeline.TimelineTrackGUI.muted get
showMarkers
bool UnityEditor.Timeline.TimelineTrackGUI.showMarkers get
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/TrackGui/TimelineTrackGUI.cs