VirtualTours: UnityEditor.Timeline.DeleteTracks Class Reference
UnityEditor.Timeline.DeleteTracks Class Reference
Public Member Functions
override bool Execute (WindowState state, TrackAsset[] tracks)
Static Public Member Functions
static void Do (TimelineAsset timeline, TrackAsset track)
Static Public Member Functions inherited from UnityEditor.Timeline.TrackAction
static void Invoke< T > (WindowState state, TrackAsset[] tracks)
static void GetMenuEntries (WindowState state, Vector2? mousePos, TrackAsset[] tracks, List< MenuActionItem > items)
static bool HandleShortcut (WindowState state, Event evt, TrackAsset[] tracks)
Static Public Member Functions inherited from UnityEditor.Timeline.MenuItemActionBase
static IEnumerable< Type > GetActionsOfType (Type actionType)
static ShortcutAttribute GetShortcutAttributeForAction (MenuItemActionBase action)
static void BuildMenu (GenericMenu menu, List< MenuActionItem > items)
static ActiveInModeAttribute GetActiveInModeAttribute (MenuItemActionBase action)
static bool IsActionActiveInMode (MenuItemActionBase action, TimelineModes mode)
Additional Inherited Members
Protected Member Functions inherited from UnityEditor.Timeline.TrackAction
virtual MenuActionDisplayState GetDisplayState (WindowState state, TrackAsset[] tracks)
virtual bool IsChecked (WindowState state, TrackAsset[] tracks)
virtual string GetDisplayName (TrackAsset[] tracks)
Static Protected Attributes inherited from UnityEditor.Timeline.MenuItemActionBase
static bool s_ShowActionTriggeredByShortcut = false
Properties inherited from UnityEditor.Timeline.MenuItemActionBase
Vector2? mousePosition [get, set]
int priority [get]
string category [get]
string menuName [get]
string? shortCut [get]
bool showInMenu [get]
Member Function Documentation
Do()
static void UnityEditor.Timeline.DeleteTracks.Do (TimelineAsset timeline, TrackAsset track) static
Referenced by UnityEditor.Timeline.DeleteTracks.Execute().
Execute()
override bool UnityEditor.Timeline.DeleteTracks.Execute (WindowState state, TrackAsset[] tracks) virtual
Implements UnityEditor.Timeline.TrackAction.
References UnityEditor.Timeline.ISequenceState.asset, UnityEditor.Timeline.DeleteTracks.Do(), UnityEditor.Timeline.WindowState.editSequence, UnityEditor.Timeline.WindowState.previewMode, UnityEditor.Timeline.WindowState.Refresh(), and UnityEditor.Timeline.TimelineAnimationUtilities.UnlinkAnimationWindowFromTracks().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Actions/TrackActions.cs