VirtualTours: UnityEditor.Timeline.ClipEditor Class Reference
UnityEditor.Timeline.ClipEditor Class Reference
Use this class to customize clip types in the TimelineEditor.
Public Member Functions
ClipEditor ()
Default constructor
virtual ClipDrawOptions GetClipOptions (TimelineClip clip)
Implement this method to override the default options for drawing a clip.
virtual void DrawBackground (TimelineClip clip, ClipBackgroundRegion region)
Override this method to draw a background for a clip .
virtual void OnCreate (TimelineClip clip, TrackAsset track, TimelineClip clonedFrom)
Called when a clip is created.
string GetErrorText (TimelineClip clip)
Gets the error text for the specified clip.
Color GetDefaultHighlightColor (TimelineClip clip)
The color drawn under the clip. By default, the color is the same as the track color.
virtual void OnClipChanged (TimelineClip clip)
Called when a clip is changed by the Editor.
virtual void GetSubTimelines (TimelineClip clip, PlayableDirector director, List< PlayableDirector > subTimelines)
Gets the sub-timelines for a specific clip. Implement this method if your clip supports playing nested timelines.
Detailed Description
Use this class to customize clip types in the TimelineEditor.
Constructor & Destructor Documentation
ClipEditor()
UnityEditor.Timeline.ClipEditor.ClipEditor ()
Default constructor
References UnityEditor.Timeline.ClipEditor.GetSubTimelines().
Member Function Documentation
DrawBackground()
virtual void UnityEditor.Timeline.ClipEditor.DrawBackground (TimelineClip clip, ClipBackgroundRegion region) virtual
Override this method to draw a background for a clip .
Parameters
clip The clip being drawn.
region The on-screen area where the clip is drawn.
Reimplemented in UnityEditor.Timeline.AudioPlayableAssetEditor.
GetClipOptions()
virtual ClipDrawOptions UnityEditor.Timeline.ClipEditor.GetClipOptions (TimelineClip clip) virtual
Implement this method to override the default options for drawing a clip.
Parameters
clip The clip being drawn.
Returns
The options for drawing a clip.
Reimplemented in UnityEditor.Timeline.ControlPlayableAssetEditor, UnityEditor.Timeline.AudioPlayableAssetEditor, and UnityEditor.Timeline.AnimationPlayableAssetEditor.
References UnityEditor.Timeline.ClipEditor.GetDefaultHighlightColor(), and UnityEditor.Timeline.ClipEditor.GetErrorText().
GetDefaultHighlightColor()
Color UnityEditor.Timeline.ClipEditor.GetDefaultHighlightColor (TimelineClip clip)
The color drawn under the clip. By default, the color is the same as the track color.
Parameters
clip The clip being drawn.
Returns
Returns the highlight color of the clip being drawn.
References UnityEngine.Timeline.TimelineClip.parentTrack.
Referenced by UnityEditor.Timeline.ClipEditor.GetClipOptions().
GetErrorText()
string UnityEditor.Timeline.ClipEditor.GetErrorText (TimelineClip clip)
Gets the error text for the specified clip.
Parameters
clip The clip being drawn.
Returns
Returns the error text to be displayed as the tool tip for the clip. If there is no error to be displayed, this method returns string.Empty.
References UnityEngine.Timeline.TimelineClip.asset.
Referenced by UnityEditor.Timeline.ClipEditor.GetClipOptions().
GetSubTimelines()
virtual void UnityEditor.Timeline.ClipEditor.GetSubTimelines (TimelineClip clip, PlayableDirector director, List< PlayableDirector > subTimelines) virtual
Gets the sub-timelines for a specific clip. Implement this method if your clip supports playing nested timelines.
Parameters
clip The clip with the ControlPlayableAsset.
director The playable director driving the Timeline Clip. This may not be the same as TimelineEditor.inspectedDirector.
subTimelines Specify the sub-timelines to control.
Reimplemented in UnityEditor.Timeline.ControlPlayableAssetEditor.
Referenced by UnityEditor.Timeline.ClipEditor.ClipEditor().
OnClipChanged()
virtual void UnityEditor.Timeline.ClipEditor.OnClipChanged (TimelineClip clip) virtual
Called when a clip is changed by the Editor.
Parameters
clip The clip that changed.
OnCreate()
virtual void UnityEditor.Timeline.ClipEditor.OnCreate (TimelineClip clip, TrackAsset track, TimelineClip clonedFrom) virtual
Called when a clip is created.
Parameters
clip The newly created clip.
track The track that the clip is assigned to.
clonedFrom The source that the clip was copied from. This can be set to null if the clip is not a copy.
The callback occurs before the clip is assigned to the track.
Reimplemented in UnityEditor.Timeline.ControlPlayableAssetEditor, and UnityEditor.Timeline.AnimationPlayableAssetEditor.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/CustomEditors/ClipEditor.cs