VirtualTours: UnityEditor.Timeline.EditClipInAnimationWindow Class Reference
UnityEditor.Timeline.EditClipInAnimationWindow Class Reference
Public Member Functions
override bool Execute (WindowState state, TimelineClip[] clips)
Protected Member Functions
override MenuActionDisplayState GetDisplayState (WindowState state, TimelineClip[] clips)
Member Function Documentation
Execute()
override bool UnityEditor.Timeline.EditClipInAnimationWindow.Execute (WindowState state, TimelineClip[] clips)
References UnityEngine.Timeline.TimelineClip.animationClip, UnityEditor.Timeline.TimelineAnimationUtilities.CreateTimeController(), UnityEditor.Timeline.TimelineAnimationUtilities.EditAnimationClipWithTimeController(), and UnityEditor.Timeline.WindowState.GetSceneReference().
GetDisplayState()
override MenuActionDisplayState UnityEditor.Timeline.EditClipInAnimationWindow.GetDisplayState (WindowState state, TimelineClip[] clips) protected
References UnityEngine.Timeline.TimelineClip.animationClip.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Actions/ClipsActions.cs