VirtualTours: UnityEditor.Timeline.BasePropertyKeyDataSource Class Reference
UnityEditor.Timeline.BasePropertyKeyDataSource Class Reference
Public Member Functions
virtual float[] GetKeys ()
virtual Dictionary< float, string > GetDescriptions ()
Protected Member Functions
virtual float TransformKeyTime (float keyTime)
Properties
abstract AnimationClip animationClip [get]
Member Function Documentation
GetDescriptions()
virtual Dictionary<float, string> UnityEditor.Timeline.BasePropertyKeyDataSource.GetDescriptions () virtual
Implements UnityEditor.Timeline.IPropertyKeyDataSource.
References UnityEditor.Timeline.BasePropertyKeyDataSource.animationClip, UnityEditor.Timeline.AnimationClipCurveCache.GetCurveInfo(), UnityEditor.Timeline.AnimationClipCurveCache.Instance, and UnityEditor.Timeline.BasePropertyKeyDataSource.TransformKeyTime().
GetKeys()
virtual float [] UnityEditor.Timeline.BasePropertyKeyDataSource.GetKeys () virtual
Implements UnityEditor.Timeline.IPropertyKeyDataSource.
References UnityEditor.Timeline.BasePropertyKeyDataSource.animationClip, UnityEditor.Timeline.AnimationClipCurveCache.GetCurveInfo(), UnityEditor.Timeline.AnimationClipCurveCache.Instance, UnityEditor.Timeline.AnimationClipCurveInfo.keyTimes, and UnityEditor.Timeline.BasePropertyKeyDataSource.TransformKeyTime().
TransformKeyTime()
virtual float UnityEditor.Timeline.BasePropertyKeyDataSource.TransformKeyTime (float keyTime) protected virtual
Reimplemented in UnityEditor.Timeline.AnimationTrackKeyDataSource.
Referenced by UnityEditor.Timeline.BasePropertyKeyDataSource.GetDescriptions(), and UnityEditor.Timeline.BasePropertyKeyDataSource.GetKeys().
Property Documentation
animationClip
abstract AnimationClip UnityEditor.Timeline.BasePropertyKeyDataSource.animationClip get protected
Referenced by UnityEditor.Timeline.BasePropertyKeyDataSource.GetDescriptions(), and UnityEditor.Timeline.BasePropertyKeyDataSource.GetKeys().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/IPropertyKeyDataSource.cs