VirtualTours: UnityEditor.Timeline.TimelineMarkerGUI Class Reference
UnityEditor.Timeline.TimelineMarkerGUI Class Reference
Public Member Functions
override void Select ()
override bool IsSelected ()
override void Deselect ()
TimelineMarkerGUI (IMarker theMarker, IRowGUI parent, IZOrderProvider provider)
override void Draw (Rect trackRect, bool trackRectChanged, WindowState state)
void QueueOverlay (Rect rect, bool isSelected, bool isCollapsed)
override void StartDrag ()
override Rect RectToTimeline (Rect trackRect, WindowState state)
IEnumerable< Edge > SnappableEdgesFor (IAttractable attractable, ManipulateEdges manipulateEdges)
bool ShouldSnapTo (ISnappable snappable)
Public Member Functions inherited from UnityEditor.Timeline.TimelineItemGUI
virtual void StopDrag ()
Properties
double time [get]
override double start [get]
override double end [get]
override ITimelineItem item [get]
Properties inherited from UnityEditor.Timeline.TimelineItemGUI
abstract ITimelineItem item [get]
abstract double start [get]
abstract double end [get]
LayerZOrder zOrder [get, set]
bool visible [get, set]
bool isInvalid [get, set]
IRowGUI parent [get]
Rect rect [get]
Rect treeViewRect [get, protected set]
Properties inherited from UnityEditor.Timeline.ILayerable
LayerZOrder zOrder [get]
Properties inherited from UnityEditor.Timeline.IAttractable
double start [get]
double end [get]
Events
Action onStartDrag
Additional Inherited Members
Protected Member Functions inherited from UnityEditor.Timeline.TimelineItemGUI
TimelineItemGUI (IRowGUI parent)
Protected Attributes inherited from UnityEditor.Timeline.TimelineItemGUI
readonly DirectorStyles m_Styles
Constructor & Destructor Documentation
TimelineMarkerGUI()
UnityEditor.Timeline.TimelineMarkerGUI.TimelineMarkerGUI (IMarker theMarker, IRowGUI parent, IZOrderProvider provider)
References UnityEditor.Timeline.CustomTimelineEditorCache.GetMarkerEditor(), UnityEditor.Timeline.IZOrderProvider.Next(), and UnityEditor.Timeline.TimelineItemGUI.zOrder.
Referenced by UnityEditor.Timeline.TimelineMarkerGUI.SnappableEdgesFor().
Member Function Documentation
Deselect()
override void UnityEditor.Timeline.TimelineMarkerGUI.Deselect () virtual
Reimplemented from UnityEditor.Timeline.TimelineItemGUI.
Referenced by UnityEditor.Timeline.TimelineMarkerClusterGUI.CycleMarkers().
Draw()
override void UnityEditor.Timeline.TimelineMarkerGUI.Draw (Rect trackRect, bool trackRectChanged, WindowState state) virtual
Implements UnityEditor.Timeline.TimelineItemGUI.
References UnityEditor.Timeline.SpacePartitioner.AddBounds(), UnityEditor.Timeline.IRowGUI.locked, UnityEditor.Timeline.TimelineItemGUI.parent, UnityEditor.Timeline.TimelineMarkerGUI.QueueOverlay(), UnityEditor.Timeline.TimelineItemGUI.rect, UnityEditor.Timeline.IRowGUI.showMarkers, UnityEditor.Timeline.WindowState.spacePartitioner, and UnityEditor.Timeline.TimelineItemGUI.treeViewRect.
Referenced by UnityEditor.Timeline.TimelineMarkerClusterGUI.Draw().
IsSelected()
override bool UnityEditor.Timeline.TimelineMarkerGUI.IsSelected () virtual
Reimplemented from UnityEditor.Timeline.TimelineItemGUI.
Referenced by UnityEditor.Timeline.TimelineMarkerClusterGUI.CanCycleMarkers().
QueueOverlay()
void UnityEditor.Timeline.TimelineMarkerGUI.QueueOverlay (Rect rect, bool isSelected, bool isCollapsed)
References UnityEditor.Timeline.TimelineWindow.AddUserOverlay(), UnityEditor.Timeline.TimelineWindow.instance, and UnityEditor.Timeline.TimelineItemGUI.rect.
Referenced by UnityEditor.Timeline.TimelineMarkerGUI.Draw().
RectToTimeline()
override Rect UnityEditor.Timeline.TimelineMarkerGUI.RectToTimeline (Rect trackRect, WindowState state) virtual
Implements UnityEditor.Timeline.TimelineItemGUI.
References UnityEngine.Timeline.IMarker.time, UnityEditor.Timeline.WindowState.timeAreaScale, and UnityEditor.Timeline.WindowState.timeAreaTranslation.
Referenced by UnityEditor.Timeline.TimelineMarkerClusterGUI.RectToTimeline().
Select()
override void UnityEditor.Timeline.TimelineMarkerGUI.Select () virtual
Reimplemented from UnityEditor.Timeline.TimelineItemGUI.
References UnityEditor.Timeline.IRowGUI.asset, UnityEditor.Timeline.IZOrderProvider.Next(), UnityEditor.Timeline.TimelineItemGUI.parent, and UnityEditor.Timeline.TimelineItemGUI.zOrder.
ShouldSnapTo()
bool UnityEditor.Timeline.TimelineMarkerGUI.ShouldSnapTo (ISnappable snappable)
Implements UnityEditor.Timeline.IAttractable.
SnappableEdgesFor()
IEnumerable<Edge> UnityEditor.Timeline.TimelineMarkerGUI.SnappableEdgesFor (IAttractable attractable, ManipulateEdges manipulateEdges)
Implements UnityEditor.Timeline.ISnappable.
References UnityEditor.Timeline.TimelineItemGUI.parent, UnityEditor.Timeline.TimelineMarkerGUI.time, and UnityEditor.Timeline.TimelineMarkerGUI.TimelineMarkerGUI().
StartDrag()
override void UnityEditor.Timeline.TimelineMarkerGUI.StartDrag () virtual
Reimplemented from UnityEditor.Timeline.TimelineItemGUI.
References UnityEditor.Timeline.TimelineMarkerGUI.onStartDrag.
Property Documentation
end
override double UnityEditor.Timeline.TimelineMarkerGUI.end get
item
override ITimelineItem UnityEditor.Timeline.TimelineMarkerGUI.item get
start
override double UnityEditor.Timeline.TimelineMarkerGUI.start get
time
double UnityEditor.Timeline.TimelineMarkerGUI.time get
Referenced by UnityEditor.Timeline.TimelineMarkerGUI.SnappableEdgesFor().
Event Documentation
onStartDrag
Action UnityEditor.Timeline.TimelineMarkerGUI.onStartDrag
Referenced by UnityEditor.Timeline.TimelineMarkerClusterGUI.CycleTop(), UnityEditor.Timeline.TimelineMarkerGUI.StartDrag(), and UnityEditor.Timeline.TimelineMarkerClusterGUI.TimelineMarkerClusterGUI().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/ItemGui/TimelineMarkerGUI.cs