VirtualTours: UnityEditor.Timeline.TrackEditor Class Reference
UnityEditor.Timeline.TrackEditor Class Reference
Use this class to customize track types in the TimelineEditor.
Public Member Functions
virtual TrackDrawOptions GetTrackOptions (TrackAsset track, UnityEngine.Object binding)
Implement this method to override the default options for drawing a track.
string GetErrorText (TrackAsset track, UnityEngine.Object boundObject, TrackBindingErrors detectErrors)
Gets the error text for the specified track.
Color GetTrackColor (TrackAsset track)
Gets the color information of a track.
System.Type GetBindingType (TrackAsset track)
Gets the binding type for a track.
virtual void OnCreate (TrackAsset track, TrackAsset copiedFrom)
Callback for when a track is created.
virtual void OnTrackChanged (TrackAsset track)
Callback for when a track is changed.
Static Public Attributes
static readonly float DefaultTrackHeight = 30.0f
The default height of a track.
static readonly float MinimumTrackHeight = 10.0f
The minimum unscaled height of a track.
static readonly float MaximumTrackHeight = 256.0f
The maximum height of a track.
Detailed Description
Use this class to customize track types in the TimelineEditor.
Member Function Documentation
GetBindingType()
System.Type UnityEditor.Timeline.TrackEditor.GetBindingType (TrackAsset track)
Gets the binding type for a track.
Parameters
track The track to retrieve the binding type from.
Returns
Returns the binding type for the specified track. Returns null if the track does not have binding.
References UnityEngine.Timeline.TrackAsset.outputs.
Referenced by UnityEditor.Timeline.TrackEditor.GetErrorText().
GetErrorText()
string UnityEditor.Timeline.TrackEditor.GetErrorText (TrackAsset track, UnityEngine.Object boundObject, TrackBindingErrors detectErrors)
Gets the error text for the specified track.
Parameters
track The track to retrieve options for.
boundObject The binding for the track.
detectErrors The errors to check for.
Returns
An error to be displayed on the track, or string.Empty if there is no error.
References UnityEditor.Timeline.GameObject, and UnityEditor.Timeline.TrackEditor.GetBindingType().
Referenced by UnityEditor.Timeline.TrackEditor.GetTrackOptions().
GetTrackColor()
Color UnityEditor.Timeline.TrackEditor.GetTrackColor (TrackAsset track)
Gets the color information of a track.
Parameters
track
Returns
Returns the color for the specified track.
Referenced by UnityEditor.Timeline.TrackEditor.GetTrackOptions().
GetTrackOptions()
virtual TrackDrawOptions UnityEditor.Timeline.TrackEditor.GetTrackOptions (TrackAsset track, UnityEngine.Object binding) virtual
Implement this method to override the default options for drawing a track.
Parameters
track The track from which track options are retrieved.
binding The binding for the track.
Returns
The options for drawing the track.
References UnityEditor.Timeline.TrackEditor.DefaultTrackHeight, UnityEditor.Timeline.TrackEditor.GetErrorText(), and UnityEditor.Timeline.TrackEditor.GetTrackColor().
Referenced by UnityEditor.Timeline.TimelineTrackGUI.TimelineTrackGUI().
OnCreate()
virtual void UnityEditor.Timeline.TrackEditor.OnCreate (TrackAsset track, TrackAsset copiedFrom) virtual
Callback for when a track is created.
Parameters
track The track that is created.
copiedFrom The source that the track is copied from. This can be set to null if the track is not a copy.
Reimplemented in UnityEditor.Timeline.ActivationTrackEditor.
OnTrackChanged()
virtual void UnityEditor.Timeline.TrackEditor.OnTrackChanged (TrackAsset track) virtual
Callback for when a track is changed.
Parameters
track The track that is changed.
Member Data Documentation
DefaultTrackHeight
readonly float UnityEditor.Timeline.TrackEditor.DefaultTrackHeight = 30.0f static
The default height of a track.
Referenced by UnityEditor.Timeline.TimelineGroupGUI.GetHeight(), UnityEditor.Timeline.TimelineTreeView.GetSizeOfRow(), and UnityEditor.Timeline.TrackEditor.GetTrackOptions().
MaximumTrackHeight
readonly float UnityEditor.Timeline.TrackEditor.MaximumTrackHeight = 256.0f static
The maximum height of a track.
MinimumTrackHeight
readonly float UnityEditor.Timeline.TrackEditor.MinimumTrackHeight = 10.0f static
The minimum unscaled height of a track.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/CustomEditors/TrackEditor.cs