VirtualTours: VSCodeEditor.ProjectGeneration Class Reference
VSCodeEditor.ProjectGeneration Class Reference
Public Member Functions
void GenerateAll (bool generateAll)
ProjectGeneration (string tempDirectory)
ProjectGeneration (string tempDirectory, IAssemblyNameProvider assemblyNameProvider, IFileIO fileIO, IGUIDGenerator guidGenerator)
bool SyncIfNeeded (List< string > affectedFiles, string[] reimportedFiles)
Syncs the scripting solution if any affected files are relevant.
void Sync ()
bool SolutionExists ()
void GenerateAndWriteSolutionAndProjects ()
string ProjectFile (Assembly assembly)
string SolutionFile ()
Static Public Attributes
static readonly string MSBuildNamespaceUri = "http://schemas.microsoft.com/developer/msbuild/2003"
Properties
string ProjectDirectory [get]
Properties inherited from VSCodeEditor.IGenerator
string ProjectDirectory [get]
IAssemblyNameProvider AssemblyNameProvider [get]
Constructor & Destructor Documentation
ProjectGeneration() [1/2]
VSCodeEditor.ProjectGeneration.ProjectGeneration (string tempDirectory)
ProjectGeneration() [2/2]
VSCodeEditor.ProjectGeneration.ProjectGeneration (string tempDirectory, IAssemblyNameProvider assemblyNameProvider, IFileIO fileIO, IGUIDGenerator guidGenerator)
References VSCodeEditor.ProjectGeneration.ProjectDirectory.
Member Function Documentation
GenerateAll()
void VSCodeEditor.ProjectGeneration.GenerateAll (bool generateAll)
Implements VSCodeEditor.IGenerator.
References VSCodeEditor.IAssemblyNameProvider.ToggleProjectGeneration().
GenerateAndWriteSolutionAndProjects()
void VSCodeEditor.ProjectGeneration.GenerateAndWriteSolutionAndProjects ()
Referenced by VSCodeEditor.ProjectGeneration.Sync().
ProjectFile()
string VSCodeEditor.ProjectGeneration.ProjectFile (Assembly assembly)
References VSCodeEditor.ProjectGeneration.ProjectDirectory.
SolutionExists()
bool VSCodeEditor.ProjectGeneration.SolutionExists ()
Implements VSCodeEditor.IGenerator.
References VSCodeEditor.ProjectGeneration.SolutionFile().
Referenced by VSCodeEditor.ProjectGeneration.SyncIfNeeded().
SolutionFile()
string VSCodeEditor.ProjectGeneration.SolutionFile ()
Implements VSCodeEditor.IGenerator.
References VSCodeEditor.ProjectGeneration.ProjectDirectory.
Referenced by VSCodeEditor.ProjectGeneration.SolutionExists().
Sync()
void VSCodeEditor.ProjectGeneration.Sync ()
Implements VSCodeEditor.IGenerator.
References VSCodeEditor.ProjectGeneration.GenerateAndWriteSolutionAndProjects().
SyncIfNeeded()
bool VSCodeEditor.ProjectGeneration.SyncIfNeeded (List< string > affectedFiles, string[] reimportedFiles)
Syncs the scripting solution if any affected files are relevant.
Returns
Whether the solution was synced.
Parameters
affectedFiles A set of files whose status has changed
reimportedFiles A set of files that got reimported
Implements VSCodeEditor.IGenerator.
References VSCodeEditor.ProjectGeneration.SolutionExists().
Member Data Documentation
MSBuildNamespaceUri
readonly string VSCodeEditor.ProjectGeneration.MSBuildNamespaceUri = "http://schemas.microsoft.com/developer/msbuild/2003" static
Property Documentation
ProjectDirectory
string VSCodeEditor.ProjectGeneration.ProjectDirectory get
Referenced by VSCodeEditor.ProjectGeneration.ProjectFile(), VSCodeEditor.ProjectGeneration.ProjectGeneration(), and VSCodeEditor.ProjectGeneration.SolutionFile().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.ide.vscode@1.2.2/Editor/ProjectGeneration/ProjectGeneration.cs