VirtualTours: UnityEditor.Timeline.TimelineRecordingContextualResponder Class Reference
UnityEditor.Timeline.TimelineRecordingContextualResponder Class Reference
Public Member Functions
TimelineRecordingContextualResponder (WindowState _state)
bool HasAnyCandidates ()
bool HasAnyCurves ()
void AddCandidateKeys ()
void AddAnimatedKeys ()
bool IsAnimatable (PropertyModification[] modifications)
bool IsEditable (Object targetObject)
bool KeyExists (PropertyModification[] modifications)
bool CandidateExists (PropertyModification[] modifications)
bool CurveExists (PropertyModification[] modifications)
void AddKey (PropertyModification[] modifications)
void RemoveKey (PropertyModification[] modifications)
void RemoveCurve (PropertyModification[] modifications)
void GoToNextKeyframe (PropertyModification[] modifications)
void GoToPreviousKeyframe (PropertyModification[] modifications)
Properties
WindowState state [get, set]
Constructor & Destructor Documentation
TimelineRecordingContextualResponder()
UnityEditor.Timeline.TimelineRecordingContextualResponder.TimelineRecordingContextualResponder (WindowState _state)
References UnityEditor.Timeline.TimelineRecordingContextualResponder.state.
Member Function Documentation
AddAnimatedKeys()
void UnityEditor.Timeline.TimelineRecordingContextualResponder.AddAnimatedKeys ()
AddCandidateKeys()
void UnityEditor.Timeline.TimelineRecordingContextualResponder.AddCandidateKeys ()
AddKey()
void UnityEditor.Timeline.TimelineRecordingContextualResponder.AddKey (PropertyModification[] modifications)
References UnityEditor.Timeline.WindowState.Refresh(), and UnityEditor.Timeline.TimelineRecordingContextualResponder.state.
CandidateExists()
bool UnityEditor.Timeline.TimelineRecordingContextualResponder.CandidateExists (PropertyModification[] modifications)
CurveExists()
bool UnityEditor.Timeline.TimelineRecordingContextualResponder.CurveExists (PropertyModification[] modifications)
References UnityEditor.Timeline.TimelineRecordingContextualResponder.state.
GoToNextKeyframe()
void UnityEditor.Timeline.TimelineRecordingContextualResponder.GoToNextKeyframe (PropertyModification[] modifications)
References UnityEditor.Timeline.WindowState.Refresh(), and UnityEditor.Timeline.TimelineRecordingContextualResponder.state.
GoToPreviousKeyframe()
void UnityEditor.Timeline.TimelineRecordingContextualResponder.GoToPreviousKeyframe (PropertyModification[] modifications)
References UnityEditor.Timeline.WindowState.Refresh(), and UnityEditor.Timeline.TimelineRecordingContextualResponder.state.
HasAnyCandidates()
bool UnityEditor.Timeline.TimelineRecordingContextualResponder.HasAnyCandidates ()
HasAnyCurves()
bool UnityEditor.Timeline.TimelineRecordingContextualResponder.HasAnyCurves ()
IsAnimatable()
bool UnityEditor.Timeline.TimelineRecordingContextualResponder.IsAnimatable (PropertyModification[] modifications)
References UnityEditor.Timeline.ISequenceState.asset, UnityEditor.Timeline.WindowState.editSequence, and UnityEditor.Timeline.TimelineRecordingContextualResponder.state.
IsEditable()
bool UnityEditor.Timeline.TimelineRecordingContextualResponder.IsEditable (Object targetObject)
KeyExists()
bool UnityEditor.Timeline.TimelineRecordingContextualResponder.KeyExists (PropertyModification[] modifications)
References UnityEditor.Timeline.TimelineRecordingContextualResponder.state.
RemoveCurve()
void UnityEditor.Timeline.TimelineRecordingContextualResponder.RemoveCurve (PropertyModification[] modifications)
References UnityEditor.Timeline.WindowState.Refresh(), and UnityEditor.Timeline.TimelineRecordingContextualResponder.state.
RemoveKey()
void UnityEditor.Timeline.TimelineRecordingContextualResponder.RemoveKey (PropertyModification[] modifications)
References UnityEditor.Timeline.WindowState.Refresh(), and UnityEditor.Timeline.TimelineRecordingContextualResponder.state.
Property Documentation
state
WindowState UnityEditor.Timeline.TimelineRecordingContextualResponder.state get set
Referenced by UnityEditor.Timeline.TimelineRecordingContextualResponder.AddKey(), UnityEditor.Timeline.TimelineRecordingContextualResponder.CurveExists(), UnityEditor.Timeline.TimelineRecordingContextualResponder.GoToNextKeyframe(), UnityEditor.Timeline.TimelineRecordingContextualResponder.GoToPreviousKeyframe(), UnityEditor.Timeline.TimelineRecordingContextualResponder.IsAnimatable(), UnityEditor.Timeline.TimelineRecordingContextualResponder.KeyExists(), UnityEditor.Timeline.TimelineRecordingContextualResponder.RemoveCurve(), UnityEditor.Timeline.TimelineRecordingContextualResponder.RemoveKey(), and UnityEditor.Timeline.TimelineRecordingContextualResponder.TimelineRecordingContextualResponder().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Recording/TimelineRecordingContextualResponder.cs