VirtualTours: UnityEditor.Timeline.RectangleTool Class Reference
UnityEditor.Timeline.RectangleTool Class Reference abstract
Public Member Functions
void OnGUI (WindowState state, EventType rawType, Vector2 mousePosition)
Protected Member Functions
abstract bool CanStartRectangle (Event evt, Vector2 mousePosition, WindowState state)
abstract bool OnFinish (Event evt, WindowState state, Rect rect)
virtual void DrawRectangle (Rect rect)
Properties
abstract bool enableAutoPan [get]
Member Function Documentation
CanStartRectangle()
abstract bool UnityEditor.Timeline.RectangleTool.CanStartRectangle (Event evt, Vector2 mousePosition, WindowState state) protected pure virtual
Implemented in UnityEditor.Timeline.RectangleZoom, and UnityEditor.Timeline.RectangleSelect.
Referenced by UnityEditor.Timeline.RectangleTool.OnGUI().
DrawRectangle()
virtual void UnityEditor.Timeline.RectangleTool.DrawRectangle (Rect rect) protected virtual
Referenced by UnityEditor.Timeline.RectangleTool.OnGUI().
OnFinish()
abstract bool UnityEditor.Timeline.RectangleTool.OnFinish (Event evt, WindowState state, Rect rect) protected pure virtual
Implemented in UnityEditor.Timeline.RectangleZoom, and UnityEditor.Timeline.RectangleSelect.
Referenced by UnityEditor.Timeline.RectangleTool.OnGUI().
OnGUI()
void UnityEditor.Timeline.RectangleTool.OnGUI (WindowState state, EventType rawType, Vector2 mousePosition)
References UnityEditor.Timeline.RectangleTool.CanStartRectangle(), UnityEditor.Timeline.RectangleTool.DrawRectangle(), UnityEditor.Timeline.RectangleTool.enableAutoPan, UnityEditor.Timeline.WindowState.GetWindow(), UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.WindowState.IsCurrentEditingASequencerTextField(), UnityEditor.Timeline.RectangleTool.OnFinish(), UnityEditor.Timeline.TimeAreaAutoPanner.OnGUI(), UnityEditor.Timeline.TimelineWindow.sequenceContentRect, and UnityEditor.Timeline.TimelineWindow.treeView.
Property Documentation
enableAutoPan
abstract bool UnityEditor.Timeline.RectangleTool.enableAutoPan get protected
Referenced by UnityEditor.Timeline.RectangleTool.OnGUI().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Manipulators/Sequence/RectangleTool.cs