VirtualTours: UnityEditor.Timeline.TrackAction Class Reference
UnityEditor.Timeline.TrackAction Class Reference abstract
Public Member Functions
abstract bool Execute (WindowState state, TrackAsset[] tracks)
Static Public Member Functions
static void Invoke< T > (WindowState state, TrackAsset[] tracks)
static void GetMenuEntries (WindowState state, Vector2? mousePos, TrackAsset[] tracks, List< MenuActionItem > items)
static bool HandleShortcut (WindowState state, Event evt, TrackAsset[] tracks)
Static Public Member Functions inherited from UnityEditor.Timeline.MenuItemActionBase
static IEnumerable< Type > GetActionsOfType (Type actionType)
static ShortcutAttribute GetShortcutAttributeForAction (MenuItemActionBase action)
static void BuildMenu (GenericMenu menu, List< MenuActionItem > items)
static ActiveInModeAttribute GetActiveInModeAttribute (MenuItemActionBase action)
static bool IsActionActiveInMode (MenuItemActionBase action, TimelineModes mode)
Protected Member Functions
virtual MenuActionDisplayState GetDisplayState (WindowState state, TrackAsset[] tracks)
virtual bool IsChecked (WindowState state, TrackAsset[] tracks)
virtual string GetDisplayName (TrackAsset[] tracks)
Additional Inherited Members
Static Protected Attributes inherited from UnityEditor.Timeline.MenuItemActionBase
static bool s_ShowActionTriggeredByShortcut = false
Properties inherited from UnityEditor.Timeline.MenuItemActionBase
Vector2? mousePosition [get, set]
int priority [get]
string category [get]
string menuName [get]
string? shortCut [get]
bool showInMenu [get]
Member Function Documentation
Execute()
abstract bool UnityEditor.Timeline.TrackAction.Execute (WindowState state, TrackAsset[] tracks) pure virtual
Implemented in UnityEditor.Timeline.TrackOffsetBaseAction, UnityEditor.Timeline.ConvertFromClipTrackAction, UnityEditor.Timeline.ConvertToClipModeAction, UnityEditor.Timeline.AddOverrideTrackAction, UnityEditor.Timeline.RemoveInvalidMarkersAction, UnityEditor.Timeline.DuplicateTracks, UnityEditor.Timeline.CopyTracksToClipboard, UnityEditor.Timeline.DeleteTracks, UnityEditor.Timeline.MuteTrack, UnityEditor.Timeline.MuteSelectedTrack, UnityEditor.Timeline.ShowHideMarkers, UnityEditor.Timeline.LockTrack, UnityEditor.Timeline.LockSelectedTrack, and UnityEditor.Timeline.EditTrackInAnimationWindow.
GetDisplayName()
virtual string UnityEditor.Timeline.TrackAction.GetDisplayName (TrackAsset[] tracks) protected virtual
Reimplemented in UnityEditor.Timeline.MuteTrack, UnityEditor.Timeline.MuteSelectedTrack, UnityEditor.Timeline.LockTrack, and UnityEditor.Timeline.LockSelectedTrack.
References UnityEditor.Timeline.MenuItemActionBase.menuName.
GetDisplayState()
virtual MenuActionDisplayState UnityEditor.Timeline.TrackAction.GetDisplayState (WindowState state, TrackAsset[] tracks) protected virtual
Reimplemented in UnityEditor.Timeline.TrackOffsetBaseAction, UnityEditor.Timeline.ConvertFromClipTrackAction, UnityEditor.Timeline.ConvertToClipModeAction, UnityEditor.Timeline.AddOverrideTrackAction, UnityEditor.Timeline.RemoveInvalidMarkersAction, UnityEditor.Timeline.MuteTrack, UnityEditor.Timeline.MuteSelectedTrack, UnityEditor.Timeline.ShowHideMarkers, UnityEditor.Timeline.LockTrack, UnityEditor.Timeline.LockSelectedTrack, and UnityEditor.Timeline.EditTrackInAnimationWindow.
GetMenuEntries()
static void UnityEditor.Timeline.TrackAction.GetMenuEntries (WindowState state, Vector2? mousePos, TrackAsset[] tracks, List< MenuActionItem > items) static
References UnityEditor.Timeline.MenuItemActionBase.category, UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.MenuItemActionBase.IsActionActiveInMode(), UnityEditor.Timeline.TimelineMode.mode, UnityEditor.Timeline.MenuItemActionBase.priority, and UnityEditor.Timeline.MenuItemActionBase.shortCut.
HandleShortcut()
static bool UnityEditor.Timeline.TrackAction.HandleShortcut (WindowState state, Event evt, TrackAsset[] tracks) static
References UnityEditor.Timeline.TimelineWindow.instance, UnityEditor.Timeline.MenuItemActionBase.IsActionActiveInMode(), UnityEditor.Timeline.ShortcutAttribute.MatchesEvent(), UnityEditor.Timeline.TimelineMode.mode, and UnityEditor.Timeline.MenuItemActionBase.s_ShowActionTriggeredByShortcut.
Referenced by UnityEditor.Timeline.TrackShortcutManipulator.ExecuteCommand().
Invoke< T >()
static void UnityEditor.Timeline.TrackAction.Invoke< T > (WindowState state, TrackAsset[] tracks) static
Type Constraints
T : TrackAction
IsChecked()
virtual bool UnityEditor.Timeline.TrackAction.IsChecked (WindowState state, TrackAsset[] tracks) protected virtual
Reimplemented in UnityEditor.Timeline.TrackOffsetBaseAction, and UnityEditor.Timeline.ShowHideMarkers.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Actions/TrackActions.cs