VirtualTours: TMPro.TMP_TextParsingUtilities Class Reference
TMPro.TMP_TextParsingUtilities Class Reference
Static Public Member Functions
static int GetHashCode (string s)
Function returning the hashcode value of a given string.
static int GetHashCodeCaseSensitive (string s)
static char ToLowerASCIIFast (char c)
Get lowercase version of this ASCII character.
static char ToUpperASCIIFast (char c)
Get uppercase version of this ASCII character.
static uint ToUpperASCIIFast (uint c)
Get uppercase version of this ASCII character.
static uint ToLowerASCIIFast (uint c)
Get lowercase version of this ASCII character.
static bool IsHighSurrogate (uint c)
Check if Unicode is High Surrogate
static bool IsLowSurrogate (uint c)
Check if Unicode is Low Surrogate
Properties
static TMP_TextParsingUtilities instance [get]
Get a singleton instance of the TextModuleUtilities.
Member Function Documentation
GetHashCode()
static int TMPro.TMP_TextParsingUtilities.GetHashCode (string s) static
Function returning the hashcode value of a given string.
References TMPro.TMP_TextParsingUtilities.ToUpperASCIIFast().
Referenced by TMPro.TMP_StyleSheet.GetStyle(), and TMPro.TMP_Style.RefreshStyle().
GetHashCodeCaseSensitive()
static int TMPro.TMP_TextParsingUtilities.GetHashCodeCaseSensitive (string s) static
IsHighSurrogate()
static bool TMPro.TMP_TextParsingUtilities.IsHighSurrogate (uint c) static
Check if Unicode is High Surrogate
Parameters
c
Returns
IsLowSurrogate()
static bool TMPro.TMP_TextParsingUtilities.IsLowSurrogate (uint c) static
Check if Unicode is Low Surrogate
Parameters
c
Returns
ToLowerASCIIFast() [1/2]
static char TMPro.TMP_TextParsingUtilities.ToLowerASCIIFast (char c) static
Get lowercase version of this ASCII character.
ToLowerASCIIFast() [2/2]
static uint TMPro.TMP_TextParsingUtilities.ToLowerASCIIFast (uint c) static
Get lowercase version of this ASCII character.
ToUpperASCIIFast() [1/2]
static char TMPro.TMP_TextParsingUtilities.ToUpperASCIIFast (char c) static
Get uppercase version of this ASCII character.
Referenced by TMPro.TMP_TextParsingUtilities.GetHashCode().
ToUpperASCIIFast() [2/2]
static uint TMPro.TMP_TextParsingUtilities.ToUpperASCIIFast (uint c) static
Get uppercase version of this ASCII character.
Property Documentation
instance
TMP_TextParsingUtilities TMPro.TMP_TextParsingUtilities.instance static get
Get a singleton instance of the TextModuleUtilities.
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/TMP_TextParsingUtilities.cs