VirtualTours: TMPro.TMP_SubMeshUI Class Reference
TMPro.TMP_SubMeshUI Class Reference
Public Member Functions
override Material GetModifiedMaterial (Material baseMaterial)
Function returning the modified material for masking if necessary.
float GetPaddingForMaterial ()
Function called when the padding value for the material needs to be re-calculated.
float GetPaddingForMaterial (Material mat)
Function called when the padding value for the material needs to be re-calculated.
void UpdateMeshPadding (bool isExtraPadding, bool isUsingBold)
override void SetAllDirty ()
override void SetVerticesDirty ()
override void SetLayoutDirty ()
override void SetMaterialDirty ()
void SetPivotDirty ()
override void Cull (Rect clipRect, bool validRect)
Override Cull function as this is handled by the parent text object.
override void Rebuild (CanvasUpdate update)
void RefreshMaterial ()
Function to update the material from the parent text object.
override void RecalculateClipping ()
Method called when the state of a parent changes.
Static Public Member Functions
static TMP_SubMeshUI AddSubTextObject (TextMeshProUGUI textComponent, MaterialReference materialReference)
Function to add a new sub text object.
Protected Member Functions
override void OnEnable ()
override void OnDisable ()
override void OnDestroy ()
override void OnTransformParentChanged ()
override void UpdateGeometry ()
override void UpdateMaterial ()
Properties
TMP_FontAsset fontAsset [get, set]
The TMP Font Asset assigned to this sub text object.
TMP_SpriteAsset spriteAsset [get, set]
The TMP Sprite Asset assigned to this sub text object.
override Texture mainTexture [get]
override Material material [get, set]
The material to be assigned to this object. Returns an instance of the material.
Material sharedMaterial [get, set]
The material to be assigned to this text object.
Material fallbackMaterial [get, set]
Material fallbackSourceMaterial [get, set]
The source material used by the fallback font
override Material materialForRendering [get]
Get the material that will be used for rendering.
bool isDefaultMaterial [get, set]
Is the text object using the default font asset material.
float padding [get, set]
Padding value resulting for the property settings on the material.
Mesh mesh [get, set]
The Mesh of this text sub object.
TMP_Text textComponent [get]
Reference to the parent Text Component.
Member Function Documentation
AddSubTextObject()
static TMP_SubMeshUI TMPro.TMP_SubMeshUI.AddSubTextObject (TextMeshProUGUI textComponent, MaterialReference materialReference) static
Function to add a new sub text object.
Parameters
textComponent
materialReference
Returns
References TMPro.MaterialReference.fontAsset, TMPro.MaterialReference.index, TMPro.MaterialReference.isDefaultMaterial, TMPro.MaterialReference.material, TMPro.TMP_Text.rectTransform, TMPro.MaterialReference.spriteAsset, TMPro.TMP_SubMeshUI.textComponent, and TMPro.TMP_Text.transform.
Referenced by TMPro.TextMeshProUGUI.SetArraySizes().
Cull()
override void TMPro.TMP_SubMeshUI.Cull (Rect clipRect, bool validRect)
Override Cull function as this is handled by the parent text object.
Parameters
clipRect
validRect
GetModifiedMaterial()
override Material TMPro.TMP_SubMeshUI.GetModifiedMaterial (Material baseMaterial)
Function returning the modified material for masking if necessary.
Parameters
baseMaterial
Returns
GetPaddingForMaterial() [1/2]
float TMPro.TMP_SubMeshUI.GetPaddingForMaterial ()
Function called when the padding value for the material needs to be re-calculated.
Returns
References TMPro.TMP_Text.extraPadding, TMPro.TMP_Text.isUsingBold, and TMPro.TMP_SubMeshUI.padding.
GetPaddingForMaterial() [2/2]
float TMPro.TMP_SubMeshUI.GetPaddingForMaterial (Material mat)
Function called when the padding value for the material needs to be re-calculated.
Returns
References TMPro.TMP_Text.extraPadding, TMPro.TMP_Text.isUsingBold, and TMPro.TMP_SubMeshUI.padding.
OnDestroy()
override void TMPro.TMP_SubMeshUI.OnDestroy () protected
References TMPro.TMP_Text.havePropertiesChanged, TMPro.TMP_SubMeshUI.RecalculateClipping(), and TMPro.TextMeshProUGUI.SetAllDirty().
OnDisable()
override void TMPro.TMP_SubMeshUI.OnDisable () protected
OnEnable()
override void TMPro.TMP_SubMeshUI.OnEnable () protected
References TMPro.TMP_SubMeshUI.RecalculateClipping().
OnTransformParentChanged()
override void TMPro.TMP_SubMeshUI.OnTransformParentChanged () protected
References TMPro.TMP_SubMeshUI.RecalculateClipping().
Rebuild()
override void TMPro.TMP_SubMeshUI.Rebuild (CanvasUpdate update)
Parameters
update
References TMPro.TMP_SubMeshUI.UpdateMaterial().
RecalculateClipping()
override void TMPro.TMP_SubMeshUI.RecalculateClipping ()
Method called when the state of a parent changes.
Referenced by TMPro.TMP_SubMeshUI.OnDestroy(), TMPro.TMP_SubMeshUI.OnEnable(), and TMPro.TMP_SubMeshUI.OnTransformParentChanged().
RefreshMaterial()
void TMPro.TMP_SubMeshUI.RefreshMaterial ()
Function to update the material from the parent text object.
References TMPro.TMP_SubMeshUI.UpdateMaterial().
SetAllDirty()
override void TMPro.TMP_SubMeshUI.SetAllDirty ()
SetLayoutDirty()
override void TMPro.TMP_SubMeshUI.SetLayoutDirty ()
SetMaterialDirty()
override void TMPro.TMP_SubMeshUI.SetMaterialDirty ()
References TMPro.TMP_SubMeshUI.UpdateMaterial().
SetPivotDirty()
void TMPro.TMP_SubMeshUI.SetPivotDirty ()
References TMPro.TMP_Text.rectTransform.
SetVerticesDirty()
override void TMPro.TMP_SubMeshUI.SetVerticesDirty ()
References TMPro.TMP_Text.havePropertiesChanged, and TMPro.TextMeshProUGUI.SetVerticesDirty().
UpdateGeometry()
override void TMPro.TMP_SubMeshUI.UpdateGeometry () protected
UpdateMaterial()
override void TMPro.TMP_SubMeshUI.UpdateMaterial () protected
References TMPro.TMP_Text.fontSharedMaterial, TMPro.TMP_SubMeshUI.materialForRendering, and TMPro.TMP_SubMeshUI.textComponent.
Referenced by TMPro.TMP_SubMeshUI.Rebuild(), TMPro.TMP_SubMeshUI.RefreshMaterial(), and TMPro.TMP_SubMeshUI.SetMaterialDirty().
UpdateMeshPadding()
void TMPro.TMP_SubMeshUI.UpdateMeshPadding (bool isExtraPadding, bool isUsingBold)
Parameters
isExtraPadding
isBold
Property Documentation
fallbackMaterial
Material TMPro.TMP_SubMeshUI.fallbackMaterial get set
Referenced by TMPro.TextMeshProUGUI.SetArraySizes().
fallbackSourceMaterial
Material TMPro.TMP_SubMeshUI.fallbackSourceMaterial get set
The source material used by the fallback font
Referenced by TMPro.TextMeshProUGUI.SetArraySizes().
fontAsset
TMP_FontAsset TMPro.TMP_SubMeshUI.fontAsset get set
The TMP Font Asset assigned to this sub text object.
Referenced by TMPro.TextMeshProUGUI.SetArraySizes().
isDefaultMaterial
bool TMPro.TMP_SubMeshUI.isDefaultMaterial get set
Is the text object using the default font asset material.
mainTexture
override Texture TMPro.TMP_SubMeshUI.mainTexture get
material
override Material TMPro.TMP_SubMeshUI.material get set
The material to be assigned to this object. Returns an instance of the material.
Referenced by TMPro.TextMeshProUGUI.GetMaterials().
materialForRendering
override Material TMPro.TMP_SubMeshUI.materialForRendering get
Get the material that will be used for rendering.
Referenced by TMPro.TextMeshProUGUI.SetCulling(), and TMPro.TMP_SubMeshUI.UpdateMaterial().
mesh
Mesh TMPro.TMP_SubMeshUI.mesh get set
The Mesh of this text sub object.
Referenced by TMPro.TextMeshProUGUI.GenerateTextMesh(), TMPro.TextMeshProUGUI.GetCompoundBounds(), and TMPro.TextMeshProUGUI.UpdateVertexData().
padding
float TMPro.TMP_SubMeshUI.padding get set
Padding value resulting for the property settings on the material.
Referenced by TMPro.TextMeshProUGUI.GenerateTextMesh(), and TMPro.TMP_SubMeshUI.GetPaddingForMaterial().
sharedMaterial
Material TMPro.TMP_SubMeshUI.sharedMaterial get set
The material to be assigned to this text object.
Referenced by TMPro.TextMeshProUGUI.GetSharedMaterials(), TMPro.TextMeshProUGUI.SetArraySizes(), and TMPro.TextMeshProUGUI.SetSharedMaterials().
spriteAsset
TMP_SpriteAsset TMPro.TMP_SubMeshUI.spriteAsset get set
The TMP Sprite Asset assigned to this sub text object.
Referenced by TMPro.TextMeshProUGUI.SetArraySizes().
textComponent
TMP_Text TMPro.TMP_SubMeshUI.textComponent get
Reference to the parent Text Component.
Referenced by TMPro.TMP_SubMeshUI.AddSubTextObject(), and TMPro.TMP_SubMeshUI.UpdateMaterial().
The documentation for this class was generated from the following file:
Library/PackageCache/com.unity.textmeshpro@3.0.1/Scripts/Runtime/TMP_SubMeshUI.cs