VirtualTours: UnityEditor.Timeline.ITrimmable Interface Reference
UnityEditor.Timeline.ITrimmable Interface Reference
Public Member Functions
void SetStart (double time, bool affectTimeScale)
void SetEnd (double time, bool affectTimeScale)
void TrimStart (double time)
void TrimEnd (double time)
Public Member Functions inherited from UnityEditor.Timeline.ITimelineItem
bool IsCompatibleWithTrack (TrackAsset track)
void Delete ()
ITimelineItem CloneTo (TrackAsset parent, double time)
void PushUndo (string operation)
Additional Inherited Members
Properties inherited from UnityEditor.Timeline.ITimelineItem
double start [get, set]
double end [get]
double duration [get]
TrackAsset parentTrack [get, set]
TimelineItemGUI gui [get]
Member Function Documentation
SetEnd()
void UnityEditor.Timeline.ITrimmable.SetEnd (double time, bool affectTimeScale)
Implemented in UnityEditor.Timeline.ClipItem.
Referenced by UnityEditor.Timeline.TrimItemModeMix.TrimEnd(), UnityEditor.Timeline.TrimItemModeReplace.TrimEnd(), UnityEditor.Timeline.TrimItemModeRipple.TrimEnd(), and UnityEditor.Timeline.TrimItemModeReplace.TrimStart().
SetStart()
void UnityEditor.Timeline.ITrimmable.SetStart (double time, bool affectTimeScale)
Implemented in UnityEditor.Timeline.ClipItem.
Referenced by UnityEditor.Timeline.TrimItemModeReplace.TrimEnd(), UnityEditor.Timeline.TrimItemModeMix.TrimStart(), UnityEditor.Timeline.TrimItemModeReplace.TrimStart(), and UnityEditor.Timeline.TrimItemModeRipple.TrimStart().
TrimEnd()
void UnityEditor.Timeline.ITrimmable.TrimEnd (double time)
Implemented in UnityEditor.Timeline.ClipItem.
TrimStart()
void UnityEditor.Timeline.ITrimmable.TrimStart (double time)
Implemented in UnityEditor.Timeline.ClipItem.
The documentation for this interface was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/Items/ITimelineItem.cs