VirtualTours: Packages.Rider.Editor.IGenerator Interface Reference
Packages.Rider.Editor.IGenerator Interface Reference
Public Member Functions
bool SyncIfNeeded (IEnumerable< string > affectedFiles, IEnumerable< string > reimportedFiles)
void Sync ()
bool HasSolutionBeenGenerated ()
string SolutionFile ()
void GenerateAll (bool generateAll)
Properties
string ProjectDirectory [get]
IAssemblyNameProvider AssemblyNameProvider [get]
Member Function Documentation
GenerateAll()
void Packages.Rider.Editor.IGenerator.GenerateAll (bool generateAll)
Implemented in Packages.Rider.Editor.ProjectGeneration.
Referenced by Packages.Rider.Editor.RiderScriptEditor.OnGUI().
HasSolutionBeenGenerated()
bool Packages.Rider.Editor.IGenerator.HasSolutionBeenGenerated ()
Implemented in Packages.Rider.Editor.ProjectGeneration.
Referenced by Packages.Rider.Editor.RiderScriptEditor.CreateSolutionIfDoesntExist().
SolutionFile()
string Packages.Rider.Editor.IGenerator.SolutionFile ()
Implemented in Packages.Rider.Editor.ProjectGeneration.
Sync()
void Packages.Rider.Editor.IGenerator.Sync ()
Implemented in Packages.Rider.Editor.ProjectGeneration.
Referenced by Packages.Rider.Editor.RiderScriptEditor.CreateSolutionIfDoesntExist(), Packages.Rider.Editor.RiderScriptEditor.Initialize(), and Packages.Rider.Editor.RiderScriptEditor.SyncAll().
SyncIfNeeded()
bool Packages.Rider.Editor.IGenerator.SyncIfNeeded (IEnumerable< string > affectedFiles, IEnumerable< string > reimportedFiles)
Implemented in Packages.Rider.Editor.ProjectGeneration.
Referenced by Packages.Rider.Editor.RiderScriptEditor.SyncIfNeeded().
Property Documentation
AssemblyNameProvider
IAssemblyNameProvider Packages.Rider.Editor.IGenerator.AssemblyNameProvider get
Referenced by Packages.Rider.Editor.RiderScriptEditor.OnGUI().
ProjectDirectory
string Packages.Rider.Editor.IGenerator.ProjectDirectory get
The documentation for this interface was generated from the following file:
Library/PackageCache/com.unity.ide.rider@1.2.1/Rider/Editor/ProjectGeneration/ProjectGeneration.cs