VirtualTours: UnityEngine.Timeline.ITimeControl Interface Reference
UnityEngine.Timeline.ITimeControl Interface Reference
Interface that can be implemented by MonoBehaviours indicating that they receive time-related control calls from a PlayableGraph.
Public Member Functions
void SetTime (double time)
Called each frame the Timeline clip is active.
void OnControlTimeStart ()
Called when the associated Timeline clip becomes active.
void OnControlTimeStop ()
Called when the associated Timeline clip becomes deactivated.
Detailed Description
Interface that can be implemented by MonoBehaviours indicating that they receive time-related control calls from a PlayableGraph.
Implementing this interface on MonoBehaviours attached to GameObjects under control by control-tracks will cause them to be notified when associated Timeline clips are active.
Member Function Documentation
OnControlTimeStart()
void UnityEngine.Timeline.ITimeControl.OnControlTimeStart ()
Called when the associated Timeline clip becomes active.
Referenced by UnityEngine.Timeline.TimeControlPlayable.OnBehaviourPlay().
OnControlTimeStop()
void UnityEngine.Timeline.ITimeControl.OnControlTimeStop ()
Called when the associated Timeline clip becomes deactivated.
Referenced by UnityEngine.Timeline.TimeControlPlayable.OnBehaviourPause().
SetTime()
void UnityEngine.Timeline.ITimeControl.SetTime (double time)
Called each frame the Timeline clip is active.
Parameters
time The local time of the associated Timeline clip.
Referenced by UnityEngine.Timeline.TimeControlPlayable.PrepareFrame().
The documentation for this interface was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Runtime/Playables/ITimeControl.cs