VirtualTours: VSCodeEditor.IGenerator Interface Reference
VSCodeEditor.IGenerator Interface Reference
Public Member Functions
bool SyncIfNeeded (List< string > affectedFiles, string[] reimportedFiles)
void Sync ()
string SolutionFile ()
void GenerateAll (bool generateAll)
bool SolutionExists ()
Properties
string ProjectDirectory [get]
IAssemblyNameProvider AssemblyNameProvider [get]
Member Function Documentation
GenerateAll()
void VSCodeEditor.IGenerator.GenerateAll (bool generateAll)
Implemented in VSCodeEditor.ProjectGeneration.
SolutionExists()
bool VSCodeEditor.IGenerator.SolutionExists ()
Implemented in VSCodeEditor.ProjectGeneration.
Referenced by VSCodeEditor.VSCodeScriptEditor.CreateIfDoesntExist().
SolutionFile()
string VSCodeEditor.IGenerator.SolutionFile ()
Implemented in VSCodeEditor.ProjectGeneration.
Sync()
void VSCodeEditor.IGenerator.Sync ()
Implemented in VSCodeEditor.ProjectGeneration.
Referenced by VSCodeEditor.VSCodeScriptEditor.CreateIfDoesntExist(), and VSCodeEditor.VSCodeScriptEditor.SyncAll().
SyncIfNeeded()
bool VSCodeEditor.IGenerator.SyncIfNeeded (List< string > affectedFiles, string[] reimportedFiles)
Implemented in VSCodeEditor.ProjectGeneration.
Referenced by VSCodeEditor.VSCodeScriptEditor.SyncIfNeeded().
Property Documentation
AssemblyNameProvider
IAssemblyNameProvider VSCodeEditor.IGenerator.AssemblyNameProvider get
ProjectDirectory
string VSCodeEditor.IGenerator.ProjectDirectory get
Referenced by VSCodeEditor.VSCodeScriptEditor.OpenProject().
The documentation for this interface was generated from the following file:
Library/PackageCache/com.unity.ide.vscode@1.2.2/Editor/ProjectGeneration/ProjectGeneration.cs