VirtualTours: UnityEditor.Timeline.LayerZOrder Struct Reference
UnityEditor.Timeline.LayerZOrder Struct Reference
Public Member Functions
LayerZOrder (Layer layer, int zOrder)
int CompareTo (LayerZOrder other)
LayerZOrder ChangeLayer (Layer layer)
Static Public Member Functions
static LayerZOrder operator++ (LayerZOrder x)
Public Attributes
Layer m_Layer
int m_ZOrder
Constructor & Destructor Documentation
LayerZOrder()
UnityEditor.Timeline.LayerZOrder.LayerZOrder (Layer layer, int zOrder)
References UnityEditor.Timeline.LayerZOrder.m_Layer, and UnityEditor.Timeline.LayerZOrder.m_ZOrder.
Referenced by UnityEditor.Timeline.LayerZOrder.ChangeLayer(), and UnityEditor.Timeline.LayerZOrder.operator++().
Member Function Documentation
ChangeLayer()
LayerZOrder UnityEditor.Timeline.LayerZOrder.ChangeLayer (Layer layer)
References UnityEditor.Timeline.LayerZOrder.LayerZOrder(), and UnityEditor.Timeline.LayerZOrder.m_ZOrder.
Referenced by UnityEditor.Timeline.TimelineClipHandle.TimelineClipHandle().
CompareTo()
int UnityEditor.Timeline.LayerZOrder.CompareTo (LayerZOrder other)
References UnityEditor.Timeline.LayerZOrder.m_Layer, and UnityEditor.Timeline.LayerZOrder.m_ZOrder.
operator++()
static LayerZOrder UnityEditor.Timeline.LayerZOrder.operator++ (LayerZOrder x) static
References UnityEditor.Timeline.LayerZOrder.LayerZOrder(), UnityEditor.Timeline.LayerZOrder.m_Layer, and UnityEditor.Timeline.LayerZOrder.m_ZOrder.
Member Data Documentation
m_Layer
Layer UnityEditor.Timeline.LayerZOrder.m_Layer
Referenced by UnityEditor.Timeline.LayerZOrder.CompareTo(), UnityEditor.Timeline.LayerZOrder.LayerZOrder(), and UnityEditor.Timeline.LayerZOrder.operator++().
m_ZOrder
int UnityEditor.Timeline.LayerZOrder.m_ZOrder
Referenced by UnityEditor.Timeline.LayerZOrder.ChangeLayer(), UnityEditor.Timeline.LayerZOrder.CompareTo(), UnityEditor.Timeline.LayerZOrder.LayerZOrder(), and UnityEditor.Timeline.LayerZOrder.operator++().
The documentation for this struct was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/Drawers/Layers/ItemsLayer.cs