VirtualTours: UnityEditor.Timeline.TrackItemsDrawer Struct Reference
UnityEditor.Timeline.TrackItemsDrawer Struct Reference
Public Member Functions
TrackItemsDrawer (IRowGUI parent)
void BuildGUICache (IRowGUI parent)
void Draw (Rect rect, WindowState state)
Public Attributes
List< ItemsLayer > m_Layers
ClipsLayer m_ClipsLayer
Properties
IEnumerable< TimelineClipGUI > clips [get]
Constructor & Destructor Documentation
TrackItemsDrawer()
UnityEditor.Timeline.TrackItemsDrawer.TrackItemsDrawer (IRowGUI parent)
References UnityEditor.Timeline.TrackItemsDrawer.BuildGUICache(), UnityEditor.Timeline.TrackItemsDrawer.m_ClipsLayer, and UnityEditor.Timeline.TrackItemsDrawer.m_Layers.
Member Function Documentation
BuildGUICache()
void UnityEditor.Timeline.TrackItemsDrawer.BuildGUICache (IRowGUI parent)
References UnityEditor.Timeline.TrackItemsDrawer.m_ClipsLayer, and UnityEditor.Timeline.TrackItemsDrawer.m_Layers.
Referenced by UnityEditor.Timeline.TrackItemsDrawer.TrackItemsDrawer().
Draw()
void UnityEditor.Timeline.TrackItemsDrawer.Draw (Rect rect, WindowState state)
References UnityEditor.Timeline.TrackItemsDrawer.m_Layers.
Referenced by UnityEditor.Timeline.TimelineTrackGUI.Draw().
Member Data Documentation
m_ClipsLayer
ClipsLayer UnityEditor.Timeline.TrackItemsDrawer.m_ClipsLayer
Referenced by UnityEditor.Timeline.TrackItemsDrawer.BuildGUICache(), and UnityEditor.Timeline.TrackItemsDrawer.TrackItemsDrawer().
m_Layers
List<ItemsLayer> UnityEditor.Timeline.TrackItemsDrawer.m_Layers
Referenced by UnityEditor.Timeline.TrackItemsDrawer.BuildGUICache(), UnityEditor.Timeline.TrackItemsDrawer.Draw(), and UnityEditor.Timeline.TrackItemsDrawer.TrackItemsDrawer().
Property Documentation
clips
IEnumerable<TimelineClipGUI> UnityEditor.Timeline.TrackItemsDrawer.clips get
The documentation for this struct was generated from the following file:
Library/PackageCache/com.unity.timeline@1.3.6/Editor/treeview/Drawers/TrackItemsDrawer.cs